### ISSUE TITLE
Subtle results with tokens_select, worth checking

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1001]
Some subtle results, not necessarily wrong, but I wanted to make sure this behaviour is what we intended.

First, we create two simple texts, with a dictionary that includes compound values.
```r
txt <- c("bad is the same as not good",
         "not bad is nearly like good")

mydict <- dictionary(list(pos = c("good", "not bad"),
                          neg = c("not good", "bad")))

toks <- tokens(txt) %>% tokens_compound(mydict)
```

Now, we slice just the positive part of the dictionary, and apply `tokens_lookup()`. This is exactly what I would expect.
```r
tokens_select(toks, mydict["pos"], padding = TRUE)
# tokens from 2 documents.
# text1 :
# [1] "" "" "" "" "" ""
# 
# text2 :
# [1] "not_bad" ""        ""        ""        "good"   
```

However, when we use the `$` operator, which returns not a dictionary, but a character vector, then the compound value is not matched:
```r
tokens_select(toks, mydict$pos, padding = TRUE)
# tokens from 2 documents.
# text1 :
# [1] "" "" "" "" "" ""
# 
# text2 :
# [1] ""     ""     ""     ""     "good"
```

Using `phrase()` makes no difference:
```r
tokens_select(toks, phrase(mydict$pos), padding = TRUE)
# tokens from 2 documents.
# text1 :
# [1] "" "" "" "" "" ""
# 
# text2 :
# [1] ""     ""     ""     ""     "good"
```

Now let's recreate the compound tokens with a different `concatenator` value.
```r
toks2 <- tokens(txt) %>% tokens_compound(mydict, concatenator = " ")
tokens_select(toks2, mydict$pos, padding = TRUE)
# tokens from 2 documents.
# text1 :
# [1] "" "" "" "" "" ""
# 
# text2 :
# [1] "not bad" ""        ""        ""        "good"   
```
That works ok.

But then it does not match again, if we use `phrase()`. 
```r
toks2 <- tokens(txt) %>% tokens_compound(mydict, concatenator = " ")
tokens_select(toks2, phrase(mydict$pos), padding = TRUE)
# tokens from 2 documents.
# text1 :
# [1] "" "" "" "" "" ""
# 
# text2 :
# [1] ""     ""     ""     ""     "good"
```

While it may not be obvious, I think all but the last are what we intended. The very last one _might_ be a bug/unexpected.

**Comment by koheiw** [comment]
I think this is OK (at least not a bug). When `pattern = mydict$pos`, tokens must have white spaces as concatenators of compounds; when `pattern = phrase(mydict$pos)`, only uncompounded tokens are selected.
