### ISSUE TITLE
Need to fix UBSAN issues

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1003]
Got this email today from the CRAN team:

> Also, please take a look at the clang-UBSAN issues reported at
> https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/quanteda/
> and try to fix.
> 
> Best,
> Uwe Ligges
> (CRAN team)

This seems to be triggered by the vignette only. We need either to explain this clearly as being not our fault, but rather that of **Rcpp**, or diagnose and fix it.

For latter, putting it to the rOpenSci Slack team might be a good start. I seem to remember some chatter about related issues there.

**Comment by kbenoit** [comment]
See more at https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Undefined-Behaviour-Sanitizer

I got this message today:

Begin forwarded message:

> From: Prof Brian Ripley <ripley@stats.ox.ac.uk>
> Subject: Re: CRAN package quanteda
> Date: 5 October 2017 at 10:24:30 BST
> To: "Benoit,KR" <K.R.Benoit@lse.ac.uk>, "CRAN@r-project.org" <CRAN@r-project.org>
> 

> > On 05/10/2017 09:56, Benoit,KR wrote:
> > Dear Uwe and the CRAN team,
> > We fixed the R version dependency already, and are working on the UBSan issues. It might be of interest to the checking system however to know that it was not a change in our package that broke the old-release versions, but rather changes to packages that we import. I’m not sure what is the best system to ensure that we depend on an R version at least as recent as the latest version dependency of all of the packages we import.
> > On the UBSan issues, what’s the best way to detect those? It looks like our package check passes, but that the vignette is somehow triggering issues.
> 

> 
> You study the manual, as the README in that area says!
> 
> But the UBSAN errors are from C++ code in package RcppParallel whose headers your code imports and whose checks show the same issue.  They occur in your examples, not just the vignette.  This needs to be solved in RcppParallel.

**Comment by kbenoit** [comment]
Keep our eyes out for a solution in **Rcpp**.

**Comment by koheiw** [comment]
Here is a nice page on how to set up Linux for the UBSAN test
https://francoismichonneau.net/2014/03/how-to-do-ubsan-tests-r-package/

Test environment details:
https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/README.txt
https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/README.txt
