### ISSUE TITLE
Error in tokens_select.tokens with dfm as pattern

### ISSUE THREAD

**Issue by maxboiten** [kbenoit/quanteda#1006]
Hi,

I'm working on an LDA-related implementation where I need a tokens object with the possibility of removing words that are infrequent or occur in all documents (such as with dfm_trim). Therefore, I produce a dfm first, trim that and use it as a pattern for tokens_select on the tokens object. After a while of calculating, this produces the following error, presumably in pattern2id:

`
Error in match(x, table, nomatch = 0L) : 
  'match' requires vector arguments
`

There is an easy fix:

`if(is.dfm(pattern)) {pattern <- featnames(pattern)}`

This removes the error and makes it more efficient. I'm new to github, so wasn't sure where to put this, apologies if it's in the wrong place.

Kind regards,

Max Boiten

**Comment by kbenoit** [comment]
Thanks @maxboiten. Can you send enough code and example data so that we can replicate the issue?

**Comment by maxboiten** [comment]
Please find code and data in the zip attached. It contains a short cleaning procedure on a subset of EUspeech data (25/787 British speeches).

[Quanteda_1006.zip](https://github.com/kbenoit/quanteda/files/1358983/Quanteda_1006.zip)

**Comment by koheiw** [comment]
Hi @maxboiten, I think it is not a bug, but confusion caused by the difference between `dfm_select()` and `tokens_select()` that the former takes a dfm as an input but the latter does not.  We will think about changing the design a bit.
```r
tokens_uk <- tokens_select(tokens_uk,dfm_trimmed) # this does not work

# please do either
tokens_uk <- tokens_select(tokens_uk, featnames(dfm_trimmed))
# or
dfm_uk <- dfm_select(dfm(tokens_uk), dfm_trimmed)
```
@kbenoit what do you think?

**Comment by kbenoit** [comment]
See `?pattern`, where it says for the `pattern` argument allowable types:

> `dfm`
>       Only `dfm_select` accepts dfm as features to create a new dfm identical in its feature set, using a fixed match.

So this is a feature, not a bug. The "workaround" is correct. However @koheiw it might be worth adding an error message to this effect, for `tokens_select()` and the other functions that allow `pattern`.

**Comment by maxboiten** [comment]
Thanks for the answers. The reason I tried this is that the tokens_select documentation said I could, had I been a bit more thorough I would have read the pattern page as well. Apologies for the laziness there.
