### ISSUE TITLE
What the best way to do lemmatization?

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1022]
I have tried to do lemmatization myself after seeing https://stackoverflow.com/questions/46731429/quanteda-fastest-way-to-replace-tokens-with-lemma-from-dictionary/46742533#46742533.

`tokens_lookup` takes 114.234 sec only with 2000 docs, while `tokens_convert` is 0.067 sec (738 times faster!). We need to think.
```r
require(quanteda)
load("/home/kohei/Documents/Brexit/Analysis/data_tokens_guardian.RData")
toks <- head(data_tokens_guardian, 2000)

# http://www.lexiconista.com/Datasets/lemmatization-en.zip
data <- read.csv("/home/kohei/Documents/Dictionary/Lemma list/lemmatization-en.txt", sep = '\t', as.is = TRUE,
                 header = FALSE)

system.time(
dict <- dictionary(split(data[,2], data[,1]))
)
# user  system elapsed 
# 67.772   1.376  69.394

length(dict) # 26058

system.time(
    toks_lemma <- tokens_lookup(toks, dict, valuetype = 'fixed', exclusive = FALSE, capkeys = FALSE)
)
# user  system elapsed 
# 43.888   3.656  44.840 

tokens_convert <- function(x, from, to) {
    type <- attr(x, 'types')
    type_new <- to[match(type, from)]
    type_new <- ifelse(is.na(type_new), type, type_new)
    attr(x, 'types') <- type_new
    quanteda:::tokens_recompile(x)
}
system.time(
    toks_lemma2 <- tokens_convert(toks, from = data[,2], to = data[,1])
)

# user  system elapsed 
# 0.072   0.004   0.067 
```

**Comment by kbenoit** [comment]
That is exactly what I was thinking too. You might even make it faster by just using indexing, rather than the match. E.g. if to is a named character vector `lemma_token`, where the value is the lemma, and the name is inflected form, then `type_new <- to[from]`. That’s the way that hyphen counts work, and while brute force, it’s super fast. Only works for fixed matches, but it would be possible to use a regex2fixed style strategy to convert regex matches to the table of fixed, and then use this.

This is how an early version of the dictionary lookups worked, before we went to hashing and C++ etc.

**Comment by kbenoit** [comment]
Thinking further, if this proves faster than the C++ tokens lookup, then we could change the way it works to convert every dictionary (the named lists) into a character vector with the fixed value match as the name, and the key as the vector’s value, and then apply this strategy.

We could also modify the dictionary constructor to take named character vectors as a list (as long as the names are unique) as input, so that the `*_lookup` functions then work for dictionary lookups but also the related lemmatisation issue.

It’s pretty easy to get a full sets of lemmas for many languages, which could then be applied using this lookup approach.

**Comment by koheiw** [comment]
`tokens_convert()` is faster because it only lookups single words, and does nothing with unmatched tokens. I don't think dictionary objects works best with lemma lists, because it is created for nested keys. It is better to create a different function, or add a new argument to `tokens_lookup()` that is different from `dictionary`.

**Comment by kbenoit** [comment]
True, it would not work for multi-word values. But where that's not the case:

```r
dict_to_vector <- function(dict, toks) {
    dictnames <- names(dict)
    dict <- unlist(as.list(dict))
    toks <- tokens_tolower(toks)
    temp <- lapply(dict, 
           function(x) {
               sapply(x, 
                      quanteda:::regex2fixed, 
                      quanteda:::types.tokens(toks), 
                      valuetype = "glob",
                      case_insensitive = TRUE) %>%
                   unlist()
           })
    temp <- unlist(temp, use.names = TRUE)
    ret <- unlist(stringi::stri_extract_all_regex(names(temp), paste(dictnames, collapse = "|")))
    names(ret) <- temp
    ret[!is.na(names(ret))]
}

tokens_convert2 <- function(x, vec, exclusive = TRUE) {
    attrs <- attributes(x)
    type <- quanteda:::types.tokens(x)
    type_new <- vec[type]
    type_new <- if (exclusive) {
        ifelse(is.na(type_new), type, type_new)
    } else {
        type_new[!is.na(type_new)]
    }
    x <- tokens_select(x, names(vec))
    x <- lapply(x, match, names(type_new))
    attributes(x) <- attrs
    attr(x, 'types') <- type_new
    quanteda:::tokens_recompile(x)
}

toks <- tokens(data_corpus_inaugural)
# currently not optimized, so this is really slow
dict <- dictionary(list(neg = data_dictionary_LSD2015[[1]][2:101], 
                        pos = data_dictionary_LSD2015[[2]][1:100])) %>%
    dict_to_vector(toks)

microbenchmark::microbenchmark(
    tokens_lookup = tokens_lookup(toks, data_dictionary_LSD2015),
    vector_lookup = tokens_convert2(toks, dict),
    times = 10
)
# Unit: milliseconds
#           expr      min       lq     mean   median        uq       max neval
#  tokens_lookup 842.5329 934.7705 983.0996 969.2320 1038.2261 1164.9092    10
#  vector_lookup 357.4901 398.4795 408.4911 412.8697  420.7453  466.2455    10
```

That's cheating a bit, since I did the conversion from regex2fixed for the specific tokens outside of the benchmark, but you can see how fast this approach is, and no C++ needed.

**Comment by kbenoit** [comment]
I say we call this `tokens_substitute()`, and create a secondary package called **lemmas** that provides lemma lookups, objects. We can define methods that work with a data.frame, as in your case, or a named vector as in my example.

**Comment by koheiw** [comment]
I like `tokens_replace()`. We could add `fun` argument as in `sapply` to allow custom stemmer etc.

Here are lemma lists for many languages under the open database license:
http://www.lexiconista.com/datasets/lemmatization/

**Comment by jansenjoost** [comment]
Can such function be integrated with the spacyR package to convert tokens to their lemma or POS?

**Comment by koheiw** [comment]
We haven't really integrated **spacyr**, but you can easily make a tokens object from lemmas:
```r
toks <- as.tokens(split(x$lemma, x$doc_id))
```
where `x` is the output of **spacyr**.

**Comment by kbenoit** [comment]
@jansenjoost The plan is definitely to work on better **spacyr** integration in our next major release, including selection of tokens on POS.

In the meantime, #1026 implements the `tokens_replace()`.
