### ISSUE TITLE
Page build warning

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1030]
I just got this message from GitHub, after merging PR #1023:

> The page build completed successfully, but returned the following warning for the `master` branch:
> 
> Your site's DNS settings are using a custom subdomain, docs.quanteda.io, that's not set up with a correct CNAME record. We recommend you set this CNAME record to point at kbenoit.github.io. For more information, see https://help.github.com/articles/using-a-custom-domain-with-github-pages/.
> 
> For information on troubleshooting Jekyll see:
> 
>  https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by koheiw** [comment]
I think it is nothing do with the merge, but my DNS setting. I change it a bit, hoping that will stop this message.
