### ISSUE TITLE
Comparison of major text analysis packages for quanteda website

### ISSUE THREAD

**Issue by stefan-mueller** [kbenoit/quanteda#1047]
@koheiw and I were thinking about adding a table for the new [website](www.quanteda.io) that compares  **quanteda** and other R text analysis packages (see [this](http://www.agconsult.com/en/usability-blog/4-product-comparison-best-practices) link as an example). The table could be placed below the user testimonials. Moreover, we could create something like [this](http://www.significantdigits.org/2017/10/switching-from-base-r-to-tidyverse/) for people who want to switch from a different R text analaysis package to **quanteda**. 

Now the question: which packages shall we compare quanteda to? I thought about

1. **tidytext**,
2. **tm**,
3. **austin**,
4. **koRpus**.

Any additions/changes? Afterwards, I am happy to prepare a draft table.

**Comment by kbenoit** [comment]
Good idea. You could add **corpus** to this.

**Comment by stefan-mueller** [comment]
Here you can find the first draft of the comparative table: https://github.com/stefan-mueller/table-compare-quanteda/blob/master/compare_quanteda.csv

I divided the functions up into larger categories and looked for the corresponding functions in the other packages (I checked the PDF manuals from CRAN).

Based on this spreadsheet, we could create a table for the website and exchange the commands with a "check" symbol (http://fontawesome.io/icon/check/) and insert a "cross" (http://fontawesome.io/icon/times/) in empty cells. Note that I have used **quanteda** as the baseline and did not pay too much attention to functions that only the alternative packages include. In the medium term we might think of a cheat sheet for users who want to switch from one of the alternative packages to **quanteda**.

What's your view on the spreadsheet? 
@koheiw, in which format would you need the table for the website? It seems that Hugo can handle tables in the [Markdown format](https://discourse.gohugo.io/t/can-hugo-generate-html-tables-from-markdown/2416/2).

**Comment by koheiw** [comment]
Thank you @stefan-mueller looks great. I think we should keep this as is, because actual commands are more informative than "check" symbols. This is useful not only to convince potential users, but existing users to find functions new to them. We need to make the first column more descriptive, and add the string-of-words functions like `textstat_collocation`, `phrase`, `tokens_combine`, but this is really good.

Why don't you add the table to a page under doc.quanteda.io (https://github.com/kbenoit/quanteda/tree/master/docs) via PR? I will also work on it and add a simpler version to quanteda.io.

We might need to give the **tm** author (or heavy users) a chance to respond.

**Comment by kbenoit** [comment]
Agreed, this is great and it's something we've been planning to do for some time just haven't.

Would be interesting to add Python's NTLK as well.

I agree with @koheiw that the function names are more informative than the checks and x's but the table is going to get pretty large!

**Comment by stefan-mueller** [comment]
See the PR #1058. Note that there are still some problems. The table is indeed pretty large although I have removed **austin** already. We might think about keeping only R packages (and remove NLTK). I'm not sure whether there are better ways to format tables in RMarkdown. Moreover, @kbenoit could you move the [table]( https://github.com/stefan-mueller/table-compare-quanteda/blob/master/compare_quanteda.csv) to the **quanteda** repo and load it in a different way?

@koheiw: on the main page of quanteda.io we might just summarise the main **quanteda** functions and refer to the article and the [cheat sheet](https://github.com/kbenoit/quanteda/raw/master/docs/articles/cheatsheet/quanteda-cheatsheet.pdf) for more detailed overviews. We should keep quanteda.io as clean as possible.
