### ISSUE TITLE
Lift length limit in textstat_collocation for lambda

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1049]
```r
col <- textstat_collocations(toks, size = 2:10, min_count = 10)
```
entails
```
 Error in textstat_collocations.tokens(toks_kanji, size = 2:10, min_count = 10) : 
  Only bigram, trigram, 4-gram and 5-gram collocations implemented so far. 
```
but the lamda method does not have such a limitation actually.

**Comment by kbenoit** [comment]
The limit is only there to stop the computer from freezing, since it's very memory intensive to compute ngrams of very large size.  But I agree, let's remove the limits.

**Comment by koheiw** [comment]
If `min_count` is high, it should not be too intensive. Let's remove the limits and add `R_CheckUserInterrupt()` in the outer loop to allow users to stop.
