### ISSUE TITLE
quanteda can't be installed on MacOS from CRAN

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#1053]
Hi,
I'm giving a text analysis course and some students with a macbook are unable to install quanteda via CRAN ('no version could be found for R Version X.X'). They all have a recent version of R installed.

Could this be related to the `xcode` instructions for installing from github? Unfortunately I have no experience with macOS at all.

Installing from github didn't work either, but this was without `xcode` being installed beforehand, so this might fix it.

**Comment by kbenoit** [comment]
If you are using R 3.4.2 it should install fine from CRAN or a CRAN mirror. If you are not using 3.4.2, I don't know.

For once, I would suggest installing only the CRAN version from source, using
```r
install.packages("quanteda", type = "source")
```

To be able to build the source, you need to have installed the items described from the [GitHub page](https://github.com/kbenoit/quanteda/blob/master/README.md).

#### macOS
```
xcode-select --install
```

#### Windows

Install [RTools](https://cran.r-project.org/bin/windows/Rtools/).

**Comment by methodds** [comment]
Thanks for the fast response, I contacted them and will report back to you asap.

**Comment by methodds** [comment]
After reinstalling everything quanteda installed without any problems. Sorry for the false alarm, this can be closed :)
