### ISSUE TITLE
Subsetting on dates doesn't give error on integer

### ISSUE THREAD

**Issue by tpaskhalis** [kbenoit/quanteda#106]
As some corpora contain metadata of class `Date`, `subset()` function allows selecting documents based on this information. The issue is that it accepts arguments of multiple classes, such as `Date`, `character` and `numeric`.  This makes it possible, by mistake, to supply an integer in the form `1980-01-01`, which leads to the actual subtraction, resulting in `1978`, which, in turn, is evaluated as a number of days since epoch, depending on the system.

It's difficult to tell whether it is expected behaviour or not. My main argument against this being normal behaviour is that the function `as.Date(1980-01-01)` returns an error, due to unspecified origin. While inside `subset()` it behaves as if origin is explicitly specified. But, strictly speaking, `Date` has type double. Honestly, my feeling is that we cannot do much about it, as this seems to be the behaviour of base R function `subset.data.frame`. Unless we can actually confirm that this is a bug in base R. So far, I couldn't find anything on Bugzilla.

```
> df <- data.frame(name = letters[1:10], 
+                  date = seq(as.Date("1976/1/1"), as.Date("1985/1/1"), "years"))
> 
> subset(df, date > as.Date("1980/1/1"))
   name       date
6     f 1981-01-01
7     g 1982-01-01
8     h 1983-01-01
9     i 1984-01-01
10    j 1985-01-01
> subset(df, date > "1980/1/1")
   name       date
6     f 1981-01-01
7     g 1982-01-01
8     h 1983-01-01
9     i 1984-01-01
10    j 1985-01-01
> subset(df, date > 1980/1/1)
   name       date
1     a 1976-01-01
2     b 1977-01-01
3     c 1978-01-01
4     d 1979-01-01
5     e 1980-01-01
6     f 1981-01-01
7     g 1982-01-01
8     h 1983-01-01
9     i 1984-01-01
10    j 1985-01-01
```

**Comment by kbenoit** [comment]
Not a bug - this is just how R evaluates expressions. `1980-01-01` is an arithmetic operation involving three numerics. `as.Date("1980/01/01")` with the comparison operator `>` keeps the two quantities as dates, as does the properly formatted strings "1980/01/01" or "1980-01-01".

So `subset.corpus()` with dates works exactly the way `subset.data.frame()` works. It's not a bug, it's a feature!
