### ISSUE TITLE
Potential C++ bug in wordfish

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1063]
I was running Memtest, and [its output](https://github.com/kbenoit/quanteda/files/1461086/valgrind.txt) suggested wordfish has some issue.
https://github.com/kbenoit/quanteda/blob/72d653b66bbc520992d831338b4bd33190c2b65b/src/wordfish_mt.cpp#L325

Suggested change is to
```c++
std::mt19937 mt(time(0));
```
which seems to be OK with Memtest.

You can run Memtest in `test-valgrind` branch, but complete package check takes very long time, so use commands in https://github.com/kbenoit/quanteda/blob/test-valgrind/tests/valgrind/textmodel_wordfish.R on individual files.

Don't forget to install valgrind `sudo apt-get install valgrind`.

**Comment by kbenoit** [comment]
@HaiyanLW can you investigate?

**Comment by HaiyanLW** [comment]
I cannot install `Valgrind` on my windows machine. But time(0) will generate same value if loops within mili-second, see this [link](https://stackoverflow.com/questions/29549873/stdmt19937-doesnt-return-random-number). `std::random_device rd; mt19937 mt(rd());` is very standard way to [generate random number](http://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution). 
@koheiw Is this issue always there or just once?
