### ISSUE TITLE
Need to be able to segment a corpus by fixed-length segments

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1066]
For instance, split a corpus of 10 documents into new, smaller documents of fixed token lengths.

I am thinking this would be implemented via:

```r
corpus_reshape(x, what = "segments", segment_length = 10L, ...)
```
where `...` passes through options to `tokens()`.

However, this might be a new `tokens_reshape()` argument. Or `tokens_segment()`, although we have kept that internal in the documentation index.

**Comment by koheiw** [comment]
We can split corpus by character length, but not by words. It should be in `tokens_reshape()`. What is the use case of this function?

**Comment by kbenoit** [comment]
Basically, for the **LIWCalike** package. The LIWC program segments documents into fixed token-length pieces and scores each one for sentiment, and I wanted to be able to replicate that. Could easily put this in **LIWCalike** only though.

**Comment by kbenoit** [comment]
Duplicates #679
