### ISSUE TITLE
dfm function sensitive to Japanese wide characters

### ISSUE THREAD

**Issue by Shooony** [kbenoit/quanteda#1068]
Here is the code I have:

> corpus("におきましてはＭＳＡ小麦の上におきましても")
Corpus consisting of 1 document and 0 docvars.
> dfm(corpus("におきましてはＭＳＡ小麦の上におきましても") )
Document-feature matrix of: 1 document, 7 features (0% sparse).
1 x 7 sparse Matrix of class "dfmSparse"
       features
docs    におきまして は ｍｓａ 小麦 の 上 も
  text1            2  1      1    1  1  1  1
> featnames(dfm(corpus("におきましてはＭＳＡ小麦の上におきましても") ))
[1] "におきまして" "は"           "ｍｓａ"       "小麦"         "の"           "上"          
[7] "も"          
> featnames(dfm(corpus("におきましてはＭＳＡ小麦の上におきましても") ))[3]
[1] "ｍｓａ"
> featnames(dfm(corpus("におきましてはＭＳＡ小麦の上におきましても") ))[3] == "msa"
[1] FALSE
> featnames(dfm(corpus("におきましてはＭＳＡ小麦の上におきましても") ))[3] == "ＭＳＡ"
[1] FALSE
> featnames(dfm(corpus("におきましてはＭＳＡ小麦の上におきましても") ))[3] == "ｍｓa"
[1] FALSE
> featnames(dfm(corpus("におきましてはＭＳＡ小麦の上におきましても") ))[3] == "ｍｓａ"
[1] TRUE

Is there any way to fix this?

**Comment by koheiw** [comment]
Great to see that you are using **quanteda** for Japanese texts. Token types are normalized using `stringi::stri_trans_nfc()` internally, so you should wrap your Japanese words by it before comparing with dfm features.

```r
require(quanteda)
corp <- corpus("におきましてはＭＳＡ小麦の上におきましても")
jp_dfm <- dfm(corp, tolower = FALSE)

featnames(jp_dfm) == stringi::stri_trans_nfc('ＭＳＡ')
# [1] FALSE FALSE  TRUE FALSE FALSE FALSE FALSE
```
However, we don't think you have to do it in most of the cases, because `dfm_select()` will the job for you.
```r
dfm_select(jp_dfm, 'ＭＳＡ')
# Document-feature matrix of: 1 document, 1 feature (0% sparse).
# 1 x 1 sparse Matrix of class "dfm"
#      features
# docs    MSA
#  text1   1

dfm_select(jp_dfm, 'msa')
# Document-feature matrix of: 1 document, 1 feature (0% sparse).
# 1 x 1 sparse Matrix of class "dfm"
#       features
# docs    MSA
#  text1   1

```

**Comment by kbenoit** [comment]
@koheiw I suggest we use @patperry’s new **utf** package add `utf8::utf8_normalize()` to our corpus constructor, so that all text is correctly UTF-8 converted and normalised. 

Related to https://github.com/kbenoit/quanteda/issues/189, which I think we moved to **readtext**.

**Comment by patperry** [comment]
Probably better to use **stringi** for this rather than add another dependency.

**Comment by kbenoit** [comment]
So: I hadn't realised this, but @koheiw already implemented normalisation for tokens and for the `pattern` argument (which includes that in `dfm_select()` etc). 

We cannot do anything about users entering strings directly (literally) so there is not really anything more to be done here.
