### ISSUE TITLE
tokens_lookup not working

### ISSUE THREAD

**Issue by riccardopinosio** [kbenoit/quanteda#1074]
Let's do:

`test <- tokenize(c('this is a test', 'of the great Quanteda package'))`

Then:

`dic <- dictionary(list(banana = c('Quanteda', 'test')))`

Then:

`tokens_lookup(test, dictionary = dic, valuetype = 'grob', exclusive = FALSE)`

Returns:

Error in UseMethod("tokens_lookup") : no applicable method for 'tokens_lookup' applied to an object of class "c('tokenizedTexts', 'list')"

What am I doing wrong here?

R.

**Comment by kbenoit** [comment]
For starters, you are not using the latest version of the package - otherwise `tokenize()` would fail, since we finally removed this deprecated function.  Please update and try it again. You will know if it works since 

```r
example(tokens_lookup)
```
will work.

**Comment by riccardopinosio** [comment]
Indeed, updating the package and replacing tokenize() with tokens() everything works as expected. The issue can be closed.
(btw: thanks a 1000000 for the amazing package. I'm making very extensive use of it and it's great!)
