### ISSUE TITLE
Make fcm() capable of handling big objects

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1076]
Currently, we cannot reproduce the steps from http://text2vec.org/glove.html, using `fcm()` instead of `tcm()` from the **text2vec** package:

```r
> wiki <- corpus(readtext::readtext("http://mattmahoney.net/dc/text8.zip"))
> wiki_dfm <- dfm(wiki, verbose = TRUE)
Creating a dfm from a corpus input...
   ... lowercasing
   ... found 1 document, 253,853 features
   ... created a 1 x 253,853 sparse dfm
   ... complete. 
Elapsed time: 19.7 seconds.
> features_to_keep <- featnames(dfm_trim(wiki_dfm, min_count = 5, verbose = TRUE))
Removing features occurring: 
  - fewer than 5 times: 182,563
  Total features removed: 182,563 (71.9%).
> wiki_toks <- tokens(wiki) %>% tokens_select(features_to_keep, padding = TRUE)
> length(features_to_keep)
[1] 71290
> length(features_to_keep)^2
[1] 5082264100

> fcm(wiki_toks, context = "window", count = "weighted", weights = 1/(1:5), tri = TRUE)

error: SpMat::init(): requested size is too large
 Error in qatd_cpp_fcm(x, length(types), count, window, weights, ordered,  : 
  SpMat::init(): requested size is too large 
```

But **text2vec**'s `create_tcm()` makes easy work of it:
```r
> str(tcm)
Formal class 'dgTMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:13945001] 56593 60751 56742 68713 62493 69896 66660 59436 60469 68759 ...
  ..@ j       : int [1:13945001] 71123 67159 70506 70044 71074 70661 69403 69722 69360 70844 ...
  ..@ Dim     : int [1:2] 71290 71290
  ..@ Dimnames:List of 2
  .. ..$ : chr [1:71290] "nulla" "caprivi" "rededication" "sutures" ...
  .. ..$ : chr [1:71290] "nulla" "caprivi" "rededication" "sutures" ...
  ..@ x       : num [1:13945001] 0.2 0.2 0.25 1 3.12 ...
  ..@ factors : list()
> prod(dim(tcm))
[1] 5082264100
```

See the `vignettes/pkgdown_only/quanteda_and_text2vec.Rmd` in the branch `dev-text2vec`.

**Comment by koheiw** [comment]
I set `ARMA_64BIT_WORD` in armardillo.h, so it no longer say `error: SpMat::init(): requested size is too large`. However, the program crashes when `qatd_cpp_fcm()` returns the large matrix to R. I think it should return `dgCMatrix` instead of `arma::sp_mat`.

See:
https://cran.r-project.org/web/packages/RcppEigen/vignettes/RcppEigen-Introduction.pdf

**text2vec**'s solution to this problem is here:
https://github.com/dselivanov/text2vec/blob/master/src/SparseTripletMatrix.h

**Comment by kbenoit** [comment]
If the solution is as easy as outputting a simple triplet sparse matrix, then we can convert in R using `as(x, “dgCMatrix”)` which is a super-fast conversion from triplet to sparse column.

**Comment by HaiyanLW** [comment]
`arma::sp_mat` is a sparse matrix, see this [link](https://cran.r-project.org/web/packages/RcppArmadillo/vignettes/RcppArmadillo-sparseMatrix.pdf)

**Comment by koheiw** [comment]
It now returns `dgTMatrix` using `i`, `j`, `x` extracted from `concurrent_vector`. Counting of tokens in the Wiki corpus takes only 1.5 second. Conversion to matrix was taking around 15 seconds before, but it is less than 4 seconds now.

```r
> fcm(wiki_toks, context = "window", count = "weighted", weights = 1/(1:5), tri = TRUE)
'Count'              1469.42 millsec
'Convert'            3660.89 millsec
Feature co-occurrence matrix of: 71,290 by 71,290 features.
```

We should use the same technique in `qutd_cpp_ca` too.
