### ISSUE TITLE
text model objects need extractor methods

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#108]
`textmodel_fitted_*` and `textmodel_predicted_*` objects need more extractor and other methods, similar to those for `lm` class objects. Currently, just `print` and `predict` methods are implemented. Candidates are:
- [ ] `confint`  
- [ ]  `formula`  
-  [ ] `summary`  
- [ ]  `model.frame`  and `model.matrix  
- [ ]  `ndoc`, `feature`  
- [ ]  `plot`  
- [ ]  `simulate`?  
- [x]  `coef`

**Comment by koheiw** [comment]
See #1007 too.

**Comment by kbenoit** [comment]
Now being resolved as part of #1007.
