### ISSUE TITLE
textstat_lsa needs margin argument

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1085]
It is great to have `textstat_lsa` but we need `margin` argument to use it for a large matrix. When estimate term-term similarity (`margin = features`) we do not need `u` matrix at all, so this is the most efficient way:
```r
S <- RSpectra::svds(mt, k=300, nu=0, nv=300, opts = list(tol = 1e-5))
result <- S$v * S$d
```
If we do not specify the margin, it takes more memory:
```r
out1 <- RSpectra::svds(mt, k=300, nu=0, nv=300, opts = list(tol = 1e-5))
out2 <- RSpectra::svds(mt, k=300, nu=300, nv=300, opts = list(tol = 1e-5))
print(object.size(out1), units = 'MB') # 113.4 Mb
print(object.size(out2), units = 'MB') # 362.5 Mb
```

Further, we should not take a product of `v`, `d`, and `u` unless `margin = both`, because it will produce large smoothed (dense) matrix:
https://github.com/kbenoit/quanteda/blob/6bb1a3aa28e17be27dd77c6b6f00cca84ab04802/R/textmodel_lsa.R#L77

**Comment by kbenoit** [comment]
That sounds fine to me, if you want to make that change.

**Comment by koheiw** [comment]
We do, but not always full-size low-rank matrix:
```r

dim(mt) # 108834  49561
nd <- 300

# margin = documents
dec_doc <- RSpectra::svds(mt, k= nd, nu = 0, nv = nd)
space$matrix_low_rank <- dec_doc$v * dec_doc$d
dim(space$matrix_low_rank) # 49561   300

# margin = both
dec_both <- RSpectra::svds(mt, k = nd, nu = nd, nv = nd)
space$matrix_low_rank <- dec_both$u %*% diag(dec_both$d) %*% t(dec_both$v)
dim(space$matrix_low_rank) # Error: cannot allocate vector of size 40.2 Gb

# margin = features
dec_feat  <- RSpectra::svds(t(mt), k = nd, nu = 0, nv = nd)
space$matrix_low_rank <- t(dec_feat$v * dec_feat$d)
dim(space$matrix_low_rank) # 300 108834
```

**Comment by HaiyanLW** [comment]
The `space$matrix_low_rank ` for margin = documents/features is not very suitable to be called `low_rank_matrix`
