### ISSUE TITLE
add POS (part of speech) tagger

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#109]
Initially, this should be implemented as a separate package that depends on quanteda. It should provide a link to external libraries, such as spaCy, Stanford core NLP, or openNLP. It would add the ability to work with pre-tokenized corpora, where a corpus would be stored as a data.table consisting of  
-  textID  
-  token  
-  type (separator, space, punctuation)  
-  part of speech tag  
-  index position

**Comment by tpaskhalis** [comment]
I added HMM POS tagger, that I showed you before, to my dev branch. It works fine, but I would still need to parse Brown corpus to get better training set.

https://github.com/tpaskhalis/quanteda/blob/dev_postag/R/postag.R

**Comment by dselivanov** [comment]
@tpaskhalis did you compare speed / accuracy of your HMM tagger with `spaCy`?

**Comment by tpaskhalis** [comment]
@dselivanov It doesn't really make much sense at the moment. HMM would be in theory inferior to averaged perceptron that is used in `spaCy` or `NLTK`. It was just easier to program without adding clunky external dependencies. I will try to add perceptron implementation as well  at some point.

**Comment by dselivanov** [comment]
@tpaskhalis I totally agree, that it would be nice to have good POS tagger without a lot of external dependencies (especially java). The reason I asked is that I had plans to implement some fast and accurate POS tagger in text2vec (thought about averaged perceptron as in `spaCy`). But I want to avoid reinventing the wheel if it already done here.

**Comment by kbenoit** [comment]
Moved to development of the [**spacyr** package](https://github.com/kbenoit/spacyr).
