### ISSUE TITLE
KWIC problems with quanteda Windows Japanese

### ISSUE THREAD

**Issue by HoenenA** [kbenoit/quanteda#1095]
Dear team,

trying to do the KWIC function for a Japanese text, it appears to not work.
```r
Sys.setlocale("LC_ALL","Japanese")
library(quanteda)
doc <- readLines(file.choose())
Encoding(doc)<-"UTF-8"
#doc<-as.character(doc)
kwic(doc,"子",window=5)
```
gives me an empty result although the token appears in the text.
At some point this code produced something useful, but for some reason I cannot
understand it stopped to work on the same computer the next day:
```r
text<-lapply(kwic(doc,"子",window=5),as.character)
```
I give SessionInfo
```r
> sessionInfo()
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Japanese_Japan.932  LC_CTYPE=Japanese_Japan.932    LC_MONETARY=Japanese_Japan.932
[4] LC_NUMERIC=C                   LC_TIME=Japanese_Japan.932    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_0.99.22   tm_0.7-2           NLP_0.1-11         wordcloud_2.5      RColorBrewer_1.1-2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.14        magrittr_1.5        xml2_1.1.1          munsell_0.4.3       colorspace_1.3-2   
 [6] lattice_0.20-35     rlang_0.1.4         fastmatch_1.1-0     stringr_1.2.0       plyr_1.8.4         
[11] tools_3.4.2         parallel_3.4.2      grid_3.4.2          data.table_1.10.4-3 gtable_0.2.0       
[16] spacyr_0.9.3        lazyeval_0.2.1      RcppParallel_4.3.20 tibble_1.3.4        Matrix_1.2-11      
[21] ggplot2_2.2.1       slam_0.1-40         stringi_1.1.6       compiler_3.4.2      scales_0.5.0       
[26] lubridate_1.7.1  
```
and attach the input file. Would be happy for any suggestions. On linux the same code works fine.

[中島敦_弟子.txt](https://github.com/kbenoit/quanteda/files/1514222/_.txt)

**Comment by kbenoit** [comment]
Try inputting the text using the **readtext** package, and make sure that the source file encoding is identified correctly. (If it's UTF-8, you should be fine.)

**Comment by HoenenA** [comment]
Hi, 
I tried
```r
library(readtext)
 doc<-readtext("C:/myPath/filenameinLatin.txt",encoding="UTF-8")
kwic(doc,"子",window=5)
```
with the same result, an empty output; as I said on Linux the above code works with readLines;
also the file is encoded in UTF-8. It still won't work.

**Comment by stefan-mueller** [comment]
Hi,

I downloaded your file and had a try. It's indeed formatted in UTF-8 and I could open it properly on my Mac.

```r


library(readtext)
library(quanteda)
library(readr)

texts <- readtext("_.txt")

corpus_texts <- corpus(texts)

readr::guess_encoding(texts$text)

# # A tibble: 1 x 2
# encoding confidence
# <chr>      <dbl>
#   1    UTF-8          1

kwic(corpus_texts ,"子", window=5) %>% 
  head(5)

# [text1, 16]          仲 由、 字 は | 子 | 路 という 者 が、   
# [text1, 336]        な の だ から、 | 子 | 路 は 勢 込 ん      
# [text1, 599] しかし」 と、 それでも | 子 | 路 は なお 逆襲 する
# [text1, 878]       で ある。 即日、 | 子 | 路 は 師弟 の 礼    
# [text1, 902]      よう な 人間 を、 | 子 | 路 は 見 た こと 
```
Does this work on your machine?

**Comment by HoenenA** [comment]
Hi again, 
thanks first of all for the efforts. Now, I tried
```r
 texts <- readtext("*.txt")#suppose it was meant to be a star
 corpus_texts <- corpus(texts)
 readr::guess_encoding(texts$text)
#here i get:
# A tibble: 1 x 2
#  encoding confidence
#     <chr>      <dbl>
#1    UTF-8          1
#Warning message:
#In if (grepl("\n", file)) { :
#  the condition has length > 1 and only the first element will be used
```
then I use your kwic + head combination but the result remains empty, even if I use Encoding(text$texts)<-"UTF-8" which gives no error, no effect. But I see in the variable window of RStudio, that the texts$text content is still somehow in the wrong encoding, I guess. I'll keep on trying some other solutions,,,

**Comment by kbenoit** [comment]
This is happening because although your text file is encoded as UTF-8, your Windows locale is [Japanese.932](https://en.wikipedia.org/wiki/Shift_JIS). `readtext()` uses assumed the native encoding by default, so is garbling the text when it expects Windows-932 and gets UTF-8.

The fix (tested on my Windows 10 VM):
```r
texts <- readtext::readtext("C:/Users/kbenoit/Downloads/*.txt", encoding = "UTF-8")
corpus_texts <- corpus(texts)
kwic(corpus_texts, "子", window = 2) %>% head()

##    [text1, 16]                         <U+5B57> <U+306F> | <U+5B50> | <U+8DEF> <U+3068><U+3044><U+3046>        
##   [text1, 336]                  <U+304B><U+3089><U+3001> | <U+5B50> | <U+8DEF> <U+306F>                        
##   [text1, 599] <U+3001> <U+305D><U+308C><U+3067><U+3082> | <U+5B50> | <U+8DEF> <U+306F>                        
##   [text1, 878]                  <U+5373><U+65E5><U+3001> | <U+5B50> | <U+8DEF> <U+306F>                        
##   [text1, 902]                          <U+3092><U+3001> | <U+5B50> | <U+8DEF> <U+306F>                        
##  [text1, 1034]                          <U+306F><U+3001> | <U+5B50> | <U+8DEF> <U+306B><U+3068><U+3063><U+3066>
```
Notice that while the text is fine, it is not printing correctly in kwic, but will print correctly using the `cat()` method:
```r
cat(mykwic$pre[1])
## 仲 由 、 字 は
``` 

If you work in a primarily Windows environment with Windows-932 encoding, you could always convert the texts either before or after import, although the advantages of working with UTF-8 instead of one of the older 8-bit encodings are extensive.

**Comment by HoenenA** [comment]
D'OH (*slightly embarrassed*)
thank you so much.
I thought about something like this, the strange thing was, that Sys.setlocale("LC_ALL","Japanese") would work, but setlocale to "ja_JP.UTF-8" not. And one doesn't exactly expect R or RStudio to choose some encoding like 932 over utf8. And also strange that although I set the System locale of Windows globally to ja_JP.UTF-8 and R keeps the locale set as German... probably upon install, but reinstalling all packages ... The cat solution is nice, the following code approximates kwic normal output
```r
text<-lapply(kwic(doc,"子",window=5),as.character)
for (i in 1:5){
print(paste0(text$pre[i ],"     |",text$keyword[i],"|    ",text$post[i]))
}
```
So for me that closes the issue. Once again thank you very much! Keep up the great community work.
