### ISSUE TITLE
Rename quantedaData to quanteda_data

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1106]
`quantedaData`'s camel case is the legacy, so need to be renamed to `quanteda_data`.

**Comment by kbenoit** [comment]
True that the camel case is inconsistent, but the underscore seems not to be allowed for CRAN package names, according to https://stackoverflow.com/questions/24201568/whats-a-good-r-package-name. _R Packages_ also states this, http://r-pkgs.had.co.nz/package.html#naming.

But the reference appears to have changed now.  From https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Package-structure:

> For maximal portability filenames should only contain only ASCII characters not excluded already (that is A-Za-z0-9._!#$%&+,;=@^(){}'[] — we exclude space as many utilities do not accept spaces in file paths): non-English alphabetic characters cannot be guaranteed to be supported in all locales.

However, there are no listed packages on CRAN that contain underscores in the name, and I don't propose we start.

In general, if there are direct extension packages for **quanteda**, call it (maybe?) the "quantedaverse", then should the first part of the package name reference **quanteda**?  **tm** has __tm.plugin.*__ packages but I would like to avoid the "." character if possible.

**Comment by koheiw** [comment]
We should allow `tm` style extension of data and models. Their names should contain **quanteda**, but need some delimiter. If **quanteda.data** should be avoided, **quanteda#data** or  **quanteda$data**? Compared to them, **quanteda_data** looks normal.

**Comment by stefan-mueller** [comment]
I agree that we should not use special characters in package names. What about **quantedata** (or is this too confusing/similar to **quanteda**)? **quantedaverse** or something similar might make sense to load **quanteda**, **readtext**, **quantedaData** and **spacyr** at once.

**Comment by kbenoit** [comment]
What if we call this **quanteda.corpora**?

Then we can create another called **quanteda.dictionaries**.

**Comment by koheiw** [comment]
*quanteda.corpora* is fine to me.

**Comment by koheiw** [comment]
Renamed 
https://github.com/quanteda/quanteda.corpora
