### ISSUE TITLE
Why head.dfm drops features?

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1110]
`head.dfm()` and `head.tokens()` heave differently:

`head.dfm()` drops features
```r
immi_dfm <- dfm(data_char_ukimmig2010)
dim(immi_dfm) # [1]    9 1656
dim(head(immi_dfm)) # [1] 6 6
```
while `head.tokens()` does not:
```r
immi_toks <- tokens(data_char_ukimmig2010)
dim(dfm(head(immi_toks))) # [1]    6 1509
```
I think `head.dfm()` should not drop any features. Current behavior looks like legacy of the older version that printed a dfm.

**Comment by kbenoit** [comment]
The reason it behaves that way is that there are typically huge numbers of features. The way to display more features is via `nfeature`. `head()` is just to inspect the dfm. However we could make the new default to be `nfeature = nfeature(x)`.

```r
> head(data_dfm_lbgexample)
Document-feature matrix of: 6 documents, 6 features (80.6% sparse).
6 x 6 sparse Matrix of class "dfm"
    features
docs A B  C  D  E  F
  R1 2 3 10 22 45 78
  R2 0 0  0  0  0  2
  R3 0 0  0  0  0  0
  R4 0 0  0  0  0  0
  R5 0 0  0  0  0  0
  V1 0 0  0  0  0  0
> head(data_dfm_lbgexample, nfeature = 10)
Document-feature matrix of: 6 documents, 10 features (70% sparse).
6 x 10 sparse Matrix of class "dfm"
    features
docs A B  C  D  E  F   G   H   I   J
  R1 2 3 10 22 45 78 115 146 158 146
  R2 0 0  0  0  0  2   3  10  22  45
  R3 0 0  0  0  0  0   0   0   0   0
  R4 0 0  0  0  0  0   0   0   0   0
  R5 0 0  0  0  0  0   0   0   0   0
  V1 0 0  0  0  0  0   0   2   3  10
```

**Comment by koheiw** [comment]
I understand why it became like that, but it should be `nfeature = nfeature(x)` in `head.dfm()`, and stop printing all the features in `print.dfm()`.

**Comment by kbenoit** [comment]
Not sure what you mean by "stop printing all the features in `print.dfm()`". The print method invocation is not part of `head.dfm()` at all, but rather the consequence of the automatic `print.dfm()` call when the output of `head()` is sent to the console. (That at least is consistent!)

**Comment by kbenoit** [comment]
Note that there is no `head.tokens()` - this just calls `head.list()` which returns the first `n` elements of the list (in the case above, documents).
