### ISSUE TITLE
Why extractor for collocation object is disabled?

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1114]
Without this method, `collocations` objects become plain `data.frame` when subset.
https://github.com/kbenoit/quanteda/blob/356d24149c70dbadff346b773afaf4de16c0818a/R/textstat_collocations.R#L206-L215

It much easier keep them as `collocations` because 

```r
# as data.frame
tokens_compound(toks, phrase(seqs[seqs$p < 0.01, 'collocation']))

# as collocations
tokens_compound(toks, seqs[seqs$p < 0.01])
```

**Comment by kbenoit** [comment]
Not sure what happened to it, but by all means add it back.
