### ISSUE TITLE
feature request: function for network data as prestep for a network plot

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#1117]
Hi,

related to @kbenoit 's suggestion in  #782, it would be very useful to have a function, e.g. `textstat_network()` which stores data for semantic networks, either in a df or in a network object. The current function `textplot_network()` could then take this as input for creating network plots. I think this has two advantages:
- it would probably be easier to implement alternative ways of creating networks in the future.
- users who would like to do more than just plotting a network could use the object from `textstat_network()` for their needs.

**Comment by koheiw** [comment]
I will add `as.network` method for fcm. I was thinking of doing this on request.
