### ISSUE TITLE
get laptop stickers for launch

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1123]
https://www.stickermule.com/uk/custom-stickers

Could just be the logo, or 

something else, like **quanteda** replacing Dharma in ![](https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Dharma_Initiative_logo.svg/1200px-Dharma_Initiative_logo.svg.png)

**Comment by stefan-mueller** [comment]
Laptop stickers would be fantastic! @koheiw, I count on your creativity.

**Comment by koheiw** [comment]
Would be like one for Amazon in the picture:
https://www.stickermule.com/uk/products/rectangle-stickers
but it should have round corner:
https://www.stickermule.com/uk/products/rounded-corner-stickers

How many do we need? 500? I can make a Dharma parody too.

**Comment by kbenoit** [comment]
Stickermule can do any shape we want, including Octogon. 

If we call the org the Quanteda Initiative, then anyone who is a Lost fan will recognise the reference. Maybe replace the bars in the Octagon with text?

Namaste!

**Comment by stefan-mueller** [comment]
Yes, replacing the bars with text is a good idea. Note that most R packages use the shape of a hexagon (https://www.stickermule.com/user/1070448958/stickers). So if we transfer the **quanteda** principle of inter-operability to sticker shapes (I admit, this sounds weird), an octagon might be problematic. If we go for a hectagon, we would also need to have the same sticker size as the other R packages. 

But I'm fine if we stand out and go for an octagon to keep the reference to Dharma alive (and then make the sticker size slightly larger than the other R package stickers to show that the octagon was not a failed replication of other stickers).

**Comment by koheiw** [comment]
I agree that our sticker should be collectable. We can make both rectangular and hexagon.

**Comment by kbenoit** [comment]
Octagon if we go with the Dharma design - hexagon is only for making the tidyverse components fit, so we don’t need that. In fact we should be distinct from it.

Collectible? That goes without saying!!

**Comment by stefan-mueller** [comment]
Ok, let's go for an Octagon that is slightly larger than the tidyverse stickers (they are 4.4 cm x 5.1 cm)?
