### ISSUE TITLE
Why nfeature() instead of nfeat()?

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1134]
`nfeature()` and `ndocument()` is consistent naming, but `nfeature()` and `ndoc()` is not. Relatedly, why not `topfeat()` instead of `topfeatures()`?

**Comment by kbenoit** [comment]
We could rename the main function to `nfeat()`, but keep `nfeature()` as an invisible alias.

`topfeatures()` is already an exception, and I don’t think we should change it now.

**Comment by koheiw** [comment]
OK leave `topfeatures()` now, and add `nfeat()` and `ndocument()`. We will have 

 full name | alias
--- | ---
`nfeature()`| `nfeat()`
`ndocument()`| `ndoc()`

I can do this along with #1133.

**Comment by kbenoit** [comment]
No need to add `ndocument()`, but let’s add `nfeat()`. It’s consistent with the other function names, but also consistent with base R `n*` functions, e.g. `nrow()`, `ncol()`, etc
