### ISSUE TITLE
Why are tf.dfm() and tfidf.dfm() exported? 

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1135]
They should be only accessible through `dfm_weight()`.

**Comment by kbenoit** [comment]
They permit more fine-grained control over weighting. See the examples.

**Comment by koheiw** [comment]
Can't we do that by adding more augments or `...` to `dfm_weight()`?  We should at least name `dfm_tf()` and `dfm_tfidf()` to comply with the naming rule.

**Comment by kbenoit** [comment]
We could add those as aliases, but I know too many people who use those as is to remove them. Could hide and deprecate them.

The other inconsistency is the names of the schemes, e.g. “relfreq” v. “prop”. 

I’m open to ideas, clearly I didn;t solve this ideally in the current setup!
