### ISSUE TITLE
Convert tokens to dictionary indices

### ISSUE THREAD

**Issue by FarzanT** [kbenoit/quanteda#1138]
Hello, I was not able to find a solution to my problem below:
Suppose I have created a DFM; how can I get a representation of each document as a sequence of the word indices? Suppose we have:
```R
> text = "I love the quanteda package"
> text2 = "I love the R language"
> myDFM = dfm(c(text, text2))
> myDFM
Document-feature matrix of: 2 documents, 7 features (28.6% sparse).
2 x 7 sparse Matrix of class "dfm"
       features
docs    i love the quanteda package r language
  text1 1    1   1        1       1 0        0
  text2 1    1   1        0       0 1        1
```
What I want `text1` to be is:
`1 2 3 4 5`
and `text2` to be 
`1 2 3 6 7`
How can one achieve this for a large DFM?

P.S. I basically want the same results that `keras::texts_to_sequences` provides:
```R
> keras_tokenizer = text_tokenizer() %>% fit_text_tokenizer(x = c(text, text2))
> keras_tokenizer %>% texts_to_sequences(c(text, text2))
[[1, 2, 3, 4, 5], [1, 2, 3, 6, 7]]
```
This will allow the full replacement of __quanteda__ with the (minimal) text pre-processing that __keras__ has.
Thanks!

**Comment by koheiw** [comment]
I like you example text.  How about this?
```r
text = c("I love the quanteda package",
         "I love the R language")
unclass(tokens(text))
```

**Comment by kbenoit** [comment]
@koheiw has shown how this would work, but since we are not really familiar with the keras format, if you could supply a more specific example we could probably add a converter function. It would be something like this:

```r
text <- c("I love the quanteda package",
          "I love the R language")
toks <- tokens(text)

as.keras <- function(x) {
    UseMethod("as.keras")
}

as.keras.tokens <- function(x) {
    retval <- unclass(x)
    attributes(retval) <- NULL
    names(retval) <- names(x)
    retval
}

as.integer(toks)
# $text1
# [1] 1 2 3 4 5
# 
# $text2
# [1] 1 2 3 6 7
```

But it would be very easy also to do this from a dfm, if you want the counts from a dfm, or a weighted dfm. 

Please supply a more specific use case.

**Comment by FarzanT** [comment]
Thank you!
Here is an example use case:
```R
> text1 = "I love the quanteda package"
> text2 = "I love the R language"
> myDFM = dfm(c(text, text2))
> myDFM
Document-feature matrix of: 3 documents, 7 features (28.6% sparse).
3 x 7 sparse Matrix of class "dfm"
       features
docs    i love the quanteda package r language
  text1 1    1   1        1       1 0        0
  text2 1    1   1        0       0 1        1
  text3 1    1   1        0       0 1        1
```
Using `quanteda::tokens()`
```R
> myTokens = tokens(c(text1, text2))
> unclassed = unclass(myTokens)
> unclassed$text1
[1] 1 2 3 4 5
> unclassed$text2
[1] 1 2 3 6 7
```
Using `keras::texts_to_sequences`
```R
> myKerasTokenizer = keras::text_tokenizer() %>%
           keras::fit_text_tokenizer(x = c(text1, text2))
> keras::texts_to_sequences(tokenizer = myKerasTokenizer, texts = c(text1, text2))
[[1, 2, 3, 4, 5], [1, 2, 3, 6, 7]]
```
Now apply to new data (e.g. after seeing the training data, want to use on the test data)
Note that keras uses a python backend here (even in the first example), so must convert to R object (list)
```R
> new_text = "I am in love with the coco"
> python_list = keras::texts_to_sequences(tokenizer = myKerasTokenizer,
           texts = list(new_text))
> r_list = reticulate::py_to_r(python_list)
> r_list
[[1]]
[1] 1 2 3
```
Here, the keras tokenizer only returns the index of the words that it has seen before: _I_, _love_, _the_
How can one use `unclass()` and `tokens()` to get the vocabulary/dictionary indices in _unseen_ data? (unseen by the `tokens` function)

Is there a similar method for DFMs?
Thanks again!

**Comment by koheiw** [comment]
I am still not sure what is the use case, but you can use `c()` to index a new tokens object in the same way as the old. Once `toks` is unclassed, it won't be re-indexed when subset by `[]`. 

```r
text1 <- c(old = "I love the quanteda package")
text2 <- c(new = "I love the R language")

toks1 <- tokens(text1)
toks2 <- tokens(text2)
toks <- c(toks1, toks2)

docnames(toks)
toks_seri <- unclass(toks)
toks_seri[1]
# $old
# [1] 1 2 3 4 5

toks_seri[2]
# $new
# [1] 1 2 3 6 7
```
You can do the same to dfm with `rbind()`:
```r
mt1 <- dfm(text1)
mt2 <- dfm(text2)
mt <- rbind(mt1, mt2)
```

**Comment by FarzanT** [comment]
The first example is exactly what I need!
Unfortunately, I still don't understand how one can convert the DFM to a list of word indices. If there was a function to convert the DFM, it would allow for seamless use of TensorFlow/Keras neural networks on preprocessed text from quanteda, especially since the text-preprocessing capabilities of Keras are quite limited.
Thank you for your time, I'm finally able to run NLP models with __proper__ text preprocessing!

**Comment by koheiw** [comment]
It is easy to convert dfm to a list:
```r
temp <- as(mt, 'dgTMatrix') # mt is a dfm
split(temp@j + 1, temp@i + 1)
```
We should add this to `convert()`.

**Comment by FarzanT** [comment]
Thanks!
I guess it would also be great if the DFM was rank-indexed, i.e. the most frequent word (in the corpus) having an index of 1, and so on.

**Comment by kbenoit** [comment]
`dfm_sort()` will do that.

**Comment by FarzanT** [comment]
This helps, but since we want to use the same indices on the new (test) data, we want to ensure that the indices the the test_DFM actually refer to the words _as they were indexed in the __training__ DFM. Now I can run `dfm_sort(x = train_dfm)`, but how can one get the same indices as in the training vocabulary? Suppose the pipeline below:

```R
# Create a dfm from training data
trainDFM <-
    dfm(
        x = trainCorpus,
        tolower = T,
        remove = stopwords(),
        verbose = T,
        remove_numbers = F,
        remove_punct = T,
        remove_hyphens = F,
        remove_url = T,
        remove_twitter = T,
        remove_symbols = T,
        ngrams = 1:NGRAM_RANGE
    )

# Sort the word by their frequency across the entire training corpus
trainDFM <- dfm_sort(x = trainDFM, margin = "features")

# Convert to the word index list (which is now based on frequency/rank)
temp <- as(trainDFM, 'dgTMatrix')
word_index_list <- split(temp@j + 1, temp@i + 1)

# Create a dictionary of the training word (to allow selection on the test data)
dictDFM <- dfm(paste0(featnames(trainDFM), collapse = " "))

testDFM <- dfm(
    x = testCorpus,
    tolower = T,
    remove = stopwords(),
    verbose = T,
    remove_numbers = F,
    remove_punct = T,
    remove_hyphens = F,
    remove_url = T,
    remove_twitter = T,
    remove_symbols = T
)
# Only keep the words that were seen in the training data
testDFM <- dfm_select(x = testDFM, pattern = dictDFM)
```
Now, if I run `dfm_sort(x = testDFM)`, everything is indexed relative to the `testDFM`, and not the `trainDFM`. (A concatenation of the tokens was suggested above, but I don't think it's applicable to DFM).

It'll be amazing if there's a `convert(x, to = "keras")` function; it would be even better if one could supply the training DFM and get the testing DFM that is processed based on the training DFM, i.e. `dfm_select()` + `index_using_dfm()`

Thank you very much for your time!
