### ISSUE TITLE
Linguistic marker in dfm.

### ISSUE THREAD

**Issue by RBonafide** [kbenoit/quanteda#1139]
Good day. Thank you for your package! It works quicker than some others. But I have some troubles with selecting words with special grammar markers in corpus. It's important for linguistics research, when scientist count grammatical attribute of lexical units.
All texts were stemmed and marked by hands. Text_example (corpus):

```r
require(quanteda)
require(stringr)

ftext <- corpus('i=PR=person be=V=prconts go=V=inf home=N= She=RR=2ndperson')

dict <- list(prepositions = c(str_extract_all(ftext$text, regex("(.?)(=PR=)"))),
             nouns = c(str_extract_all(ftext$text, regex("(.?)(=N=)"))))

# remove repeating words:
dict2 <- dictionary(list(verbs = c(unique(unlist(dict$prepositions))),
                         nouns = c(unique(unlist(dict$nouns)))))

# removing unnecessary markers
dmstm_l <- c("inf", "person")
mydfm <- dfm(lis2, dictionary = dict2, remove_symbols = FALSE, what = "fasterword", 
             remove_numbers = TRUE, remove_punct = FALSE, remove_url = TRUE, remove_separators = FALSE,
             verbose = FALSE, stem = FALSE, tolower = FALSE, remove = c(stopwords = c("english"), dmstm_l))

```
It works correctly. But now i can't find any solution to build matrix with marked words. It should look like:
```
      features
docs             i=pr     be=v   home=n   she
text.txt         400      123     80            300
```
I've tried to do same variants:
1. Extract in dfm only meta symbols with words (by the means of regular expressions) 
2. ngrams=2, but it takes also right word (pr_person). I need only first left grams(i_pr) 
Are there any ideas to solve this problem? Could i use regular expressions in dictionary or in dfm?

**Comment by koheiw** [comment]
How about this?
```r

corp <- corpus('i=PR=person be=V=prconts go=V=inf home=N= She=RR=2ndperson')
toks <- tokens(corp, what = 'fastestword')
type <- types(toks)
type
# [1] "i=PR=person"      "be=V=prconts"     "go=V=inf"         "home=N="          "She=RR=2ndperson"

tag <- str_extract_all(type, regex("^(.+)=([A-Z]+)"), simplify = TRUE)

toks_tag <- tokens_replace(toks, type, tag)                
dfm(toks_tag)
# Document-feature matrix of: 1 document, 5 features (0% sparse).
# 1 x 5 sparse Matrix of class "dfm"
#          features
#  docs    i=pr be=v go=v home=n she=rr
# text1    1    1    1      1      1
```

**Comment by RBonafide** [comment]
Thank you! It seems OK. It works on a small corpus with certain markers. 
But when I load more text with labels, I should switch off some  markers and remove others from corpus
text1 :
[1] "**by**=_PR_=\ni=SPRO,sing,1-p=(v|r)\n**good**=_ADV_=introd\n**that**=_SPRO_,sing,inan=(v|im)\ntoday=ADV=\nnot=PART=\nturn=V,sing,3-p\ni=SPRO,sing,1-p=(pr|d)\n**tomorrow**=_ADV_=\n_early_=_ADV_=\nget=V,np=inf\nmother=A,posses=(im,pl|v,pl,inan)\norder=S,inan=(v,pl|im,pl)\ngive=V,pe=inf\nto=S,abr=(pl|pr,sing|v,pl|v,pl|im,sing)\nshe=SPRO,sing,3-p,fem=im\nwork=V,np=psts,sing,indicat,3-p\nf??\npfdnhf??\nyt??\npyf??\nnot=PART=\nknow=V, prs,sing,1-p\n**home**=_ADV_=\ndrive=V,t=psts,sing,indicat,fem\n**it**=_SPRO_,sing,sr,inan=(v|im)\n**yet**=_ADV_=\n**with**=_PR_=\n**she**=_SPRO_,sing,3-p,fem\ndisput=V=sing,imper,2-p\ntipe?=S,m,sing=\n**then**=_SPRO_,sing,sr,inan=r\ntalk=V,\np=sing,imper,2-p\n**with**=_PR_=\n**she**=_SPRO_,...<truncated>

result:
Document-feature matrix of: 1 document, 1 feature (0% sparse).
1 x 1 sparse Matrix of class "dfm"
       features
docs    by=pr
  text1    1

##As a test variant we include to dfm only word (bold) and first grammar marker (italic). "\n is a new line". Also we are going to add some new  markers (words with mistakes: Ex.: desput=V=err; some emotional lexical units: delight=N=emot)

**Comment by koheiw** [comment]
Good. Why don't you print out your your corpus with `cat(texts(corp)[[1]])` and post a clean text?

**Comment by RBonafide** [comment]
Thank you. I showed you translation our text into English. In fact, we work with Russian text. So... It looks like:
1. Cleaned text (remove unnecessary markers):
x <- unlist(strsplit(toks2$text1, c("=" )))
x <- x[!x %in% dmstm_l] ##dmstm_l incudes list of all  unnecessary markers
paste(x, collapse = "=")
cat(texts(x)[[1]])
"**у**=_PR_=
я=
**хорошо**=_ADV_=
что=
**сегодня**=_ADV_=
не=
**с**=_PR_=
**но**=_CONJ_=
##I shouldn't extract words (я=, что=, не= ). All  words mast be calculated in tf-idf
2. Load cleaned text in corpus
corp2 <- corpus(x)
3. No idea((

**Comment by koheiw** [comment]
Still not sure about your data... Why don't you upload a subset of you corpus object?

**Comment by RBonafide** [comment]
Sorry, fagot about uploading corpus (upload part of corp):
`>cat(texts(corp2)[[1]])`
у=PR=
а=CONJ=
что=
ну=
или=CONJ=
мда=
всеееее=ADV=
как=CONJ=
сам=
да=CONJ=
только=
домой=ADV=
недавно=ADV=
да=CONJ=
из=PR=
D=
в=PR=
и=CONJ=
отдавать=
ну=
вероятно=ADV=
у=PR=
а=CONJ=
потом=
как-то=

**Comment by RBonafide** [comment]
I have an idea!
Removed all "=" from corpus and got new cleaned corpus:
уPR
аCONJ
что
ну
илиCONJ
мда
всеееееADV
какCONJ
then applied  dfm_select function.
Got result:
Document-feature matrix of: 1 document, 4 features (0% sparse).
1 x 4 sparse Matrix of class "dfm"
       features
docs     уpr    аconj   илиconj  изpr
text1    460    702     104         64
It seems, that idea works

**Comment by koheiw** [comment]
Thanks for the text. Your data is strange in that tags are followed by new lines, but you do not need to anything special.

```r
txt <- 'у=PR=
а=CONJ=
что=
ну=
или=CONJ=
мда=
всеееее=ADV=
как=CONJ=
сам=
да=CONJ=
только=
домой=ADV=
недавно=ADV=
да=CONJ=
из=PR=
D=
в=PR=
и=CONJ=
отдавать=
ну=
вероятно=ADV=
у=PR=
а=CONJ=
потом=
как-то='

mt <- dfm(tokens(txt, what = 'fasterword'), tolower = FALSE)
dfm_select(mt, '*=PR*')
# Document-feature matrix of: 1 document, 3 features (0% sparse).
# 1 x 3 sparse Matrix of class "dfm"
#        features
# docs           у=PR=               из=PR=        в=PR=
#   text1            2                    1            1
```

**Comment by RBonafide** [comment]
Thank you! It works.
