### ISSUE TITLE
Add dfm_replace()

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#1140]
We have `tokens_convert()` but no `dfm_convert()`. We should also highlight these functions in documentations for linguistic analysis like  #1139.

**Comment by kbenoit** [comment]
We only have `convert()`, which works to convert dfm objects to foreign dfm formats. It’s not called `dfm_convert()` because by the grammatical rules, that would require it to output a dfm, which it does not.

**Comment by koheiw** [comment]
`tokens_convert()` and `dfm_convert()` are fastest lookup functions, and nothing do with `convert()`.

**Comment by koheiw** [comment]
Actually the names of the functions are `tokens_replace()` is `dfm_replace()`. Sorry for the confusion. `tokens_convert()` is the old name.
