### ISSUE TITLE
Improve consistency of textstat_*() functions

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1154]
Following on #1153:

Current state of `textstat_*` functions:

| function | output object | row.names | dimension(s) | name |
|:--------|:---------|:------|:------|:-----|
| `textstat_collocations` | data.frame | no | collocation | `collocation` |
| `textstat_frequency` | data.frame | no | feature | `feature` |
| `textstat_keyness` | data.frame | yes | feature | - |
| `textstat_lexdiv` | data.frame | yes | document | - |
| `textstat_readability` | data.frame | yes | document | - |
| `textstat_dist` | dist | yes | feature or document | n/a |
| `textstat_simil` | simil/dist | yes | feature or document | n/a |

This suggests that `keyness`, `lexdiv`, and `readability` should:
- remove the row.names and use a new column called either `feature` or `document` depending on the function (or the `margin` value if applicable); and 
- not have a `drop` argument, so that they always return a data.frame.

`dist` and `simil` are special matrix-like objects so should remain unchanged.

**Comment by koheiw** [comment]
- [ ] `textstat_collocations`
 - [ ] `textstat_frequency`
 - [ ] `textstat_keyness`
 - [ ] `textstat_lexdiv`
 - [ ] `textstat_readability`
 - [ ] `textstat_dist`
 - [ ] `textstat_simil`

**Comment by koheiw** [comment]
Why we `textstat_keyness` returns p-values but `textstat_collocations` does not?

**Comment by kbenoit** [comment]
Because the `textstat_collocations()` return is a score, and not a test statistic. It only has a p-value subject to some assumptions that we are not sure we want to make at this stage. But a good question for Jouni.

**Comment by koheiw** [comment]
@kbenoit what the class labels for textstat object should be? `textstat_keyness`, `textstat_collocations` etc? Or `keyness`with `textstat`, `collocations`with `textstat` etc? The former is consistent with `textmodel_*` object, but the latter is an extension of the current labels.

**Comment by kbenoit** [comment]
Just data.frame unless there is a compelling reason. For collocations, since this is a legal feature type, we needed a custom class label.

Sent from my iPhone

On 20 Dec 2017, at 12:06, Kohei Watanabe <notifications@github.com<mailto:notifications@github.com>> wrote:


@kbenoit<https://github.com/kbenoit> what the class labels for textstat object should be? textstat_keyness, textstat_collocations etc? Or keynesswith textstat, collocationswith textstat etc? The former is consistent with textmodel_* object, but the latter is an extension of the current labels.

**Comment by koheiw** [comment]
`subset()` method for textstat objects needs class labels. I also think `textplot_keyness.data.frame()` should be `textplot_keyness.keyness()`

**Comment by kbenoit** [comment]
That's fine. Let's class the data.frames with an additional label that is the same as the _b_ in _somethingplot_b_.

**Comment by koheiw** [comment]
It seems to me that `textstat_lexdiv()` options `c("all", "TTR", "C", "R", "CTTR", "U", "S", "Maas")` have to be lowercased.

**Comment by kbenoit** [comment]
Not really - for other arguments that take case, I just use `argval <- match.arg(char_tolower(argval)` so case becomes irrelevant. I tried them as lowercase and they just look weird.

I think we should leave them in this case, otherwise we get into a host of changes including all of the readability values too. (and they also look weird in lowercase)

**Comment by koheiw** [comment]
OK, I will keep the arguments (and column names) as they are.
