### ISSUE TITLE
make help titles start with a capital letter

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1156]
**quanteda** uses lowercase for the descriptions in http://docs.quanteda.io/reference/index.html but other packages start these capitalised. We should (eventually) change ours to the standard.

But we would not add an end-of-sentence punctuation character (".").

**Comment by kbenoit** [comment]
There is a [Tidyverse style guide](http://style.tidyverse.org/code-documentation.html) but I don't agree with all of its recommendations. 

Mainly, I do not think that the parameter descriptions need sentence case or full stops unless they consist of more than one sentence. Base R - see `help(package = "base")` does not capitalise parameter descriptions although they do add a full stop.

**Comment by kbenoit** [comment]
@stefan-mueller if you want to take charge of this one, that's fine, but it's not a huge priority since our documentation is pretty nice already and very consistent. If you do tackle this then I suggest you try one or two and then I'll review, before you sink the time into making sweeping changes on all the functions.

**Comment by stefan-mueller** [comment]
I agree that sentence case is unnecessary. I created a [branch](https://github.com/kbenoit/quanteda/commit/4469422d602204694f33207953ed7c866af1d880) that contains a few examples already. Is this the way you would like to have it?

**Comment by kbenoit** [comment]
Yes that looks just fine, thanks!

**Comment by stefan-mueller** [comment]
I will keep an eye on this and make adjustments if find additional help titles that need to be changed.
