### ISSUE TITLE
Fix C++ issues for CRAN

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1164]
CRAN feedback: We need to fix the following:

```
Check: whether package can be installed, Result: WARNING
 Found the following significant warnings:
   collocations_mt_dev.cpp:107:47: warning: ISO C++ forbids variable length array ‘size’ [-Wvla]
   collocations_mt_dev.cpp:107:60: warning: ISO C++ forbids variable length array ‘coord’ [-Wvla]
   collocations_mt_dev.cpp:169:41: warning: ISO C++ forbids variable length array ‘size’ [-Wvla]
   collocations_mt_dev.cpp:169:54: warning: ISO C++ forbids variable length array ‘coord’ [-Wvla]
   collocations_mt_dev.cpp:250:52: warning: ISO C++ forbids variable length array ‘check’ [-Wvla]
   collocations_mt_dev.cpp:250:64: warning: ISO C++ forbids variable length array ‘icon’ [-Wvla]
```

And:

> Thanks, we see the last CRAN version had
> 
> Additional issues:
>  clang-UBSAN <https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/quanteda>
>  gcc-UBSAN <https://www.stats.ox.ac.uk/pub/bdr/memtests/gcc-UBSAN/quanteda>
> 
> Have these been fixed too?
> 
> Best,
> Uwe Ligges
> 
> Please fix and resubmit after Jan 3 (we are on vacations now).
> 
> Best,
> Uwe Ligges

**Comment by koheiw** [comment]
I can look into this tomorrow, but it can be tricky as it is coming from C code for IPF. 

We should probably remove `collocations_dev` from CRAN version.

**Comment by kbenoit** [comment]
OK thanks. 

We could make a branch without collocations_dev - but the C code to compute expected counts is coming straight from the stats package!

**Comment by koheiw** [comment]
I think putting the C code in a C++ file is the problem.
