### ISSUE TITLE
test-textplot.R error in textplot_network()?

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#1173]
I get an error when running this standalone, but not when running using CHECK:
https://github.com/kbenoit/quanteda/blob/master/tests/testthat/test-textplot.R#L195-L197

Why is this wrapped in `plot()`? I don't think the error trap is working as expected.

**Comment by koheiw** [comment]
I guess that `plot()` is just a mistake. The test should be skipped on Windows, becasue `vertex_labelfont` affects other graphic functions.
