### ISSUE TITLE
dfm constructor in batch mode

### ISSUE THREAD

**Issue by tpaskhalis** [kbenoit/quanteda#118]
R script with dfm constructor gives error when launched in batch mode with `Rscript` command. However, it executes fine when used with `R CMD BATCH`.

For example, the following simple script `test.R`:
```
library(quanteda)
df <- dfm(ie2010Corpus)
```

fails with the following error when started with `Rscript test.R` from Ubuntu console:

```
Attaching package: ‘quanteda’

The following object is masked from ‘package:stats’:

    df

The following object is masked from ‘package:base’:

    sample

Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 14 documents
   ... indexing features: 4,881 feature types
   ... created a 14 x 4881 sparse dfm
   ... complete. 
Elapsed time: 0.113 seconds.
Error in UseMethod("features") : 
  no applicable method for 'features' applied to an object of class "dfmSparse"
Calls: dfm ... dfm.character -> dfm -> dfm.tokenizedTexts -> features
Execution halted
```

but runs perfectly fine when started as `R CMD BATCH test.R`:

```
> library(quanteda)

Attaching package: ‘quanteda’

The following object is masked from ‘package:stats’:

    df

The following object is masked from ‘package:base’:

    sample

>
> df <- dfm(ie2010Corpus)
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 14 documents
   ... indexing features: 4,881 feature types
   ... created a 14 x 4881 sparse dfm
   ... complete.
Elapsed time: 0.217 seconds.
>
> proc.time()
   user  system elapsed
  2.101   0.419   2.107
```

**Comment by tpaskhalis** [comment]
My guess is that it has to do with multiple inheritance of S4 class `dfmSparse`.

```
setClass("dfmSparse",
         contains = c("dfm", "dgCMatrix"))
```

This, under some peculiar method lookup going on internally in `Rscript`, results in this bug. As I understand from this http://adv-r.had.co.nz/S4.html, multiple inheritance isn't recommended for this reason.

**Comment by kbenoit** [comment]
I’ll investigate but I don’t think that’s it.  Multiple inheritance is a major design feature of the entire Matrix package, not unique to quanteda’s dfm.


On 26 Mar 2016, at 18:40, tpaskhalis <notifications@github.com<mailto:notifications@github.com>> wrote:


My guess is that it has to do with multiple inheritance of S4 class dfmSparse.

setClass("dfmSparse",
         contains = c("dfm", "dgCMatrix"))


This, under some peculiar method lookup going on internally in Rscript, results in this bug. As I understand from this http://adv-r.had.co.nz/S4.html, multiple inheritance isn't recommended for this reason.

**Comment by kbenoit** [comment]
Here's the problem: Rscript does not load the methods package by default, even though it's the first package listed in the quanteda Imports: section of DESCRIPTION.

Solution:

`Rscript --default-packages=methods ./test.R`

or you can add `library(methods)` to test.R.

**Comment by dselivanov** [comment]
Why not to add `methods` to "Depends" section? It is natural if package uses S4. The only reason `Rscript` do not load `methods` by default is the following: *"The default for Rscript omits methods as it takes about 60% of the startup time."* -  see [Rscript manual](https://stat.ethz.ch/R-manual/R-devel/library/utils/html/Rscript.html). But actually it is only a few milliseconds.

**Comment by tpaskhalis** [comment]
I agree that it probably should be a dependency in this case. To me it seems like a rather odd decision on part of `Rscript` authors. It makes the behaviour of batch modes `R CMD BATCH` and `Rscript` inconsistent and leads to unpredictable bugs. Particularly, given that `Rscript` is currently the recommended way of running R scripts from shell. While the gain doesn't look very impressive even by R standards:

```
tom@SVF1421X1EB-Ubuntu:~$ Rscript -e 'system.time(library(methods))'
   user  system elapsed 
  0.054   0.000   0.053 
```

**Comment by Sangs181** [comment]
Hi ...
I am using R version 3.3.2 and followed the steps you mentioned.
First loaded methods and then quanteda, but still getting the same issue.

Can you please help?
Thanks,
Sangha

**Comment by kbenoit** [comment]
@Sangs181 Not sure what "issue" you are still getting - can you provide details as to the problem? Including `sessionInfo()` output, and code generating the problem so we can reproduce it?

**Comment by Sangs181** [comment]
I tried to run the below code:
install.packages("RDCOMClient")
install.packages("tm")
install.packages("quanteda")
library(RDCOMClient)
library(tm)
library(quanteda)
# Establish the Connection
wordApp <- COMCreate("Word.Application")
# Let's set visible to true so you can see it run
wordApp[["Visible"]] <- TRUE
# Define the resumes we want to open
kirancv <- "D:/GL/ScoreResume/KiranVedula_137533.docx"
debocv <- "D:/GL/ScoreResume/DebojyotiBiswas_539213.docx"
# Open the resumes to check
resume1 <- wordApp[["Documents"]]$Open(kirancv)
resume2 <- wordApp[["Documents"]]$Open(debocv)
# Get the text in variables
doc1 <- resume1$range()$text()
doc2 <- resume2$range()$text()
# Define the job titles
job1 <- "Architect"
job2 <- "DotNet Developer"
# Create a datafarme with the text and job-titles
jobInfo = data.frame("text" = c(doc1,doc2), "job" = c(job1,job2))
myCorpus <- corpus(jobInfo$text)
Error in UseMethod("corpus") : 
  no applicable method for 'corpus' applied to an object of class "factor"
# Now I tried to define the Corpus using the below method of tm package it got created.
myCorpus <- Corpus(VectorSource(jobInfo$text)) 
# Now I wanted to use "KeyWord In Context" (kwic) function 
kwic(myCorpus, "net")
Error in UseMethod("kwic") : 
  no applicable method for 'kwic' applied to an object of class "c('SimpleCorpus', 'Corpus')"**

I am getting the above error for any fuction that I try to use from the quanteda package

Session Info:

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] devtools_1.13.2      dplyr_0.7.1          quanteda_0.9.9-65    rJava_0.9-8          RWekajars_3.9.1-3    RWeka_0.4-34        
 [7] SnowballC_0.5.1      tm_0.7-1             NLP_0.1-10           RDCOMClient_0.93-0.2

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11        git2r_0.18.0        plyr_1.8.4          bindr_0.1           tools_3.3.2         digest_0.6.12      
 [7] memoise_1.1.0       tibble_1.3.3        gtable_0.2.0        lattice_0.20-34     pkgconfig_2.0.1     rlang_0.1.1        
[13] Matrix_1.2-7.1      fastmatch_1.1-0     curl_2.7            parallel_3.3.2      bindrcpp_0.2        withr_1.0.2        
[19] stringr_1.2.0       httr_1.2.1          grid_3.3.2          glue_1.1.1          data.table_1.10.4   R6_2.2.2           
[25] ggplot2_2.2.1       magrittr_1.5        scales_0.4.1        assertthat_0.2.0    colorspace_1.3-2    stringi_1.1.5      
[31] RcppParallel_4.3.20 lazyeval_0.2.0      munsell_0.4.3       slam_0.1-40

**Comment by kbenoit** [comment]
@Sangs181 You cannot run `quanteda::kwic()` on a **tm** `Corpus` object. Better to do this:

```r
require(quanteda)
myCorpus <- corpus(jobInfo)
kwic(myCorpus, "net")
```
