### ISSUE TITLE
Provide rough estimate of corpus to memory size conversion in manual

### ISSUE THREAD

**Issue by Ninoninoninonino** [kbenoit/quanteda#1184]
The manual says:
"If you can fit it into memory, quanteda will handle it quickly.  (And eventually,  we will make it possible to process objects even larger than available memory.)"

It would be great to add some rough estimates of how corpus size converts to memory size to the manual. This could help to allocate memory more efficiently when working on clusters ..

**Comment by koheiw** [comment]
Thank you for the suggestion. Tokens object is the most bulky and they take roughly the 5-10 times the size of raw texts (short documents take more memory than long texts if the total number of words is the same). Where do you think is the best place to discuss this?

**Comment by Ninoninoninonino** [comment]
Thanks! For now I would just add a footnote to "If you can fit it into memory", so that anybody searching for 'memory' can find it.
