### ISSUE TITLE
Error in downloading corpus

### ISSUE THREAD

**Issue by SyuuGenn** [kbenoit/quanteda#1187]
Dear quanteda team,

 I'm learning to use quanteda to do Chinese text analysis from your page (http://docs.quanteda.io/articles/pkgdown/examples/chinese.html). But when I use 
`corp <- quanteda.corpora::download(url = "https://www.dropbox.com/s/37ojd5knz1qeyul/data_corpus_chinesegovreport.rds?dl=1")`
to download the corpus, it returns
`trying URL 'https://www.dropbox.com/s/37ojd5knz1qeyul/data_corpus_chinesegovreport.rds?dl=1'
Content type 'application/binary' length 1138844 bytes (1.1 MB)
downloaded 1.1 MB

Error in readRDS(temp) : error reading from connection`
I hope you can help me to fix this problem.

Your sincerely, Syu

**Comment by koheiw** [comment]
It seems that the cached file is corrupt. Restart R or try 
```r
corp <- quanteda.corpora::download(url = "https://www.dropbox.com/s/37ojd5knz1qeyul/data_corpus_chinesegovreport.rds?dl=1", cache = FALSE)
```
Even if neither works, you can download directly from the Dropbox folder in your browser and load using `readRDS()`.

**Comment by SyuuGenn** [comment]
Thank you for your reply, Dr. Watanabe! I tried your code, but it returns

trying URL 'https://www.dropbox.com/s/37ojd5knz1qeyul/data_corpus_chinesegovreport.rds?dl=1'
Content type 'application/binary' length 1138844 bytes (1.1 MB)
downloaded 1.1 MB

Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'C:\Users\Jovid\AppData\Local\Temp\RtmpSuGSWQ/a151ce9ee2e9589e8b35ca19bfd9208d', probable reason 'No such file or directory'

I then directly downloaded the data and created the corpus.

**Comment by koheiw** [comment]
I saw the same error on my Windows. I fixed, so please reinstall and try:
```r
devtools::install_github("quanteda/quanteda.corpora", force = TRUE)
```

**Comment by SyuuGenn** [comment]
It worked! It's really nice of you, Dr. Watanabe! Thanks a lot!
