### ISSUE TITLE
Using kwic() to extract sentences in the context

### ISSUE THREAD

**Issue by contefranz** [kbenoit/quanteda#1189]
I was wondering if there is a way to use `kwic()` in order to extract sentences and not just words around the pattern. We could name the function `ksic()` as *keysentences-in-context*. See example below: 

### Standard behaviour
This is the standard behaviour of the function where I extract 5 words on each side.
```r
text = "Hi there, how you doing? Your bike looks cool. Can I try it? I have never seen a bike like that one. You are very lucky!"
kwic( text, "bike", window = 5 )
# [text1, 9] how you doing? Your | bike | looks cool. Can I 
# [text1, 23] I have never seen a | bike | like that one. You
```

What I would like to do is to extract a given number of sentences before and after the sentences where the matched pattern is located. I think we can choose different ways to produce the output. Here are two examples given by the different usage of the hypothetical argument `flatten`.

### Proposed version 1
```r
kwic( text, "bike", window_sentence = 1, flatten = FALSE )
# [1] Hi there, how you doing?
# [2] Your | bike | looks cool.
# [3] Can i try it?
```
### Proposed version 2
```r
kwic( text, "bike", window_sentence = 1, flatten = TRUE )
# [1] Hi there, how you doing? Your | bike | looks cool. Can i try it?
```
Thank you.

**Comment by koheiw** [comment]
How about doing in this way?

```r
text <- "Hi there, how you doing? Your bike looks cool. Can I try it? I have never seen a bike like that one. You are very lucky!"
toks <- tokens(text, what = 'sentence')
kwic(toks, '* bike *', windo = 1)
                                                                                                    
#  [text1, 2] Hi there, how you doing? |          Your bike looks cool.          | Can I try it?      
#  [text1, 4]            Can I try it? | I have never seen a bike like that one. | You are very lucky!
```
You can then tokenize sentences into words for further analysis.

**Comment by contefranz** [comment]
This seems to do the job so thank you very much. Though, why don’t have just a bunch of high level wrappers which can work at different levels like words (you already have it), sentences and possibly others like characters. It appears that to achieve what I am asking we have to go through the tokenization process. I would like to hide that and have a direct function which takes care of that. 

How about this?

**Comment by koheiw** [comment]
You are welcome. We are trying to keep **quanteda** functions very basic so that users can combine them to achieve their goals. I agree that you sometimes need to write a lot of code for very specific applications, but it should be done in separate extension packages. We will create a guideline for how to write and distribute those packages. I hope you to create one for your application.

**Comment by kbenoit** [comment]
Here's yet one more way: You can reshape your corpus into sentences, and then specify a context window larger than any sentence so that your context is the entire sentence.

```r
txt <- "Hi there, how you doing? Your bike looks cool. Can I try it? I have never seen a bike like that one. You are very lucky!"

corpus(txt) %>%
    corpus_reshape(to = "sentences") %>%
    kwic("\\bbike\\b", valuetype = "regex", window = 1000)
# [text1.2, 2]                Your | bike | looks cool.   
# [text1.4, 6] I have never seen a | bike | like that one.
```

**Comment by contefranz** [comment]
This is also interesting. Thank you!

**Comment by dnguyen-td** [comment]
If I changed the text as the following:
`text <- "Hi there, how you doing? Your bike-blabla looks cool. Can I try it? I have never seen a bike like that one. You are very lucky!"
toks <- tokens(text, what = 'sentence')
kwic(toks, '\\bbike\\b', valuetype = 'regex', window = 1)

 [text1, 2] Hi there, how you doing? |     Your bike-blala looks cool.      | Can I try it?      
 [text1, 4]            Can I try it? | I have never seen a bike like that one. | You are very lucky!`

It seems that the word boundary `(\\b)` that we put for "bike" does not work. The result shows "bike-services" also. Can anyone explain to me this issue?

Thank you a lot!

**Comment by koheiw** [comment]
It is because the regex matches the sentences.
```r
> sent <- c("Your bike-blabla looks cool", "I have never seen a bike like that one.")
> stringi::stri_detect(sent, regex = '\\bbike\\b')
[1] TRUE TRUE
```
You should explain what you wan to do on [StackOverflow](https://stackoverflow.com/).
