### ISSUE TITLE
tokenize is not cleaning '_' in URIs

### ISSUE THREAD

**Issue by Muhomorik** [kbenoit/quanteda#121]
Hi,
I am using quanteda_0.9.4 fom CRAN and fund a strange thing.
Reproduction:

```
lines <- "See the original article at http://www.yogajournal.com/for_teachers/697?utm_source=DailyInsight&utm_medium=newsletter&utm_campaign"
tok <- tokenize(lines, 
                 removeNumbers = T, 
                 removePunct = T, 
                 removeSeparators = T,
                 #removeTwitter = T,
                 removeHyphens = T,
                 ngrams = 2,
                 skip = 2,
                 verbose = F)
tok
tokenizedText object from 1 document.
Component 1 :
 [1] "See_article"                      "the_at"                          
 [3] "original_http"                    "article_www.yogajournal.com"     
 [5] "at_for_teachers"                  "http_utm_source"                 
 [7] "www.yogajournal.com_DailyInsight" "for_teachers_utm_medium"         
 [9] "utm_source_newsletter"            "DailyInsight_utm_campaign"
```

Basically, **utm_source_newsletter** is not a correct bigram.

EDIT: this is strange, because one would guess that punctuation is defined by regex **[:punct:]**
    Punctuation characters:
    ! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~.

**Comment by kbenoit** [comment]
Not really a strange thing, since `"_"` is also a "word" character:

```
> grepl("\\w", "_")
[1] TRUE
```

It's the only punctuation character that is also a word character. This makes it very useful for using as a default concatenator character for forming ngrams, since it will not be split during subsequent token processing.

The main problem here is that your URI is getting split up. Early versions of `tokenize()` had a `removeURL` argument, that detected and either preserved or removed URIs. But this was slow and imperfect so we disabled it. But I can see why it should return. I'll keep this issue open as a feature request.

**Comment by Muhomorik** [comment]
I think a warning would be enough.
I was writing ngrams to csv and splitting by the '_'. Suddenly there was an unexpected row.

**Comment by kbenoit** [comment]
I’ll add a note to the man page for tokenize().  If you can live with a much simpler definition of word boundaries based on white space, you can always supply the what = “fasterword” to tokenize(), and this will not split URLs.  You could then easily remove them using

removeFeatures(yourtokenizedWords, “http*”)



On 2 Apr 2016, at 10:05, Dmitri Peredera <notifications@github.com<mailto:notifications@github.com>> wrote:


I think a warning would be enough.
I was writing ngrams to csv and splitting by the '_'. Suddenly there was an unexpected row.

**Comment by kbenoit** [comment]
**Update**: Just added a removeURL argument to `tokenize()`, and improved the behaviour of `what = "fasterword"` (which may soon become the default - it's not that much faster).

Now you can either remove the URL, and form your bigrams, or keep the URL and use it to form a component of the bigram.  Not sure which you wanted.

```
> tokenize(lines, ngrams = 2, removeURL = TRUE)
tokenizedText object from 1 document.
Component 1 :
[1] "See_the"          "the_original"     "original_article" "article_at"      

> tokenize(lines, ngrams = 2, what = "fasterword")
tokenizedText object from 1 document.
Component 1 :
[1] "See_the"                                                                                                  
[2] "the_original"                                                                                             
[3] "original_article"                                                                                         
[4] "article_at"                                                                                               
[5] "at_http://www.yogajournal.com/for_teachers/697?utm_source=DailyInsight&utm_medium=newsletter&utm_campaign" 
```

I'd welcome feedback on the new functionality. Is this what you need?

**Comment by Muhomorik** [comment]
Yes, thank you. I am happy with both solutions.
Is that in https://github.com/kbenoit/quanteda/commit/a41d9c973108537897e2f5e6660836e3ee6e7471?

**Comment by kbenoit** [comment]
In the current master. Thanks!
