### ISSUE TITLE
Faster token scanning

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#125]
R's default match or %in% is slow to scan large numbers of tokens, but `fmatch` in `fastmatch`package is really fast. A function like below, easily scan multi-million tokens one-by-one. That would benefit quanteda globally.

```
removeTokens <- function(tokens, remove, spacer=FALSE){
  if(spacer){
    tokens2 <- lapply(tokens, function(x, y){ 
      x[!is.na(fmatch(x, y))] <- ''
      return(x)
    }, 
    remove)
  }else{
    tokens2 <- lapply(tokens, function(x, y) x[is.na(fmatch(x, y))], remove)
  }
  attributes(tokens2) <- attributes(tokens)
  return(tokens2)
}
```

**Comment by kbenoit** [comment]
Ah I see now this picks up from #123.  Thanks!


On 22 Apr 2016, at 07:18, koheiw <notifications@github.com<mailto:notifications@github.com>> wrote:


R's default match or %in% is slow to scan all the tokens, fmatch does really a good job fastmatchpackage. A function like below, easily scan multi-million tokens one-by-one. That would benefit quanteda globally.

removeTokens <- function(tokens, remove, spacer=FALSE){
  if(spacer){
    tokens2 <- lapply(tokens, function(x, y){
      x[!is.na(fmatch(x, y))] <- ''
      return(x)
    },
    remove)
  }else{
    tokens2 <- lapply(tokens, function(x, y) x[is.na(fmatch(x, y))], remove)
  }
  attributes(tokens2) <- attributes(tokens)
  return(tokens2)
}

**Comment by kbenoit** [comment]
I took a look, and it looks quite good, but the fastmatch documentation states that the only advantage is realised in second searches - for a first search, it's the same as match. It seems that when the match is performed using `lapply`, it creates the lookup table only once, resulting in a substantial performance gain. When done just once, there appears to be some overhead. Needs more testing, but so far it looks like it improves `selectFeatures.tokenizedTexts()` dramatically but slows down `selectFeatures.dfm()`:

```
require(fast match

toks <- tokenize(inaugCorpus)
microbenchmark::microbenchmark(
    current = removeFeatures(toks, stopwords("english")),
    fastmatch = removeTokens(toks, stopwords("english")), unit = "relative"
)
## Unit: relative
##       expr      min       lq     mean  median       uq      max neval
##    current 6.902879 6.826388 5.269816 6.61182 7.615659 2.824025   100
##  fastmatch 1.000000 1.000000 1.000000 1.00000 1.000000 1.000000   100


itDfm <- dfm(inaugCorpus, verbose = FALSE) 
microbenchmark::microbenchmark(
    current = removeFeatures(itDfm, stopwords("english"), verbose = FALSE),
    fastmatch = itDfm[, unlist(removeTokens(features(itDfm), stopwords("english")))],
    unit = "relative"
)
## Unit: relative
##       expr      min       lq     mean   median       uq      max neval
##    current 1.000000 1.000000 1.000000 1.000000 1.000000  1.00000   100
##  fastmatch 5.075572 4.344572 4.731457 4.348862 5.125243 11.09961   100
```

I think this would help `kwic()` a lot too. Suggest you create a new branch off master and write new methods:
`kwic2.tokenizedTexts()`
`selectFeatures2.tokenizedTexts()`
and we can compare performance, and then replace the existing match-based methods with those.

Keep in mind however that this only applied when `valuetype = "fixed"` - for glob and regex we won't be able to use it.

**Comment by koheiw** [comment]
I had noticed the relatively large overhead of fmatch when I tried to
ditect different stirngs in evety run. It works only for exact match, but
we can adapt this for regex if we initially construct a list of all tokens
that match a regex pattern using a index. Happy to work on this in a branch.

**Comment by kbenoit** [comment]
That would be great - but I wonder if the regex match to all tokens would not remove the speed gain from fmatch.

**Comment by koheiw** [comment]
There will be no performance gain for small corpus, but there is significant gain for scanning of over million tokens. Here is the result of my experiment. This is good enough for me as my corpus is usually 3 to 6 million words. 

removeTokensRegex <- function(x, regex, spacer=FALSE){
  types <- unique(unlist(tokens))
  types <- types[stringi::stri_detect_regex(types, regex)]
  tokens <- removeTokens(tokens, types, spacer)
  return(tokens)
}

> length(tokens) # 548235
[1] 548235
> microbenchmark::microbenchmark(
+   removeTokensRegex(tokens, '^[a-z\\-]{3,}$'),
+   removeFeatures(tokens, '^[a-z\\-]{3,}$', case_insensitive=FALSE), times=10)
Unit: seconds
                                                                 expr      min       lq     mean   median       uq      max neval
                        removeTokensRegex(tokens, "^[a-z\\\\-]{3,}$") 6.661970 7.390765 7.793918 7.716363 8.249249 9.103294    10
 removeFeatures(tokens, "^[a-z\\\\-]{3,}$", case_insensitive = FALSE) 6.195094 6.879769 7.315152 7.196490 7.595497 8.854618    10
> 
> tokens_long <- rep(tokens, 5)
> length(tokens_long) # 2741175
[1] 2741175
> class(tokens_long) <- class(tokens)
> microbenchmark::microbenchmark(
+   removeTokensRegex(tokens_long, '^[a-z\\-]{3,}$'),
+   removeFeatures(tokens_long, '^[a-z\\-]{3,}$', case_insensitive=FALSE), times=10)
Unit: seconds
                                                                      expr       min        lq      mean    median        uq
                        removeTokensRegex(tokens_long, "^[a-z\\\\-]{3,}$")  7.001777  8.090132  8.349919  8.416061  8.584894
 removeFeatures(tokens_long, "^[a-z\\\\-]{3,}$", case_insensitive = FALSE) 35.082795 37.335318 40.585556 40.873940 43.462836
       max neval
  9.703999    10
 46.811167    10

**Comment by koheiw** [comment]
I implemented a token selection function in C++, which is much faster than fmatch. Please check dev_featureSelection branch.

**Comment by kbenoit** [comment]
Great, will do!

Sent from my iPhone

On 30 Apr 2016, at 03:29, koheiw <notifications@github.com<mailto:notifications@github.com>> wrote:


I implemented a token selection function in C++, which is much faster than fmatch. Please check dev_featureSelection branch.

-
