### ISSUE TITLE
sample.corpus not working with corpus from character source from readLines

### ISSUE THREAD

**Issue by mbeigel** [kbenoit/quanteda#128]
Hi,

First off I know there is `textfile` for reading a corpus source from a file but for my purposes it would not do since the texts are newline separated.

When I take a corpus whose source is from a character vector whose source is from `readLines` and call `sample` on it, the result is a corpus that appears to be an incorrect state instead of a character vector as expected. The functions that expect a corpus such as `ndoc` do function normally, and `corpus$document` is a vector of character instead of a data frame. However, setting the document-level meta-data prior to using `sample` seems to circumvent this issue. 

Reproducibility:
R version 3.2.4 (2016-03-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.4 (El Capitan)
RStudio Version 0.99.893
quanteda_0.9.4
[mybug.zip](https://github.com/kbenoit/quanteda/files/245985/mybug.zip)

**Comment by kbenoit** [comment]
Thanks, you have found a bug! `sample.corpus()` fails when there are no docvars. I will fix this in the morning, but you will need to install from GitHub to get the fix. (0.9.4 is the CRAN version, it gets updated only slowly). I'll update this issue when its fixed.

Thanks for the careful example!

**Comment by mbeigel** [comment]
Okay, downloaded the latest version (0.9.5-24) and it works, thanks! 

I do want to say one more one thing though. I noticed that when rerunning my the script that generated the bug, that while `my_sample` (sampled from `my_corpus`) is of class `"character"`, the other sample, `my_new_sample` is of class `"corpus" "list"`. Although this isn't as big an issue as before because `my_new_sample` has the correct number of documents (2) and the corpus methods work on it, if we are assuming a `"character"` then that create problems downstream.

**Comment by kbenoit** [comment]
I checked your code again, and line 8, `my_sample` is a sample from a character vector, not a corpus, hence it returns a character. On line 68, it's a sample from a corpus, and returns a corpus. I think it's working as it should, but correct me if you check again and find it's not.
