### ISSUE TITLE
Support non-identical variable/column names in structured source text files 

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#131]
Currently, if multiple structured text files (i.e. containing both text and docvars, like json, csv. etc) are loaded with `textfile`, they must all have the same column/variable names.

**Comment by adamobeng** [comment]
@kbenoit any objection to introducing a dependency on dplyr so we can use `rbind_all`?

**Comment by kbenoit** [comment]
Yes, that package has too many dependencies and overhead, I want to avoid it.

look at how `+`.corpus and rbind.dfm() work - I think they do the same thing: put together non-column-conforming objects.

Ken
