### ISSUE TITLE
textfile() only supports globbing in last part of filename

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#132]
Suppose you have the following directory structure:

```
.
├── testdir
│   ├── 1
│   │   └── test.txt
│   └── 2
│       └── test.txt
```

```
> testcorpus <- corpus('./testdir/*/test.txt')
> testcorpus
Corpus consisting of 1 document.
```
It should have two documents.

The offending functions are `get_docs` and `get_datas` in `textfile.R`.

**Comment by kbenoit** [comment]
Not really - that's not a valid wildcard pattern for filename matching at the command line either.

**Comment by adamobeng** [comment]
`cat testdir/*/test.txt` works for me in zsh 5.2 and bash 3.2.

According to [the manpage](http://man7.org/linux/man-pages/man7/glob.7.html) (section 'Pathnames'), glob can match any component of a pathname, just not '/'.

**Comment by kbenoit** [comment]
I stand corrected...

**Comment by adamobeng** [comment]
The [rewrite of textfile.R](https://github.com/kbenoit/quanteda/tree/dev_textfile_rewrite) fixes this
