### ISSUE TITLE
Named Entity Recognition

### ISSUE THREAD

**Issue by masalmon** [kbenoit/quanteda#134]
Following your comment here https://github.com/ropensci/unconf16/issues/8#issuecomment-205556034

Do you plan on adding Named Entity Recognition to the package features? Or was it added already (I had a quick look at your repo looking for "spacy" and "NER" for instance)?

cc @sckott

**Comment by kbenoit** [comment]
We're looking at ways to add POS tagging that will be cross-platform, easy for the user to install - ideally as an R package without additional configuration - and fast. The first excludes anything to do with RPython, the second excludes coreNLP, and the third excludes openNLP. I'd love to get spaCy integrated but it's tricky, and requires some not-too-difficult but far from trivial user-side installation outside of R.

I'm looking into http://www.cs.cmu.edu/~ark/TurboParser/ now - this could be compiled as C++ through Rcpp and wrapped in a package.

**Comment by masalmon** [comment]
Do you think a R package for accessing the Monkeylearn API (see e.g. http://docs.monkeylearn.com/article/public-extractors/) would make sense? I could start one. The API has a limit of 100,000 requests per month http://monkeylearn.com/pricing/

**Comment by kbenoit** [comment]
@masalmon Sounds like a great idea, would be happy to assist.

**Comment by masalmon** [comment]
Do you know MonkeyLearn? I didn't before today and I must say it seems good (and even if one gets good instead of very good results, it has the advantage of only demanding a few R dependencies + the user registering which is possible through Github). I'll post here again when I've opened a repo and obviously I'd be happy if you assist, thanks a lot.

**Comment by masalmon** [comment]
So nothing much to see currently (except I made a 1st successful request to the API! yeah!) but this will be the repo https://github.com/masalmon/monkeylearn

**Comment by masalmon** [comment]
The API doc is currently down (it has been for half an hour I think -- the API and dashboard are not down) but:

* I have added a better description of the scope of the package (only for use of existing modules, not creation/adding category, etc.)

* I show an example of Named Entity Recognition with the public NER module of the API -> @kbenoit how would you assess how good it is?

* I have to implement something to deal with the throttle limit, I think I have seen something like that in the past. Google will be my friend.

* I don't know how to provide the users with a list of classifiers&extractors. The API didn't seem to provide that, it only lists the modules of a person (e.g. if I had added modules to my profile I could access them) so maybe I should do a table myself with ID/name/URL (because I'm not going to copy all the information). I'm open to any suggestion.

**Comment by masalmon** [comment]
Please note that while *I* don't want to add functions for the API endpoints related to train and create new ML models, I'd welcome PR adding ths. I won't do ML using the API, I just want to take advantage of the existing modules, but maybe other users would like to train and publish their ML models with R+monkeylearn.

**Comment by masalmon** [comment]
Package submitted to rOpenSci https://github.com/ropensci/onboarding/issues/45

Feedback welcome anywhere (this issue, the onboarding issue, the repo)!

**Comment by kbenoit** [comment]
@masalmon I followed your onboarding with rOpenSci, well done. In the meantime, we have been working on a fast, locally-installable POS tagger, dependency parser, and NER system through the package [**spacyr**](https://github.com/kbenoit/spacyr), which we will integrate tightly with **quanteda** for tagging indexed and tokenised text objects. 

More soon!

**Comment by masalmon** [comment]
Thanks! And cool, congrats on the new package!
