### ISSUE TITLE
There is no explicit license

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#145]

**Comment by kbenoit** [comment]
DESCRIPTION states 

`License: GPL-3`

Is that not explicit?

**Comment by adamobeng** [comment]
The FSF advice is to include the whole GPL as a file called COPYING as well as a brief disclaimer at the beginning of each source code file. Is that too much?

**Comment by kbenoit** [comment]
Not usual practice, but we could be more explicit. Can you find other packages as examples with more explicit license info?

Also, are we sure GPL-3 is the preferred license?

**Comment by adamobeng** [comment]
AFAICT, there are no R packages on github which have a disclaimer in each file, but [a bunch of C and C++ projects do](https://github.com/search?utf8=%E2%9C%93&q=%22is+free+software%3A+you+can+redistribute+it+and%2For+modify+it+under+the+terms+of+the+GNU+General+Public+License%22&type=Code&ref=searchresults).

As to which license is preferred, it depends on what uses you see for the library. CRAN packages seem to mostly be GPL.
