### ISSUE TITLE
Add "keyness" calculation

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#148]
To compute the "keyness" of words, for one document versus another or one corpus versus another. Might consider accessing the "baby BNC" for comparison.

This would function similarly to [Wordsmith](http://www.lexically.net/wordsmith/).

**Comment by adamobeng** [comment]
Is this the same thing as [SIPs](https://en.wikipedia.org/wiki/Statistically_improbable_phrase)?

**Comment by adamobeng** [comment]
Is this the same thing as [SIPs](https://en.wikipedia.org/wiki/Statistically_improbable_phrase)?

**Comment by kbenoit** [comment]
Similar idea, but for terms instead of phrases. Rather than tag SIPs by a threshold, it would just score words according to:

* log likelihood (ratio)
* $\Chi^2$

**Comment by kbenoit** [comment]
@koheiw Remember some time ago when you purchased [Wordsmith](http://www.lexically.net/wordsmith/) with the idea of replicating its computation of keywords?  This would be very easy to program for LR and Chi2 from a dfm. 

e.g.
```r
require(magrittr)
corpus_subset(data_corpus_inaugural, President %in% c("Obama", "Reagan")) %>% 
    dfm(groups = "President") %>%
        textstat_keyness
```

where `textstat_keyness` returns a special tokens class of terms with scores indicating their degree of association (LR) with one of the dfm categories. However if this inputs a dfm and returns a tokens object, we might consider making this a `tokens_` function, for consistency, e.g. `tokens_keyness` rather than dfm, even if internally it would need to create a dfm. Something to think about carefully.

An additional feature would be to complete the passing through of docvars to dfm (and tokens) objects, so that grouping could be done even after the dfm is constructed, e.g.

```r
textstat_keyness(x ~ President) 
```
or
```r
textstat_keyness(x, groups = "President")
```

**Comment by koheiw** [comment]
This is the way I am calculating keyness with the new API. I need this funciton myself very soon.

```r
rownames(mx) <- ifelse(some_criteria == TRUE, 'POL', 'NON-POL')
mx2 <- dfm_compress(mx)
textstat_keyness(mx2, 'POL', 'NON-POL')

textstat_keyness <- function(x, target, reference, min_count = 5, smooth = 1){
    
    mx <- x[c(target, reference),]
    mx <- mx[,colSums(mx) >= min_count]
    sums <- rowSums(mx)
    keywords <- apply(mx, 2, function(x, y, z) keyness(x[1], x[2], y, z), sums[1], sums[2])
    keywords <- sort(keywords, decreasing = TRUE)
    return(keywords)
}

keyness <- function(col, non, sum_col, sum_non, smooth=1){
    tb <- as.table(rbind(c(col, non), c(sum_col - col, sum_non - non)))
    tb <- tb + smooth
    suppressWarnings(
        chi <- stats::chisq.test(tb)
    )
    #print(tb)
    #print(chi$expected)
    col_exp <- chi$expected[1,1]
    if(col > col_exp){
        return(unname(chi$statistic))
    }else{
        return(unname(chi$statistic) * -1)
    }
}

```
