### ISSUE TITLE
fix examples in convert

### ISSUE THREAD

**Issue by jangorecki** [kbenoit/quanteda#151]
There is an attempt to load `tm` namespace in examples - https://github.com/kbenoit/quanteda/blob/master/man/convert.Rd#L112
As `tm` is suggested dependency, it should not be required to run examples according to R-exts. This can be conditionally escaped with requireNamespace.
It is possible there are other cases of that issue in other examples, this one was to first that fails.

**Comment by kbenoit** [comment]
**quanteda**  defines its own methods for as.DocumentTermMatrix, so they are not being called from **tm**'s namespace - although the internal code does make a call to `tm::as.DocumentTermMatrix()`. 

There are a few namespace conflicts between quanteda and tm and therefore I do not want to import its entire namespace, or make it more than an optional dependency. (The converter is the only function that requires something from **tm**.)

**Comment by jangorecki** [comment]
For that purpose there is `if(requireNamespace(.)) ...` function, then always use `pkg::fun()` calls. If the issue is somewhere downstream, then I would report it there or workaround that.
