### ISSUE TITLE
ngrams(x, n=2, skip=2) does not produce expected results

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#153]
According to (A Closer Look at Skip-gram Modelling)[http://homepages.inf.ed.ac.uk/ballison/pdf/lrec_skipgrams.pdf] by Guthrie, the 2-skip-bi-grams of “Insurgents killed in ongoing fighting.” should be {insurgents killed, insurgents in, insurgents ongoing, killed in, killed ongoing, killed fighting, in ongoing, in fighting, ongoing fighting}.

`quanteda` produces:

```
>  ngrams(c('insurgents', 'killed', 'in', 'ongoing', 'fighting'), n=2, skip=2)
[1] "insurgents_ongoing" "killed_fighting"
```

**Comment by kbenoit** [comment]
Already implemented, but the `skip` argument needs the range as in the Guthrie paper: see `?skipgrams`.

```
> skipgrams(tokens, n = 2, skip = 0:2, concatenator = " ") 
[1] "insurgents killed"  "insurgents in"      "insurgents ongoing" "killed in"          "killed ongoing"    
[6] "killed fighting"    "in ongoing"         "in fighting"        "ongoing fighting" 
```
