### ISSUE TITLE
textmodel_NB(): 'names' attribute must be the same length as the vector

### ISSUE THREAD

**Issue by 7804j** [kbenoit/quanteda#162]
When the vector of training labels (second argument) is not made of factors, the method textmode_NB() returns an error.

Ex:
`textmodel_NB(email_dfm, emails$weekday)`
> Error in names(Pc) <- rownames(d) : 'names' attribute [2] must be the same length as the vector [0]

Changing my code like that, however, works:
`textmodel_NB(email_dfm, factor(emails$weekday))`

The documentation says "These will be converted to factors if not already factors.", but it doesn't look like it works.

**Comment by adamobeng** [comment]
Thanks for the report @7804j.

Unfortunately, I am not able to reproduce this: passing a vector as the y argument works on my test data. 

Would it be possible for you to share the dataset you're using --- or even better, a minimal dataset which still produces the error?

**Comment by 7804j** [comment]
I am not sure how to directly share a preformatted dfm, but here is the code that generated the bug:

`#Connect to db
db <- dbConnect(dbDriver("SQLite"), "output/database.sqlite")

#get all emails
emails <- dbGetQuery(db, "
                     SELECT ExtractedBodyText body,MetadataSubject subject, MetadataDateSent date 
                     FROM Emails e 
                     INNER JOIN Persons p 
                     ON e.SenderPersonId=P.Id 
                     WHERE p.Name='Hillary Clinton'  
                     AND e.ExtractedBodyText != '' 
                     ORDER BY RANDOM()
                     LIMIT 100")

emails = emails %>% separate(date,"date", sep = "T") %>% mutate(weekday = weekdays(as.Date(emails$date)))

email_corpus = corpus(emails$body)
email_dfm <- dfm(email_corpus,ignoredFeatures = stopwords("english"), stem = TRUE)

training_labels = emails$weekday

textmodel_NB(email_dfm, training_labels)`

The data comes from the Kaggle Hillary Clinton emails: https://www.kaggle.com/kaggle/hillary-clinton-emails/

**Comment by 7804j** [comment]
Additional note: after running the previous code to which I added the factor(), I tried making a prediction, but received another error:

`NB = textmodel_NB(email_dfm, factor(training_labels))`
`predict(NB)`

> Error in predict.textmodel_NB_fitted(NB) : scores must be equal in length to number of classes.

Any idea what this might be due to?

**Comment by adamobeng** [comment]
This doesn't seem to be a problem with quanteda given that the code below produces no errors for me.

```
library(RSQLite)
library(dplyr)
library(tidyr)
library(quanteda)
#Connect to db
db <- dbConnect(dbDriver("SQLite"), "~/phd/LSE/output/database.sqlite")
#get all emails
emails <- dbGetQuery(db, "
		     SELECT ExtractedBodyText body,MetadataSubject subject, MetadataDateSent date 
		     FROM Emails e 
		     INNER JOIN Persons p 
		     ON e.SenderPersonId=P.Id 
		     WHERE p.Name='Hillary Clinton'
		     AND e.ExtractedBodyText != '' 
		     ORDER BY RANDOM()
		     LIMIT 100")

emails = emails %>% separate(date,"date", sep = "T") %>% 
	mutate(weekday = weekdays(as.Date(emails$date)))

email_corpus = corpus(emails$body)
email_dfm <- dfm(email_corpus,ignoredFeatures = stopwords("english"), stem = TRUE)

training_labels = emails$weekday

NB = textmodel_NB(email_dfm, training_labels)

predict(NB)
```

This might be a problem with your call to `tidyr::mutate` given that it issues a warning. What is the output of your `sessionInfo()`?

**Comment by 7804j** [comment]
I don't think that it is due to the mutate. The warning just informs me that I didn't provide enough columns for the split, so some data was not stored (which is intentional).

I tried running the code you just gave me, and I get the same errors again. Here is my sessionInfo():


> sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_0.9.4 tidyr_0.4.1    klaR_0.6-12    MASS_7.3-43    ggplot2_2.1.0  dplyr_0.4.3    RSQLite_1.0.0  DBI_0.3.1     

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.4      ca_0.64          magrittr_1.5     munsell_0.4.2    colorspace_1.2-6 lattice_0.20-33  R6_2.1.1         plyr_1.8.3      
 [9] tools_3.2.2      parallel_3.2.2   grid_3.2.2       data.table_1.9.6 gtable_0.1.2     lazyeval_0.1.10  assertthat_0.1   Matrix_1.2-2    
[17] SnowballC_0.5.1  stringi_0.5-5    scales_0.3.0     combinat_0.0-8   chron_2.3-47

**Comment by adamobeng** [comment]
Thanks, @7804j. This problem existed in v0.9.4, and is resolved in the current version of quanteda on CRAN (0.9.6). Please install the latest version, and all should be sorted!

**Comment by 7804j** [comment]
That solved it indeed. Thanks!
