### ISSUE TITLE
textfile('test.json') assumes that the file is a Twitter json formatted file

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#163]

**Comment by kbenoit** [comment]
True

Sent from my iPad so there could be strange auto-corruptions

On 16 May 2016, at 14:07, Adam Obeng <notifications@github.com<mailto:notifications@github.com>> wrote:


-

**Comment by adamobeng** [comment]
As of 92f074b, this is fixed. `textfile` now guesses somewhat intelligently at the format of a supplied JSON file.
