### ISSUE TITLE
CRAN releases aren't tagged on Github

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#165]
It would be helpful for debugging problems with specific versions.

@kbenoit Could you confirm the following correspondence between CRAN release and the commits they're built from?

CRAN version | commit
--------------------|-----------------
0.9.6 | cc31d3c2604a037b88e96641a079d677623053da
0.9.5 | ?
0.9.4 | 53701a220104d41fa8998f26fe1e99a04467d9d2
0.9.3 |  089c13a0fc3f843a9f6b96bb6c2410ff4d939127
0.9.2 | a6493a203341d9e891d135afd74f638ee99d1114

**Comment by kbenoit** [comment]
I've been doing it this way: release an even number, and increment sub-minor (fourth) numbers on CRAN for bug-fix only, and as soon as features are added, change third number to odd and start incrementing fourth number until the next CRAN release increments the third number to even.

So: 0.9.5 was never a CRAN release.

**Comment by adamobeng** [comment]
OK. Do the commits for 0.9.2, 0.9.4 and 0.9.6 make sense, then?

**Comment by kbenoit** [comment]
0.9.3 no, since that was never CRANned
0.9.6 It was one commit later, since I had to fix a very minor issue about the names in the DESCRIPTION - it will correspond to the commit for version 0.9.6-1.
