### ISSUE TITLE
plot.kwic does not allow user control over plot elements

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#177]
Is there a way to pass them in `...` or is that incompatible with the ggplot structure? Or, could the plot object be returned invisibly to be modified before sending to the graphics device? 

Right now all kwic object arguments are  parsed from `(...)`, so additional handling will be needed to disentangle graphics options from the (multiple) kwic objects.

**Comment by adamobeng** [comment]
No, passing additional arguments doesn't make sense for ggplot. As it stands, the plot object is returned and could be modified, as is the ggplot way. I've added some documentation to show this: https://github.com/kbenoit/quanteda/tree/dev_kwic.plot_modification
