### ISSUE TITLE
Error in convert() from dfm to lda

### ISSUE THREAD

**Issue by mbossetta** [kbenoit/quanteda#179]
Hi! Apologies in advance if I don't report this correctly, as I am relatively new to R. 

When using convert() to convert a dfm to lda format, I receive the following error (even though I have installed and uninstalled the slam package multiple times):

Error in dfm2ldaformat.dfm(x) : 
  You must install the slam package installed for this conversion.

Here is the code:
##Create dfm
UKdfm <- dfm(UKcorp, verbose = TRUE, toLower = TRUE,
             removeNumbers = TRUE, removePunct = TRUE, removeSeparators = TRUE,
             removeTwitter = FALSE, stem = TRUE, ignoredFeatures = stopwords(kind="english"),
             keptFeatures = NULL, language = "english", thesaurus = NULL,
             dictionary = NULL, valuetype = "regex")
print(UKdfm)

##convert to other model formats
library(slam)
UKlda <- convert(UKdfm, to="lda")

---------------------------------
It occurs also when trying: 

convert(UKdfm, to = c("lda", "tm", "stm", "austin", "topicmodels"))

**Comment by kbenoit** [comment]
Works fine for me, even with your options. BTW you don't want to specify `valuetype = "regex"` with the default stopword list, or it will also remove words such as "candy", "sand", "Andrew", etc because of the match with stopword "and".


```
R version 3.3.0 (2016-05-03) -- "Supposedly Educational"
Copyright (C) 2016 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[R.app GUI 1.68 (7202) x86_64-apple-darwin13.4.0]

[Workspace restored from /Users/kbenoit/.RData]
[History restored from /Users/kbenoit/.Rapp.history]

> require(quanteda)
Loading required package: quanteda
quanteda version 0.9.6.9


Attaching package: ‘quanteda’

The following object is masked from ‘package:base’:

    sample

> myDfm <- dfm(inaugCorpus, stem = TRUE, ignoredFeatures = stopwords("english"), valuetype = "regex")
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 57 documents
   ... indexing features: 9,214 feature types
   ... removed 8,032 features, from 174 supplied (regex) feature types
   ... stemming features (English), trimmed 401 feature variants
   ... created a 57 x 782 sparse dfm
   ... complete. 
Elapsed time: 0.408 seconds.
> ldaDfm <- convert(myDfm, to = "lda")
> str(ldaDfm)
List of 2
 $ documents:List of 57
  ..$ 1789-Washington: int [1:2, 1:70] 0 2 1 2 2 1 3 5 4 5 ...
  ..$ 1793-Washington: int [1:2, 1:12] 3 1 4 1 17 1 22 1 25 1 ...
  ..$ 1797-Adams     : int [1:2, 1:104] 0 3 3 4 4 10 5 1 6 5 ...
  ..$ 1801-Jefferson : int [1:2, 1:90] 4 4 5 1 6 2 7 1 8 2 ...
```

**Comment by mbossetta** [comment]
Thanks, Ken...appreciate the tip. Don't know why it's not working for me, but I will look into it. Just FYI (in case of future reports), the convert() to stm and austin works fine - it is tm, stm, and topicmodels that bring the error. 

I noticed the following in the source code - thought it might be related:

dfm2tmformat <- function(x, weighting=tm::weightTf) {
    if (!("tm" %in% installed.packages()[, "Package"])) 
        stop("You must install the tm package installed for this conversion.")
    if (!("slam" %in% installed.packages()[, "Package"]))
        stop("You must install the slam package installed for this conversion.")
    sl <- slam::as.simple_triplet_matrix(x)
    td <- tm::as.DocumentTermMatrix(sl, weighting=weighting)
    return(td)

**Comment by mbossetta** [comment]
Update: I ran the exact same code on a Mac and it worked (was running on a PC before). Seemed to be the issue.
