### ISSUE TITLE
plot.kwic, comparing token indexes for different documents

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#180]
When documents are of different token length, the plot does not differentiate between the absence of tokens at the end of the file, versus a shorter text having no tick marks because there were no tokens to index.

**Comment by adamobeng** [comment]
Good point. Should the non-existent part of the shorter text be greyed out, or should the x-axis be relative token index.

**Comment by kbenoit** [comment]
Ideally we could have an option for scale = c(“absolute”, “relative”) where the second would eliminate this issue, and the first would pad the missing parts with gray.

**Comment by adamobeng** [comment]
Should the plot stop at the index of the last token or the index of the last occurrence of the keyword?

**Comment by kbenoit** [comment]
at the last token.  we want whitespace to mean there were tokens but not a match with the keyword

**Comment by kbenoit** [comment]
Added in 0.9.7-7
