### ISSUE TITLE
Error caused when dfm called with only non-characters the last element, and 

### ISSUE THREAD

**Issue by ravimakhija** [kbenoit/quanteda#181]
There seems to be an error caused whenever dfm is called with an input that contains only non-characters as the last element, with stem and removeNumbers/removePunct set to true. 

Reproducible error examples:

```
dfm(c("one", "0"), stem = TRUE, removeNumbers = TRUE)
dfm(c("one", "!!"), stem = TRUE, removePunct = TRUE)
```

On the other hand, the following code runs without any error.

`dfm(wordstem(tokenize(c("one", "0"), removeNumbers = TRUE)))`

**Comment by kbenoit** [comment]
Was a bug in wordstem.dfm, caused when recombining the matrix after stemming the words, and there was a feature that was all zero. (also applied to documents with zero features).
