### ISSUE TITLE
quanteda doesn't perform Unicode normalization

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#189]
This means that, for example, precomposed characters are not seen as equivalent to their equivalent expression using combining characters:

```
> kwic('aaa été aaa', 'été')
[1] NA
> kwic('aaa été aaa', 'été')
           contextPre keyword contextPost
[text1, 2]      aaa [     été       ] aaa
```

Probably the best version for our purposes would be Normalization Form KC, given that we're likely to ignore merely visual differences between equivalent forms.

**Comment by kbenoit** [comment]
How about: when constructing a corpus, we normalise all text using `stringi::stri_trans_nfc`? That should make equivalent forms such as:

````
> stri_trans_nfc('\u00e9') == stri_trans_nfc('\u0065\u0301')
[1] TRUE
```

**Comment by adamobeng** [comment]
We should do something along those lines, but:

1. At what point(s) do we perform normalisation? If we just do it on constructing a corpus, then character arguments to various functions (like `kwic`, above) won't be normalised.

2. Which normalisation? I think NFKC is the most appropriate for a text processing library, but I could be convinced.

**Comment by kbenoit** [comment]
> On 31 May 2016, at 13:57, Adam Obeng <notifications@github.com> wrote:
> 
> We should do something along those lines, but:
> 
> 	• At what point(s) do we perform normalisation? If we just do it on constructing a corpus, then character arguments to various functions (like kwic, above) won't be normalised.

We can also normalise the inputs to things also such as kwic and anything taking feature vectors, such as dictionary(), selectFeatures(), etc.  We do this in the functions.


> 
> 	• Which normalisation? I think NFKC is the most appropriate for a text processing library, but I could be convinced.

True there are many choices!  But if we do all these consistently, and internally, it won’t matter to the user.  But we should try to choose the most standard one - if there is such a thing!

**Comment by kbenoit** [comment]
How about: We define a function for normalisation, with options for all of the stringi normalisation variants. This is applied to corpus texts and features internally. The function choice can be set globally by the user in the quanteda settings (which exist but currently have no API functions for setting or querying them). That way we can set a standard but allow users to override if they need to, for languages that prefer a specific form of normalisation.

**Comment by kbenoit** [comment]
See new branch dev_unicodeNorm

**Comment by adamobeng** [comment]
Issue transferred to readtext
