### ISSUE TITLE
Add options to corpus to normalise or remove character classes

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#190]
This should by specifying Unicode character properties, and could replace, e.g. all quotation marks by  U+0022 QUOTATION MARK, all line separators by U+2028 LINE SEPARATOR, or remove private use area characters altogether.

Also, remove the existing normalisation of hyphens and 'smart' quotes.

**Comment by kbenoit** [comment]
@adamobeng Should we make this functionality linked to constructing a corpus (within **quanteda**), or should it moved (similar to `encoding()`) to **readtexts**?

**Comment by adamobeng** [comment]
should be moved to readtext
