### ISSUE TITLE
quanteda does not have a DOI for citations

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#192]
Perhaps use zenodo.org?

**Comment by kbenoit** [comment]
I have created a Zenodo account and linked this to **quanteda**, but it appears to provide a DOI for each tagged release. I'd prefer a reference that is more stable, rather than considering each release separately. I will investigate as to whether there is an easy way to do this.

**Comment by kbenoit** [comment]
For Zenodo: https://guides.github.com/activities/citable-code/
