### ISSUE TITLE
plot.kwic doesn't have a vignette

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#193]

**Comment by kbenoit** [comment]
See the Literature vignette - it's used in that one

**Comment by adamobeng** [comment]
Would that be the best place to add examples which include multiple documents, or should I start a new vignette entirely?

**Comment by kbenoit** [comment]
I think that's too specific for a vignette, instead the various combinations of use can be in the `plot.kwic.Rd` `@examples` section. A vignette would be appropriate however for plotting text objects, and could cover all of the quanteda graphic types.
