### ISSUE TITLE
kwic() with non-existent keyword returns NA rather than empty kwic object

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#197]
```
> kwic(inaugCorpus, 'quine')
[1] NA
```

Is this best practice? For instance, it produces a surprising error when you try to plot it.

**Comment by kbenoit** [comment]
An error in plot.kwic then - I'd say this is appropriate behaviour for kwic() when there is no match.

**Comment by adamobeng** [comment]
It doesn't get dispatched to plot.kwic, because it's not of 'kwic' class. But if returning `NA` is in general correct, then this is Someone Else's Problem.

To be explicit f1or posterity, if you get the following error:

```
> plot(kwic(inaugCorpus, 'quine'))
Error in plot.window(...) : need finite 'ylim' values
In addition: Warning messages:
1: In min(x) : no non-missing arguments to min; returning Inf
2: In max(x) : no non-missing arguments to max; returning -Inf
No traceback available
```

That probably means that your keyword doesn't exist in the corpus, so `kwic` is returning `NA`.
