### ISSUE TITLE
Add a plot method for fitted scaled objects

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#207]
This would be a friendly wrapper around the code attached below, called for instance by:

`dotchart.ci(betas, groups = groups, labels = labels, stderr = betas.se)`

This produces this sort of plot, here grouped by party:
![poissonscalingb](https://cloud.githubusercontent.com/assets/2182246/15931984/dc177264-2e51-11e6-9c95-55fc12c5e07d.png)

Similar to `plot.wordfish()` in the **austin** package.It would take scaled quantities directly from the fitted wordfish or predicted wordscores models, and plot the theta and theta_se as CIs, as appropriate.

Note: This is also an excellent opportunity to write extractor functions such as `coef()` for these object types, so that the code does not break in the future.  As per #108.

``` r
dotchart.ci <- function(theta, groups, labels, stderr, pch, xlab, sortwithingroupalpha=FALSE,
                        color.groups=FALSE, ...) {
  tMedians <- aggregate(theta, list(groups), median, na.rm=T)
  party <- factor(groups, levels=tMedians[order(tMedians$x, decreasing=T), 1])

  if (length(pch)>1) {
    pch <- pch[order(party,-theta,decreasing=T)]
  }

  df.temp <- data.frame(theta, party, labels, stderr, pct)
  if (sortwithingroupalpha) {
    df.temp <- df.temp[order(df.temp$labels),]
  }
  else {
    df.temp <- df.temp[order(df.temp$theta),]
  }
  dotchart2(df.temp$theta, groups=df.temp$party, labels=df.temp$labels,
            stderr=df.temp$stderr, pch=pch, xlab=xlab, color.groups=color.groups, gdata=NULL, ...)

}

dotchart2 <- function (x, labels = NULL, groups = NULL, gdata = NULL, cex = par("cex"), 
    pch = 21, gpch = 21, bg = par("bg"), color = par("fg"), gcolor = par("fg"), 
    lcolor = "gray", xlim = range(x[is.finite(x)]), main = NULL, 
    xlab = NULL, ylab = NULL, stderr=NULL, color.groups=FALSE, lwd=1, ...) 
{
    opar <- par("mai", "mar", "cex", "yaxs")
    on.exit(par(opar))
    par(cex = cex, yaxs = "i")
    if (!is.numeric(x)) 
        stop("'x' must be a numeric vector or matrix")
    n <- length(x)
    if (is.matrix(x)) {
        if (is.null(labels)) 
            labels <- rownames(x)
        if (is.null(labels)) 
            labels <- as.character(1L:nrow(x))
        labels <- rep(labels, length.out = n)
        if (is.null(groups)) 
            groups <- col(x, as.factor = TRUE)
        glabels <- levels(groups)
    }
    else {
        if (is.null(labels)) 
            labels <- names(x)
        glabels <- if (!is.null(groups)) 
            levels(groups)
        if (!is.vector(x)) {
            warning("'x' is neither a vector nor a matrix: using as.numeric(x)")
            x <- as.numeric(x)
        }
    }
    plot.new()
    linch <- if (!is.null(labels)) 
        max(strwidth(labels, "inch"), na.rm = TRUE)
    else 0
    if (is.null(glabels)) {
        ginch <- 0
        goffset <- 0
    }
    else {
        ginch <- max(strwidth(glabels, "inch"), na.rm = TRUE)
        goffset <- 0.4
    }
    if (!(is.null(labels) && is.null(glabels))) {
        nmai <- par("mai")
        nmai[2L] <- nmai[4L] + max(linch + goffset, ginch) + 
            0.1
        par(mai = mai)

```

}
if (is.null(groups)) {
    o <- 1L:n
    y <- o
    ylim <- c(0, n + 1)
}
else {
    # tMedians <- aggregate(x, list(groups), median, na.rm=T)
    # groups <- factor(groups, levels=tMedians[order(tMedians$x, decreasing=F), 1])
    glabels <- levels(groups)
    o <- sort.list(as.numeric(groups), decreasing=T)
    x <- x[o]
    groups <- groups[o]
    stderr <- stderr[o]
    color <- rep(color, length.out = length(groups))[o]
    pcolor <- color
    if (color.groups) {
      pcolor <- unclass(labels)[o]
      pcolor[pcolor==2] <- 4   # make group 2 blue
    }
    lcolor <- rep(lcolor, length.out = length(groups))[o]
    offset <- cumsum(c(0, diff(as.numeric(groups)) != 0))
    y <- 1L:n + 2 \* offset
    ylim <- range(0, y + 2)
}
plot.window(xlim = xlim, ylim = ylim, log = "")
lheight <- par("csi")
if (!is.null(labels)) {
    linch <- max(strwidth(labels, "inch"), na.rm = TRUE)
    loffset <- (linch + 0.1)/lheight
    labs <- labels[o]
    mtext(labs, side = 2, line = loffset, at = y, adj = 0, 
        col = color, las = 2, cex = cex, ...)
}
abline(h = y, lty = "dotted", col = lcolor)
points(x, y, pch = pch, col = pcolor, bg = bg)
for (i in 1:length(y)) {
  lines(c(x[i]-1.96_stderr[i], x[i]+1.96_stderr[i]), c(y[i],y[i]), col=pcolor[i], lwd=lwd)
}
if (!is.null(groups)) {
    gpos <- rev(cumsum(rev(tapply(groups, groups, length)) + 
        2) - 1)
    ginch <- max(strwidth(glabels, "inch"), na.rm = TRUE)
    goffset <- (max(linch + 0.2, ginch, na.rm = TRUE) + 0.1)/lheight
    mtext(glabels, side = 2, line = goffset, at = gpos, adj = 0, 
        col = gcolor, las = 2, cex = cex, ...)
    if (!is.null(gdata)) {
        abline(h = gpos, lty = "dotted")
        points(gdata, gpos, pch = gpch, col = gcolor, bg = bg, 
               ...)
    }
}
axis(1)
box()
title(main = main, xlab = xlab, ylab = ylab, ...)
invisible()

```

}

```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/9231340245136/156066931236688)

**Comment by adamobeng** [comment]
Could you give me a more specific usage example? I can't quite work out how the components of the wordfish model correspond to the arguments to this function

**Comment by kbenoit** [comment]
```{r}
dotchart.ci(wfmodel@theta,
            groups = docvars(ie2010Corpus, "party"),
            labels = docvars(ie2010Corpus, "name"),
            stderr = wfmodel@se.theta,
            pch = 20, xlim=c(-1.5,2))
abline(v=0, lty="dashed", col="red")
```

**Comment by conjugateprior** [comment]
PR #232 is this for wordfish. There's no grouping, though, since I wrote it before saw this issue.

**Comment by kbenoit** [comment]
Implemented (without grouping) in https://github.com/kbenoit/quanteda/commit/7b2ef099f590183894082538c80de06e6ae46a89.
