### ISSUE TITLE
plot.kwic() for multiple documents reorders kwic objects

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#210]
```r
plot(
     kwic(inaugCorpus, "american"),
     kwic(inaugCorpus, "people"),
     kwic(inaugCorpus, "communist")
)
```

results in
![rplot](https://cloud.githubusercontent.com/assets/2182246/16062313/34d728e0-328a-11e6-9c96-c2315db750d7.png)

**Comment by adamobeng** [comment]
Having looked into this, it's not so much that plot.kwic changes the order of texts, but that the kwic objects don't know anything about the texts which did not create their keywords. When we rbind them together, all the keywords from the first kwic object come first, so all those texts appear first in the plot. In effect, the plot is sorted lexicographically by keyword, text.

We could re-order the multiple-keyword dataframe by docname, but that would change the order of the documents for a corpus that was not originally ordered that way. We would have to offer an option to turn it off.

**Comment by adamobeng** [comment]
see [PR 112](https://github.com/kbenoit/quanteda/pull/211)

**Comment by kbenoit** [comment]
I was thinking that it gets ordered alphabetically because of conversion to a factor. If we control that conversion then we can keep the order specified in the call, so that the user controls the order through the order of patterns supplied.

But I'll look soon at the PR to see how you did it. Thx!

**Comment by adamobeng** [comment]
Oh, you're talking about the order of the keywords. I thought you were talking about the order of the documents. Let me revise the pull request.

**Comment by adamobeng** [comment]
OK, fixed in [PR 112](https://github.com/kbenoit/quanteda/pull/211)
