### ISSUE TITLE
Check compliance with ropensci guidelines

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#218]

**Comment by adamobeng** [comment]
Here are some possible mismatches with the guidelines:

[Packaging guidelines](https://github.com/ropensci/onboarding/blob/master/packaging_guide.md)
- The order of the README sections is off
- We don't consistently use snake_case
- No rOpenSci footer, but that makes sense
- No code of conduct
- Missing git tags for CRAN releases
- We don't use `httr` for http requests
- We have some calls to `print` outside of `print.*()` methods

[Wickham's "R packages"](http://r-pkgs.had.co.nz/r.html)
- There are a lot of problems with our style as reported by both formatR and lintr

**Comment by kbenoit** [comment]
*  We can update README  
*  I don't agree with the diktat about snake_case  
*  rOpenSci footer only comes if you submit to rOpenSci and are accepted  
*  Could add a code of conduct. It should include a prohibition on accessing object internals directly :-)  
*  We should add (and I think you have been adding) git tags for CRAN releases, including one I just submitted - and resubmitted - and resubmitted - yesterday and this morning. (If one offending line in the C++ now passes CHECK on Solaris, then it will stay and we can tag it.)  
*  Could and should switch to `httr`  
*  We don't have many (any?) calls to `print()` that are not designed to invoke `print` methods, but we do have a lot of `cat()` calls. It would be easy to hunt these down and replace with `messages()` calls.

**Comment by adamobeng** [comment]
[This branch](https://github.com/kbenoit/quanteda/tree/dev_ropensci_guidelines) is available to implement the changes. In that branch:

- I have updated the README
- I have replaced `download.file` with `httr`
- I am working on replacing calls to `cat`, but it's not a simple find-and-replace
- lintR has [this output](https://gist.github.com/adamobeng/eb225021cea186368462538b4976c92f), and formatR makes [these changes](https://gist.github.com/adamobeng/8b8a38fafb9e53f78471996bdc3328fa)
- WONTFIX snake_case, rOpenSci footer

**Comment by adamobeng** [comment]
Re-opening final remaining issue as #234
