### ISSUE TITLE
convert to="stm" indexes from 0 instead of 1

### ISSUE THREAD

**Issue by bstewart** [kbenoit/quanteda#222]
Ken- as always, amazing package.

Thanks so much for having a converter out to stm.  Defying conventions of all programming languages except R we index our documents object from 1 instead of 0.  The converter for stm indexes from 1 in the current development and CRAN versions.  Replication code below using some data we have in our package

```
#devtools::install_github("kbenoit/quanteda")
library(stm)
library(quanteda)
corp<-corpus(gadarian,textField="open.ended.response")
stmdfm <- convert(myDfm, to = "stm") 
storage<-stm(stmdfm$documents,stmdfm$vocab,K=7) #throws an error
stmdfm$documents$`344` #hey look that first index is 0!
```

**Comment by kbenoit** [comment]
Thanks @bstewart! 

I rewrote the converter last week to make it more efficient, adapting **stm**'s `ijv.to.doc()` function, but forgot that **slam** indexes its simple triplet matrix from 1 and **Matrix** indexes its from zero.

Fixed in quanteda 0.9.7-18, just pushed.

```r
> summary(unlist(stmdfm$documents))
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    1.0     1.0     4.0   390.9   781.0  1506.0 
> length(stmdfm$vocab)
[1] 1506
```
