### ISSUE TITLE
Maybe `trim` should not be idempotent

### ISSUE THREAD

**Issue by conjugateprior** [kbenoit/quanteda#223]
Applying `trim` to a `dfm` should probably have different `minDoc` and `minCount` defaults.  In particular, *not* `minCount=1`. Combined with a lack of info message, this gives the user the impression that something has happened when nothing actually has.

**Comment by kbenoit** [comment]
Well, the info message is on by default. And the question is, what should be the defaults? Should there even be defaults?

**Comment by conjugateprior** [comment]
No info message in 0.9.7-17:
```
> gg <- dfm(inaugCorpus)
Creating a dfm from a corpus ...
   ... lowercasing
   ... tokenizing
   ... indexing documents: 57 documents
   ... indexing features: 9,214 feature types
   ... created a 57 x 9215 sparse dfm
   ... complete. 
Elapsed time: 0.221 seconds.
> hh <- trim(gg) # *crickets*
> 
```

**Comment by adamobeng** [comment]
@conjugateprior is right, the "Removing features occurring fewer than" message only triggers if minCount > 1.
