### ISSUE TITLE
ngrams() appears to have gotten slower

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#226]
See comment thread from http://stackoverflow.com/questions/31570437/really-fast-word-ngram-vectorization-in-r/31601473?noredirect=1#comment63519932_31601473

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/9231340245136/156067377010492)

**Comment by kbenoit** [comment]
@koheiw @HaiyanLW I am assuming we have addressed this with the latest ngram improvements. But there is still a `dev_ngrams` branch (although I think @koheiw will delete this), and we have yet to run direct performance comparisons against the ngrams code in **tokenizers** and **text2vec**.

@HaiyanLW if you have programmed these comparisons, could you put them into `benchmarks/` as per the guidelines I wrote that folder?

**Comment by kbenoit** [comment]
@koheiw see some mods I made to `benchmarks/benchmark_tokens/ngrams.R` in https://github.com/kbenoit/quanteda/commit/9ca760b79cfb00968d9843cd978f38922afcfe00.

**Comment by kbenoit** [comment]
@koheiw is this issue and #149 now addressed and in the master?

**Comment by koheiw** [comment]
Yes. We addressed this.
