### ISSUE TITLE
dictionary() should automatically recognise formats by file ending

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#227]
From @conjugateprior:

> While your complete knowledge is swapped in: should 'dictionary' work by file ending inference and convention like textfile, or explicitly as it currently does?

Good point, it would be sensible to include:
*  `.dic` = LIWC
*  `.cat` = Wordstat
*  `.ykd` = Yoshikoder
*  `.lcd` = Lexicoder

**Comment by adamobeng** [comment]
We don't currently support Lexicoder at all, right?

**Comment by adamobeng** [comment]
Except for Lexicoder, this is now implemented in [PR #226](https://github.com/kbenoit/quanteda/pull/226).
