### ISSUE TITLE
Add support for lexicoder dictionaries

### ISSUE THREAD

**Issue by adamobeng** [kbenoit/quanteda#228]
Format reference [here](http://www.lexicoder.com/docs/Lexicoder3Manual.pdf), p.6.

Do we want to support v2.0 dictionaries or just v3.0?

**Comment by conjugateprior** [comment]
2.0 format is the same as Yoshikoder afaik, for reasons you can probably guess, just tweak the conditional in `dictionary`

**Comment by adamobeng** [comment]
@conjugateprior Does 2.0 format use the '.ykd' extension too?

**Comment by conjugateprior** [comment]
It uses `.lcd` but is otherwise the same. Here's an old manual that describes it.
[Lexicoder2Manual.pdf](https://github.com/kbenoit/quanteda/files/335106/Lexicoder2Manual.pdf)
The new one (3) seems to be suffixed `.lc3`.
