### ISSUE TITLE
token length parameter for dfm

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#235]
Hi,

it would be very convenient if ```dfm()``` would accept a parameter, like ``min_len``, to remove all tokens with length < ``min_len``.

**Comment by kbenoit** [comment]
could, but some already think `dfm()` is bloated with too many arguments as is!

Suggest that you do the following:

```r
min_len <- 4  # for example
myDfm <- dfm(myCorpus)
mDfm <- myDfm[, stringi::str_len(features(myDfm)) >= min_len]
```

**Comment by methodds** [comment]
okay thanks for the tip, that will do it as well :)
