### ISSUE TITLE
Convert Quanteda TDM to STM ready format. 

### ISSUE THREAD

**Issue by rxb230** [kbenoit/quanteda#236]
I am having trouble with the STM package in R. I have built a corpus in Quanteda and I want to convert it into the STM format. I have saved the metadata as an independent CSV file and I want code that merges the text documents with the metadata. The readCorpus() and the "convert() functions do not automatically add the metadata information to the corpus.

This what it looks like in Quanteda:
```{r}
EUdocvars <- read.csv("EU_metadata.csv", stringsAsFactors = FALSE)

EUdocvars$Period <- as.factor(EUdocvars$Period)
EUdocvars$Country <-as.factor(EUdocvars$Country)
EUdocvars$Region <- as.factor(EUdocvars$Region)

EUCorpus <- corpus(textfile(file='PROJECT/*.txt'), encodingFrom = "UTF-8-BOM")
docvars(EUCorpus) <- EUdocvars

EUDfm <- dfm(EUCorpus) 

```
Is there a way to do the same thing using the STM package?

So far I have been able to convert the TDM into an STM ready format by using the code: 
```{r} 
EUstm <- convert(EUdfm, to = "stm", docvars = docvars(EUCorpus))
``` 

However, when I try to build a stm model using the code: 
```{r}	 	
stm(EUdfm$documents, EUdfm$vocab, K, EUdfm$prevalence)
```
I get: Error in stm(EUstm$documents, EUstm$vocab, K, EUstm$prevalence) : 
  Word indices are not positive integers

**Comment by kbenoit** [comment]
Do you have the latest quanteda?  This sounds like an issue with https://github.com/kbenoit/quanteda/issues/222.

Also you need to make sure that your `EUdfm$prevalence` values are valid arguments to `stm()` -- I don't have your data so have no idea if these are valid.

Ken

**Comment by kbenoit** [comment]
Did upgrading your version solve this?

**Comment by rxb230** [comment]
Hey Ken, Thank you for your update. I did need to update, however, for some reason it would not load in the metadata when I did it that way. The conversion worked perfectly, but R would not respond to the metadata in this way.  As such, I had to deal with it in this way: 

```{r}
#Converting the corpus into something that can be used in the STM package 
EUstm <- convert(EUDfm, to = "stm", docvars = docvars(EUCorpus))
``` 
Then to get the metadata to work with the stm package I had to do this: 

```{r}
meta<-EUstm$meta
vocab<-EUstm$vocab
docs<-EUstm$documents
out <- prepDocuments(docs, vocab, meta)
docs<-out$documents
vocab<-out$vocab
meta <-out$meta
```

**Comment by kbenoit** [comment]
That shouldn't be necessary...it probably has something to do with your docvars argument. Here when I send it a single variable, I need to make sure that this remains a data.frame. But this works fine:

```r
data(SOTUCorpus, package = "quantedaData")
post1900sotu <- subset(SOTUCorpus, Date > as.Date("1900-01-01"))
presDfm <- dfm(post1900sotu, ignoredFeatures = stopwords("english"), stem = TRUE)
presDfm <- trim(presDfm, minCount = 5)
presDfmSTM <- convert(presDfm, to = "stm", 
                      docvars = data.frame(party = docvars(post1900sotu, "party")))
require(stm)
stmFitted <- stm(presDfmSTM$documents, presDfmSTM$vocab, K = 10, prevalence = ~ party, data = presDfmSTM$meta)
```

Note: 
```r
> packageVersion("quanteda")
[1] ‘0.9.7.20’
```

**Comment by rxb230** [comment]
Thank you very much, up and running now: 

```{r}
EUstm <- convert(EUDfm, to = "stm", docvars = docvars(EUCorpus))
stmfitted <- stm(EUstm$documents, EUstm$vocab, 20, prevalence=~Region + Period, data=EUstm$meta, max.em.its=25,  init.type=c("LDA"))
```
