### ISSUE TITLE
tokens_compound() is order-dependent on sort of collocations

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#240]
Collocations that overlap, e.g. "united states of", "states of America", will not both form because collocations are phrase-ified in the order of their location in the phrases vector.

``` r
> phrasetotoken("The people of the United States of America.", c("United States of", "States of America"))
[1] "The people of the United_States_of America."
> phrasetotoken("The people of the United States of America.", c("States of America", "United States of"))
[1] "The people of the United States_of_America."

```

This is particularly an issue for the method signature where the phrases argument is a collocation object and there are many overlapping collocations. We cannot process ALL of them, because that would form one phrase from the whole document! but we should have a priority rule less arbitrary than order.

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/9231340245136/156067377087840)

**Comment by conjugateprior** [comment]
Strike two against pre-joining things before subsequent processing?

**Comment by kbenoit** [comment]
Possibly so. What's the best behaviour for this? Keep in mind the objective: to be able to treat multi-word expressions as a single token, such as "capital gains" and "capital gains tax".

**Comment by kbenoit** [comment]
@koheiw With the new `tokens_compound()` this remains an issue:

```r
> tokens_compound(tokens("The people of the United States of America."), 
                  tokens(c("United States of", "States of America")))
tokens from 1 document.
Component 1 :
[1] "The"              "people"           "of"               "the"             
[5] "United_States_of" "America"          "."   
```

**Comment by koheiw** [comment]
Longer compounds have the priority. If the lengths are the same, compounds appear earlier in the text are joined, so united_states_of. There is no dependency on order in the list, because the function is implemented with unordered_map in C++.

**Comment by koheiw** [comment]
```
> tokens_compound(tokens("The people of the United States of America."), 
+                   tokens(c("United States of", "States of America")))
tokens from 1 document.
Component 1 :
[1] "The"              "people"           "of"               "the"              "United_States_of" "America"          "."               

> tokens_compound(tokens("The people of the United States of America."), 
+                   tokens(c("States of America", "United States of")))
tokens from 1 document.
Component 1 :
[1] "The"              "people"           "of"               "the"              "United_States_of" "America"          "."               
```

**Comment by kbenoit** [comment]
We will consider this a feature and not a bug, and consider this the appropriate behaviour:

```r
tokens_compound(tokens("The people of the United States of America."), 
                c("United States", "United States of America"))
## tokens from 1 document.
## Component 1 :
## [1] "The"                      "people"                   "of"                       
## [4] "the"                      "United_States_of_America" "."                       
```
