### ISSUE TITLE
word length

### ISSUE THREAD

**Issue by tyokota** [kbenoit/quanteda#244]
Is it possible to have dfm incorporate something like this?

```tdm <- TermDocumentMatrix(corpus, control = list(wordLengths = c(1, Inf)))```

**Comment by kbenoit** [comment]
You can do this two ways, after creating a dfm:

1.  Select the features with a boolean based on `myDfm[, stringi::str_length(features(myDfm)) > 3)`

2. Use `selectFeatures(myDfm, "\\w{3,}", valuetype = "regex" )` on the dfm.

**Comment by tyokota** [comment]
Thank you!
