### ISSUE TITLE
Reading in TEI based XML files

### ISSUE THREAD

**Issue by cownr10r** [kbenoit/quanteda#245]
Is there a way to read in TEI based XML files?

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/9231340245136/174360631409188)

**Comment by kbenoit** [comment]
Not explicitly, but the general XML format importer might work on these.  have you tried it?

**Comment by cownr10r** [comment]
Yes, I have tried the xml importer, with no success. The idea would be to somehow expedite this following code based on Jockers (2014), without having to incorporate the for loop.

nput.dir <- "~/Desktop/writing stuff"
files.v <- dir(path=input.dir, pattern="*.xml")

library(XML)
parse <- xmlTreeParse("filename.xml", useInternalNodes=T)
paras <- getNodeSet(parse, "/tei:TEI/tei:text/tei:body//tei:p",
		c(tei = "http://www.tei-c.org/ns/1.0"))
words <- paste(sapply(paras,xmlValue), collapse="")
library(quanteda)
mydfm <- dfm(words, ignoredFeatures = stopwords("english"), stem=TRUE)
weighted <- weight(mydfm, "relFreq") * 100
topfeatures(mydfm,20)

ideas?

Tks!

**Comment by kbenoit** [comment]
We could try improving the XML importer to allow for such schema. @adamobeng rewrote the XML handling about 2 months ago, maybe he'd look at this? 

Could you upload 2-3 of the XML files formatted in this way, for us to test?

**Comment by adamobeng** [comment]
I did, and I've also worked with TEI XML quite extensively...

At the moment, we only support the subset of XML files handled by XML:xmlToDataFrame, which are basically tabular.

We could relatively easily add support for extracting texts from XML by passing an XPath specifier as the `textfield` argument, but we would not be able to extract docvars from those documents without modifying the signature of `textfile`.

Does that sound worth doing?

**Comment by cownr10r** [comment]
Dear Drs. Benoit and Obeng,

I have enclosed the three examples of the TEI schema for you to try. I appreciate your help with the XML formatting.

-M


[Archive.zip](https://github.com/kbenoit/quanteda/files/453062/Archive.zip)

**Comment by adamobeng** [comment]
Thanks @cownr10r. Am I right in understanding that for your application each xml file contains only one document?

**Comment by cownr10r** [comment]
yes, that's right.

**Comment by adamobeng** [comment]
Just to keep you updated, @cownr10r, the relevant functionality is being moved from quanteda to a new package called [readtext](https://github.com/kbenoit/readtext). I've opened a [new issue over there](https://github.com/kbenoit/readtext/issues/8) to track this.

**Comment by cownr10r** [comment]
Thanks very much, adamobeng. I am currently using a basic way to do this, with the following code, 

library(XML)
x <- xmlTreeParse(path to xml doc, useInternalNodes=TRUE)
para <- getNodeSet(x, "/tei:TEI//tei:div1/tei:p", namespaces = c(tei="http://www.tei-c.org/ns/1.0"))
words <- paste(sapply(para, xmlValue), collapse="")
#with the assumption that the text is in a particular <div> as set forth in the most basic XML TEI markup. This code comes from a paraphrase of Jockers (2014).
