### ISSUE TITLE
* operator in the Matrix package on which the dfm class is based does not work when assigning numeric weights.

### ISSUE THREAD

**Issue by sanjayprithiani** [kbenoit/quanteda#248]
details here
http://stackoverflow.com/questions/39858572/assigning-different-numeric-weights-to-different-terms-in-quanteda-dfm-does-not

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/9231340245136/192474936201762)

**Comment by kbenoit** [comment]
Closed after further investigation - see the SO link above where I updated the answer.
