### ISSUE TITLE
how to get rid of super-sparse features?

### ISSUE THREAD

**Issue by randomgambit** [kbenoit/quanteda#259]
Hello everyone,

I just discovered this package and it is really fast! Great job!
I have a dataframe with about 2 millions short sentences such as `do you know this quanteda stuff?`.

So far, I am able to get the `DFM` matrix quite simply, using 

`myDfm <- dfm(mycorpus ,ignoredFeatures = stopwords("english"), stem = TRUE)`

Problem is, I want to feed this matrix to machine learning algorithm, and I want to restrict the matrix to words that appear at least x% of the time in the corpus. Some form of sparsity filtering. 

Is this currently possible with `quanteda`?

Thanks!

**Comment by kbenoit** [comment]
Glad you like it! Yes is the answer to your question, see `?trim`.

**Comment by randomgambit** [comment]
nice, very nice! thanks!

I actually want to use this matrix as an input to `xgboost`. Have you ever done that? Does that make sense?

**Comment by kbenoit** [comment]
Haven't tried that yet, but you can find coercion methods in **quanteda** for converting a dfm to a data.frame or matrix (`as.data.frame()`, `as.matrix()`) that should provide workable inputs to **xgboost**.

**Comment by randomgambit** [comment]
ok got it thanks! btw, if you happen to know some tutorial that use `quanteda` to perform text classification I would be interested.

Thanks again
Keep up the good work

**Comment by randomgambit** [comment]
actually, I now realize there might a problem here.

Suppose I start with a dataframe that contains two columns, the `output` and the `text` column.

Now, I can extract the `text` column, and use `quanteda` to obtain the dummy coding for each word in each sentence. But if I trim the `dfm` matrix, it may happen that some rows (containing very rare terms) will actually disappear from the `dfm`.

In other words, the number of rows in `outcome` and in `dfm` are not the same. They are not aligned. Am I missing something here?

**Comment by pnulty** [comment]
This issue has come up before, and one solution is to use the keptFeatures argument to dfm, see: final comment on #46
