### ISSUE TITLE
converting the sparse dtm matrix to other formats?

### ISSUE THREAD

**Issue by randomgambit** [kbenoit/quanteda#264]
Hello,

I am having some difficulties converting the `dtm` matrix I get after

`myDfm <- dfm(mycorpus ,ignoredFeatures = stopwords("english"), stem = TRUE)`

to a sparse-matrix format that other packages (like `xgboost`) can use. 

When I feed `myDfm` to `xgboost`,  using 

`bst <- xgboost(data = small_df, label = data$outcome, max.depth = 4,
               eta = 1, nthread = 2, nround = 10,objective = "binary:logistic")` 

I get an error 

`Error in xgb.get.DMatrix(data, label) : xgboost: Invalid input of data`

I thought the `dtm` class was built on top of the sparse-matrix format in `Matrix` (which is accepted by `xgboost`)? 
Am I missing something? How can I convert my `dfm` to a common sparse-matrix representation? 

Thanks again for writing this amazingly fast package!

**Comment by kbenoit** [comment]
In your code, `small_df` is not defined, so I cannot tell how you created that object.  But if you want a regular sparseMatrix, you can drop the dtm attributes simply by coercing it like this:

```r
regularDtm <- as(myDfm, "sparseMatrix")
```

which is the S4 means of coercing one data object into another (assuming type is compatible).

**Comment by randomgambit** [comment]
thanks @kbenoit , there was a small missing line indeed

`small_df <- trim(myDfm,50)`

Let me try your suggestion right now

**Comment by randomgambit** [comment]
works like a charm, thanks @kbenoit 

I would recommend you put a small `exporting quanteda objects to other common ML packages` section on the first page or `quanteda`. 

I think that will make it even more accessible to people that use your package as an input for ML (and not necessarily for pure text processing)

Keep up the great work!
