### ISSUE TITLE
Unnecessary cast to dense matrix in fcm()

### ISSUE THREAD

**Issue by dselivanov** [kbenoit/quanteda#267]
Tried to compare `create_tcm()` and `fcm()`. Got following:
> Error in asMethod(object) : 
Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105 
9.asMethod(object) 
8.as(x, "matrix") 
7.as.matrix.Matrix(x) 
6.as.matrix(x) 
5.lower.tri(result, diag = FALSE) 

[This](https://github.com/kbenoit/quanteda/blob/2fb93728d8a008d4e251aad91d43c47b9f5c042e/R/fcm.R#L190-L191) casts sparse matrix to dense (see source code for `base::lower.tri()` function):
```r
    # discard the lower diagonal if tri == TRUE
    if (tri)
        result[lower.tri(result, diag = FALSE)] <- 0
```
Should be trivial to do it with `Matrix` functions and without casting to dense.

**Comment by kbenoit** [comment]
Thanks @dselivanov you're right on this. These are just pushed and need review, which I will be working on today.
