### ISSUE TITLE
Targets for Refactoring

### ISSUE THREAD

**Issue by pnulty** [kbenoit/quanteda#27]
Accessor functions:

texts()
words()
data() - (return only the attribs or texts + attribs?)
tokenizedTexts() - I suggest that when we run tokenize() we should store the result in the corpus object and simply retrieve the tokenized texts afterwards

Generic Functions:
clean() corpus, text, (dfm?)
tokenize() corpus, text
stopwords() corpus, text, dfm
sample() corpus, dfm

**Comment by kbenoit** [comment]
Some issues resolved by last hackathon, others distributed into new issues.
