### ISSUE TITLE
Extend plot.textmodel_wordfish_fitted to fitted wordscores objects

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#275]
Probably this will involve a method that works on some new hierarchical class of scaled text model objects, since the code will be nearly identical (except the input names). 

If we write the extractor functions then the plot method could call the same extractor function to get feature and document-level parameter estimates for producing the same plot.

**Comment by methodds** [comment]
Would it also be possible to please enable ggplot for the textmodel plots similar to ``textplot_xray``?

**Comment by kbenoit** [comment]
Yes we want to make `textplot_scale1d` the general plotter for textmodel functions that scale texts, e.g. wordscores, ca, and wordshoal. 

As for basing this on **ggplot2**, @adamobeng is our resident **ggplot2** expert and hopefully he will put this on his to-do list. 

We also want to add a `groups` argument for grouping the documents (e.g. by party) and for sorting within group.
