### ISSUE TITLE
Greek support

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#282]
Hi, are there any plans to fully support Greek as a language? From what I can tell there are no stopwords available although  [some sources](https://pypi.python.org/pypi/many-stop-words) already exist.

**Comment by kbenoit** [comment]
Thanks for the link, that's very useful. Reviewing it, however, the list of English stopwords (at 895 words) is far longer and more extensive than the fairly conservative lists currently available in **quanteda** through `stopwords()` (where `length(stopwords("english"))` is 174). 

However the Greek list from the source you listed has only 79 words, so it is much smaller. However this also shows that the coverage of the different languages from your source is highly imbalanced. What do you think of the 79 words, compared to the other language lists in `stopwords()`?

**Comment by methodds** [comment]
To be honest I have absolutely no idea. I'm in the middle of processing greek parliamentary written questions and only see a bunch of weird characters ;-).
I will contact a native ASAP and let you know his or her opinion about the stopwords.

**Comment by methodds** [comment]
I just sent you a mail with a pretty exhaustive stop word list created by a native speaker (and translated to English).

**Comment by methodds** [comment]
There is still one mistake in the stopword list: "τηs", which is the translation of "hers", should be replaced with "της".

**Comment by kbenoit** [comment]
Thanks, fixed in https://github.com/kbenoit/quanteda/commit/8fc9954ecdec70c4f1517fc0d398a9cd9e96b06e
