### ISSUE TITLE
Large memory consumption in tokens generator

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#286]
Hashed ``tokens`` are much smaller than tokenizedTexts, but it creates list of character vectors before hashing. This becomes a real problem corpus is really large, because the intermediate object uses a lot of memory, so the new tokens creator has to be incremental like ``tokenizeHashed()`` by default.

**Comment by kbenoit** [comment]
I was thinking about this too ... perhaps we should set a threshold before this is needed. How large is "really large"?

**Comment by koheiw** [comment]
In ``tokenizeHashed()``, the size of batch is 1000 documents, so it is less than that. It is virtually the same as one-off tokenization. This setting is parameterlized.

**Comment by kbenoit** [comment]
@koheiw I think we have now solved this issue, with the new batch `tokens` function. Please affirm, and if yes, close the issue.
