### ISSUE TITLE
how to stem both words of bigrams

### ISSUE THREAD

**Issue by andreskull** [kbenoit/quanteda#30]
dfm with bigrams=TRUE and stem=TRUE creates bigrams, where only the last word of bigram is stemmed. How to stem both words of the bigram?

> dfm(c("banking industry"), clean=FALSE, stem=TRUE, bigrams=TRUE, verbose=FALSE)
Document-feature matrix of: 1 document, 3 features.
1 x 3 sparse Matrix of class "dfmSparse"
       features
docs    bank banking_industri industri
  text1    1 

I need "bank_industri" instead of "banking_industri"

**Comment by andreskull** [comment]
The workaround using tm+quanteda:
vs <- VectorSource(texts)
corp <- Corpus(vs)
corp <- tm_map(corp,  removeWords, stopwords("english"))
corp <- tm_map(corp, stemDocument)
corp2 <- corpus(corp)
dtm <- dfm(corp2, clean=TRUE, bigrams=TRUE, stem=FALSE)

**Comment by kbenoit** [comment]
Fixed in 0.8.7-8.

    > dfm("Banking industry", stem = TRUE, ngrams = 2, verbose = FALSE)
    Document-feature matrix of: 1 document, 1 feature.
    1 x 1 sparse Matrix of class "dfmSparse"
           features
    docs    bank_industri
      text1             1
    > wordstem(tokenize("Banking industry", n = 2))
    tokenizedText object from 1 document.
    Component 1 :
    [1] "Bank_industri"

**Comment by atheeralattar** [comment]
How does the stem completion works in quanteda, sorry if the question looks too basic but I couldn't find the answer so I decided to use the last resort (Ask the developer).

**Comment by koheiw** [comment]
You can do this by stemming words before makeing ngrams:
```r
toks <- tokens(data_corpus_inaugural)
toks_stem <- tokens_wordstem(toks)
toks_stem_bigram <- tokens_ngrams(toks_stem)
```

**Comment by kbenoit** [comment]
@atheeralattar stem completion is not implemented in quanteda. What's the use case for this? I've always been curious as to why people need this.
