### ISSUE TITLE
Document C++ functions, remove those unneeded

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#304]
Can you and @HaiyanLW go through all of the C++ code and document it, since one of the glaring differences between the R and C++ code concerns the documentation. R's check does not enforce any documentation for C++, and therefore we have provided almost none. It's becoming increasingly difficult to tell what each function does, and I suspect there are some vestigial functions that are unused.

Fine for the documentation to be in comments within the C++ code.

**Comment by koheiw** [comment]
There are many C++ files because we still support tokenizedTexts. I cannot wait dropping this object altogether. Giving documentation to C++ functions seems like a good idea. I will do.

**Comment by HaiyanLW** [comment]
I think we should add a comment of the purpose of the code at the beginning, something similar to @description in R code, including by which R code this c++ code is called.

**Comment by koheiw** [comment]
We also need a naming rules for C++ files in src directory.

**Comment by koheiw** [comment]
I did renaming of C++ files and functions. Unused files are also removed.
