### ISSUE TITLE
wordstem() should work with corpus data type as well

### ISSUE THREAD

**Issue by andreskull** [kbenoit/quanteda#32]
wordstem() works only with array of words. It should work with corpus too. if you need to stem words before doing dfm (that supports only stemming of the second word) then you have to transform data from corpus/text to array and then back to corpus.

**Comment by kbenoit** [comment]
Should this return a stemmed corpus, or should it return a character vector of the corpus texts that are stemmed?

**Comment by andreskull** [comment]
It should allow the following use case:
  corp <- corpus(ct$texts)
  corp <- clean(corp, removeTwitter=TRUE, verbose=TRUE)
  corp <- removeFeatures(corp, stopwords("SMART"))
  corp <- wordstem(corp)
  corp <- bigrams(corp, include.unigrams = FALSE)
  dtm <- dfm(corp, clean=FALSE, stem=FALSE)

**Comment by kbenoit** [comment]
Our philosophy is that a corpus object is designed to be a repository of original texts and meta-data, and not be subject to modification, except for redefining or selecting documents. Methods for stemming existing for the following objects, but not corpus. 

    > methods("wordstem")
   [1] wordstem.character*      wordstem.dfm*            wordstem.tokenizedTexts*

Feature, not bug. :-)  See the **Design Principles and Development Plans** vignette for justification.
