### ISSUE TITLE
Deprecate and remove functions marked for this fate

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#323]
function name | replacement name | input object | output object | notes
:--------|:------------- |:------- |:------------- |:-------
`describeTexts` | `describeTexts` | character | |
`clean` |  | | |
`textfile` | (new **readtext** package) | *(files)* | corpus | incorporated into `corpus()`
`as.wfm`|`convert` |   dfm | austin::wfm |
`dfm2ldaformat` | `convert` |  dfm | **lda** input object |
`quantedaformat2dtm` | `convert` |  dfm | tm::DocumentTermMatrix |
`wordlists` | `data_char_wordlists` | *(data)* | character | replaced by

**Comment by diegocgaona** [comment]
Hi!

Thanks for the package!

What I would use in place of clean()? There's a substitute to clean the text?

Thanks!!

**Comment by kbenoit** [comment]
@diegocgaona see the options available through `tokens()` and `dfm()`.  There are numerous ways also to stem words (`tokens_wordstem()`, `dfm_wordstem()`) and remove words (`tokens_remove()`, `dfm_remove()`).
