### ISSUE TITLE
Question: High number of document similarity

### ISSUE THREAD

**Issue by parayamelo** [kbenoit/quanteda#342]
Hi Ken,

First, thanks for the great package! Found it today and it has solve a lot of issues I was dealing with in the past few days.

My question is regarding similarity between texts. Perhaps I missed it the explanation from the documentation, I apologize beforehand if that is the case. I have a low amount of documents (~200), and a high number of "news documents", ~ 2 Million. I want to do text similarity between each document and each news, i.e., doc1 with news1, doc1 with news2, and so on. But I do not want to study similarity between documents (doc1 with doc2, doc2 with doc3, and so on), and I also do not want to study similarity between news (news1 with news2, news2 with news3, and so on).

I saw the "groups" keywords in the dfm function, but when applying similarity, it still calculates similarity between all texts. One obvious option if to do a for loop for each document and each news, but it can take forever due to the high amount of news.

Is there another keyword I missed, or do you have an idea on how to perform this?

I am working in a 32Gb memory computer, so I think memory would not be an issue.

Thanks!

**Comment by kbenoit** [comment]
I'm away but will get to this soon. Could you upload some sample data for demonstration/testing?

**Comment by parayamelo** [comment]
Thank you for reaching out! I am sending a small sample of my data set. In the zip file there are two R object files, docs.RData and news.RData (readRDS). Each has 200 documents, they are already cleaned. Basically, I want to do cosine similarity between each document to each news. As it is now (as far as I understand), if I do similarity(), it will do a similarity between all single documents. Only way to achieve what I want is through a for loop (foreach), but given that I have ~2 million documents, it will take a while....

Thanks again!

[files.zip](https://github.com/kbenoit/quanteda/files/633359/files.zip)

**Comment by kbenoit** [comment]
Two methods, see below. If you can compute all of it, why not? If not, try the loop.

```r
require(quanteda)

load("~/Downloads/files/news.RData")
names(news) <- paste0("news", 1:length(docs))
load("~/Downloads/files/docs.RData")
names(docs) <- paste0("docs", 1:length(docs))

# make a corpus with documents named
combined_corpus <- corpus(news) + corpus(docs)
combined_corpus

# make a single dfm
combined_dfm <- dfm(combined_corpus, removePunct = TRUE, removeNumbers = TRUE)

### METHOD 1: COMPUTE EVERYTHING, GET RID OF THE UNWANTED PARTS

result1 <- as.matrix(similarity(combined_dfm, margin = "documents", method = "cosine"))
result1 <- result1[order(rownames(result1)), order(colnames(result1))]
result1 <- result1[-grep("^doc", rownames(result1)), -grep("^news", colnames(result1))]
result1[1:10, 1:5]


#### METHOD 2: COMPUTE I A LOOP JUST THE ONES WE WANT

# compute similarity of each news to all docs
results <- list()
for (dname in names(news)) {
    results <- c(results, 
                 similarity(combined_dfm[c(dname, names(docs)), ], selection = dname, method = "cosine"))
}

# need to reorder each element
results

results <- as.data.frame(results)
results[1:10, 1:5]
##              news1      news2     news3      news4      news5
## docs117 0.06225728 0.24809303 0.7922118 1.00000000 0.17589889
## docs1   0.00000000 0.15724273 0.1807754 0.11805627 0.16939423
## docs2   0.00000000 0.15602241 0.1807754 0.07229440 0.14472072
## docs3   0.00000000 0.11013346 0.1807754 0.07076101 0.14022700
## docs4   0.00000000 0.10573611 0.1807754 0.06628598 0.11363310
## docs5   0.00000000 0.09449112 0.1807754 0.06397127 0.11162390
## docs6   0.00000000 0.07793496 0.1807754 0.04496797 0.10759948
## docs7   0.00000000 0.07793496 0.1807754 0.03904344 0.09877296
## docs8   0.00000000 0.07793496 0.1807754 0.03365956 0.09454609
## docs9   0.00000000 0.07793496 0.1807754 0.03246660 0.09417632
```
Those texts are very small, and very sparse, and this complicates the similarity measures, but it's pretty fast.

**Comment by kbenoit** [comment]
@HaiyanLW I noticed there is quite a performance difference in the old `similarity()` and the new `textstat_simil()`, which is odd because that part of the code should be the same. Can you check what is happening?

```r
# old method
results_old <- list()
# new method
results_new <- list()
# benchmark
rbenchmark::benchmark(
    old = for (dname in names(news)) {
        results_old <- c(results_old, 
                         similarity(combined_dfm[c(dname, names(docs)), ], selection = dname, method = "cosine"))
    },
    
    new = for (dname in names(news)) {
        results_new <- c(results_new, 
                         as.list(textstat_simil(combined_dfm[c(dname, names(docs)), ], selection = dname, method = "cosine")))
    },
    
    replications = 1
)
##   test replications elapsed relative user.self sys.self user.child sys.child
## 2  new            1  54.215   26.839    31.881   21.774      0.049     0.055
## 1  old            1   2.020    1.000     1.981    0.031      0.000     0.000

packageVersion("quanteda")
## [1] ‘0.9.8.9022’
```

**Comment by parayamelo** [comment]
Thank @kbenoit ! The set I sent you is just a sample, I have 2 million texts, and since I was working in a laptop, I ran out of memory when trying to compute everything.

Will try both approaches, and see what is faster. 

Thanks again!

**Comment by kbenoit** [comment]
@parayamelo I suggest you try >= v0.9.8.9029 since this implements parallel and sparse methods for `textstat_simil` that might help with this issue. 

I'll close it but feel free to reopen, or start a new issue, depending on how it works for you.

**Comment by parayamelo** [comment]
Thanks! I will continue working with this, will write if I need more help.
