### ISSUE TITLE
use readr instead of read.csv for text import functions

### ISSUE THREAD

**Issue by pnulty** [kbenoit/quanteda#35]

**Comment by kbenoit** [comment]
Totally agree, but we will have to wait until it's on CRAN (right now it's GitHub only).

**Comment by conjugateprior** [comment]
http://cran.r-project.org/web/packages/readr/ <http://cran.r-project.org/web/packages/readr/>

Will

**Comment by kbenoit** [comment]
Well that was awkward.  But hey from https://github.com/hadley/readr:

## Installation

Currently, readr is not available from CRAN, but you can try out the dev version with:

```R
# install.packages("devtools")
devtools::install_github("hadley/readr")
```

**Comment by kbenoit** [comment]
We tried and there were no real performance or usability advantages.
