### ISSUE TITLE
tokens_lookup needs same signature and behaviour as applyDictionary.tokens

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#355]
I adopted `applyDictionary2` for the new `tokens_lookup` function, but it has different behaviour and different arguments. @koheiw can you match the `tokens_lookup` to the old function behaviour?

Note that the old functions are still there, just hidden (through `@keywords internal`).

**Comment by koheiw** [comment]
Sure, but what should I do with ``exclusive`` and ``capkeys``? They are not really used in applyDictionary.tokenizedTexts. ``concatenator`` in the new functions is harmless as far as the default is ' '. The difference that I cannot change in the new function is that this function retains the original order of the tokens even when keys are in a random order (as it should do).

**Comment by kbenoit** [comment]
The former functions worked with this, until we replaced them. The `exclusive` and `capkeys` are for the implementation of the "thesaurus" version of a non-exclusive dictionary. This still works in dfm, but of course `dfm_lookup` does not work with multi-word dictionary keys. (Note: The warning message is incorrect, it should say "multi-word **values**" not **keys**. Needs to be fixed.)

```r
toks <- tokens(c(doc1 = "Mexico signed a new libertarian law with Canada.",
                 doc2 = "Let freedom ring in the United States!"),
               removePunct = TRUE)
dict <- dictionary(list(country = c("united states", "mexico", "canada"), 
                        "law words" = c('law*', 'constitution'), 
                        freedom = c('free', "freedom", 'libertarian')))
(mydfm <- dfm(toks))
## Document-feature matrix of: 2 documents, 15 features (50% sparse).
## 2 x 15 sparse Matrix of class "dfmSparse"
##       features
## docs   mexico signed a new libertarian law with canada let freedom ring in the united states
## doc1      1      1 1   1           1   1    1      1   0       0    0  0   0      0      0
## doc2      0      0 0   0           0   0    0      0   1       1    1  1   1      1      1

dfm_lookup(mydfm, dictionary = dict, exclusive = TRUE)
## applying a dictionary consisting of 3 keys
## Document-feature matrix of: 2 documents, 3 features (0% sparse).
## 2 x 3 sparse Matrix of class "dfmSparse"
##       features
## docs   country law words freedom
## doc1       2         1       1
## doc2       0         0       1
## Warning message:
##     In dfm_lookup(mydfm, dictionary = dict, exclusive = TRUE) :
    
dfm_lookup(mydfm, dictionary = dict, exclusive = FALSE)
## applying a dictionary consisting of 3 keys
## Document-feature matrix of: 2 documents, 13 features (38.5% sparse).
## 2 x 13 sparse Matrix of class "dfmSparse"
##      signed a new with let ring in the united states COUNTRY LAW WORDS FREEDOM
## doc1      1 1   1    1   0    0  0   0      0      0       2         1       1
## doc2      0 0   0    0   1    1  1   1      1      1       0         0       1
## Warning message:
##     In dfm_lookup(mydfm, dictionary = dict, exclusive = FALSE) :
##     You will probably not get correct behaviour applying a dictionary with multi-word keys to a dfm.

dfm_lookup(mydfm, dictionary = dict, exclusive = FALSE, capkeys = FALSE)
## Document-feature matrix of: 2 documents, 15 features (50% sparse).
## 2 x 15 sparse Matrix of class "dfmSparse"
##       features
## docs   mexico signed a new libertarian law with canada let freedom ring in the united states
## doc1      1      1 1   1           1   1    1      1   0       0    0  0   0      0      0
## doc2      0      0 0   0           0   0    0      0   1       1    1  1   1      1      1

```

**Comment by kbenoit** [comment]
No need to match the order to the earlier function, btw, I like the new function (preserving the original order) better.

**Comment by koheiw** [comment]
I added `capkey`, so it looks a bit closer. 
```
> dfm(tokens_lookup(toks, dictionary=dict, capkey=TRUE), tolower=FALSE)
'Dictionary lookup'  0.128483 millsec
Document-feature matrix of: 2 documents, 3 features (16.7% sparse).
2 x 3 sparse Matrix of class "dfmSparse"
      features
docs   COUNTRY LAW WORDS FREEDOM
  doc1       2         1       1
  doc2       1         0       1
```
Current version is the all the dictionary entries even overlapped or nested. It does not retain the original order of tokens, but it should be for usual purposes of dictionary look up.

**Comment by koheiw** [comment]
For `exclusive`, I suggest to make token substitution funciton `tokens_replace`. This will not detect all overlapped or nested tokens, but keep the original tokens. This is actually a generalization of tokens_select, where unneeded target tokens are substituted with empty tokens.

**Comment by koheiw** [comment]
I added parallel `tokens_select` and `tokens_replace`, both of which support multi-word features. With `tokens_lookup` and these two, we can do whatever we want to.

**Comment by kbenoit** [comment]
Have you tested the build on windows?

**Comment by koheiw** [comment]
No, because my R on windows builds nothing. But Intel TBB supports Windows.

**Comment by koheiw** [comment]
For non-exclusive, we should add `tokens_replace`. With this function, users can replace words keeping all other words. This function will use `qatd_cpp_tokens_replace()`.

**Comment by koheiw** [comment]
`tokens_lookup` has `capkey` already.

**Comment by koheiw** [comment]
`tokens_replace` is a function to replace single or multi word entries based on one-to-one correspondence (e.g. normalizing spelling).

`qatd_cpp_tokens_lookup` cannot keep the original tokens. There is no way to do this, keeping its ability to detect overlapped entries. The implementation closest (ugly) to `exclusive = FALSE` and `capkeys = TRUE` would be:
```
mx <- cbind(dfm(tokens_remove(toks, dict)), dfm(tokens_lookup(toks, dict, capkeys=TRUE))

```
It prefer the option to run the `tokens_compound` when multi-words entries are important.

**Comment by kbenoit** [comment]
What if we use the same priority rules as `tokens_compound` for `exclusive = FALSE`, first compounding then replacing, so that we get this behaviour:

```r
toks <- tokens(c(doc1 = "Mexico signed a new libertarian law with Canada.",
                 doc2 = "Let freedom ring in the United States!"),
               removePunct = TRUE)
dict <- dictionary(list(country = c("united states", "mexico", "canada"), 
                        "law words" = c('law*', 'constitution'), 
                        freedom = c('free', "freedom", 'libertarian'),
                        overlap = "United"))

tokens_lookup(toks, dict, exclusive = FALSE, capkeys = TRUE)
# tokens from 2 documents.
# doc1 :
# [1] "COUNTRY"      "signed"      "a"           "new"         "FREEDOM" "LAW WORDS"        
# [7] "with"        "COUNTRY"     
# 
# doc2 :
# [1] "Let"     "FREEDOM" "ring"    "in"      "the"     "COUNTRY"
```

Note that the `COUNTRY` tag takes priority over the `OVERLAP` for `"States"`, since it is first formed as part of the compound `"United States"`.

**Comment by koheiw** [comment]
I think I can do this easily using the same underlying function as of tokens_compound.

**Comment by kbenoit** [comment]
Great, then we restore the "thesaurus"-type functionality to multi-word value dictionaries, for tokens. This is a valuable feature imho.

**Comment by koheiw** [comment]
Here it is
```
> tokens_lookup(toks, dict, exclusive = FALSE, capkeys = TRUE)
tokens from 2 documents.
doc1 :
[1] "COUNTRY"   "signed"    "a"         "new"       "FREEDOM"   "LAW WORDS" "with"      "COUNTRY"  

doc2 :
[1] "Let"     "FREEDOM" "ring"    "in"      "the"     "COUNTRY"
```

**Comment by kbenoit** [comment]
Nice! Is that in a new branch?

**Comment by kbenoit** [comment]
Solved in https://github.com/kbenoit/quanteda/commit/2a4a644f11909015953bc7d11e8e54c0c117964c.
