### ISSUE TITLE
need language parameter for stemming in dfm

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#368]
possibly change the argument from `stem = TRUE` to:

```r
dfm(x, stem = c("none", SnowballC::getStemLanguages())
```

where `"none"` is the default disabling stemming. To prevent old code from breaking, `TRUE` will trigger the default `language = "english"`. (Sometimes the anarchy of S3 can be put to good use!)

**Comment by jonasmoons** [comment]
Thank you, I was looking for this. For anyone looking for this as well, this works for now:

```
my_dfm <- dfm(text_corpus)
my_dfm <- dfm_wordstem(my_dfm, language = "dutch")
```

Replace "dutch" with the language you are looking for.

**Comment by kbenoit** [comment]
Note: Could address this through `quanteda_options("language")`.

**Comment by kbenoit** [comment]
### Proposal:

**New "language" argument in `quanteda_options`:**

```r
quanteda_options(language = "english")
```

**New `*_wordstem()` default arguments:**

```r
char_wordstem(x, language = quanteda_options("language"))
tokens_wordstem(x, quanteda_options("language"))
dfm_wordstem(x, quanteda_options("language"))
```

**New `stopwords()` default argument:**

```r
stopwords(kind = quanteda_options("language"))
```

To set the language, the user would run this before the `dfm()` call:
```r
quanteda_options(language = "french")
```
to get French stopwords and stemming using this call:
```r
dfm(x, stem = TRUE, stopwords = stopwords())
```

**Comment by koheiw** [comment]
It makes sense to put extra arguments to options to avoid functions to become too complex, but `language` seems to general here, because users might need to set `quanteda_options(language = "SMART")`, but SMART is not a language. It should be like `quanteda_options(stopwords_kind = "SMART")` more specifically.

`language` option can also cause confusion with `Sys.setlocale()` which changes R's behavior much more broadly.

**Comment by kbenoit** [comment]
Good point. A user could always override the defaults for stopwords, of course, but I agree this might be confusing and somewhat inconsistent with other options that rely on languages.

Perhaps we should use a language option that affects only stemming? 

Or, we simply add a `stem_language` option to `dfm()`.
