### ISSUE TITLE
Wishlist: Add ability to sort by count in collocations function

### ISSUE THREAD

**Issue by BobMuenchen** [kbenoit/quanteda#385]
Over the years I've watched as many university departments switch from quantitative analysis of numbers to manual qualitative analysis of text using tools like NVivo. Their members are often weak on statistical analysis, so the simpler you can make quanteda, the more of them you'll get using it. One way to do this is to have the collocations function default to sorting by descending count, and displaying no other statistic when none is requested. At least adding that as an option would be nice.

On a related topic, I'm used to the G2 and X2 stats being similar from two-way numeric tables, so I was surprised to see them be so different in collocations. I haven't really dug into the two equations in the help file, but here's an example in case you were also expected their calculations to yield similar results:

> seeking_ngrams <- collocations(
+              seeking_df$text,
+              method = "lr",
+              size = 2:3)
> head(seeking_ngrams, 10)
      word1      word2 word3 count       G2
 1: looking        for          62 492.3429
 2:      at        box          52 449.3582
 3: message         at          32 273.4155
 4:      if     you're          30 251.1167
 5:     i'm    looking          51 223.9604
 6:   leave          a          34 200.9349
 7:       a    message          33 171.2980
 8:      my     name's          18 167.1263
 9:  you're interested          18 164.0933
10:   brown       hair          18 113.3327
> seeking_ngrams <- collocations(
+   seeking_df$text,
+   method = "chi2",
+   size = 2:3)
> head(seeking_ngrams, 10)
          word1     word2 word3 count   X2
 1:  absolutely   nothing           1 3391
 2:      active intellect           1 3391
 3:    aerobics   bowling           1 3391
 4:         age    aren't           1 3391
 5: alternative  medicine           1 3391
 6:      aren't important           1 3391
 7:      around      bars           1 3391
 8:         art   teacher           1 3391
 9:         bar     fight           1 3391
10:    baseball    maniac           1 3391

**Comment by BobMuenchen** [comment]
I've learned a bit more about this sorting process. The help file for collocations says, “Detects collocations from texts or a corpus, returning a data.frame of collocations and their scores, sorted in descending order of the association measure.” This is not true when you specify “size=2:3” as all the bigrams sort first, then the trigrams. This drove me totally crazy since the popular bigrams I had were “sense of” and “of humor”. The trigram “sense of humor” occurred with exactly the same frequency, but it was located hundreds of lines away due to 1) sorting and 2) G2 value that put it toward the bottom of the second (trigram) set. For people starting out studying phrases, that would boggle their minds!  Sorting by overall G2 regardless of *gram would be better, but sorting by count to me makes far more sense as a default.

**Comment by koheiw** [comment]
@BobMuenchen is right that the sorting order is funny:
```r
txts <- c("quanteda is a package for quantitative text analysis", 
          "quantitative text analysis is a rapidly growing field", 
          "The population is rapidly growing")
toks <- tokens(txts)
extstat_collocations(toks, method = "lr", max_size = 3, min_count = 1)

                  collocation count        G2
1           quantitative text     2 12.557955
2               text analysis     2 12.557955
3             rapidly growing     2 12.557955
4                        is a     2  8.738870
5                 package for     1  7.724130
6            for quantitative     1  7.724130
7               growing field     1  7.724130
8              The population     1  7.724130
9                   a package     1  4.951541
10                quanteda is     1  3.905045
11                analysis is     1  3.905045
12              population is     1  3.905045
13                  a rapidly     1  2.304034
14                 is rapidly     1  1.390970
15 quantitative text analysis     2 23.560468
16   package for quantitative     1 14.695802
17      for quantitative text     1 14.695802
18      rapidly growing field     1 14.695802
19          a rapidly growing     1 13.736956
20         is rapidly growing     1 12.857319
21              quanteda is a     1 12.536461
22              analysis is a     1 12.536461
23               is a package     1 12.536461
24              a package for     1 11.923213
25           text analysis is     1 11.923213
26          The population is     1 11.923213
27               is a rapidly     1 10.084731
28      population is rapidly     1  8.424986
```

**Comment by BobMuenchen** [comment]
That's a good example. I wonder how often a sort by count, then G2 within count, would work as well as it would with this corpus. With that as default, someone who didn't know what G2 was, would see "quantitative text analysis" at the top, tied with the others that had a count of 2. With very long lists, it would at least draw their eye to what's important even though they may not understand G2. 

To me, the default of sorting first by n-gram level is of no interest at all.

**Comment by koheiw** [comment]
If, for example, `method = "lr"` is makes sense to sort by G2. But we had `method = "count"`, its fine to sort by count. @kbenoit, what do you think?

**Comment by BobMuenchen** [comment]
That makes sense. It's the sort by n-gram level THEN count that doesn't make sense to me. When sorting by count, in this example how would you break all the ties? That's where I like the approach of sorting by G2 within count, even when method = "count".

**Comment by koheiw** [comment]
I am fixing separate sorting of bigrams and trigrams now. Almost done.

**Comment by kbenoit** [comment]
There's always ex-post sorting, show below using **data.table**:

```r
textstat_collocations(toks, method = "lr", max_size = 3, min_count = 1)
# collocation count        G2
# 1           quantitative text     2 12.557955
# 2               text analysis     2 12.557955
# 3             rapidly growing     2 12.557955
# 4                        is a     2  8.738870
# 5                 package for     1  7.724130
# 6            for quantitative     1  7.724130
# 7               growing field     1  7.724130
# 8              The population     1  7.724130
# 9                   a package     1  4.951541
# 10                quanteda is     1  3.905045
# 11                analysis is     1  3.905045
# 12              population is     1  3.905045
# 13                  a rapidly     1  2.304034
# 14                 is rapidly     1  1.390970
# 15 quantitative text analysis     2 23.560468
# 16   package for quantitative     1 14.695802
# 17      for quantitative text     1 14.695802
# 18      rapidly growing field     1 14.695802
# 19          a rapidly growing     1 13.736956
# 20         is rapidly growing     1 12.857319
# 21              quanteda is a     1 12.536461
# 22              analysis is a     1 12.536461
# 23               is a package     1 12.536461
# 24              a package for     1 11.923213
# 25           text analysis is     1 11.923213
# 26          The population is     1 11.923213
# 27               is a rapidly     1 10.084731
# 28      population is rapidly     1  8.424986

coll <- textstat_collocations(toks, method = "lr", max_size = 3, min_count = 1)

require(data.table)
coll_dt <- data.table(coll)
setorder(coll_dt, -G2)
coll_dt
# collocation count        G2
# 1: quantitative text analysis     2 23.560468
# 2:   package for quantitative     1 14.695802
# 3:      for quantitative text     1 14.695802
# 4:      rapidly growing field     1 14.695802
# 5:          a rapidly growing     1 13.736956
# 6:         is rapidly growing     1 12.857319
# 7:          quantitative text     2 12.557955
# 8:              text analysis     2 12.557955
# 9:            rapidly growing     2 12.557955
# 10:              quanteda is a     1 12.536461
# 11:              analysis is a     1 12.536461
# 12:               is a package     1 12.536461
# 13:              a package for     1 11.923213
# 14:           text analysis is     1 11.923213
# 15:          The population is     1 11.923213
# 16:               is a rapidly     1 10.084731
# 17:                       is a     2  8.738870
# 18:      population is rapidly     1  8.424986
# 19:                package for     1  7.724130
# 20:           for quantitative     1  7.724130
# 21:              growing field     1  7.724130
# 22:             The population     1  7.724130
# 23:                  a package     1  4.951541
# 24:                quanteda is     1  3.905045
# 25:                analysis is     1  3.905045
# 26:              population is     1  3.905045
# 27:                  a rapidly     1  2.304034
# 28:                 is rapidly     1  1.390970
# collocation count        G2
```

**Comment by BobMuenchen** [comment]
Yes, sorting provides whatever order one might need. I'm just hoping to get defaults optimized for as low-level R knowledge as possible.
