### ISSUE TITLE
tokens_ngrams(x, n = ...) fails when ntokens(x) < n

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#391]
```r
packageVersion("quanteda")
## [1] ‘0.9.8.9029’

tokens_ngrams(tokens("a"), n = 2)
## Warning: stack imbalance in '.Call', 38 then 39
## Warning: stack imbalance in '{', 35 then 36
## Warning: stack imbalance in '<-', 28 then 29
## tokens from 1 document.
## Component 1 :
## character(0)
```

Note this is not the case for `char_ngrams()`:
```r
char_ngrams("a", n = 2)
## NULL
```

**Comment by koheiw** [comment]
I found this is coming from `stringi::stri_encode` when it tries to set encoding of empty type vectors.

**Comment by kbenoit** [comment]
Still not solved; I think it's part of the C++ code in `qatd_cpp_tokens_ngrams` rather than coming from `stringi::stri_encode()`. I did use the `stringi::stri_encode()` in a modified `types()` in the latest commit (87251aa) however. Please use the `types()` functions instead of directly addressing the `attr(x, "types")` since this encapsulates and centralises this functionality, meaning if we change the object type for some reason, we can change the behaviour in the single function.

**Comment by koheiw** [comment]
That is strange. I do not see warnings in the branch.
```
> tokens_ngrams(tokens("a"), n = 2)
tokens from 1 document.
Component 1 :
character(0)
```
I am not using `type()` here because it does not work with the list object returned from the C++ function. If I add class attributes in the C++ code, it will work, but not sure I should do this. 
```
 x <- qatd_cpp_tokens_ngrams(x, types(x), concatenator, n, skip + 1)
types_ngm <- attr(x, 'types')
```

**Comment by kbenoit** [comment]
That branch is deleted. While you might have a local copy, it's gone from the repo. You should create a new branch to solve this.

I modified `types()` to make it work, and as per comments above prefer you do as well to fix this. And make the test pass when it's commented out.

**Comment by koheiw** [comment]
Do you mean that you deleted bugfix_391-392 without merging my fix to the master, and I have to push another branch with the same fix?

**Comment by kbenoit** [comment]
No those fixes are all in the master now, except the last fix part of #391. make a new issue-391 and all your previous work will be in there. (Previous work subject to a few modifications on my end.)

**Comment by koheiw** [comment]
I can see the warnings in the master. It looks like another trick by tokens methods.

```
> tokens_ngrams(tokens("a"), n = 2)
tokens from 1 document.
Warning: stack imbalance in '.Call', 82 then 83
Warning: stack imbalance in '{', 79 then 80
Warning: stack imbalance in '{', 71 then 72
Component 1 :
character(0)

> out <- tokens_ngrams(tokens("a"), n = 2)
Warning: stack imbalance in '.Call', 215 then 216
Warning: stack imbalance in '{', 212 then 213
Warning: stack imbalance in '{', 204 then 205
Warning: stack imbalance in '.Call', 215 then 216
Warning: stack imbalance in '{', 212 then 213
Warning: stack imbalance in '{', 204 then 205
Warning: stack imbalance in '.Call', 234 then 235
Warning: stack imbalance in '{', 231 then 232
Warning: stack imbalance in '{', 223 then 224
> unclass(tokens_ngrams(tokens("a"), n = 2))
[[1]]
integer(0)

attr(,"types")
character(0)
attr(,"what")
[1] "word"
attr(,"ngrams")
[1] 2
attr(,"concatenator")
[1] "_"
attr(,"skip")
[1] 0

```

**Comment by kbenoit** [comment]
I can work on the tokens `"[["` aspects but the return should be `NULL` in the list element rather than `character(0)`, as per this:

```r
> char_ngrams("a", n = 2)
NULL
```

**Comment by kbenoit** [comment]
This is a problem in reassign_attributes so I will fix it. Although: it would be nice if:

```r
> quanteda:::qatd_cpp_tokens_ngrams(tokens("a"), "a", "_", 2L, 0L)
[[1]]
NULL

attr(,"types")
character(0)
```
 
(instead of `[[1]]` being `character(0`)

**Comment by koheiw** [comment]
I am just changing the C++ code to return NULL for empty documents.

**Comment by kbenoit** [comment]
perfect, then I will fix `reassign_attributes()` to avoid the `'.Call'` errors.
