### ISSUE TITLE
char_ngrams/token_ngrams.character call different C++ ngrams generator from tokens_ngrams()

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#392]
`char_ngrams/token_ngrams.character`:   calls `skipgramcpp()`

`tokens_ngrams.tokens`: calls `qatd_cpp_ngram_mt_list()`

Is this intentional? Behaviours are different: see #391.

**Comment by koheiw** [comment]
I will use qatd_cpp_tokens_ngrams() with tokens() to remove skipgramcpp() entirely.
