### ISSUE TITLE
print.tokens() does not print padding

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#394]
`print` method does not show padding indexed zero (not registered in `types`) as shown below. There are set of modified `tokens` methods for this purpose in dev_lookup branch, but not merged in the master. Inspection of padding is very important because contiguous collocations and ngrams terminates at paddings. 
 
```r
toks <- tokens(c("This is a sentence.", "This is a second sentence."), 
                 removePunct = TRUE)
tokens_select(toks, c("is", "a", "this"), selection = "keep", padding = FALSE)
# tokens from 2 documents.
# Component 1 :
# [1] "This" "is"   "a"   
# 
# Component 2 :
# [1] "This" "is"   "a"   

tokens_select(toks, c("is", "a", "this"), selection = "keep", padding = TRUE)
# tokens from 2 documents.
# Component 1 :
# [1] "This" "is"   "a"   
# 
# Component 2 :
# [1] "This" "is"   "a"   

tokens_select(toks, c("is", "a", "this"), selection = "remove", padding = FALSE)
# tokens from 2 documents.
# Component 1 :
# [1] "sentence"
# 
# Component 2 :
# [1] "second"   "sentence"

tokens_select(toks, c("is", "a", "this"), selection = "remove", padding = TRUE)
# tokens from 2 documents.
# Component 1 :
# [1] "sentence"
# 
# Component 2 :
# [1] "second"   "sentence"
```

**Comment by kbenoit** [comment]
I'm fixing it by redefining `tokens_hashed_recompile()` to map any 0s in the integer table to a new type with a value of `""`, but this is a workaround for a more fundamental problem that with padding, the `tokens_select(x, padding = TRUE)` code should not have used 0 in the hash table. We index the types using the integer table values themselves, and R cannot index from 0, so this value breaks the basic way that our hashing lookup works.

Anyway it's fixed but would be better to fix at the source (the C++ code).

**Comment by koheiw** [comment]
Index value for padding is arbitrary, and I can change it to any other integer values in C++ easily. But I think zero is good, because it is not used in R.

**Comment by kbenoit** [comment]
It's *not* good *because* it's not used in R! Essentially we need to keep the same scheme but add a new type called "", and this needs to have a non-zero index. This is what the workaround does.

**Comment by koheiw** [comment]
Adding "" to the type vector is one solution, but my solution was to shift the vector by one like this. Very simple, isn't it?
```
c("", types)[index + 1]
```
Anyway, I really want the index of padding to be always the same for the efficiency of the C++ code.
