### ISSUE TITLE
Implement word2vec and related methods for corpus objects

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#40]
Will need to index the tokens/sentences first

**Comment by igorbrigadir** [comment]
This is relevant to my interests! I'm new to R & quanteda - only noticed this issue now.

There's a package that wraps the original C implementation here: http://rpackages.ianhowson.com/rforge/tmcn.word2vec/ I might be missing something, but it looks like that doesn't allow you to set any of the parameters in word2vec (training iterations, learning rate, vector size etc.), which is of limited use.

A wrapper to load trained models could be useful though, and (maybe?) easy to implement? .bin models created by word2vec in C are just strings & floats separated by spaces & newlines packed into a binary file.

**Comment by igorbrigadir** [comment]
Just found this: https://github.com/bmschmidt/wordVectors

Looks like it has most things you'll need for word2vec

**Comment by kbenoit** [comment]
thanks for the reference!

On 23 Oct 2015, at 06:47, Igor Brigadir <notifications@github.com<mailto:notifications@github.com>> wrote:


Just found this: https://github.com/bmschmidt/wordVectors

Looks like it has most things you'll need for word2vec

**Comment by dselivanov** [comment]
If you really need word embeddings - just use `glove()` from [text2vec](https://github.com/dselivanov/text2vec) which implements [GloVe](http://nlp.stanford.edu/projects/glove/) algorithm. It is faster and more accurate than word2vec. I spent **a lot** of time for fully parallel and efficient C++ implementation.

**Comment by kbenoit** [comment]
thanks, I’ve cloned it and will spend some time working through the source and examples.  I’d love to be able to make the core C++ parts work with our tokenized text object, tokenized as ngrams.  This object class is essentially a named list of character object, with each element in the list being a vector of tokens.

On 19 Dec 2015, at 14:15, Dmitriy Selivanov <notifications@github.com<mailto:notifications@github.com>> wrote:


If you really need word embeddings - just use glove() from text2vec<https://github.com/dselivanov/text2vec> which implements GloVe<http://nlp.stanford.edu/projects/glove/> algorithm. It is faster and more accurate than word2vec. I spent a lot of time for fully parallel and efficient C++ implementation.

**Comment by dselivanov** [comment]
This will be simple, you just need to create correct iterator.
20 дек. 2015 г. 11:50 пользователь "Kenneth Benoit" <
notifications@github.com> написал:

> thanks, I’ve cloned it and will spend some time working through the source
> and examples. I’d love to be able to make the core C++ parts work with our
> tokenized text object, tokenized as ngrams. This object class is
> essentially a named list of character object, with each element in the list
> being a vector of tokens.
>
> On 19 Dec 2015, at 14:15, Dmitriy Selivanov <notifications@github.com

**Comment by kbenoit** [comment]
I’d be delighted if you wanted to demonstrate!

Ken

On 20 Dec 2015, at 09:35, Dmitriy Selivanov <notifications@github.com<mailto:notifications@github.com>> wrote:

This will be simple, you just need to create correct iterator.
20 дек. 2015 г. 11:50 пользователь "Kenneth Benoit" <
notifications@github.com<mailto:notifications@github.com>> написал:

> thanks, I’ve cloned it and will spend some time working through the source
> and examples. I’d love to be able to make the core C++ parts work with our
> tokenized text object, tokenized as ngrams. This object class is
> essentially a named list of character object, with each element in the list
> being a vector of tokens.
>
> On 19 Dec 2015, at 14:15, Dmitriy Selivanov <notifications@github.com<mailto:notifications@github.com>

**Comment by Monduiz** [comment]
I see that this is closed. However, there would be a very good case and for having a word2vec and doc2vec implementation inside a quanteda workflow.

**Comment by kbenoit** [comment]
Agreed. We've started work on a vignette to show how **quanteda** can work well with the (newest) **text2vec**.
