### ISSUE TITLE
tokens_hashed_recompile needs serious optimization and fix 

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#415]
`tokens_hashed_recompile` is really slowing down the system, canceling out all the performance gain of the new architecture. It is clearly not only padding as you can see in the profvis result, too many slow `lapply()` and  `types()`.

More seriously, since `tokens_hashed_recompile` changes padding index to none zero values, `ngrams` and `sequences` does not work as it should. Padding has to be the same value always. If 0 is not convenient, 1 should be assigned to padding always.

```
> txts <- data_char_inaugural
> toks <- tokens(txts)
> microbenchmark::microbenchmark(
+     recompile=tokens_select(toks, stopwords("english"), "remove", "fixed", padding = TRUE),
+     no_recompile=tokens_select(toks, stopwords("english"), "remove", "fixed", padding = FALSE), times=10
+ )
Unit: milliseconds
         expr       min        lq      mean    median        uq       max neval
    recompile 213.63521 232.59023 271.87881 264.83559 291.31817 391.36906    10
 no_recompile  19.43363  21.29833  23.06471  21.58685  26.28745  27.44845    10
> profvis::profvis(tokens_select(toks, stopwords("english"), "remove", "fixed", padding = TRUE))

> unclass(toks2)[1]
$`1789-Washington`
   [1]   1   2   3   4   4   5   4   4   4   6   4   7   8   9   4  10  11   4  12   4  13   4   4  14   4   4  15  16   4   4   4   4   4
  [34]  17   4  18   4   4  19  20   4  21   4   4  22  23   4   4  24  25  26   4   4  27  28  20   4   4  29   4   4  30  20  31  32   4
  [67]  33  34  35   4   4  36   4  37  20   4   4  38   4   4   4  39   4   4  40  41  20   4  20   4   4  42  43  20   4   4  44  45  20
 [100]   4   4  46   4   4  47  48   2   2   4  38   4   4  49  50  23   4  51   4  52   4   4  53   4   4   4   4  54   4  55   4  56  20
 [133]   4   4  57  58   4   4  59   4   4  60  61  62   4   4   4  63  26   4   4   4  28  20   4  64   4  65   4   4  66   4   4   4  32
 [166]   4   4  67  68   4  20   4  69   4  70   4   4  71   4   4  72   4   4  73   4  74  75   4   4  76  20   4   4   4  77   4  78  27
 [199]   4  79  80  81  82   4  83   4  84   4   4  85   4  86  87  88   4   4   4  89  90   4   4   4  91  26   4   4  92   4  93   4   4
```

**Comment by kbenoit** [comment]
We're talking milliseconds still, but let's put this on the list for the next performance revision. Your suggestion about shifting the index by +1 is the simplest.

**Comment by koheiw** [comment]
200 milliseconds in small corpus (1MB) means 200 seconds or more in large corpus (1GB). `toknes_select` is not working with the Guardian corpus.

**Comment by koheiw** [comment]
I could not see the end of token selection in the Guardian corpus (234926 documents) with the function in 3 hours. There is not surprise given this:
```> microbenchmark::microbenchmark(
+     n1=tokens_select(head(toks, 1), stopwords(), valuetype = 'fixed', padding=TRUE),
+     n10=tokens_select(head(toks, 10), stopwords(), valuetype = 'fixed', padding=TRUE),
+     n100=tokens_select(head(toks, 100), stopwords(), valuetype = 'fixed', padding=TRUE),
+     n1000=tokens_select(head(toks, 1000), stopwords(), valuetype = 'fixed', padding=TRUE),
+     n2000=tokens_select(head(toks, 2000), stopwords(), valuetype = 'fixed', padding=TRUE),
+     times=1
+ )
Unit: milliseconds
  expr        min         lq       mean     median         uq        max neval
    n1   366.0379   366.0379   366.0379   366.0379   366.0379   366.0379     1
   n10   383.5364   383.5364   383.5364   383.5364   383.5364   383.5364     1
  n100   623.6510   623.6510   623.6510   623.6510   623.6510   623.6510     1
 n1000 11067.8069 11067.8069 11067.8069 11067.8069 11067.8069 11067.8069     1
 n2000 33493.7539 33493.7539 33493.7539 33493.7539 33493.7539 33493.7539     1
```

**Comment by kbenoit** [comment]
ok then clearly we need to rework it!

**Comment by kbenoit** [comment]
We can start by removing the `stri_encode()` call.

**Comment by kbenoit** [comment]
The main performance hit - and you are right, this was massive - is not the `lapply()` calls but rather the `stri_encode()` call on the types. This has now been removed, so that `types(x)` simply looks up the `attr(x, "types")` and nothing more - so no reason *ever* in our code not to use `types(x)`.

I also implemented the indexing so that if a 0 is found, which can only happen after being returned from `qatd_cpp_tokens_select()`, then it shifts the indexes by +1 and makes `""` the first type (new index value 1). If you need to send this back to C++ code then just implement the shift. If we do implement a shift, I suggest writing an internal function to go back and forth. Right now the code is hard-wired into `tokens_hashed_recompile()` to shift up by 1.
