### ISSUE TITLE
one-pass collocation detection

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#42]
for size=2, 3 as the same function
to remove bigrams that are parts of trigrams, trigrams that contain just a bigram

**Comment by koheiw** [comment]
sequences_tree.cpp in `kw-collocations` is my prototype for this.

**Comment by kbenoit** [comment]
Sounds good, but the sequence on cracking this ought to be first, make sure our calculations are correct, second, optimise. Hard to optimise if we are not first sure the non-optimised version is correct.

**Comment by koheiw** [comment]
That is not an optimize but purpose-built version for creating 2x2 tables for nested bingrams. It is not parallelized, so easy to work on.
