### ISSUE TITLE
Padding is not zero

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#428]
Padding is playing an important role in `tokens_ngrams()`. If paddings are zero, there will be not ngrams with of empty strings.
```r
toks <- tokens('a b c d e f g')
toks2 <- tokens_remove(toks, c('b', 'e'), padding = FALSE)
toks3 <- tokens_remove(toks, c('b', 'e'), padding = TRUE)
tokens_ngrams(toks)
# tokens from 1 document.
# Component 1 :
# [1] "a_b" "b_c" "c_d" "d_e" "e_f" "f_g"

tokens_ngrams(toks2)
# tokens from 1 document.
# Component 1 :
# [1] "a_c" "c_d" "d_f" "f_g"

tokens_ngrams(toks3)
# tokens from 1 document.
# Component 1 :
# [1] "a_"  "_c"  "c_d" "d_"  "_f"  "f_g"

unclass(toks3)
# [[1]]
# [1] 2 1 3 4 1 5 6
# 
# attr(,"types")
# [1] ""  "a" "c" "d" "f" "g"
# attr(,"what")
# [1] "word"
# attr(,"ngrams")
# [1] 1
# attr(,"concatenator")
# [1] ""
```
There was a set of code to keep padding = 0 in dev_lookup branch.

**Comment by koheiw** [comment]
Other cases
```
> tokens_ngrams(toks3, n=3)
tokens from 1 document.
Component 1 :
[1] "a__c" "_c_d" "c_d_" "d__f" "_f_g"

> tokens_ngrams(toks3, n=3, skip=1:2)
tokens from 1 document.
Component 1 :
[1] "a_c_"  "a_c_f" "a_d_f" "a_d_g" "_d_f"  "_d_g"  "__g"   "c__g" 
```

**Comment by kbenoit** [comment]
OK we can start this with a new branch from master. Which functions besides `tokens_ngrams` are affected?  And which C++ functions expect a 0-indexed `""` token?

I propose we fix this by adding code to perform the left-shift just before sending it to `qatd_cpp_tokens_ngrams()` and any other C++ functions that expect the 0-indexed `""`.

**Comment by koheiw** [comment]
Only `qatd_cpp_tokens_ngrams()` and `qatd_cpp_sequences()` have padding ID hard coded. But if padding is none-zero value, and the R's type vector has an empty string,  `regex2id()` will be affected (used in all the `token_*` and `kwic` functions).

There is no easy solution to this, but option 1 is still the easiest. Ad-hoc solutions would make the problem more complex.

Option 1: Set padding = 0, and modify some of the `tokens` methods. 
Option 2: Set padding = 1, and modify  `regex2id` (potentially all the `tokens_*` functions), `qatd_cpp_tokens_select()`, `qatd_cpp_tokens_ngrams()`, `qatd_cpp_sequences()`, and few of the `tokens` methods.
Option 3: Make padding ID dynamic: redesign `regex2id` (potentially all the `tokens_*` functions), `qatd_cpp_tokens_select()`, `qatd_cpp_tokens_ngrams()`, and `qatd_cpp_sequences()`.

**Comment by kbenoit** [comment]
OK since I am going to be in interviews again all day tomorrow until 5pm, I created a branch for this issue, `issue-428`. I propose we try to fix this in the simplest manner possible, which I thought was this: https://github.com/kbenoit/quanteda/compare/issue-428.

The tests I added are failing, so the fixes ought to make them pass. I think the behaviour for `n = 2, skip = 2` is wrong, by the way - see the tests for `padding = FALSE`.

Gives you something to work on tomorrow in any case!

**Comment by kbenoit** [comment]
Re your comment above, I think more things would be affected - indexing of `tokens` in particular!! - by option 1 than by catching the inputs and outputs around the two affected functions. So I definitely vote for the "ad hoc" fixes until we come up with something more systematic.

My first commits to the `issue-428` ought to fix the call to `qatd_cpp_tokens_ngrams()`. 

I looked at `regex2id()` but that in the file where that function lives, none of the functions are documented.  (Except `vector2list()`...) So hard for me to figure out the input fix for that one.

**Comment by koheiw** [comment]
`dfm` is also affected if type has an empty string.

```
> dfm(toks3)
Document-feature matrix of: 1 document, 6 features (0% sparse).
1 x 6 sparse Matrix of class "dfmSparse"
       features
docs      a c d f g
  text1 2 1 1 1 1 1
```

**Comment by kbenoit** [comment]
the dfm behaviour is a feature, not a bug. If someone wants to keep "" through `padding = TRUE` then they probably want the `""` "tokens" to be counted.

**Comment by koheiw** [comment]
For the maximum efficiency of internal processing, types should not include padding. Padding is important for human inspection, but it is usually of a small part of the data, so the cost of on-the-fly right shift (where padding is zero) in `print.tokes()`, `as.list.tokens()` etc. is small. If we re-index tokens for each of the functions, we will lose all the performance gain. Why don't you have a look at my code in `dev_lookup` branch (I can upload it if you need) for a systematic solution? It worked perfectly for me, at least.

I will add add more documentation to `regex2id()` in the next push, but it is not easy for me to find a fix for that either.

**Comment by koheiw** [comment]
Maybe the best ad-hoc solution is to hide the padding option. We do not need to waste our time for a temporary solution.
