### ISSUE TITLE
Consolidate phrases, sequences, collocations into tokens_collocations

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#434]
This would record multi-word expressions as a single token, and keep an associated list of scores inside the object, in a special sub-class of tokens.

```r
tokens_collocations(mytokens, method = "lr")
```
for instance would do what `collocations(x, "lr")` does at the moment. `sequences()` would become a method in this.

**Comment by kbenoit** [comment]
To do:
- [ ] `as.tokens()` for a collocations object
- [ ] make the existing `collocations()` object into a phrasal structure with n for length of the sequence, same as the structure of the output from `sequences()`
- [ ] explore how to make the input to `collocations()` be an `fcm` object (as well as a `tokens` object)  
- [ ] integrate the method of `sequences` into `collocations`
- [ ] figure out the best way to do the existing selection of feature patterns as in `sequences()`
- [ ] logically consistent implementation of target-based collocation in #521

**Comment by koheiw** [comment]
I changed the output of `sequences()` in as the first step. It is a data.frame but has a list of IDs and types int its attribute. I added an extractor for this method, so the list is also trimmed or ordered in the same way as the data.frame. The list is sued to bypass slow `regex2id()` in `tokens_compound()`.
```r
> head(seqs)
                      lambda      sigma count         z p
United States       20.56459 0.04324223   155 475.56728 0
Federal Government  16.07807 0.09312539    32 172.64966 0
General Government  14.50954 0.12914263    24 112.35286 0
National Government 12.88826 0.15847837    11  81.32504 0
Almighty God        13.10835 0.16301521    15  80.41181 0
Chief Justice       12.17009 0.18109481    11  67.20288 0
```

```r
> str(head(seqs))
Classes ‘collocation_new’ and 'data.frame':	6 obs. of  5 variables:
 $ lambda: num  20.6 16.1 14.5 12.9 13.1 ...
 $ sigma : num  0.0432 0.0931 0.1291 0.1585 0.163 ...
 $ count : int  155 32 24 11 15 11
 $ z     : num  475.6 172.6 112.4 81.3 80.4 ...
 $ p     : num  0 0 0 0 0 0
 - attr(*, "ids")=List of 6
  ..$ : num  167 168
  ..$ : num  1281 169
  ..$ : num  1356 169
  ..$ : num  2291 169
  ..$ : num  150 3061
  ..$ : num  528 1097
 - attr(*, "types")= chr  "Fellow" "-" "Citizens" "Senate" ...
```
However, I noticed that we cannot used `tokens_select()` before `sequences()` to remove its `features` argument, because `tokens_select()` reindexs types. This is the same to `collocations()`, although it seems that it is using characters instead of IDs internally...

**Comment by kbenoit** [comment]
@kohei would you be able to resuscitate this from the partially sidelined `dev-collocaton` branch, in a new branch from the current `master`, to (re)create the wrapper function `textstat_collocations()`? 

signature:

```r
textstat_collocations(x, method =  c("lr", "chi2", "pmi", "dice", "bj"), 
                      case_insensitive = TRUE, 
                      min_count = 1, 
                      size = 2, n = NULL)
```

with a method defined only for `tokens`.

We can keep, but make internal, `sequences()` but I'd prefer not to put selection into the `textstat_collocations()` function, since we have a separate function for that. If we keep the pads, that will also prevent non-adjacent collocations from forming. In the size I think we could also vectorise that so that it finds collocations within a range, although we could also add a `max_size` as per existing `sequences()`, which means `2:max_size` if an existing `collocations()` method is called.

We can make the `collocations()` function internal (but exported) and have `textstat_collocations()` as a wrapper for now, and work on rewriting this for the next release. `method = "bj"` of course will call `sequences()` but (without feature selection).

**Comment by koheiw** [comment]
`textstat_collocations()` has returned from hibernation to issue-434.
```r
cols <- textstat_collocations(toks, method = "lr", "^([a-z]+)$", valuetype = "regex", min_count = 1)

                 count        G2
software testing     2 11.780234
for word             1  7.347901
word pairs           1  7.347901
more Software        1  7.347901
Software Testing     1  7.347901
This is              1  4.575312
is more              1  4.575312
testing again        1  4.575312
a software           1  4.575312
again for            1  4.575312
this is              1  4.575312
is software          1  1.956722
looking for          1  1.956722
looking again        1  1.956722

as.tokens(cols)

tokens from 14 documents.
Component 1 :
[1] "software" "testing" 

Component 2 :
[1] "for"  "word"

Component 3 :
[1] "word"  "pairs"

Component 4 :
[1] "more"     "Software"

Component 5 :
[1] "Software" "Testing" 

Component 6 :
[1] "This" "is"  

Component 7 :
[1] "is"   "more"

Component 8 :
[1] "testing" "again"  

Component 9 :
[1] "a"        "software"

Component 10 :
[1] "again" "for"  

Component 11 :
[1] "this" "is"  

Component 12 :
[1] "is"       "software"

Component 13 :
[1] "looking" "for"    

Component 14 :
[1] "looking" "again"  
```

**Comment by kbenoit** [comment]
This is not currently working:
```r
txts <- c("quanteda is a package for quantitative text analysis", 
          "quantitative text analysis is a rapidly growing field", 
          "The population is rapidly growing")
toks <- tokens(txts)
coll <- textstat_collocations(toks, method = "lr")
as.tokens(coll)
# tokens from 5 documents.
# Component 1 :
# [1] NA NA NA
# 
# Component 2 :
# [1] NA NA
# 
# Component 3 :
# [1] NA NA
# 
# Component 4 :
# [1] NA NA
# 
# Component 5 :
# [1] NA NA
```
