### ISSUE TITLE
KWIC with keywords of length>1 (multiple keywords)

### ISSUE THREAD

**Issue by toddntucker** [kbenoit/quanteda#44]
It would nice to be nice to be able to use your KWIC function with keywords of length longer than 1. Maybe this is already possible, but I tried using a regex workaround (i.e. kwic(df$text,"(united)\\s(states),window = 3) to no avail.

**Comment by kbenoit** [comment]
No, only words are implemented so far, but we totally agree this would be a useful feature, and plan to implement it at the same time as we implement corpus indexing.  so: coming soon.

On 20 May 2015, at 23:48, Todd Tucker <notifications@github.com<mailto:notifications@github.com>> wrote:


It would nice to be nice to be able to use your KWIC function with keywords of length longer than 1. Maybe this is already possible, but I tried using a regex workaround (i.e. kwic(df$text,"(united)\s(states),window = 3) to no avail.

**Comment by toddntucker** [comment]
Thanks.   Keep up the great work.

**Comment by conjugateprior** [comment]
In the meantime (and if you can install it) there's multiword concordances available in [rjca](https://github.com/conjugateprior/rjca).  The vignette has examples at the end.

**Comment by conjugateprior** [comment]
As you could probably surmise from the Java code my implementation of multiword concordances involves a 'walk and match' procedure from each first word start point provided by the document's word level inverted index. Hand-rolled and nothing fancy. This feels like it would be a natural Rcpp task in quanteda.

**Comment by kbenoit** [comment]
Added in 0.8.5-4 (5 October). New formals and new options for pattern matching too, also better object-oriented behaviour. See `?kwic`.
