### ISSUE TITLE
features should behave consistently

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#450]
Right now, functions that take a "features" argument have inconsistent handling of this argument type. From `tokens_select`:

> `features`  one of: a character vector of features to be selected, a dictionary class object whose values (not keys) will provide the features to be selected.

But in fact a list works too: 

```r
toks <- tokens(c(d1 = "a b c d e", d2 = "a d e f g"))
mydfm <- dfm(toks)
feats <- c(one = "a", two = "c", three = "f")

tokens_select(toks, feats)
# tokens from 2 documents.
# d1 :
# [1] "a" "c"
# 
# d2 :
# [1] "a" "f"
#
tokens_select(toks, as.list(feats))
# tokens from 2 documents.
# d1 :
# [1] "a" "c"
# 
# d2 :
# [1] "a" "f"
#
tokens_select(toks, dictionary(as.list(feats)))
# tokens from 2 documents.
# d1 :
# [1] "a" "c"
# 
# d2 :
# [1] "a" "f"
#
```

However this is not the case for `dfm_select`:
```r
dfm_select(mydfm, feats)
# kept 3 features, from 3 supplied (glob) feature types
# Document-feature matrix of: 2 documents, 3 features (33.3% sparse).
# 2 x 3 sparse Matrix of class "dfmSparse"
#     features
# docs a c f
#   d1 1 1 0
#   d2 1 0 1
dfm_select(mydfm, as.list(feats))
# Error in dfm_select.dfm(mydfm, as.list(feats)) : 
#  features must be of type character, dictionary, or dfm 

dfm_select(mydfm, dictionary(as.list(feats)))
# kept 3 features, from 3 supplied (glob) feature types
# Document-feature matrix of: 2 documents, 3 features (33.3% sparse).
# 2 x 3 sparse Matrix of class "dfmSparse"
#     features
# docs a c f
#   d1 1 1 0
#   d2 1 0 1
```

**Preferred approach:**

We consolidate the features/sequences function as in `tokens_compound`, which uses `@inheritParams sequence2list` which has its own argument list. This way, as with `valuetype`, we centralise and standardise the handling of the arguments for features and sequences.

These take:
*  character vector, whose elements will be split on whitespace;
*  list of characters, consisting of a list of token patterns, separated by white space;
*  tokens object;
*  dictionary object;
*  collocations object.

**Functions affected**:

* `tokens_compound`  
* `tokens_select`
* `sequences`  
* `dfm_select`
* did I miss any others??

**Comment by koheiw** [comment]
It is a good idea to use `sequence2list()` to standardize inputs. `kwic` should be included in the list of functions affected, but `sequences` is not, because id does not accept a list, and a list is coerced to a vector.

**Comment by koheiw** [comment]
How will we treat a list of characters separated by white spaces, which are multi-word features, in dfm_select?

**Comment by kbenoit** [comment]
Good question - I'll give this some thought. Time soon for a "designathon" where we talk about scored multi-word tokens, tagged tokens, and sequence/feature pattern structures.
