### ISSUE TITLE
Wishlist: 2d positions 

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#452]
Hi,
it's really nice to see that the 1d implementation of wordshoal is already available in quanteda. Can you please also provide support for the 2d model as described in [Lauderdale and Herzog 2016](https://academic.oup.com/pan/article/24/3/374/2223347/Measuring-Political-Positions-from-Legislative)?

**Comment by kbenoit** [comment]
Up to @lauderdale ...

**Comment by methodds** [comment]
As another suggestion for improvements, it would be nice if wordshoal models could include feature names and effects marginal effects. I cannot find this in the documentation:

- tol:	log-posterior tolerance used in fitting
- dir: global identification of the dimension
- theta: estimated document positions-
- beta: debate marginal effects
- alpha: estimated document fixed effects
- psi: estimated document debate-level positions
- groups: document groups
- authors: document authors 
- ll: log likelihood at convergence
- se.theta: standard errors for theta-hats
- data: corpus to which the model was fit

**Comment by kbenoit** [comment]
@methodds this sounds like a separate issue - but I was not entirely clear on what you meant. Perhaps create a new issue and clarify?

**Comment by methodds** [comment]
I just meant the wordshoal "equivalents" of ``@features``, ``@beta``, ``@psi`` in ``textmodel_wordfish()``. You still want me to open a new issue?

**Comment by kbenoit** [comment]
Yes since it's not about implementing a two-dimensional version and its resolution is independent of that issue.

**Comment by methodds** [comment]
okay, I opened #598
