### ISSUE TITLE
figure out how point quanteda.io to the quanteda GitHub web page

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#456]
There are instructions for this, but I didn't figure it out before I exceeded my time budget and had to move on. @amatsuo you'd be good at this.

github.io is registered at https://www.namecheap.com - I can provide login details.

Just to make things even more interesting, I also bought quanteda.com but through a different DNS registration company (https://www.irishdomains.com).

**Comment by amatsuo** [comment]
http://quanteda.io is live now.
