### ISSUE TITLE
tokens_ngram is producing inconsistent output

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#469]
This is caused by a race condition in ngram_id generation. mutext locking would help, but slow down should be minimal.

**Comment by koheiw** [comment]
Here is the test of reliability and stability.

```r

library(quanteda)
library(testthat)
txt <- c(one = toLower("Insurgents killed in ongoing fighting."),
         two = "A B C D E")
toks <- tokens(txt, removePunct = TRUE)

for(k in 1:1000) {
    cat('tokens:', k, "\n")
    out <- tokens_ngrams(toks, n = 2:3)
    expect_equivalent(as.list(out),
                      list(c("insurgents_killed", "killed_in", "in_ongoing", "ongoing_fighting", 
                             "insurgents_killed_in", "killed_in_ongoing", "in_ongoing_fighting"),
                           c("A_B", "B_C", "C_D", "D_E", "A_B_C", "B_C_D", "C_D_E")))
}

toks <- tokens(data_corpus_inaugural)

for (i in 1:100) {
    cat('types:', i, "\n")
    ngms <- tokens_ngrams(toks)
    types <- attr(ngms, 'types')
    expect_equal(length(types), 65181)
}

for(j in 1:100) {
    cat('dfm', j, "\n")
    dfm(tokens_ngrams(toks, n = 2))
}
```

**Comment by koheiw** [comment]
@kbenoit and @HaiyanLW , please try this on your machines. It's installation is falling but fine on my Linux and Windows.

**Comment by koheiw** [comment]
The reason for the build failure on Travis was due to old compiler that does not support c++11. The solution was to upgrade Travis from Ubuntu 12 to 14 by `dist: trusty` in travis.yml.

**Comment by kbenoit** [comment]
Nice. It's possible to specify the requirements for g++ I think in `Makevars`. You might want to double check that file to make sure you are happy with the compiler settings.

**Comment by koheiw** [comment]
I installed libraries before the build and edit `Makevars`, but did not work. It should  be possible, but seems very complex, as you can see in https://github.com/travis-ci/travis-ci/issues/979. 

On Ubuntu 14, the default C++ compiler is gcc 4.8.4, so I do not need to anything just like my own machines. We should switch to Ubuntu 14 anyway, because Ubuntu 12's official life time will end this April (no one is using such a old version for desktop).
