### ISSUE TITLE
Maybe show top corner of the dfm when printing

### ISSUE THREAD

**Issue by zachmayer** [kbenoit/quanteda#47]
```{R}
> print(dfm(inaugTexts, verbose=FALSE))
Document-feature matrix of: 57 documents, 9214 features.
```
It might be nice to also see the top "corner" of the matrix (the first 5 rows and 5 columns)

**Comment by kbenoit** [comment]
Just added: 

    myDfm <- dfm(inaugTexts, verbose = FALSE) 
    head(myDfm)
    tail(myDfm)
