### ISSUE TITLE
Return zero for non-existent documents/features

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#479]
I often face errors when trying to subset matrix by non-existing document/feature names. Why doesn't `dfm` return zero for those? It should not be difficult.

```r
mx <- dfm(c(x='a b c', y='a b'))
str(mx)
print(mx)

mx[c('y', 'z'),] # error

# Hack the matrix
doc_non <- setdiff(c('z'), rownames(mx))
attr(mx, 'Dim')[1L] <- attr(mx, 'Dim')[1L] + length(doc_non)
attr(mx, 'Dimnames')$docs <- c(attr(mx, 'Dimnames')$docs, doc_non)

mx[c('y', 'z'),] # fine

```

**Comment by kbenoit** [comment]
Currently, it's consistent with indexing for any matrix-like object:
```r
(mat <- matrix(1:6, dimnames = list(c("d1", "d2"), letters[1:3]), nrow = 2))
##    a b c
## d1 1 3 5
## d2 2 4 6
mat[c("a", "c")]
## [1] NA NA
mat[, c("a", "c")]
##    a c
## d1 1 5
## d2 2 6
mat[, c("a", "d")]
## Error in mat[, c("a", "d")] : subscript out of bounds
```

If we expand the answer when indexing on dimensions that do not exist, this is a very non-standard method of indexing. Have we considered all of the side effects?

**Comment by koheiw** [comment]
We can just let users to chose like this `dfm[,,non_existent=TRUE]` and insert the the features or documents on the fly.

**Comment by koheiw** [comment]
If face this type of problem when there is not document for reference in `textstats_keyness`, or I try to get daily frequency going through `seq.Date('2016-01-01', '2016-12-31')`.

**Comment by kbenoit** [comment]
Good suggestion on the `non_existent = TRUE` (although that sounds a bit like some mysterious Zen koan... maybe something less contradictory sounding such as `pad = TRUE`?)

We already modify how `[.dfm` works to disable `drop` (since a dfm operation should always return a dfm) so adding that option would be simple, especially if the default is `pad = FALSE`).

**Comment by koheiw** [comment]
`pad` sounds promising.

**Comment by koheiw** [comment]
By the way, this is a tiny issue, but it is good to set `verbose=FALSE` in dfm_select.

**Comment by kbenoit** [comment]
I'm thinking we should set `verbose = FALSE` for all functions, and have a global that can override them if people want to turn on all verbose messages.

**Comment by koheiw** [comment]
I think so, `verbose = FALSE` by default. Otherwise quanteda will be like some other package.
