### ISSUE TITLE
How do I turn a dfm into a sparseMatrix?

### ISSUE THREAD

**Issue by zachmayer** [kbenoit/quanteda#48]
dfm already looks a lot like a sparse Matrix:
```{R}
> str(dfm(inaugTexts, verbose=FALSE))
Formal class 'dfmSparse' [package "quanteda"] with 9 slots
  ..@ settings :List of 1
  .. ..$ : NULL
  ..@ weighting: chr "frequency"
  ..@ smooth   : num 0
  ..@ Dim      : int [1:2] 57 9214
  ..@ Dimnames :List of 2
  .. ..$ docs    : chr [1:57] "1789-Washington" "1793-Washington" "1797-Adams" "1801-Jefferson" ...
  .. ..$ features: chr [1:9214] "14th" "15th" "18th" "19th" ...
  ..@ i        : int [1:43719] 0 27 30 52 52 45 46 8 52 51 ...
  ..@ p        : int [1:9215] 0 1 3 4 5 7 9 11 12 13 ...
  ..@ x        : num [1:43719] 1 1 1 1 2 1 2 1 3 1 ...
  ..@ factors  : list()
```
I want to be able to look at the matrix elements and pass it to modeling functions that take Matrix inputs.

**Comment by pnulty** [comment]
Hi Zach, Ken knows this part of the code better so he can confirm, but dfm is a subtype of Matrix:

```R
> d <- dfm(inaugCorpus, verbose=FALSE)
> is(d, 'Matrix')
[1] TRUE
```
So for any functions that accept Matrix inputs, you should be able to substitute in a dfm. In practice there might still be issues, so if you find any particular cases where it doesn't work then let us know.

**Comment by kbenoit** [comment]
That's correct, dfmSparse inherits from the sparse matrix from Matrix.

**Comment by zachmayer** [comment]
Is there a direct conversion method?  Something as simple as "as.DgMatrix" would be nice.



—
