### ISSUE TITLE
Why tokens() has camel-cased arguments like removePunct?

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#484]
We have both camel and snake-cased arguments in the functions. Why not changing `removePunct` to `remove_punct`, for example?

**Comment by kbenoit** [comment]
It's planned - but since this is one of the most commonly used functions, I wanted to figure out how to deprecate the older names first. See approach suggested in #478.

New names would be `remove_punct`, `remove_numbers`, etc.

**Comment by koheiw** [comment]
How about this?

```r
catcher <- function(arg_new, argOld){
    if (missing(arg_new)) return(argOld)
    if (missing(argOld)) return(arg_new)
    return(arg_new)
}

test_func <- function(arg_new, ...){
    arg <- catcher(arg_new, ...)
    cat('arg:', arg, "\n")
}

test_func(arg_new = 'aaa')
test_func(argOld = 'aaa')
test_func(arg_new = 'ccc', argOld = 'ddd') # new one has the priority
```
