### ISSUE TITLE
Improvements to textstat_keyness

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#495]
This is working well now but here are some improvements for the to do list:

- [x] match the output to [Wordsmith](http://www.lexically.net/wordsmith/)'s output, since this function is likely to attract users of that program, and also it offers a method for validating our implementation

- [x] consider outputting a data.frame with additional quantities, such as counts - similar the output from the other `textstat_*` functions, e.g. `textstat_readability`

- [ ] allow a reference input that could be a vector of word frequencies, for instance the Brown corpus from `?zipfR::Brown`

- [x] performance improvements are possible, esp for the functions that `apply()` a test from `stats`, such as the implementation of the `measure = "exact"`

- [x] we ought to better investigate the literature (cited in the References section of the help page) to make sure we are applying corrections appropriately, such as Yates correction

**Comment by methodds** [comment]
Hi Ken,
thanks for the update. It works just the way it should for me, returning a dataframe with two columns, where on are the p values. 

I just had another idea: Could ```textstat_keyness``` be implemented in a way that calling ```plot()``` on it would create a word cloud with the highest score terms? 
Even better would be an option where the cloud would transform to some sort of  *contrast cloud*, where the words with highest scores are displayed in the upper half and words with the lowest scores in the lower half of the cloud. Of course this can also be done manually, but I thought this might be convenient and actually be used quite often.

**Comment by kbenoit** [comment]
Good idea. How about starting a new issue to ask for a keyness plot? If you included some rough code and/or a plot illustrating what you prefer it to look like, that would be a great start for us.

**Comment by methodds** [comment]
See #528 :)

**Comment by koheiw** [comment]
Here is a comparison with Wordsmith. What is missing from our textstat_keyness is normalized frequency of words in percent.

```r


corp <- data_corpus_inaugural

# Exprot for Wordsmith
#cat(texts(corpus_subset(corp, Year <= 1945)), file = 'pre-war.txt')
#cat(texts(corpus_subset(corp, Year > 1945)), file = 'post-war.txt')

data_ws <- read.csv('keyness.txt', sep = '\t', stringsAsFactors = FALSE)
data_ws$word <- char_tolower(data_ws$Keyword)
data_ws$Freq. <- as.numeric(data_ws$Freq.)
data_ws$RC.Freq. <- as.numeric(data_ws$RC.Freq.)

toks <- tokens(corp, remove_punct = TRUE)
data_qt <- textstat_keyness(dfm(toks), docvars(toks, 'Year') > 1945)
data_qt$word <- rownames(data_qt)

data_both <- merge(data_ws, data_qt, by = 'word', all = TRUE)
data_both <- data_both[order(data_both$Keyness, decreasing = TRUE),]
data_both <- data_both[!is.na(data_both$Keyness),]

cor(data_both$Freq., data_both$n_target, use = 'pairwise.complete.obs') # 0.999986
cor(data_both$Keyness, data_both$chi2, use = 'pairwise.complete.obs') # 0.9942549

```
Ouput from Wordsmith: [https://1drv.ms/t/s!AnEkIea2cHXzgYQ_dW6NdyEYgPfQ0g](url)

**Comment by kbenoit** [comment]
@koheiw that link doesn't seem to be working. 

Are we ok on this issue now, or do you suggest we add the normalised measure as per Wordsmith?
