### ISSUE TITLE
dfm_lookup needs "non-matched" column option

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#496]
For computing relative frequencies in a dfm after applying a dictionary, what is usually needed is the dictionary count relative to all features. But `dfm_lookup` only keeps features found. To get relative frequencies of all tokens requires some workarounds, but it would be better to have directly. (An earlier version of `dfm()` did behave this way.)

```r
require(magrittr)

txt <- c(d1 = "a b c a a b d",
         d2 = "a a b d", 
         d3 = "a b d D d D d")
toks <- tokens(txt)

mydict <- dictionary(list(A = "a", BC = c("b", "c")))

# how to get frequencies of non-dictionary items?
dfm(toks, tolower = FALSE, dictionary = mydict) %>% 
    dfm_weight("relFreq")
## Document-feature matrix of: 3 documents, 2 features (0% sparse).
## 3 x 2 sparse Matrix of class "dfmSparse"
##     features
## docs         A        BC
##   d1 0.5000000 0.5000000
##   d2 0.6666667 0.3333333
##   d3 0.5000000 0.5000000

# not idea since cannot distinguish keys from original features
dfm(toks, tolower = FALSE) %>% 
    dfm_lookup(dictionary = mydict, exclusive = FALSE) %>% 
    dfm_weight("relFreq")
## applying a dictionary consisting of 2 keys
## Document-feature matrix of: 3 documents, 4 features (16.7% sparse).
## 3 x 4 sparse Matrix of class "dfmSparse"
##            d         D         A        BC
## d1 0.1428571 0         0.4285714 0.4285714
## d2 0.2500000 0         0.5000000 0.2500000
## d3 0.4285714 0.2857143 0.1428571 0.1428571



# workaround
tokens_select(toks, unlist(mydict), padding = TRUE) %>%
    tokens_lookup(dictionary = mydict, exclusive = FALSE) %>%
    dfm(tolower = FALSE) %>%
    dfm_weight("relFreq")
## Document-feature matrix of: 3 documents, 3 features (0% sparse).
## 3 x 3 sparse Matrix of class "dfmSparse"
##     features
## docs                   A        BC
##   d1 0.1428571 0.4285714 0.4285714
##   d2 0.2500000 0.5000000 0.2500000
##   d3 0.7142857 0.1428571 0.1428571
```

**Comment by koheiw** [comment]
I think this is related to  #479.

**Comment by kbenoit** [comment]
> I think this is related to #479.

Only partially - my issue is not to pad non-existent features with zeroes, but rather to count all tokens not matching a dictionary key as an "Other" count. The workaround does this by counting the pads `""` after removing all matches to keys, then applying the dictionary to the tokens, then passing to straight `dfm()` which preserves the pads as a `""` feature.

**Comment by koheiw** [comment]
How about recording the `lengths()` of tokens in an attribute before the `exclusive=TRUE` tokens lookup, and use it in `dfm_weight()`?

**Comment by kbenoit** [comment]
Excellent idea that would work for dfm_lookup too.

**Comment by koheiw** [comment]
I am working on this. `ntoken` will be saved in `_doclen` in docvars to normalized lookup results in `dfm_weight()`. There are two ways to do: 
1) always use `_doclen` in `dfm_weight` when `type = relFreq` and a **dfm** has `dictionary` attribute.
2) add `type = dictionary` to `dfm_weight()` and use `_doclen` only when this option is chosen.

**Comment by kbenoit** [comment]
I don't think we should modify `dfm_weight()` at all for this, but rather we should add a column to the dictionary dfm for "_NON_DICT_" (or something with a nicer name?) when `exclusive = TRUE`, to count all the tokens not in a dictionary. Then the relative weights would work because this column would be present. 

We could implement a similar version for tokens if you want. 

The whole notion of weights gets more complicated when a dictionary has keys whose values overlap. This means you cannot simply store the length of the tokens, and subtract the matches. For instance, this should be:

```r
dict <- dictionary(list(one = c("a", "b"), two = "a"))
dfm("a b c", dictionary = "dict")
```
under this scheme should produce:
```
       one    two  _NOT_DICT_ 
text1   2      1      1        
```
which sums to more than the number of tokens.

**Comment by koheiw** [comment]
OK let's leave `dfm_weight()` intact. I would prefer to store the number of original tokens in docvars, because tokens will look funny when there are hundreds of _NOT_DICT_. If the docvar is accessible to users, they can normalize dfm in the same way as they would do if it is in the column.
This is
```r
mx < dfm("a b c", dictionary = "dict")
mx / docvar(mx, "document_length")
```
instead of 
```r
mx < dfm("a b c", dictionary = "dict")
mx / rowSums(mx)
```

Alternatively, we can extend `ntoken()` adding `original` argument.
```r
mx < dfm("a b c", dictionary = "dict")
mx / ntoken(mx, original = TRUE)
```
I like the third option the best, actually.

**Comment by kbenoit** [comment]
I like the third option best too, and storing the original ntokens in a slot/attribute for dfm and tokens respectively. 

There would only ever be one column of `_NOT_DICT_`, and I think creating this this ought to be the default for `dfm_lookup(x, dictionary = , exclusive = TRUE)`. Then `dfm_weight()` works applied to the dfm.

**Comment by koheiw** [comment]
Great. I will go for the third option. I will use a internal docvar for this instead of slot/attributes, because tokens and dfm could be subset by users after applying dictionaries.

**Comment by koheiw** [comment]
This is a good opportunity (although not easy) to update the way we handle docvars. To keep original ntoken, we should add an internal variable to docvars. `corpus_segment()` already adds internal-only variables ('_document', '_docid' and '_segid'). Similarly, tokens_* and dfm_* can be record ntoken as '_length` (we have to think about the names as well). I believe all these internal variables should **always** exist in corpus, tokens, and dfm. In this case, we have to update constructors for those object.

Addition of internal docvars is not only to solve this issue, but to enable future extension of those object, such as off-memory corpus and xpointer tokens objects. For example,

**Comment by kbenoit** [comment]
If you have added stuff to the definition of the "matadoc" type of docvars, that's fine, we can use them in v0.9.9.9000 and figure out final 1.0 versions in prep for that release. This is internal and doesn't involve any significant redesign, so should be fine. Discuss next week?

**Comment by koheiw** [comment]
Ad-hoc implementation is not difficult at all. Happy to discuss next week.
