### ISSUE TITLE
Warning message thrown from tokens_compound if sequence is a single term

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#512]
Discovered from #506:

If `sequences` does not include whitespace, then although the correct behaviour results, a warning is thrown. We want to trap and stop the warning.

```r
> tokens_compound(tokens("This is a sentence."), "is")
tokens from 1 document.
Component 1 :
[1] "This"     "is"       "a"        "sentence" "."

Warning message:
In max(stringi::stri_length(unlist(regex, use.names = FALSE))) :
  no non-missing arguments to max; returning -Inf
```

Does not happen if at least one element of `sequences` has whitespace:

```r
> tokens_compound(tokens("This is a sentence."), c("is", "a sentence"))
tokens from 1 document.
Component 1 :
[1] "This"       "is"         "a_sentence" "."  
```

**Comment by koheiw** [comment]
I fixed this in #506. It will polity warn "No sequences is provided".

**Comment by kbenoit** [comment]
OK. I'd suggest just being silent and returning the original object - which is what should (and does) happen.

Same as e.g. `char_tolower("already lower case")`.

**Comment by koheiw** [comment]
Done in `issue-502`.
