### ISSUE TITLE
Stemming

### ISSUE THREAD

**Issue by RBonafide** [kbenoit/quanteda#514]
Hello! Thank you for a good project! Script works quickly and clear! Good job!
I have a question
Is it possible to use in code another stemmer from Yandex company?
https://tech.yandex.ru/mystem/

```r
> mystem <- function(txt) {
  library(stringr)
  stxt <- system('/path/mystem -nld -e utf-8 ', intern=T, input=txt)
  attributes(stxt) <- attributes(txt)
  stxt
}
`mystem(as.character(corpus))`
my_corpus <- as.list(corpus)
```

It combines all words in corpus into one vector from various texts. But in fact it must stem every  text file.

**Comment by koheiw** [comment]
How about using `tokens_lookup()`? The code would be something like this:
```
toks <- tokens(txt)
types <- attr(toks, 'types')
stems <- yourStemmer(types)
ls <- as.list(types)
names(ls) <- stems
tokens_lookup(toks, dictionary(ls))
```

**Comment by koheiw** [comment]
This uses quanteda's internal function, but should work:
```
toks <- tokens(txt)
types <- attr(toks, 'types')
attr(toks, 'types') <- yourStemmer(types)
toks <- quanteda:::tokens_hashed_recompile(toks)
```

**Comment by kbenoit** [comment]
The best would be to write a package providing an R wrapper around the Yandex stemmer, the same way that **SnowballC** works currently, and then we would be happy to include this an option.

There seemed to be only Russian-language documentation I could find at the link you provided.
