### ISSUE TITLE
mac binary CRAN build v0.9.9-24 version fails on OS X

### ISSUE THREAD

**Issue by tingleyd** [kbenoit/quanteda#519]
Hi,
I had been using .9.8.5 release for awhile. It corpus, you designated text field by textField. In the recent dev release, its text_field

But after I fix that, I can't figure out what this below error is coming from.

When I go back and install .9.8.5 everything works fine. I'm sorry I must be missing something. Thanks. dt

Listening on http://127.0.0.1:4257
Warning: Error in validObject: invalid class “dfmSparse” object: superclass "replValueSp" not defined in the environment of the object's class
Stack trace (innermost first):
    56: validObject
    55: .nextMethod
    54: callNextMethod
    53: initialize
    52: initialize
    51: new
    50: compile_dfm.tokens
    49: compile_dfm
    48: dfm.tokenizedTexts
    47: dfm
    46: dfm.character
    45: dfm
    44: dfm.corpus
    43: dfm
    42: server [redactedaddress/server.R#1305]
     1: runApp
Error in validObject(.Object) : 
  invalid class “dfmSparse” object: superclass "replValueSp" not defined in the environment of the object's class

**Comment by kbenoit** [comment]
Pls supply:
* the code causing the error, and the `ndoc()` for your corpus object.  
* sessionInfo()

Suggest you also try the GitHub version rather than CRAN, since that release has a bug affecting tokenisation >10,000 documents. (CRAN refresh expected within days though.)

**Comment by tingleyd** [comment]
dev version for the win. With apologies for not trying that first.

**Comment by kbenoit** [comment]
No problem. new CRAN up now, Windows binaries built, but still waiting for macOS build.

**Comment by conjugateprior** [comment]
CRAN version 99-2-4 also fails with this error.

```
data <- corpus(readtext("Data/*"))

> class(data)
[1] "corpus" "list"  

> ndoc(data)
[1] 10

mydfm <- dfm(data)
Error in validObject(.Object) : 
  invalid class “dfmSparse” object: superclass "replValueSp" not defined in the environment of the object's class

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X El Capitan 10.11.6

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readtext_0.2.9000 quanteda_0.9.9-24

loaded via a namespace (and not attached):
 [1] httr_1.2.1          R6_2.2.0            Matrix_1.2-7.1      tools_3.3.2        
 [5] fastmatch_1.1-0     Rcpp_0.12.9         stringi_1.1.2       grid_3.3.2         
 [9] data.table_1.10.0   RcppParallel_4.3.20 lattice_0.20-34     ca_0.64            
```

**Comment by kbenoit** [comment]
Hmm, odd one. Could you 

1.  Upload the 10 text files you are reading from `Data` so we can reproduce exactly and

2.  Try reading them in to a character vector using base methods and see if you get the same error? What happens if run `example(dfm)` on your antique platform? 😉

**Comment by conjugateprior** [comment]
It's not the documents:

```
> corp <- corpus(c("Mary had a little lamb", "and then she had some more"))
> summary(corp)
Corpus consisting of 2 documents.

  Text Types Tokens Sentences
 text1     5      5         1
 text2     6      6         1

Source:  /Users/wlowe/Documents/* on x86_64 by wlowe
Created: Thu Feb 16 15:36:50 2017
Notes:   

> dfm(corp)
Error in validObject(.Object) : 
  invalid class “dfmSparse” object: superclass "replValueSp" not defined in the environment of the object's class
```

**Comment by kbenoit** [comment]
OK, seems to be an incompatibility with something in El Capitan. Please try this, and see if you get the same output:
```r
toks1 <- tokens(c(one = "a b c d A B C D",
                  two = "A B C d"))
attr(toks1, "types") <- char_tolower(attr(toks1, "types"))
quanteda:::tokens_hashed_recompile(toks1, method = "R")
## tokens from 2 documents.
## one :
## [1] "a" "b" "c" "d" "a" "b" "c" "d"
##
## two :
## [1] "a" "b" "c" "d"

quanteda:::tokens_hashed_recompile(toks1, method = "C++")
## tokens from 2 documents.
## one :
## [1] "a" "b" "c" "d" "a" "b" "c" "d"
## 
## two :
## [1] "a" "b" "c" "d"
```

**Comment by kbenoit** [comment]
Would be interesting to see what happens if you try to run `R CMD CHECK --as-cran` on the source.

**Comment by kbenoit** [comment]
@conjugateprior If you have installed from GitHub (building from source) does this also happen?

**Comment by hugoquene** [comment]
Hi, Same problem for me:

Here's a minimal example lifted from the dfm-class {quanteda} help page:
_x <- dfm(tokens(c("this contains lots of stopwords",
                  "no if, and, or but about it: lots",
                  "and a third document is it"),
                removePunct = TRUE))_

Error in validObject(.Object) :
  invalid class “dfmSparse” object: superclass "replValueSp" not defined in the environment of the object's class

_sessionInfo()_
R version 3.3.1 (2016-06-21)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] datasets  utils     stats     graphics  grDevices methods   base

other attached packages:
 [1] readtext_0.2.9000     devtools_1.12.0       quanteda_0.9.9-24
 [4] plotrix_3.6-3         changepoint_2.2.2     zoo_1.7-14
 [7] koRpus.lang.nl_0.01-3 koRpus_0.07-2         hqmisc_0.1-1
[10] foreign_0.8-67        languageR_1.4.1       lme4_1.1-12
[13] Matrix_1.2-7.1        MASS_7.3-45

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7         ca_0.70             splines_3.3.1
 [4] lattice_0.20-34     R6_2.2.0            fastmatch_1.1-0
 [7] minqa_1.2.4         httr_1.2.1          tools_3.3.1
[10] grid_3.3.1          data.table_1.10.0   nlme_3.1-128
[13] git2r_0.18.0        withr_1.0.2         digest_0.6.10
[16] RcppParallel_4.3.20 nloptr_1.0.4        curl_2.3
[19] memoise_1.0.0       stringi_1.1.1

-- Hugo Quené

**Comment by kbenoit** [comment]
OK, having investigated this issue now, by installing OS X 10.11.6 in a virtual machine and run some tests, I can report that the binary **quanteda** build from CRAN will *not* work with that operating system version. 

**However** it will work if you install this way:

```r
install.packages("quanteda", type = "source")
```

For this to work, you will need to have Xcode tools installed, using this command from the Terminal:
```
xcode-select --install 
```

**Comment by amatsuo** [comment]
The solution Ken suggested worked with my even older version of OSX.
```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X Yosemite 10.10.5
```

**Comment by inesvidal** [comment]
Worked for me, thanks!! (IOS 10.11.6)

**Comment by hugoquene** [comment]
This worked for me too -- thanks a lot for the assistance!
BTW this only worked after I had (restarted the computer,) upgraded R to 3.3.2, started R in terminal window, and after I disabled my redefined .First and .Last functions (which messed up the install from source). Might be helpful for others to know. Thanks!

**Comment by conjugateprior** [comment]
CRAN version installed from source works.

fyi I got all the same tokenization results as you did above.  Didn't test an install from Github.

**Comment by rwilldred27** [comment]
I just started exploring quanteda package tonight. Had the same issue as @conjugateprior with the exact same OS X El Capitan 10.11.6 and R Studio version, by coincidence. Updated my system tools for El Capitan, restarted my Macbook, uninstalled the CRAN version of **quanteda**, and then downloaded the github version from the RStudio console. The **dfm()** function is no longer throwing that error. Really appreciate the help on this!!

**Comment by pglezen** [comment]
`install.packages('quanteda', type='source')` worked for me on macOS Sierra 10.12.3.  I had the same symptoms as originally reported with the plain (not source) install from CRAN.

**Comment by kbenoit** [comment]
@pglezen That's very interesting - I am using macOS Sierra 10.12.3 and the binary install from CRAN does work ok for me.

**Comment by pglezen** [comment]
Hmmm.  That is interesting.  First, I need to apologize for an omission in my report.  I reviewed my notes and I have the following entry for Monday, February 20 regarding **quanteda**:

> The install informed me that a more recent source version of `data.table` existed than the binary version.  I opted for compiling the newer source.  This seemed to work fine.

So while I hadn't explicitly requested a compile of the **quanteda** source, I did request compilation of the **data.table** source.  It's not clear to me if there is a relationship.  After the install last Monday, I observed the following upon loading the library.

```
> library(quanteda)
quanteda version 0.9.9.24
Using 7 of 8 cores for parallel computing

Attaching package: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

The following object is masked from ‘package:base’:

    sample
```
I didn't start working in earnest with `quanteda` until yesterday when I encountered the symptoms related above.  Perhaps if I had opted **not** to recompile the `data.table` source and thereby consistently use everything in the CRAN binary package, I might have avoided the problem.  When I followed the suggestion of recompiling everything from source, the libraries were once again consistent.

**Comment by sjankin** [comment]
The same issue with macOS Sierra 10.12.3, when installing binary build from CRAN. 

```
> corp <- corpus(c("Mary had a little lamb", "and then she had some more"))
> summary(corp)
Corpus consisting of 2 documents.

  Text Types Tokens Sentences
 text1     5      5         1
 text2     6      6         1

> dfm(corp)
Error in validObject(.Object) : 
  invalid class “dfmSparse” object: superclass "replValueSp" not defined in the environment of the object's class

> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS Sierra 10.12.3

locale:
[1] en_GB.UTF-8/en_GB.UTF-8/en_GB.UTF-8/C/en_GB.UTF-8/en_GB.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_0.9.9-24

loaded via a namespace (and not attached):
 [1] Matrix_1.2-7.1      tools_3.3.2         fastmatch_1.1-0     Rcpp_0.12.9         stringi_1.1.2       grid_3.3.2         
 [7] data.table_1.10.4   RcppParallel_4.3.20 lattice_0.20-34     ca_0.70 
```
Installation from source works fine.

**Comment by regiso** [comment]
_Hello - I am a Courseara Data Science capstone student and excited to dive into the quanteda package. I installed it using the Rstudio install packages drop down. Unfortunately I am running into some errors. Thanks for any advice you can send my way._ 

__I tried following the advice above - uninstalling then installing, and took a step backward._

_Here is how my journey started:__

```
test <- corpus(c("In the beginning was the Word"))
testdfm <- dfm(test)
```

Error in validObject(.Object) : 
  invalid class “dfmSparse” object: superclass "replValueSp" not defined in the environment of the object's class


`sessionInfo()`

R version 3.3.2 (2016-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tm_0.6-2          NLP_0.1-9         quanteda_0.9.9-24

loaded via a namespace (and not attached):
 [1] Matrix_1.2-7.1      parallel_3.3.2      tools_3.3.2        
 [4] fastmatch_1.1-0     Rcpp_0.12.7         slam_0.1-40        
 [7] stringi_1.1.2       grid_3.3.2          data.table_1.9.6   
[10] chron_2.3-47        RcppParallel_4.3.20 lattice_0.20-34    
[13] ca_0.70   



_So, I uninstalled and tried to reinstall within the R console (not from the RStudio install packages list) and  here's what happened:_



`install.packages("quanteda", type="source")`

Installing package into ‘C:/Users/analyticsrmo/Documents/R/win-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/quanteda_0.9.9-24.tar.gz'
Content type 'application/x-gzip' length 4644119 bytes (4.4 MB)
downloaded 4.4 MB

* installing *source* package 'quanteda' ...
** package 'quanteda' successfully unpacked and MD5 sums checked
** libs
Warning: running command 'make -f "Makevars.win" -f "C:/Users/ANALYT~1/DOCUME~1/R/R-33~1.2/etc/i386/Makeconf" -f "C:/Users/ANALYT~1/DOCUME~1/R/R-33~1.2/share/make/winshlib.mk" CXX='$(CXX1X) $(CXX1XSTD)' CXXFLAGS='$(CXX1XFLAGS)' CXXPICFLAGS='$(CXX1XPICFLAGS)' SHLIB_LDFLAGS='$(SHLIB_CXX1XLDFLAGS)' SHLIB_LD='$(SHLIB_CXX1XLD)' SHLIB="quanteda.dll" OBJECTS="RcppExports.o dist_mt.o fcm_mt.o sequences_mt.o tokens_compound_mt.o tokens_detect_mt.o tokens_lookup_mt.o tokens_match_mt.o tokens_ngrams_mt.o tokens_recompile_mt.o tokens_replace_mt.o tokens_select_mt.o utility.o wordfish.o"' had status 127
ERROR: compilation failed for package 'quanteda'
* removing 'C:/Users/analyticsrmo/Documents/R/win-library/3.3/quanteda'
Warning in install.packages :
  running command '"C:/Users/ANALYT~1/DOCUME~1/R/R-33~1.2/bin/i386/R" CMD INSTALL -l "C:\Users\analyticsrmo\Documents\R\win-library\3.3" C:\Users\ANALYT~1\AppData\Local\Temp\Rtmp82ho5a/downloaded_packages/quanteda_0.9.9-24.tar.gz' had status 1
Warning in install.packages :
  installation of package ‘quanteda’ had non-zero exit status

The downloaded source packages are in
	‘C:\Users\analyticsrmo\AppData\Local\Temp\Rtmp82ho5a\downloaded_packages’


` require(quanteda)
`

Loading required package: quanteda
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘quanteda’

**Comment by kbenoit** [comment]
Try installing the RTools first, as per the instructions [here](https://github.com/kbenoit/quanteda/blob/master/README.md), then your source install should work.

**Comment by regiso** [comment]
Thanks - will check it out and let you know how it works.

Regis O'Connor
President
716-816-8004

**Comment by regiso** [comment]
Ok - the good news - quanteda loaded, and so did readtext!
I was able to create the corpus and do summary.
However, still getting the same error for dfm

test <- corpus(c("In the beginning was the Word"))
testdfm <- dfm(test)

Error in validObject(.Object) :
  invalid class “dfmSparse” object: superclass "replValueSp" not defined in
the environment of the object's class

Regis O'Connor
President
716-816-8004

**Comment by kbenoit** [comment]
I just replicated this error on Windows 7. Then I reinstalled the **Matrix** package and it worked.  Try:
```r
install.packages("Matrix")
require(quanteda)
example(dfm)
```

**Comment by regiso** [comment]
Bingo! It works!
Thank you so much!

**Comment by empirical-bayesian** [comment]
Yes, Matrix does it, but y'need to do the order correctly, and might need to reinstall quanteda afterwards.

**Comment by kbenoit** [comment]
If anyone has an explanation as to what causes this, and/or how to prevent it for the next CRAN binary build, please do share!
