### ISSUE TITLE
invalid class “dgTMatrix” object: length(Dimnames[1]) differs from Dim[1]

### ISSUE THREAD

**Issue by jofrerocabert** [kbenoit/quanteda#520]
Dear Ken

I am using your version 0.9.9-3 and I am running into an error that did not appear with the same data and code using previous versions. I believe this issue has already been treated in [issue 168](https://github.com/kbenoit/quanteda/issues/168). As it is suggested there, I have updated all my packages including Matrix. 
The error I am getting now is:
```r
dfm_de <- dfm(corpus_de)
invalid class “dgTMatrix” object: length(Dimnames[1]) differs from Dim[1]
```

Is it possible that this is created by the new version? Thank you very much for your help. I am also leaving a testimonial to thank you for the package. 
Jofre

**Comment by kbenoit** [comment]
I think this is solved in the GitHub versions in which we fixed what was a bug that caused this behaviour when you have >10k documents. Is that the case with your `corpus_de`?

Suggest installing the GitHub version or waiting a few days for us to refresh the CRAN release.

**Comment by hugokoopmans** [comment]
ok I can confirm with this github version all works ok, even the 500k docs, and fast!

**Comment by kbenoit** [comment]
We've used it on 20 million+ documents and it is reasonably fast (5-10 mins to tokenize and construct the dfm).

**Comment by jofrerocabert** [comment]
Hello,

Thank you very much for your answers, they are really helpful. In my case
it seems like I would have to wait because I am working on a server in
which I have no access to install anything from outside R and to isntall
from GitHub I need R tools. Is there any other way? My corpus is of 280k
documents.

I would also like to ask you if you know whether Naive Baies un quanteda
works faster than in e1701, I do not know what I am doing wrong but for a
subsample of this data it takes hours.

Thanks again, greatly appreciated.

Jofre

**Comment by kbenoit** [comment]
It's on CRAN now, and the Windows and macOS binaries should build automatically within 24-48 hours.

As for Naive Bayes, please file a new issue once you have tried the newest version, and if you think there is a performance problem. The e1701 is not applicable to text, as it does not use a multinomial or Bernoulli distribution for the word counts. `textmodel_NB` matches the textual predictions from IIR (see `?textmodel_NB` as well as the worked example in the new edition (online only) of Jurafsky and Martin.

**Comment by jofrerocabert** [comment]
Thank you very much! I will look into this and let you know in a few days.
