### ISSUE TITLE
Implement target word-based collocation finder

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#521]
There are `fcm()` and `collocations()`, but they are all-by-all collocations analysis, which is inefficient with large corpus when users are interested in particular word. I need this function in my ongoing project, in which I analyze a 1GB corpus.

I tries to create this using existing functions, but R part appeared too slow to go through 138,108 full text news. One option is to add `window` argument to `qatd_cpp_tokens_detect`.

**Comment by koheiw** [comment]
If this does not fit to quanteda well, I can add this to my LSS package (there is one for tokenizedTexts obejct already).

**Comment by kbenoit** [comment]
Let's schedule a design meeting and discussion about collocations generally. I am eager to develop this part of the package in a coordinated and efficient fashion, and agree that the "all ngram" approach from collocations is inefficient for large texts (but it does work!).

**Comment by koheiw** [comment]
Here is my target word-based collocation finder created from `kwic`. Not superfast but works with a large corpus (600MB).
```r
text <- c('z a b c d c b a')
collocations_target(tokens(text), 'z', window = 1)

collocations_target <- function(x, keywords, window = 5, valuetype = c("glob", "regex", "fixed"), 
                                case_insensitive = TRUE, ..., new = TRUE) {
    
    valuetype <- match.arg(valuetype)
    keywords <- quanteda:::vector2list(keywords)
    
    # add document names if none
    if (is.null(names(x))) {
        names(x) <- paste("text", 1:length(x), sep="")
    }
    
    types <- attr(x, 'types')
    keywords_id <- quanteda:::regex2id(keywords, types, valuetype, case_insensitive, FALSE)
    
    target <- quanteda:::qatd_cpp_tokens_detect(x, keywords_id)
    
    ids <- which(sapply(target, sum, USE.NAMES = FALSE) > 0)
    
    spread <- target
    df_result <- data.frame()
    if (length(ids)) {
        for (id in ids) {
            spread[[id]] <- spread_mask(spread[[id]], window)
        }
    }
    index <- unlist(x, use.names = FALSE)
    mask <- as.integer(unlist(spread, use.names = FALSE) != 0 & 
                       unlist(target, use.names = FALSE) == 0)

    if (attr(x, 'padding')) {
        types <- c("", types)
        index <- index + 1
    }
    result <- Matrix::sparseMatrix(i = mask + 1,
                                   j = index,
                                   x = 1L,
                                   dimnames = list(class = c('F', 'T'), 
                                                   features = as.character(types)))
    
    mx <- new("dfmSparse", result)
    mx <- mx[,which(featnames(mx) == '') * -1] # drop padding
    return(mx)
    
}

spread_mask <- function(mask, window) {
    
    # Expand vector for matches at the top or end
    mask <- c(0, mask, 0)
    len <- length(mask)
    
    # Detect starting and ending positions of keywords
    start <- which(diff(c(0, mask)) == 1)
    end <- which(diff(c(mask, 0)) == -1)
    
    for (i in 1:length(start)) {
        mask[max(0, start[i] - window):min(len, end[i] + window)] <- 1
    }
    return(mask[c(-1, length(mask) * -1)])
}
```

**Comment by koheiw** [comment]
The parallel fcm looks fairly fast but not working with my 800MB tokens. 
```r
toks <- readRDS('data_tokens_asahi.RDS')
out <- fcm(toks, 'window')
object.size(toks) # 843907544 bytes
```
```
error: SpMat::init(): requested size is too large
 Show Traceback
 
 Rerun with Debug
 Error in qatd_cpp_fcm(x, nfeature(x), count, window, weights, ordered,  : 
  SpMat::init(): requested size is too large > object.size(toks)
```
I am only interested only one word "United States", nothing else! It would be good to add target word option with multi-word feature support (easy).

**Comment by kbenoit** [comment]
I think that’s called “kwic” !!

On 8 Feb 2017, at 22:17, Kohei Watanabe <notifications@github.com<mailto:notifications@github.com>> wrote:


The parallel fcm looks fairly fast but not working with my 800MB tokens.

toks <- readRDS('data_tokens_asahi.RDS')
out <- fcm(toks, 'window')
object.size(toks) # 843907544 bytes

error: SpMat::init(): requested size is too large
 Show Traceback

 Rerun with Debug
 Error in qatd_cpp_fcm(x, nfeature(x), count, window, weights, ordered,  :
  SpMat::init(): requested size is too large > object.size(toks)


I am only interested only one word "United States", nothing else! It would be good to add target word option with multi-word feature support (easy).

**Comment by koheiw** [comment]
I agree that it is close to kwic  (the underlying function of `collocation_target` is actually `tokens_detect`), but `kwic` object is not good because I will construct a collocation matrix, and put it into `dfm_keyness()`. This is what people has been doing in other tools (QDA Miner, WordSmith, Sketch Engine etc.) when they investigate how particular entities or concepts are represented in documents. I will use all-by-all collocation to fit vector space models, but more often target-by-all to obtain syntactical associates. Others users would agree with me.

**Comment by kbenoit** [comment]
If you just want a window-based collocation around a target word, why not use fcm on a kwic output? But maybe I didn't catch what it was you wanted exactly. Could you be more specific, showing the example of the outputs you want?

**Comment by koheiw** [comment]
`kwic` is inefficient because it returns characters. Here is an example of my collocation analysis:

```r

collocations_target <- function(x, keywords, window = 5, valuetype = c("glob", "regex", "fixed"), 
                                case_insensitive = TRUE, ..., new = TRUE) {
    
    valuetype <- match.arg(valuetype)
    keywords <- quanteda:::vector2list(keywords)
    
    # add document names if none
    if (is.null(names(x))) {
        names(x) <- paste("text", 1:length(x), sep="")
    }
    
    types <- attr(x, 'types')
    keywords_id <- quanteda:::regex2id(keywords, types, valuetype, case_insensitive, FALSE)
    
    target <- quanteda:::qatd_cpp_tokens_detect(x, keywords_id)
    
    ids <- which(sapply(target, sum, USE.NAMES = FALSE) > 0)
    
    spread <- target
    df_result <- data.frame()
    if (length(ids)) {
        for (id in ids) {
            spread[[id]] <- spread_mask(spread[[id]], window)
        }
    }
    index <- unlist(x, use.names = FALSE)
    mask <- as.integer(unlist(spread, use.names = FALSE) != 0 & 
                           unlist(target, use.names = FALSE) == 0)
    
    if (attr(x, 'padding')) {
        types <- c("", types)
        index <- index + 1L
    }
    result <- Matrix::sparseMatrix(i = mask + 1L,
                                   j = index,
                                   x = 1L,
                                   dimnames = list(class = c('F', 'T'), 
                                                   features = as.character(types)))
    mx <- new("dfmSparse", result)
    mx <- quanteda::dfm_remove(mx, '')
    return(mx)
    
}



spread_mask <- function(mask, window) {
    
    # Expand vector for matches at the top or end
    mask <- c(0, mask, 0)
    len <- length(mask)
    
    # Detect starting and ending positions of keywords
    start <- which(diff(c(0, mask)) == 1)
    end <- which(diff(c(mask, 0)) == -1)
    
    for (i in 1:length(start)) {
        mask[max(0, start[i] - window):min(len, end[i] + window)] <- 1
    }
    return(mask[c(-1, length(mask) * -1)])
}


toks <- tokens(data_corpus_inaugural)
mx_col <- collocations_target(toks, 'president*', window = 5)
head(textstat_keyness(mx_col, 'T'), 10)

```

**Comment by koheiw** [comment]
This function is very important for people in digital humanity and corpus linguistics, but I am not sure how to integrate into the package.

In corpus and computational linguistics, wrods that occure close to target-words are called "collocation" and sequences that `textstat_collocation()` finds are called "multiword unit":

http://wordhoard.northwestern.edu/userman/analysis-collocates.html
http://www.stefan-evert.de/SIGIL/sigil_R/
http://www.lexically.net/downloads/version5/HTML/index.html?collocation_basics.htm
http://www.collocates.info/

Following this convention, how about calling this `textstat_collocation()` and rename existing one  `textstat_multiword()`?

**Comment by kbenoit** [comment]
What we are identifying and scoring in `textstat_collocations()` is the same thing, although we do not provide for a "skip" of > 0 in considering adjacency. However `fcm()` does and this is one reason we could use `fcm()` for scoring bigram collocations. This raises interesting issues for the computation of the scores, however, since with skips the N for sequences is much greater.

We could add in a skip or window argument to `textstat_collocations()` but otherwise the only difference in the function you describe is the targeting of a particular phrase.

What would the input and output of the function you are proposing look like?

**Comment by koheiw** [comment]
Here is a working example:

```r
devtools::install_github('koheiw/Collocation')
require(quanteda)

toks <- tokens(data_corpus_inaugural, remove_punct = TRUE)
mx <- collocation::collocations(toks, target = 'econom*', negative_targets = c('college', 'university'))
col <- quanteda::textstat_keyness(mx)
head(col)
# chi2            p n_target n_reference
# expenditures  133.45487 0.000000e+00        8          16
# barriers       74.08670 0.000000e+00        3           2
# rigid          60.92237 5.884182e-15        3           3
# social         53.11732 3.141931e-13        6          24
# reduction      51.52394 7.073231e-13        3           4
# strongest      44.47918 2.570766e-11        3           5
# idealism       44.47918 2.570766e-11        3           5
# extravagance   39.00354 4.230373e-10        3           6
# public         34.38584 4.519998e-09       15         206
# recovery       31.04787 2.517430e-08        3           8
# world's        25.57504 4.255080e-07        4          20
# expenditure    25.55011 4.310406e-07        3          10
# defenses       25.50382 4.415081e-07        2           3
# drive          25.50382 4.415081e-07        2           3
# suffer         21.52712 3.488605e-06        3          12
# vigorous       20.77510 5.165015e-06        2           4
# possibilities  20.77510 5.165015e-06        2           4
# bounty         20.77510 5.165015e-06        2           4
# security       20.71122 5.340215e-06        6          56
# strict         19.89583 8.177853e-06        3          13
```
The function has familiar signature:
```
collocation::collocation(x, targets, negative_targets = NULL, min_count = 5, window = 10, valuetype = c("glob", "regex", "fixed"), case_insensitive = TRUE)
```
It counts words around `target` but not `negative_target` in tokens object given to x.  `negative_target` very is useful to exclude false positives. For example, c('college', 'university') will stop names of schools from being included.

**Comment by kbenoit** [comment]
I think I've now understood this feature request, which is based on grouping a corpus/tokens/dfm based on whether the tokens occurred within a user-defined window of a target pattern, or not.

The natural way to integrate this into the **quanteda** ecosystem seems to me the following:
* use `kwic()` as is, to return a kwic object. This includes the start and stop position of the tokens
* use a version of `tokens_group()` that takes as the groups argument the kwic, and then segment. the tokens by whether they are in the index of beginning and ending position +/- the window size. (This could include options as to whether to include the pattern match itself or not, and to make sure that the arguments applied to the tokens object or the tokens object itself, are identical to the ones on which the kwic was performed.)
* from that, create a dfm and use `textstat_keyness()` our whatever other tool is desired, to yield comparisons on the differences between the text that occurred within and without of the context.

**Comment by koheiw** [comment]
As @mpadge proposed, it would be good to put this function as `textsearch_collocation()`.

**Comment by kbenoit** [comment]
Migrated from 2nd half of #1011, following discussions.

Solution:
* Add `window` argument to `tokens_select()`.
* `window` argument will be default 0, and take one or two integers, for the pre and post pattern size of the window. If a scalar is supplied, these will be the same (for a symmetric window). If window is zero, pick up no context (default).
* no other behaviours will be affected, i.e. `padding`, `selection`, etc.
* this will not affect the definition of documents
* this will never increase the total number of tokens by double-counting, so that if windows overlap, the tokens in the overlapping window and only included once.

**Comment by koheiw** [comment]
Solve via #1014
