### ISSUE TITLE
Question: Using quanteda for co-occurence tests

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#524]
Hi,
this is not a bug report but rather a question on how you would use quanteda to solve a simple problem:

Let's say that I have a corpus and use a dictionary to divide it into two parts, e.g. "migration-related" and "not migration-related".

I then find the 10 most frequent  terms (other than those from the dictionary) in the "migration-related" part and would like to know if these terms are significantly (based on a proper test) more often contained within "migration-related" documents than in "not migration-related" documents.

What would be the best way to do this? Do you have a suggestion and maybe even a small example?

Thanks and Cheers
Carsten

**Comment by kbenoit** [comment]
In the newest version (now on CRAN) we added `textstat_keyness()`. You would need to partition the corpus first using `dfm(yourcorpus, groups = yourmigrationgroupingvariable)` first. 

We're very interested to hear how this works for you.

**Comment by methodds** [comment]
I'll check it out and report back to you, thanks =)

**Comment by methodds** [comment]
Okay I just tried the examples in the manual and it worked very well. I will test it on another corpus soon.

Two thoughts: 
- The ``exact`` test is rather slow. is it computational intensive? Also in this context, I assume the smoothing from the example is necessary so that there are no 0's for the fraction denominators ?
- Would you consider adding a parameter that would also return p-values, e.g. for the chi² tests? Personally I don't like them, but I guess they are still widely used in our discipline.

**Comment by kbenoit** [comment]
Yes the exact test is slow because literally it has to compute the exact combinatorics of the test once for each feature.

Easy to recover p-values for the Chi-squared test or CIs for the lr test. Will add these soon.

**Comment by kbenoit** [comment]
I've moved this to #495 and created a branch `issue-495` with these changes. 

You can try installing it with:

```r
devtools::install_github("kbenoit/quanteda", ref = "issue-495")
```

and let us know what you think.
