### ISSUE TITLE
Wishlist: Comparison and Keyness clouds

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#528]
Hi, 

I'd like to suggest adding additional word cloud shortcuts to Quanteda, comparison and keyness clouds.

Comparison clouds would simply use the function ``worccloud::comparison.cloud()``, e.g. on a grouped dtm like this:

```
library(quanteda)

period <- ifelse(docvars(data_corpus_inaugural, "Year") < 1945, "pre-war", "post-war")
mydfm <- dfm(data_corpus_inaugural, groups = period,
             remove=stopwords('english'),
             removePunct=T)

grouped_df <- t(as.data.frame(mydfm)) # comparison clouds expects words as rows

comparison.cloud(grouped_df,max.words=80, title.size=2, colors=c('red', 'blue'))
```
![comparisoncloud](https://cloud.githubusercontent.com/assets/7460499/22404139/0490100c-e62b-11e6-94d5-7cd866302cde.png)

As for the keyness clouds, I guess its not too difficult to implement it if one is just interested in finding the words with the largest keyness:

```
library(dplyr)
keyness <- textstat_keyness(mydfm)  %>% rownames_to_column('terms')  %>% filter(chi2 > 0)
wordcloud(keyness$terms, keyness$chi2, max.words=80)

```

![keyness_cloud](https://cloud.githubusercontent.com/assets/7460499/22404196/49f2fb0e-e62c-11e6-9f82-c1887c4ec48f.png)

Of course the scaling in the cloud is usually based upon frequencies and not chi2 or other statistics, so this is a bit questionable,  but I think it's still an interesting figure.

Where I'm struggling at the moment is another option for a keyness cloud, where one would, similar to above, plot the words for both groups in contrast. For ```measure= 'chi2'``` this could for instance be the most positive terms at the top and the most negative terms at the bottom. However, I did not yet find a proper way to do this with ``comparison.cloud``, maybe you'd have an idea for that.

So if all of this would be implemented, one could simply call a function on a grouped dfm with a parameter ``type=c('comparison', 'keyness', 'keyness_grouped')``.

**Comment by kbenoit** [comment]
Implemented in `textplot_keyness()` and also with `textplot_wordcloud(x, comparison = TRUE)`.
