### ISSUE TITLE
CRAN build for v0.9.9-17 not working on all platforms

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#530]
See https://cran.r-project.org/web/checks/check_results_quanteda.html.

We're having some problems with the recent CRAN build. Some of these (Solaris etc) seem to be related to errors in C++. One of the devel errors is from compressed corpus objects. @koheiw I'll fix the second, can you fix the first?

**Comment by kbenoit** [comment]
@HaiyanLW @koheiw are we good on this front? I could resubmit to CRAN if so, but also if we have some pending improvements underway, happy to wait for these to be completed first.

**Comment by koheiw** [comment]
I think we addressed all the C++ issues. I am only working on the overlap things, which requires more time.
