### ISSUE TITLE
Passing docvars to tokens would increase usability

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#534]
When I am working with large large tokens object, I drop original corpus from the working environment to free memory, but it becomes a problem when I need docvars in the downstream. Why not adding an option to pass docvars to the tokenizer like `tokens(x, docvar = TRUE)`?

**Comment by kbenoit** [comment]
As in #508? 😄

**Comment by koheiw** [comment]
You were a bit quicker :1st_place_medal:
