### ISSUE TITLE
Installation fails on R 3.2.5 x86_64-pc-linux-gnu 

### ISSUE THREAD

**Issue by jkraut** [kbenoit/quanteda#537]
I tried to install the latest version of quanteda (0.9.9) on my Ubuntu system, but installation failed. The error messages reported were as follows:

I am able to successfully install quanteda_0.9.9-3.

```tokens_ngrams_mt.cpp: In function ‘Rcpp::List qatd_cpp_tokens_ngrams(Rcpp::List, Rcpp::CharacterVector, Rcpp::String, Rcpp::IntegerVector, Rcpp::IntegerVector)’:
tokens_ngrams_mt.cpp:203:24: error: conversion from ‘int’ to non-scalar type ‘ngrams::IdNgram {aka tbb::atomic<unsigned int>}’ requested
make: *** [tokens_ngrams_mt.o] Error 1
ERROR: compilation failed for package ‘quanteda’
* removing ‘/home/pilgor/R/x86_64-pc-linux-gnu-library/3.2/quanteda’
Error: Command failed (1)
```

I tried updating Rcpp + RcppArmadillo, but neither of those seemed to work.

My R.version is as follows:
```platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu           
status                                     
major          3                           
minor          2.5                         
year           2016                        
month          04                          
day            14                          
svn rev        70478                       
language       R                           
version.string R version 3.2.5 (2016-04-14)
nickname       Very, Very Secure Dishes
```
sessionInfo() gives:
```R version 3.2.5 (2016-04-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu precise (12.04.5 LTS)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.1.0      R6_2.2.0        tools_3.2.5     withr_1.0.1     curl_0.9.7     
 [6] memoise_1.0.0   knitr_1.12.3    git2r_0.14.0    digest_0.6.12   devtools_1.11.1
```

**Comment by kbenoit** [comment]
This could be due to our using newer functionality in the latest **quanteda** code. @koheiw is this because TBB or some other functionality requires R >= 3.3.0? We should figure out which version is needed and update the R version requirements in `DESCRIPTION`.

@jkraut Can you try this on a newer version of R?

**Comment by koheiw** [comment]
This is because of the old compiler. Please run `gcc --version` in the console. The compiler has to be newer than 4.8.1. quanteda 0.9.9-19 can be installed in old systems, but parallel computation will be disabled on these systems.

**Comment by kbenoit** [comment]
Time to upgrade from Ubuntu 12...  But please do try the latest GitHub build since we tried to use compiler directives that would use the serial versions of some functions if the required TBB libraries are not present.

**Comment by jkraut** [comment]
Thanks for taking care of this so quickly.

Sucsesfully updated to `quanteda version 0.9.9.21` after upgrading to `gcc version 4.9.4`.

Turns out I had version `4.6.3`.  It'll be a slower process to upgrade Ubuntu versions as there are lots of other dependencies to worry about, but this fix works for now.  Appreciate all the work on quanteda and how quickly you and your team reply to issues.
