### ISSUE TITLE
How to normalize word frequency in dfm?

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#539]
Does `dfm` have a function equivalent to this? Its easy to do, but mx loses dfm class after the normalization.
```r
mx <- quanteda::dfm(some_text)
mx <- scale(mx, center = TRUE, scale = TRUE)
```

**Comment by kbenoit** [comment]
None at the moment. This is probably best added as an option to `dfm_weight()`. The trick is to do it without making it dense along the way, although the scaling will result in a much higher density or even 100% density. Try this:

```r
#' @examples 
#' head(scaleddfm <- dfm_scale(data_dfm_LBGexample))
#' is.dfm(scaleddfm)
dfm_scale <- function(x) {
    new("dfmSparse", as((t(apply(x, 1, function(x) (x - mean(x)) / sd(x)))), "dgCMatrix"))
}
```

`scale()` is an example of a badly written function, as the `center` and `scale` arguments are Boolean as defaults, but also take numeric vectors. And the return object is even more (unnecessarily) complicated.
