### ISSUE TITLE
ignoredFeature

### ISSUE THREAD

**Issue by angeloklin** [kbenoit/quanteda#54]
Is the code `quanteda/R/dfm-main.R` in use?  
If so, the line `370` shouldn't be (note the "-" instead of "!" in front of ignoredfeatIndex):
```
if (length(ignoredfeatIndex) > 0) alltokens <- alltokens[-ignoredfeatIndex]
```
instead of:
```
if (length(ignoredfeatIndex) > 0) alltokens <- alltokens[!ignoredfeatIndex]
```

PS: This might be related with another issue in the list about the stopWords not working.

**Comment by kbenoit** [comment]
Wasn't the problem, but there was another bug in removeFeatures() (which dfm() calls to remove stopwords) that is now fixed in 0.8.3-2.
