### ISSUE TITLE
Improve regex2id performance

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#542]
`regex2id()` (in `regex2fixed.R` is an important part of the new matching strategies for "valuetype" matches, but it is not yet optimised for performance. After benchmarking, we should identify performance bottlenecks and see how this could be improved.

Process: 
- [ ] @kbenoit to get familiar with the code and issues, since @koheiw wrote almost of the existing code since `regex2id` replaced earlier functions.
- [ ] @kbenoit and @koheiw to discuss a plan of attack once the issues are identified 
- [ ] reimplement selected elements for improved performance

**Comment by koheiw** [comment]
There are two options:

1) Link to stringi from C++
https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Linking-to-native-routines-in-other-packages

2) Pass R fcunctions to C++
```c

#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::export]]
NumericVector callFunction(CharacterVector x, Function f) {
    NumericVector res = f(x);
    return res;
}

// [[Rcpp::export]]
CharacterVector callFunction2(CharacterVector x, CharacterVector y, Function f) {
    CharacterVector res = f(x, y);
    return res;
}

```
They are called from R
```r
callFunction(letters, stringi::stri_width)
callFunction2(letters, "[a-h]", stringi::stri_subset_regex)
```

**Comment by koheiw** [comment]
I learned that all the `stringi` functions are (officially) accessible in C++. This looks promising.
https://github.com/gagolews/ExampleRcppStringi/blob/master/src/test.cpp

**Comment by kbenoit** [comment]
That’s excellent - then we can move quanteda to 100% stringi and remove all remaining base R string handling calls, and it will be consistent in both R and C++.


On 9 Feb 2017, at 07:13, Kohei Watanabe <notifications@github.com<mailto:notifications@github.com>> wrote:


I learned that all the stringi functions are (officially) accessible in C++. This looks promising.
https://github.com/gagolews/ExampleRcppStringi/blob/master/src/test.cpp

**Comment by koheiw** [comment]
`regex2id` is not a bottle neck in most of the use cases, so better not changing before v1.0.
