### ISSUE TITLE
Confusing error message from textfile()

### ISSUE THREAD

**Issue by kmunger** [kbenoit/quanteda#552]
When trying to use the (now deprecated) "readtext" function, I get this message:

Error: 'textfile' is defunct.
Use 'textfile' instead.

I now understand that this refers to a different package, but it's very confusing as written!

**Comment by kbenoit** [comment]
Please include `packageVersion()` and the code + output.

**Comment by kmunger** [comment]
> packageVersion("quanteda")
[1] ‘0.9.9.13’

##code
proc.df<-textfile(proc_files, docvarnames = df$years)

##output
Error: 'textfile' is defunct.
Use 'textfile' instead.
