### ISSUE TITLE
dfm error with special characters

### ISSUE THREAD

**Issue by jhfowler** [kbenoit/quanteda#554]
i am trying to turn a list of tweets into a dfm and it occasionally creates an error on special characters.  here's an example:

> library(quanteda)
> x <- dfm(corpus("あﾞづいﾞ"))
Error in Matrix::sparseMatrix(i = index, p = cumsum(c(1, lengths(x))) -  : 
  NA's in (i,j) are not allowed

**Comment by jhfowler** [comment]
On further inspection, it seems like the error is always caused by Hiragana.  Strings that fail: "づいﾞ",
"゛んﾞ","# たーﾟ"

**Comment by kbenoit** [comment]
OK, definitely one for @koheiw. It's an issue with the hashing function:
```r
> tokens(c("づいﾞ", "゛んﾞ", "たーﾟ"))
tokens from 3 documents.
Component 1 :
[1] "づ"  NA    "いﾞ"

Component 2 :
[1] "゛"  NA    "んﾞ"

Component 3 :
[1] "た"  NA    "ーﾟ"

> tokens(c("づいﾞ", "゛んﾞ", "たーﾟ"), hash = FALSE)
tokenizedTexts from 3 documents.
Component 1 :
[1] "づ"  ""    "いﾞ"

Component 2 :
[1] "゛"  ""    "んﾞ"

Component 3 :
[1] "た"  ""    "ーﾟ"
```

**Comment by jhfowler** [comment]
Thanks!  BTW I am really loving the package.   This is the first snag I've hit.
j

**Comment by kbenoit** [comment]
Thanks Jim!

Testimonials always welcome at https://github.com/kbenoit/quanteda/issues/461.

Ken


On 16 Feb 2017, at 23:42, jhfowler <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks! BTW I am really loving the package. This is the first snag I've hit.
j
