### ISSUE TITLE
Installation fails: "Error loading TBB: std::bad_alloc"

### ISSUE THREAD

**Issue by vincentarelbundock** [kbenoit/quanteda#556]
Thanks a lot for your work on quanteda. I love it!

I'm trying to install the package from CRAN or from Github (using devtools' `install_github`) on a couple of linux (virtual) machines, but installation fails with the following error message:

```
** testing if installed package can be loaded
Error : .onAttach failed in attachNamespace() for 'quanteda', details:
  call: RcppParallel::setThreadOptions(threads - 1)
  error: Error loading TBB: std::bad_alloc
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/lib/R/library/quanteda’
Error: Command failed (1)
```

This is on an Archlinux Linode, but I get the same error when trying to install on Ubuntu 16.10 or 16.04.

I loaded each of the dependencies individually, and they all seem to be installed and to work.

More information: 

```
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Arch Linux

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] RcppArmadillo_0.7.700.0.0 yaml_2.1.14              
 [3] ggplot2_2.2.1             fastmatch_1.1-0          
 [5] stringi_1.1.2             ca_0.70                  
 [7] RcppParallel_4.3.20       Rcpp_0.12.9              
 [9] proxy_0.4-17              wordcloud_2.5            
[11] RColorBrewer_1.1-2        SnowballC_0.5.1          
[13] data.table_1.10.4         Matrix_1.2-7.1           
[15] devtools_1.12.0           pacman_0.4.1             

loaded via a namespace (and not attached):
 [1] munsell_0.4.3    colorspace_1.3-2 lattice_0.20-34  R6_2.2.0        
 [5] plyr_1.8.4       httr_1.2.1       tools_3.3.2      grid_3.3.2      
 [9] gtable_0.2.0     git2r_0.18.0     withr_1.0.2      assertthat_0.1  
[13] lazyeval_0.2.0   digest_0.6.12    tibble_1.2       curl_2.3        
[17] memoise_1.0.0    slam_0.1-40      scales_0.4.1    
```

Thoughts?

**Comment by vincentarelbundock** [comment]
Follow-up: I just successfully install 0.9.9-17 on the same machine, so breakage happened between then and master...

**Comment by kbenoit** [comment]
Thanks @vincentarelbundock, @koheiw and I will investigate asap.

**Comment by koheiw** [comment]
@vincentarelbundock, can you tell me how many CPU cores does you machine have?

**Comment by vincentarelbundock** [comment]
I think this was one of the cheap 1 core linode machines, but I already killed so I can't be 100% sure. Sorry!

**Comment by koheiw** [comment]
If it was on a 1 core Linode server, I am sure that the number of thread was set to zero. Thank you for reporting this. I will fix this.

**Comment by Ninoninoninonino** [comment]
I received a similar error on a virtual linux machine with Quanteda 0.9.9-24. Is there anything that I can do to avoid it until the fix is going to be implemented in the next Quanteda version?

**Comment by vincentarelbundock** [comment]
Install from github? 

```
library(devtools)
install_github('kbenoit/quanteda')
```

**Comment by Ninoninoninonino** [comment]
Thanks,  when doing `install_github('kbenoit/quanteda')` on a server I get
```
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Operation was aborted by an application callback
```

**Comment by vincentarelbundock** [comment]
Do you have curl and Rcurl installed?

**Comment by Ninoninoninonino** [comment]
Curl and Rcurl are both installed.

**Comment by vincentarelbundock** [comment]
I don't know. In any case, that's a problem with ``devtools`` or your local machine. I recommend you wait for the next CRAN release or research a solution to your devtools issue.

**Comment by RuqinRen** [comment]
I had the same error message, which brought me to this page.

Installing from github directly solved the problem, but still I am getting this warning message. It seems the problems from direct installation is with the parallel core.

> Reloading installed quanteda
quanteda version 0.9.9.44
Disabling parallel computing

Attaching package: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

Warning messages:
1: replacing previous import by ‘data.table::data.table’ when loading ‘quanteda’ 
2: replacing previous import by ‘data.table::setnames’ when loading ‘quanteda’ 
3: replacing previous import by ‘stringi::stri_trans_tolower’ when loading ‘quanteda’ 
4: replacing previous import by ‘stringi::stri_trans_toupper’ when loading ‘quanteda’

**Comment by kbenoit** [comment]
We should be doing a CRAN refresh soon, hopefully this will solve the problem.
