### ISSUE TITLE
kwic() repeats first keyword when it's first word in document

### ISSUE THREAD

**Issue by pablobarbera** [kbenoit/quanteda#57]
For example:
```r
kwic(inaugTexts, "fellow citizens", window=5)[3,]
#                                contextPre         keyword                        contextPost
#     [1793-Washington, 1:2]         Fellow Fellow citizens , I am again called               
```

**Comment by kbenoit** [comment]
It's even worse than that:

    > kwic(c("Fellow citizens of the world, unite", "I talk frequently to my fellow citizens"), "fellow citizens")
                 contextPre         keyword         contextPost
    [text1, 1:2]     Fellow Fellow citizens of the world, unite

**Comment by kbenoit** [comment]
Fixed.
