### ISSUE TITLE
convert(dfm , to="stm") not working properly with ignoredFeatures from dfm command

### ISSUE THREAD

**Issue by zgreene** [kbenoit/quanteda#570]
I find that when I run the convert command on a dfm created using dfm() that the command does not carry over the ignored terms from the original dfm. 

For example, in the example code below, the words "krant", "zegt", "nederland" and many of the other specifically excluded words show up in the output from the stm command. 

NL.dfm<- dfm(NLcorpus,  removeNumbers=TRUE, toLower=TRUE,
                   removePunct=TRUE, removeSeparators=TRUE, language="dutch", stem=TRUE
        , ignoredFeatures= c( stopwords("dutch"), "woord", "dutch",
                              "zegt", "nederland", "krant", "we", "partij",
                              "vvd", "cda", "sp", "cu", "groenlinks", "pvda", "pvdd", "jar"),                  removeTwitter=TRUE)

stm.NL<-convert(NL.dfm, to="stm", docvars=docvars(NLcorpus))

results<- stm(stm.NL$documents,  stm.NL$vocab,  K=12)

**Comment by kbenoit** [comment]
See `?dfm` - we replaced the argument `ignoredFeatures` some time ago with `remove`. That's what the output means: :smile:
```r
> dfm(data_char_inaugural, ignoredFeatures = stopwords())
Document-feature matrix of: 58 documents, 9,232 features (91.6% sparse).
Warning message:
In tokens.character(x, ...) : Argument ignoredFeatures not used.
```
