### ISSUE TITLE
Instllation fails on Ubuntu 16.04 when compiling dist_mt.cpp

### ISSUE THREAD

**Issue by toxicafunk** [kbenoit/quanteda#572]
* installing *source* package ‘quanteda’ ...
** package ‘quanteda’ successfully unpacked and MD5 sums checked
** libs
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I.  -I"/home/toxicafunk/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/toxicafunk/R/x86_64-pc-linux-gnu-library/3.2/RcppParallel/include" -I"/home/toxicafunk/R/x86_64-pc-linux-gnu-library/3.2/RcppArmadillo/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG -I.  -I"/home/toxicafunk/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include" -I"/home/toxicafunk/R/x86_64-pc-linux-gnu-library/3.2/RcppParallel/include" -I"/home/toxicafunk/R/x86_64-pc-linux-gnu-library/3.2/RcppArmadillo/include"   -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c dist_mt.cpp -o dist_mt.o
dist_mt.cpp: In member function ‘virtual void CanberraDistance::operator()(std::size_t, std::size_t)’:
dist_mt.cpp:226:20: error: ‘arma::colvec {aka class arma::Col<double>}’ has no member named ‘replace’
                 bb.replace(arma::datum::nan, 0);
                    ^
dist_mt.cpp: In member function ‘virtual void CanberraDistance2::operator()(std::size_t, std::size_t)’:
dist_mt.cpp:255:20: error: ‘arma::colvec {aka class arma::Col<double>}’ has no member named ‘replace’
                 bb.replace(arma::datum::nan, 0);
                    ^
/usr/lib/R/etc/Makeconf:143: recipe for target 'dist_mt.o' failed
make: *** [dist_mt.o] Error 1
ERROR: compilation failed for package ‘quanteda’
* removing ‘/home/toxicafunk/R/x86_64-pc-linux-gnu-library/3.2/quanteda’
* restoring previous ‘/home/toxicafunk/R/x86_64-pc-linux-gnu-library/3.2/quanteda’

**Comment by HaiyanLW** [comment]
You may need to update your RcppArmadillo package. Function .replace() is added in RcppArmadillo version of  0.7.400.2.0 (2016-08-24).

**Comment by kbenoit** [comment]
@HaiyanLW If we rely on that version of RcppArmadillo, then let's update the version requirement in `DESCRIPTION` under `Imports:`.

**Comment by HaiyanLW** [comment]
Will do a PR

**Comment by toxicafunk** [comment]
Thanks @HaiyanLW , updating RcppArmadillo did the trick!
