### ISSUE TITLE
dfm fails if the last document has zero tokens

### ISSUE THREAD

**Issue by guyjacobson** [kbenoit/quanteda#58]
Here's a minimal example:

    library(quanteda)
    x <- dfm(c("hello there","how are you?","I'm fine","????"))

Running this produces this error:

    Creating a dfm from a character vector ...
       ... lowercasing
       ... tokenizing
       ... indexing documents: 4 documents
       ... indexing features: 7 feature types
    Error in validObject(r) : 
      invalid class “dgTMatrix” object: length(Dimnames[1]) differs from Dim[1] which is 3

This is using the latest version of quanteda.

**Comment by kbenoit** [comment]
Solved already, see issue #36. Your example works on the latest (GitHub) build. 

But thanks for the bug report - keep 'em coming.

**Comment by guyjacobson** [comment]
Kenneth,

Thanks for the speedy reply! Didn't know that this was exactly the same as
issue #36.

--Guy
