### ISSUE TITLE
create a cheatsheet

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#581]
This would be a 2-page "cheatsheet" using the format at https://www.rstudio.com/resources/cheatsheets/.

Editing the draft can be done directly at https://www.dropbox.com/s/ipa873yak4v55ci/Cheatsheet%20template%20notes.docx?dl=0.

**Comment by stefan-mueller** [comment]
I have created a first draft of a **quanteda** cheatsheet. Please have a look at the [PDF file](https://github.com/stefan-mueller/quanteda-cheatsheet/blob/master/cheatsheet-quanteda.pdf) which is in stored in this repo: https://github.com/stefan-mueller/quanteda-cheatsheet.

As the **RStudio** cheatsheets are created with PowerPoint, it is difficult/impossible to collaborate on this cheatsheet on GitHub. You might make notes in the [pdf](https://github.com/stefan-mueller/quanteda-cheatsheet/blob/master/cheatsheet-quanteda.pdf) or [pptx](https://github.com/stefan-mueller/quanteda-cheatsheet/blob/master/cheatsheet-quanteda.pptx) files, upload them/send them to me via email, and I update the files based on your feedback. 

I tried to keep it to one page. I could not include any `tokens_` commands, but focus on `corpus_`, `dfm_`, `fcm_`, `textstat_`, `textmodel_` and `textplot_`. If you think `tokens_` should be added, we might restructure the sheet. If space allowed, I used worked examples for each function.

 I'm looking forward to your thoughts and comments.

**Comment by stefan-mueller** [comment]
@kbenoit, based on your amendments in the documentation, I made some changes in the cheatsheet (in particular I updated the `dfm_` and `fcm_` boxes and tried to remove all occurrences of camelCase). I plan to link each function in the sheet to the respective man page on www.quanteda.io, but I'd do this when we have decided what to add/cut.

**Comment by kbenoit** [comment]
Excellent. We should be more or less done with the API changes by end of next week. We are trying to figure out, mainly:

- the difference between `corpus_segment` and `corpus_reshape`, and
- whether `corpus_trim` needs to be renamed (since the only other `_trim` function, `dfm_trim`, operates on features only, whereas `corpus_trim` can change the documents.

**Comment by stefan-mueller** [comment]
Ok, perfect. I wait until you have completed the API changes, and then present you an updated version. Afterwards,  we can send the sheet to the RStudio team for review. They agreed to provide a link to the the quanteda cheat sheet on their website (http://www.rstudio.com/resources/cheatsheets/) and I think we should take this opportunity.

**Comment by kbenoit** [comment]
@stefan-mueller I created a `/vignettes/cheatsheet/` folder, what do you think of moving the cheatsheet materials from Dropbox to there?

**Comment by stefan-mueller** [comment]
Yes, feel free to move the two files (pptx and pdf) from the Dropbox to the folder.

**Comment by kbenoit** [comment]
Wouldn't we want also to move the .Rmd files that create the plots, etc. (in other words, everything?)

**Comment by stefan-mueller** [comment]
Yes, that's alright! I just tidied up the R script, it's now ready for upload. Feel free to move it from the Dropbox.
