### ISSUE TITLE
Incompatibility with TextReuse

### ISSUE THREAD

**Issue by Ninoninoninonino** [kbenoit/quanteda#585]
When `library(textreuse)`, `library(tm) `and
`library(quanteda)` are loaded, I get the following error: 

```
> tokenised <- tokenize(texts)
Error in UseMethod("tokenize", x) : 
  no applicable method for 'tokenize' applied to an object of class "character"
```
Without `library(textreuse)` it works ..

I guess this is also an issue for the author of TextReuse ..

**Comment by kbenoit** [comment]
It's impossible to tell without knowing what sort of object `texts` is. But **quanteda**'s tokeniser is now called `tokens()`, not `tokenize()` (although that still works, it's deprecated).

Remember you can always guarantee the function you are calling by prefixing the function name with the package, e.g.
```r
quanteda::tokenize(texts)
```
(but use `tokens()` instead!)
