### ISSUE TITLE
Cosine similarity for large dfms

### ISSUE THREAD

**Issue by FinScience** [kbenoit/quanteda#594]
Hi,

I have a dfm that has 191431 docs and 815367 features. My requirement is to create a dataframe that will store the cosine distance measure of each word with all other words. I tried the following code, which works for smaller dfms but is failing for my specific case. Any workaround for this would be great. I am new to parallel processing in R as well. Hence I am unable to figure out a smart approach to this.

         y <- similarity(mydfm, margin="features", method = "cosine")
         
         Error in asMethod(object) : 
         Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

**Comment by kbenoit** [comment]
Try this with the latest version:
```r
textstat_simil(mydfm, margin="features", method = "cosine")
```
and it should work as the matrix stays sparse.

**Comment by kbenoit** [comment]
Also note that it returns a `dist` class object, just as `stats::dist()` produces, which is less than half the size of the equivalent data.frame.

**Comment by FinScience** [comment]
@kbenoit - Thanks a ton for the super fast response. I shall try this out. Is it possible to change the dist class to dataframe, as this needs to be stored for further reference.

**Comment by kbenoit** [comment]
```r
> presDfm <- dfm(corpus_subset(inaugCorpus, Year > 1980), 
+                remove = stopwords("english"), stem = TRUE)
> tmp <- textstat_simil(presDfm, margin = "documents", method = "cosine")
> as.data.frame(as.matrix(tmp))
             1981-Reagan 1985-Reagan 1989-Bush 1993-Clinton 1997-Clinton 2001-Bush 2005-Bush 2009-Obama 2013-Obama 2017-Trump
1981-Reagan    1.0000000   0.9691584 0.9606863    0.9401555    0.9399138 0.9508808 0.9359961  0.9399460  0.9397146  0.9304059
1985-Reagan    0.9691584   1.0000000 0.9545683    0.9460518    0.9481989 0.9384177 0.9314487  0.9436339  0.9422001  0.9166806
1989-Bush      0.9606863   0.9545683 1.0000000    0.9369276    0.9392663 0.9552474 0.9360356  0.9416945  0.9376157  0.9324248
1993-Clinton   0.9401555   0.9460518 0.9369276    1.0000000    0.9252803 0.9271724 0.9154801  0.9015783  0.9125611  0.8963897
1997-Clinton   0.9399138   0.9481989 0.9392663    0.9252803    1.0000000 0.9334965 0.9102329  0.9399306  0.9403480  0.9227011
2001-Bush      0.9508808   0.9384177 0.9552474    0.9271724    0.9334965 1.0000000 0.9447611  0.9255036  0.9371368  0.9364654
2005-Bush      0.9359961   0.9314487 0.9360356    0.9154801    0.9102329 0.9447611 1.0000000  0.9004034  0.9217499  0.9213632
2009-Obama     0.9399460   0.9436339 0.9416945    0.9015783    0.9399306 0.9255036 0.9004034  1.0000000  0.9473229  0.9137103
2013-Obama     0.9397146   0.9422001 0.9376157    0.9125611    0.9403480 0.9371368 0.9217499  0.9473229  1.0000000  0.9177145
2017-Trump     0.9304059   0.9166806 0.9324248    0.8963897    0.9227011 0.9364654 0.9213632  0.9137103  0.9177145  1.0000000
```

**Comment by FinScience** [comment]
Hi,

I am still getting the same size error.

       y <- textstat_simil(mydfm, margin="features", method = "cosine")
      Error in asMethod(object) : 
      Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

**Comment by kbenoit** [comment]
`sessionInfo()` please

**Comment by FinScience** [comment]
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_0.9.9-24

loaded via a namespace (and not attached):
 [1] Matrix_1.2-8        tools_3.3.2         fastmatch_1.0-4     Rcpp_0.12.9         stringi_1.1.2      
 [6] grid_3.3.2          data.table_1.10.4   RcppParallel_4.3.20 lattice_0.20-34     ca_0.70

**Comment by kbenoit** [comment]
How much RAM, and what's does `print(mydfm)` indicate?

**Comment by FinScience** [comment]
> print(mydfm)
Document-feature matrix of: 191,431 documents, 815,367 features (100% sparse).
> object.size(mydfm)
194573832 bytes

**Comment by kbenoit** [comment]
Interesting... it looks like you have a completely sparse dfm, but it's 194MB in size! What does `head(mydfm)` show? How much system RAM in your machine?

**Comment by FinScience** [comment]
features
docs    logiccoverage conditionalstatements errorhandling calculations purpose perform
  text1             1                     1             1            1       1       1
  text2             0                     0             0            0       0       0
  text3             0                     0             0            0       0       0
  text4             0                     0             0            0       0       0
  text5             0                     0             0            0       0       0
  text6             0                     0             0            0       1       0


RAM is 8 GB

**Comment by kbenoit** [comment]
I think you are going to have trouble with that matrix no matter what. 815k features where over 99% of your cells are zero is not going to be meaningful anyway. Suggest you trim some features before trying to compute a similarity.

And get some more RAM! 😉

**Comment by FinScience** [comment]
Yep...that is the ideal solution..Thanks for helping out...:)

**Comment by FinScience** [comment]
Opps...Sorry to bother again. I tried the stuff on a different machine with 128 GB RAM. And still the same error.

      Error in asMethod(object) : 
       Cholmod error 'problem too large' at file ../Core/cholmod_dense.c, line 105

![image](https://cloud.githubusercontent.com/assets/11004504/23874547/12765426-085c-11e7-9138-6189698a33f6.png)

Any insights would be great

**Comment by kbenoit** [comment]
The problem here is not just RAM. 

* I think there are limits in the matrix function code (implemented by R in C,  hence the `Cholmod error 'problem too large' at file ../Core/cholmod_dense.c` message) and with `margin = "features"` you are trying to produce a matrix that is 815367^2 = 6.6e+11. That's just too big. The solution is feature selection to pare this down.

* Most of your observed feature counts are zeros, from what you showed in the `head(mydfm)`, and the sparsity was near 100%. This means you are trying to compute similarities on feature counts whose values are nearly zero across the document set. This is more than a technical problem, it's a substantive problem. Trim the features, and consider not using bigrams, which you are using, apparently, from the above evidence of feature names such as "conditionalstatements".

**Comment by phanindraSami** [comment]
Hi,
I am also facing the same issue while finding the cosine similarity.

my dataframe is of 141271 rows, 880 columns.

Did you find any solution @FinScience

**Comment by kbenoit** [comment]
Trimming the low-frequency features would be my suggestion.
