### ISSUE TITLE
fcm is double counting collocations

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#600]
I noticed that the frequencies of features in `fcm` sometimes become greater than those in `dfm`:
```r
toks <- tokens("A D A C E A D F E B A C E D")
fcm(toks, 'window', window = 2, tri = FALSE)
Feature co-occurrence matrix of: 6 by 6 features.
6 x 6 sparse Matrix of class "fcm"
        features
features A D C E F B
       A 1 3 3 4 1 1
       D 3 0 2 3 1 0
       C 3 2 0 2 0 1
       E 4 3 2 0 1 1
       F 1 1 0 1 0 1
       B 1 0 1 1 1 0

dfm(toks, tolower = FALSE)
Document-feature matrix of: 1 document, 6 features (0% sparse).
1 x 6 sparse Matrix of class "dfmSparse"
       features
docs    A D C E F B
  text1 4 3 2 3 1 1
```
In the example, C and E is greater in `fcm`, because the function counts these features twice. Double counting can make collocation association measures inaccurate. If we allow `fcm` to double count, how can we obtain marginal frequency count?

**Comment by HaiyanLW** [comment]
`fcm' counts, for example, `A-C` in this way: second `A`- first `C`, first `C`-third `A` and  the 4th `A'- 2nd `C`.  It doesn't count the combination twice.

**Comment by koheiw** [comment]
I see. If fcm distinguishes left and right collocations, why don't you use upper and lower triangles for the two? Also, a mode that does not distinguish left and right is really needed.

**Comment by HaiyanLW** [comment]
The command you used doesn't distinguish left and right collocations. If you want to, set `ordered = TRUE`
```r
> fcm(toks, 'window', window = 2, ordered = T, tri = FALSE)
Feature co-occurrence matrix of: 6 by 6 features.
6 x 6 sparse Matrix of class "fcm"
        features
features A D C E F B
       A 1 2 2 2 1 0
       D 1 0 1 1 1 0
       C 1 1 0 2 0 0
       E 2 2 0 0 0 1
       F 0 0 0 1 0 1
       B 1 0 1 0 0 0
```

**Comment by HaiyanLW** [comment]
And if `tri = TRUE`, you can get the triangular fcm,
```r
Feature co-occurrence matrix of: 6 by 6 features.
6 x 6 sparse Matrix of class "fcm"
        features
features A D C E F B
       A 1 3 3 4 1 1
       D . . 2 3 1 .
       C . . . 2 . 1
       E . . . . 1 1
       F . . . . . 1
       B . . . . . .
```
