### ISSUE TITLE
Disable some arguments for tokens()

### ISSUE THREAD

**Issue by HaiyanLW** [kbenoit/quanteda#606]
Maybe the arguments not applicable should be disabled to avoid confusing, for instance  `removePunct` : 
```r
> poetry <- paste0("I wandered lonely as a cloud\n",
+ "That floats on high o'er ,,, vales and hills.\n",
+ "They stretched in  # never-ending @line.\n")
> tokens(poetry, what = "sentence", removePunct = T)
tokens from 1 document.
Component 1 :
[1] "I wandered lonely as a cloud That floats on high o'er ,,, vales and hills."
[2] "They stretched in  # never-ending @line."            
```

**Comment by kbenoit** [comment]
Issue a warning?

**Comment by HaiyanLW** [comment]
Or just strip the unused arguments from the particular functions. For example, remove `removePunt` from `tokens_sentence`.

**Comment by kbenoit** [comment]
But...we don't have a function called `tokens_sentence()`. If we did it would mean removing the `what = "sentence"` from tokens. But I see that none of the options apply to "sentence" tokenisation, so maybe that option should be in a separate function.

Note at the moment we have:

* `corpus_segment(x, what = "sentences")`
* `char_segment(x, what = "sentences")`
* `corpus_reshape(x, to = "sentences")`

`corpus_segment()` works with tags, but for sentences and paragraphs it's pretty much the same as `corpus_reshape()`. @HaiyanLW I suggest you take a critical look at these functions and decide if you think they make sense. I don't like having multiple functions to perform the same action, but I cannot remember now why we did this for segment *and* reshape.

**Comment by HaiyanLW** [comment]
We do have those as internal functions, with unified interface though, see line 549 in `tokens.R`
```r
tokens_sentence <- function(txt, what, removeNumbers,  removeSymbols, removeSeparators, 
                            removeTwitter, removeHyphens, removeURL, verbose){
```

**Comment by kbenoit** [comment]
See my comment here: https://github.com/kbenoit/quanteda/issues/619#issuecomment-291405779. I think if we separate segmentation from the `tokens` constructor, it would alleviate this confusion. 

Also I don't think we should allow tokens objects to consist of sentences at all, since there is no advantage to hashing them (since the type to token ratio would be near 1.0).
