### ISSUE TITLE
add method for predicted wordscores model to textplot_scale1d 

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#610]
This involves making the `textplot_scale1d()` modular, separating the underlying code into an internal function to scale document positions, and one to scale feature positions by weights, and then making `textplot_scale1d.textmodel_wordfish_fitted` call the two underlying functions after extracting the document or feature positions from the object. Then we will need to write a new `textplot_scale1d.textmodel_wordscores_predicted` method that operates the same way, after extracting the analogous wordscores quantities.

**Comment by kbenoit** [comment]
@stefan-mueller you are welcome to give this a go if you want, otherwise it's on my medium-term list.

**Comment by stefan-mueller** [comment]
I'm happy to have a go at this, probably next week. Two clarifying questions:

1. Does this mean that we have two different `wordscores` plots, one one the `documents` and one on the `features` level? I'm not sure how the `features` level plot should look like. What's on the x- and y-axis? Do you have an example from a publication? Would the `documents`plot be like Figure 3 in [Laver, Benoit and Garry (2003)](http://faculty.washington.edu/jwilker/tft/Laver.pdf) with the Wordscores on the x-axis?

1. Do I understand it correctly that we have something like this at the end: `textplot_scaled1d(type = "wordfish"/"wordscores", margin = "documents"/"features")` to call either the wordfish or wordscores and determine whether the documents or features level should be plotted?

**Comment by kbenoit** [comment]
Re: 1:
* documents plot is just for the estimated textscore positions
* features plot can be the word scores by log frequency

Re: 2:
* No, the object dispatch for S3 will take care of that, see the updated code. You just need a function for `textplot_scale1d.textmodel_wordscores_predicted` and it will dispatch on that object class.

**Comment by stefan-mueller** [comment]
This makes sense. For plotting the estimated textscore positions, we probably need an extra option for `rescaling` to choose between the `raw`, `lbg`, and/or `mv`scores? I have a close look at this next week and get back to you.

**Comment by kbenoit** [comment]
no, that's part of the predicted object, so the user sets that when creating that object.

**Comment by stefan-mueller** [comment]
This is the first part of `textplot_scale1d.textmodel_wordscores_predicted` which plots the textscores (either raw or as a transformation). 

```r
library(quanteda)
library(ggplot2)

textplot_scale1d.textmodel_wordscores_predicted <- 
    function(x, margin = c("documents", "features"), 
             textscore = "raw", doclabels = NULL, 
             sort = TRUE, groups = NULL, highlighted = NULL, alpha = 0.7, 
             highlighted_color = "black") {
      
      margin <- match.arg(margin)

      if (margin == "documents") {
        n <- length(x@textscores$textscore_raw)
        if (is.null(doclabels))
          doclabels <- x@newdata@Dimnames$docs
        stopifnot(length(doclabels) == n)

        if (sort & !is.null(groups)) {
          temp_medians <- aggregate(x@textscores$textscore_raw, list(groups), median, na.rm = TRUE)
          groups <- factor(groups, levels = temp_medians[order(temp_medians$x, decreasing = TRUE), 1])
        }
        
        if (textscore == "raw") {
          textscore_raw <- textscore_raw_lo <- textscore_raw_hi <- NULL
          textscore_lbg <- textscore_lbg_lo <- textscore_lbg_hi <- NULL
          
          results <- data.frame(doclabels = doclabels, 
                              textscore = x@textscores$textscore_raw, 
                              lower = x@textscores$textscore_raw_lo, 
                              upper = x@textscores$textscore_raw_hi)
        }
        
        if (textscore == "lbg") {
          textscore_lbg <- textscore_lbg_lo <- textscore_lbg_hi <- NULL
          results <- data.frame(doclabels = doclabels, 
                                textscore = x@textscores$textscore_lbg, 
                                lower = x@textscores$textscore_lbg_lo, 
                                upper = x@textscores$textscore_lbg_hi)
        }
        
        if (textscore == "mv"){
          textscore_mv <- textscore_mv_lo <- textscore_mv_hi <- NULL
          results <- data.frame(doclabels = doclabels, 
                                textscore = x@textscores$textscore_mv)
        }
        if (!is.null(groups))
          results$groups <- groups
        
        p <- if (sort) {
          ggplot(data = results, aes(x = reorder(doclabels, textscore), y = textscore))
        } else {
          ggplot(data = results, aes(x = doclabels, y = textscore))
        }
        p <- p + 
          coord_flip() + 
          { if (!is.null(groups))
            facet_grid(as.factor(groups) ~ ., scales = "free_y", space = "free") } +  
          { if (textscore != "mv")
          geom_pointrange(aes(ymin = lower, ymax = upper), lwd = .25, fatten = .4) } +
          geom_point(size = 1) +
          { if (textscore == "raw")
            ylab("Estimated textscore") } +
          { if (textscore == "lbg")
             ylab("Estimated textscore (LBG transformation)") } +
          { if (textscore == "mv")
             ylab("Estimated textscore (MV transformation)") } + 
          xlab(NULL)
      }

      # apply a minimal theme
      p <- p + 
        theme_bw() + 
        theme(panel.background = ggplot2::element_blank(),
              panel.grid.major.x = element_blank(),
              panel.grid.minor.x = element_blank(), 
              # panel.grid.major.y = element_blank(),
              panel.grid.minor.y = element_blank(), 
              plot.background = element_blank(),
              axis.ticks.y = element_blank(), 
              # panel.spacing = grid::unit(0.1, "lines"),
              panel.grid.major.y = element_line(linetype = "dotted"))
      
      suppressMessages(p)
    }  
```

I added a new option called `textscore`. Here we can select whether to plot the raw textscore, the `lbg`, or the `mv` transformation . Let me know whether I need to change something in the function above.

Below are some MWEs: 

```r
textplot_scale1d.textmodel_wordscores_predicted(ws, margin = "documents",
                                                doclabels = doclab)

textplot_scale1d.textmodel_wordscores_predicted(ws, 
                                                textscore = "lbg",
                                                margin = "documents",
                                                doclabels = doclab,
                                                groups = docvars(data_corpus_irishbudget2010, "party"))

textplot_scale1d.textmodel_wordscores_predicted(ws, 
                                                textscore = "mv",
                                                margin = "documents",
                                                doclabels = doclab,
                                                groups = docvars(data_corpus_irishbudget2010, "party"))
```
By the way: How can I access the log frequency for each word? I need them for the second part of the function.

**Comment by kbenoit** [comment]
great, please fork and work on a branch for which you can issue a PR. This gives me a chance to review it and modify the code if needed.

You can get the log frequency for each word this way:
```r
> ws <- textmodel_wordscores(data_dfm_LBGexample, c(seq(-1.5, 1.5, .75), NA))
> pred <- predict(ws)
> colSums(pred@newdata)
  A   B   C   D   E   F   G   H   I   J   K   L   M   N   O   P   Q   R   S   T   U   V   W   X   Y   Z  ZA  ZB  ZC  ZD  ZE  ZF  ZG  ZH  ZI 
  2   3  10  22  45  80 118 158 183 201 217 241 279 317 347 356 344 316 280 246 220 208 204 204 201 196 195 191 180 156 118  80  45  22  10 
 ZJ  ZK 
  3   2 
```

**Comment by stefan-mueller** [comment]
I'm almost there and will issue a PR. Is it correct that the `predict()` wordscores object does not include the textscores for each word? Thus, do we need to refer back to the `textmodel_wordscores` object to get the word-level textscores there? 

This seems a bit error-prone (to plot the textscores per word one would need to specify both objects in the formula?), but from your comments above I assume that only the predicted wordscores model (`x`) should be used as in the formula. As far as I see, we need both objects to create this plot which becomes problematic if `textmodel_wordscores()` and `predict()` were conducted in the same step. What should we do?

```r
ws <- textmodel_wordscores(data_dfm_LBGexample, c(seq(-1.5, 1.5, .75), NA))
ws@Sw

head(ws@Sw)
#       A        B        C        D        E        F 
# -1.50000 -1.50000 -1.50000 -1.50000 -1.50000 -1.48125 

ws_pred <- predict(ws, rescaling = c("lbg"))
# ws_pred@Sw does not contain scores for each word
```

**Comment by kbenoit** [comment]
Actually...it is supposed to be part of the predicted object but looking at the code now, I see that it is not. Give me an hour or so and I will fit this!
