### ISSUE TITLE
Specify minimum hardware requirement

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#611]
Problems on small virtual machines have been reported to us. It is no surprise that quanteda does not work as expected on a system with only 1GB RAM and 1 CPU core. #608 seems to be this case. It depends on the size of data and the type of analysis, but users needs to have at least 2 cores and 4GB RAM. Recommended hardware specification is more than 4 cores and 8GB RAM. Use of latest operating systems should be also encouraged.

**Comment by gjunqueira** [comment]
May I comment on this matter?

Even better than having a specification outsite the code, maybe it would be a better ideia for the memory intensive functions to display a warning when the expected memory usage is likely to be higher than the available memory on the system.

I believe you have some good benchmarks on this based on the corpus size.

For instance: if it is common for a 4 MB corpus to use 400 MB, than there is a estimated factor of 100x. So if a user intend on processing a 25 MB corpus and have less than 25 GB of memory, a warning would be displayed.

Does it make sense?

**Comment by koheiw** [comment]
It is an interesting idea, thank you. We have a formula to estimate the size of the output vectors in the ngram generator to pre-allocate memory already. I am not sure when the leak happen, but I can still warn users of the possibility.

**Comment by koheiw** [comment]
Also #1184

**Comment by koheiw** [comment]
I am not sure where this should go, but somewhere docs wbesite or README.

**System requirements**

**quanteda** is cross-platform but we recommend Mac or Linux as an operating system for their better handling of Unicode. RAM depends on the size and the structure of the textual data to analyze. Usually, a text file of 100MB on disk takes 500MB to 1GB on memory as a tokens object (short texts needs more memory than long texts when the total number of words is the same). 

| | Minimum | Recommended |
| --- | :---: | :---: |
| OS | Windows/Mac/Linux | Mac/Linux |
| CPU | 1 core | 4 cores or more |
| RAM | 2GB | 8GB more more |
| IDE | | R Studio |

**Comment by koheiw** [comment]
Added to docs.quanteda.io
