### ISSUE TITLE
Question regarding the new wordfish implementation

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#612]
Hi,

I just tested the new wordfish implementation and it is muuuch faster than before which is totally awesome. Did you test the new version against the old one for corpora that you know and achieved similar results? 
At the moment I'm playing around with wordshoal at lot and as far as I understand, wordshoal directly uses wordfish in the first stage. After now rerunning some wordshoal models with the new wordfish implementation, I can definitely notice some differences. Is this to be expected?

**Comment by kbenoit** [comment]
See #613. If you install that branch, you will be able to pass arguments to the wordfish function that give you a bit more control over the new behaviours.

But remember that `textmodel_wordshoal()` remains quite experimental, until @lauderdale works on the code and tests for this function a bit more!

**Comment by methodds** [comment]
Thanks, I'll check out that branch. And yes, I'm aware of wordshoal being quite experimental for the moment, but I still like and am very much looking forward to when @lauderdale will find the time to further test and improve it :)
