### ISSUE TITLE
internal compiler error for installation via Github

### ISSUE THREAD

**Issue by Ninoninoninonino** [kbenoit/quanteda#617]
On an Amazon Ubuntu server for `install_github('kbenoit/quanteda')`

I get 

```
...

g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
/usr/lib/R/etc/Makeconf:141: recipe for target 'wordfish.o' failed
make: *** [wordfish.o] Error 4
ERROR: compilation failed for package ‘quanteda’
```

```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_1.12.0

loaded via a namespace (and not attached):
[1] httr_1.2.1    R6_2.2.0      tools_3.3.3   withr_1.0.2   curl_2.3     
[6] memoise_1.0.0 knitr_1.15.1  git2r_0.18.0  digest_0.6.12
> 

```

**Comment by kbenoit** [comment]
Hmm, it's hard to diagnose this unless we know your installation. Have you checked that the packages Imported (see `DESCRIPTION`) are all present in their correct versions? Also what are the VM's parameters (RAM, CPU cores, etc)?

Finally, does the CRAN version install? Ubuntu will compile this by source, and it would be interesting to see how that works. You could also try installing an earlier version, e.g.

```r
devtools::install_github("kbenoit/quanteda", ref = "03ae172")
```

will install one of the last versions before we just rewrote the wordfish C++ functions, which from your message may be causing a problem.

**Comment by dani-lbnl** [comment]
Error persists, any other thought?

**Comment by kbenoit** [comment]
Strange, since I test it on my Ubuntu 16.04 LTS build and it's fine. I suspect your Amazon instance simply lacks some of the libraries you need to `apt-get`.  Maybe update your compiler?
