### ISSUE TITLE
Reimplement bootstrap_dfm

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#648]
Strangely `bootstrap_dfm` takes a `corpus` object and segment into sentences internally, but it should take a `dfm`. Also, `corpus_reshape`, which is used in the function, looks like a very older version of `corpus_segment`. We should kill this.

**Comment by kbenoit** [comment]
We need to think of the design for bootstrapping text, but the function behaves correctly for what it needs to do and as used by two other (currently private) packages I have. The reshape is there because the resampling is done at the sentence level. 

Something to discuss, for certain.

**Comment by koheiw** [comment]
If we record document ID in `corpus_segment`, we can still bootstrap documents on a `dfm`. I will leave this until `corpus_segment` is upgraded.

**Comment by kbenoit** [comment]
Well, we can't bootstrap using sentence-level resampling from a dfm if the features are words, since we have no more record of the unit. Yes we could bootstrapping on a segmented corpus, but that is what bootstrap_dfm already does.

**Comment by koheiw** [comment]
My idea is to segment corpus into sentences beforehand, so units are sentences in this dfm.

**Comment by kbenoit** [comment]
Ah I see. But the computed quantities needed are at the document-level - the sentence resampling is just to estimate variability. So we would not want a dfm at the sentence level.

**Comment by koheiw** [comment]
Your are right. We cannot calculate document level quantities  with this currently.
```r
txt <- c(textone = "This is a sentence.  Another sentence.  Yet another.", 
         texttwo = "Premiere phrase.  Deuxieme phrase.")
corp <- corpus(txt)
corp_sent <- corpus_segment(corp)
dfm(corp_sent)

Document-feature matrix of: 5 documents, 10 features (66% sparse).
5 x 10 sparse Matrix of class "dfmSparse"
           features
docs        this is a sentence . another yet premiere phrase deuxieme
  textone.1    1  1 1        1 1       0   0        0      0        0
  textone.2    0  0 0        1 1       1   0        0      0        0
  textone.3    0  0 0        0 1       1   1        0      0        0
  texttwo.1    0  0 0        0 1       0   0        1      1        0
  texttwo.2    0  0 0        0 1       0   0        0      1        1
```
I am suggesting to record original document ID in the docvar when `corpus_segment` is applied. So dovar will have  a vector `docid = c(1, 1, 1, 2, 2)`, and `bootstrap_dfm` can resample within documents.
