### ISSUE TITLE
Allow selecting docvars to be passed to tokens, dfm and kwic

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#649]
When `include_docvars = TRUE`, all document variables are passed to tokens or dfm, but not all variables are used in the downstream, so it is good to allow users to specify variables to pass in a character vector of variables names. Showing selected document variables in kwic is also good.

**Comment by kbenoit** [comment]
We could define `docvars<-.tokens`, `docvars<-.dfm` that would allow users to select out these, and this would allow some users to associate additional variables with these for convenience. However we want to discourage this generally, since the corpus object is the designed to be the main vessel for the texts and associated variables.

For a `kwic` object, I'm not sure how this would work, because we've gone from document units to keyword-based units.

**Comment by koheiw** [comment]
We do need to assign new variables to tokens or dfm. I want to choose docvar for kwic, because docvars become multiplied in it, if include_docvars = true. I only need dates, for example.

**Comment by kbenoit** [comment]
Got it. 

Can we think of a neater way to select docvars than adding (yet) another argument to each of the constructor functions?

**Comment by koheiw** [comment]
How about `include_docvars = c('party', 'date')` to select, while `include_docvars = TRUE` is all variables?

**Comment by kbenoit** [comment]
I'm not a big fan of arguments that take multiple value types, but let me think about this.

**Comment by koheiw** [comment]
It would be much more efficient to keep an original data.frame even when a corpus is segmented. Instead creating a data.frame with many duplicated rows, we can multiply document level variables when docvars() is called using recently added `_docid`. Here, only `_docid` and `_segid` needs to be the same N as texts.


not multiplying rows in `corpus_segment`. My suggestion is

**Comment by koheiw** [comment]
I started thinking that it is better to export `docvars <-` for tokens and dfm object. For example, a docvar is the best place to keep topics of documents when we fit a LDA to a dfm.

Exporting `docvars <-` also allow users to drop variables that will be no longer need in the downstream. If we really do not want users tempering with docvars, we can make `docvars_add(dfm, 'topic')` and `docvars_remove(dfm, 'not needed')`.

**Comment by kbenoit** [comment]
Ok on the exports, but not on the new commands. Not needed and not grammatically consistent.
