### ISSUE TITLE
textfile() needs stress-testing and robust error reports

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#65]
Works well now...when it works.

**Comment by adamobeng** [comment]
Tests for the current version of textfile.R are almost done in [dev_textfile_tests](https://github.com/kbenoit/quanteda/tree/dev_textfile_tests).

**Comment by adamobeng** [comment]
The [rewrite of textfile.R](https://github.com/kbenoit/quanteda/tree/dev_textfile_rewrite) has 100% test coverage as of 379adb7.
