### ISSUE TITLE
Allow subsetting dfm with lgCMatrix

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#650]
Relational operations with dfm return lgCMatrix, but it cannot be used with dfm.
```r
txt <- c('a b c', 'a b c', 'b c d e')
mx <- dfm(txt)
mx[,'d'] > 0 
mx[mx[,'d'] > 0,]  # error
```
We have to do like this at the moment:
```r
mx[which(mx[,'d'] > 0),] 
```

**Comment by koheiw** [comment]
dfm's signature need to be defined unambiguously to do subsetting by a logical vector. This is related to #494.

**Comment by koheiw** [comment]
This involves reimplementation of `dfm`. Should be solved along with #494.

**Comment by kbenoit** [comment]
I think the will be easier to solve than that, just involves a new method for `[`. I'll give it a try.

**Comment by kbenoit** [comment]
May not be our fault:

```r
as(mx, "dgCMatrix")[mx > .5, ]
# Error in as(x, "generalMatrix")[i = i, , drop = TRUE] : 
#   invalid or not-yet-implemented 'Matrix' subsetting
```
(appears to be an issue in **Matrix**)

**Comment by koheiw** [comment]
I could write
```r
setMethod("[",
          signature = c("dfm", i = "lgCMatrix", j = "missing", drop = "missing"),
          function(x, i, j, ..., drop = FALSE) {
              return(x[as.vector(i),])
          })
```
to make it work, but there is not guarantee that the **lgCMatrix** has only one column.
The right way of doing this is 
```r
mx[rowSums(mx[,'d']) > 0,] 
```
then we do not need a new method for **lgCMatrix**.
