### ISSUE TITLE
char_segment raises worng warning

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#657]
It is not segmenting into tokens, apparently.
```r
out <- char_segment(data_char_ukimmig2010, what = "sentences", delimiter = '. ')
Warning message:
In get_delimiter(what, delimiter, valuetype) :
  delimiter is not used for tokens
```

**Comment by koheiw** [comment]
@kbenoit  `corpus_segment` has a option `what = tags`, which looks like a legacy from earlier versions. Do we still need this?

**Comment by kbenoit** [comment]
The `what = "tags"` is just a convenience for users who have marked up their documents with `##TAG` type tags, and who don't know much about regular expressions. It's the same as "other" but with a specific delimiter in the regex. I know a lot of users who are find this useful, so prefer to keep the option.
