### ISSUE TITLE
Augment the trim() command with relative frequency thresholds

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#66]
1.  Add the ability to specify a proportion to `minDocs`, where this means "keep only terms appearing in this proportion of documents".  
2.  Add the ability to specify a proportion to `minTerms`, where this means "keep only terms whose relative frequency across all texts is at least this proportion.  
3. Add a new argument called `sparse.tm`, which operates like the `sparse` argument in `tm::removeSparseTerms()`. See http://stackoverflow.com/questions/28763389/how-does-the-removesparseterms-in-r-work/33830637#33830637.

**Comment by pnulty** [comment]
1, 2, and 3 done and added testthats.
