### ISSUE TITLE
textmodel_ca broken for multi-threading

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#663]
This is not showing up in the CI tests because we do not import or suggest the **ca** package, so the tests are skipped, but I noticed two things:

1. Multi-threading is broken:

    ```r
    ie2010dfm <- dfm(data_corpus_irishbudget2010)
    wtca <- textmodel_ca(ie2010dfm, threads = 2, sparse = TRUE)
    ## Error in .Call("quanteda_cacpp", PACKAGE = "quanteda", objm, threads,  : 
    ##  "quanteda_cacpp" not available for .Call() for package "quanteda" > wtca <- textmodel_ca(ie2010dfm, threads = 2)
    ```

2. This should print a warning but does not:

    ```r
    ie2010dfm <- dfm(data_corpus_irishbudget2010)
    wtca <- textmodel_ca(ie2010dfm, threads = 2)
    ```

    I'd like it to print:
    ```
    Warning message:
    threads reset to 1 when sparse = FALSE 
    ```

I've started a branch `bugfix-ca` where I added the **ca** package to the `Suggests:` section so that the tests will now run on CI and CRAN.

**Comment by HaiyanLW** [comment]
Fix it. Somehow, the `cacpp` function is not included in `init.c`.
