### ISSUE TITLE
Converting to stm causes indexing error after weighting with tfidf

### ISSUE THREAD

**Issue by danielmerken** [kbenoit/quanteda#667]
```
mydfm <- dfm(mycorpus) 
weighted_dfm <- tfidf(dfm)
storage <- stm(weighted_dfm, 10)
```
The above example code throws the following error: 
`Word indices must be sequential integers starting with 1.`

**Comment by kbenoit** [comment]
This doesn't work for several reasons:
* topic models of this sort require counts, not fractional values of the sort returned by tf-idf weighting; and
* you need to use `convert()` to translate the dfm into the format required by **stm**.
