### ISSUE TITLE
tm Vcorpus to corpus conversion fails

### ISSUE THREAD

**Issue by jkeuskamp** [kbenoit/quanteda#672]
I have a large Vcorpus that I try to import into quanteda, using the command
`quanteda::corpus(My_Vcorpus)`, but that renders the following error:

`Error in as.POSIXlt.default(X[[i]], ...) : 
  do not know how to convert 'X[[i]]' to class “POSIXlt”`

Now I do not know anything about the structure of a VCorpus, so I am somewhat in the dark about what the issue could be. Obviously some date/time related field has unexpected formatting, but I am not quite sure how to solve that.

Any suggestions on how to solve this?

**Comment by kbenoit** [comment]
Hi @jkeuskamp - If you can send me a link to the object, I can try to reproduce (and then solve) the error.

**Comment by kbenoit** [comment]
I'm closing this, if you still want help, reopen the issue and send me a link to the object.
