### ISSUE TITLE
dfm fails when executed by Rscript

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#676]
Not many people run quanteda by Rscript, but I am doing head-to-head comparison with Python. This can be a sign of deeper problem.

```
kohei@Linux:~/projects/benchmark$ Rscript test1.R
Loading required package: quanteda
quanteda version 0.9.9.48
Using 7 of 8 cores for parallel computing

Attaching package: ‘quanteda’

The following object is masked from ‘package:utils’:

    View

Loading required package: stringi
Error in validObject(r) : 
  invalid class “dgTMatrix” object: Not a valid 'Mnumeric' class object
Calls: dfm ... compile_dfm.tokens -> <Anonymous> -> <Anonymous> -> validObject
Execution halted
```
The content of test1.R is only
```r
#!/usr/bin/Rscript 
require(quanteda)
require(stringi)
mx <- dfm(data_corpus_inaugural)
```

**Comment by kbenoit** [comment]
See https://github.com/kbenoit/quanteda/issues/118

Strange but true.

**Comment by koheiw** [comment]
Loading `methods` worked. We should include `methods` to the dependency.

**Comment by koheiw** [comment]
`methods` is actually in imports, simply not loaded...

**Comment by kbenoit** [comment]
This is a problem for all packages using Rscript, and S4 or anything else in the **methods** package. It's an obscure but documented feature of Rscript, so I suggest we leave as is.

**Comment by koheiw** [comment]
The solution is to add it to `depends`.
