### ISSUE TITLE
Improve dispersion plot, method for plot.kwic

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#68]
Currently works (very) crudely. Should be more like the one in qdap or nltk.

Relates to #78.

**Comment by adamobeng** [comment]
kwic only produces positions for a single term, qdap and nltk allow comparing multiple terms within the same document. If we want to match their output, should we modify kwic to also produce output for multiple terms?

**Comment by adamobeng** [comment]
Fixed by [PR 146](https://github.com/kbenoit/quanteda/pull/146)
