### ISSUE TITLE
Moving tm corpus to quanteda corpus

### ISSUE THREAD

**Issue by ijavid100** [kbenoit/quanteda#680]
I am facing the problem while working with quanteda package of R. I have uploaded text files in tm package and want to move in quanteda corpus.

corpus of tm package contains files with this name "large simplecorpus (95 elements, 53mb)

Earlier, I uploaded corpus of text documents, it only have "corpus" instead of "large simplecorpus".

When I move corpus to quanteda corpus, This gives the following message with error:

Error in UseMethod("corpus") :
  no applicable method for 'corpus' applied to an object of class "c('SimpleCorpus', 'Corpus')"

please reply me to solve this issue.

**Comment by kbenoit** [comment]
try this:

```r
corpus(yourSimpleCorpus$content, docvars = yourSimpleCorpus$dmeta)
```

**Comment by kbenoit** [comment]
To do still:

- [ ] add support for corpus metadata import
- [ ] test on PCorpus
