### ISSUE TITLE
collocations returns no rows

### ISSUE THREAD

**Issue by trinker** [kbenoit/quanteda#688]
@kbenoit when I use `collocations` I get a zero row dataframe back.  This is the example from the help file.  I am using R 3.4.0 on Win machine (`sessionInfo` @ bottom).  Not sure of the root of the issue (R version, quanteda version, minimal dependency versions not met, etc.) but the est start is to see if you can reproduce the problem.

## MWE 

```
library(quanteda)

txt <- c("This is software testing: looking for (word) pairs!  
         This [is] a software testing again. For.",
         "Here: this is more Software Testing, looking again for word pairs.")

quanteda::collocations(txt, punctuation = "dontspan", method = 'all') 

## [1] word1 word2 word3 count G2    X2    pmi   dice 
## <0 rows> (or 0-length row.names)
```

Same results w/ `quanteda::collocations(txt) ` 

## Session Info 

```
R version 3.4.0 (2017-04-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 14393)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_0.9.9-50

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10        lattice_0.20-35     grid_3.4.0         
 [4] plyr_1.8.4          gtable_0.2.0        pacman_0.4.1       
 [7] scales_0.4.1        RcppParallel_4.3.20 ggplot2_2.2.1      
[10] stringi_1.1.5       lazyeval_0.2.0      data.table_1.10.4  
[13] Matrix_1.2-9        fastmatch_1.1-0     tools_3.4.0        
[16] munsell_0.4.3       compiler_3.4.0      colorspace_1.3-2   
[19] tibble_1.3.0       
```

**Comment by kbenoit** [comment]
Thanks @trinker - we've been modifying this function, the best is to use `textstat_collocations()` on a tokenised text instead. This works:

```r
> toks <- tokens(txt)
> textstat_collocations(toks)
       collocation count       G2
1 software testing     2 15.33228
```
but we will also look into what changed the underlying function.

**Comment by trinker** [comment]
@kbenoit  I have a GitHub package that depends on quanteda for finding frequent ngrams.  I need to make updates to it to address the changes in quanteda but would prefer to have a more permanent fix.  Is the `textstat_collocations` api that you recommended stable enough to rely on it in a package?

**Comment by kbenoit** [comment]
Yes, although we are currently revising that function and how it operates. Should have it very stable within two weeks. The functionality will be more or less the same, with the collocation provided in the text column returned as a data.frame as per the current format (although the statistical scoring methods may change). Sorry for the flux - we are trying to make it as fast, stable, and correct as possible.

**Comment by trinker** [comment]
Perfect...thanks for the quick reply

**Comment by kbenoit** [comment]
Should be ok now:

```r
textstat_collocations(tokens(txt)) 
##        collocation count       G2
## 1 software testing     2 15.33228
```
