### ISSUE TITLE
Corpus constructor's notes argument is not working

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#689]
```r
> corpus(c('a b c', 'e f g'), notes = 'this is a note')
Corpus consisting of 2 documents and 0 docvars.
Warning message:
In corpus.character(c("a b c", "e f g"), notes = "this is a note") :
  Argument notes not used.
```

**Comment by koheiw** [comment]
This is the new way in documentation, but this is cumbersome and discouraging users to add meta info. It would be better to add `notes` and `source` as arguments.
```r
corpus(c('a b c', 'e f g'), metacorpus = list(notes = 'this is a note'))
```

**Comment by kbenoit** [comment]
That was the old way, but it made the argument list too cumbersome to have special metacorpus fields directly. It's now a single argument called `metacorpus`, which is a named list.
