### ISSUE TITLE
object constructors should work on the class they construct

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#690]
`dfm()` already does this, for instance. We should add:

- [ ] `dfm.dfm()` needs thorough testing to make sure the options work
- [ ] `fcm()` needs implementation and testing
- [x] `tokens.tokens()` needs implementation and testing
- [x] `corpus.corpus()` (implemented in #880)
- [x] `dictionary()` (implemented in #880)

Note that the key here is not simply to make the constructor work, but also for all of the options to work the way they should, to change the input object. We will need to test each of these.

**Comment by kbenoit** [comment]
@koheiw Here's a use case for `tokens.tokens()`: Right now, the `remove_*` options don't work in `dfm.tokens(x)`, because the `x` is already tokenised and therefore (e.g.) `remove_punct` is never passed to `tokens()`. If we _always_ called `tokens()` as part of `dfm()`, however, then this would be more consistent behaviour in `dfm()` and solve this problem generally.

```r
toks <- tokens("This, is punctuation.")
dfm(toks, remove_punct = TRUE)
## Document-feature matrix of: 1 document, 5 features (0% sparse).
## 1 x 5 sparse Matrix of class "dfmSparse"
##        features
## docs    this , is punctuation .
##   text1    1 1  1           1 1
```

So I'm suggesting that we want this to work:
```r
tokens(toks, remove_punct = TRUE)
```
and (hopefully, obviously) for this to be `TRUE`:
```r
identical(toks, tokens(toks))
```

**Comment by koheiw** [comment]
`remove_punct = TRUE` is done by `stri_split_boundaries(skip_word_none = TRUE)`, so we probably need to change how tokenization is done to make `identical(toks, tokens(toks))`.

**Comment by kbenoit** [comment]
Since we might end up with different tokenizers, we should probably just remove the character class `\\p{P}` here (controlling for Twitter). It will still match for simple examples.

**Comment by koheiw** [comment]
I have been experimenting with an approach where we do not do any filtering before serialization:
```r
corp <- corpus_subset(data_corpus_guardian, year == 2015)
txts <- texts(corp)


pre <- function(x){
    x <- stri_replace_all_fixed(x, c("#", "@"), c("_ht_", "_as_"), vectorize_all = FALSE)
    toks <- stri_split_boundaries(x, type = "word", skip_word_none = TRUE)
    toks <- lapply(toks, stri_replace_all_fixed, c("_ht_", "_as_"), c("#", "@"), vectorize_all = FALSE)
    toks <- as.tokens(toks)
    return(toks)
}

post <- function(x){
    toks <- stri_split_boundaries(x, type = "word", skip_word_none = FALSE)
    toks <- as.tokens(toks)
    toks <- tokens_compound(toks, list(c('#', '*'), c('@','*')), valuetype ='glob', concatenator = '')
    toks <- tokens_select(toks, '^\\w+$', valuetype ='regex')
    return(toks)
}


microbenchmark::microbenchmark(
    pre(txts), 
    post(txts), times = 10
)

# Unit: seconds
# expr      min       lq     mean   median       uq      max neval
# pre(txts) 14.72523 15.25922 15.72813 15.82389 16.07331 16.61927    10
# post(txts) 25.49464 26.87887 27.71604 27.71393 28.77701 29.60643    10
```
Pre-flitering is faster, but it is easier to make `identical(toks, tokens(toks))` in  post-filtering. The post-method could be a bit (~30%) faster with a new tokens object based on xpointer.

The following regex patters are the close (not exact) equivalents for tokens objects:
```r
remove_numbers: "^[\\p{N}]$"
remove_punct: "^[\\p{P}]$", 
remove_symbols: "^[\\p{N}]$", 
remove_separators: "^[\\p{S}]$", 
remove_twitter: "^(@|#).+", 
remove_hyphens: "-", 
remove_url: "^https?", 
```

**Comment by kbenoit** [comment]
Good stuff, probably best noted in #373

**Comment by kbenoit** [comment]
For `tokens.tokens()`, calling `tokens()` on any input in `dfm()` including `dfm.tokenizedTexts()` will solve this problem about warnings:
```r
txt <- c(textone = "This is a sentence.  Another sentence.  Yet another.",  
         texttwo = "Premiere phrase.  Deuxieme phrase.")

tmp <- dfm(tokens(txt), removePunct = TRUE)
# Warning messages:
# 1: In dfm.tokenizedTexts(tokens(txt), removePunct = TRUE) :
#   Argument removePunct not used.
# 2: In dfm.dfm(result, tolower = FALSE, stem = stem, valuetype = valuetype,  :
#   Argument removePunct not used.
```

since the trapping and conversion of the older arguments into the new will take place in the deprecated argument code of `tokens_internal()` now. Fixing this will solve #826.
