### ISSUE TITLE
Conversion from DFM to STM swallows one document

### ISSUE THREAD

**Issue by Ninoninoninonino** [kbenoit/quanteda#696]
Conversion from DFM to STM swallows one document and makes further analysis impossible.

```r
> quantdfm
Document-feature matrix of: 56,920 documents, 12,423 features (98% sparse).
> presDfmSTM <- convert(quantdfm, to = "stm", docvars = meta)
> length(presDfmSTM$documents)
[1] 56919`

All meta data column lengths look fine:

E.g. `> length(meta$datetimestamp)
[1] 56920`

Couldn't find NA values either:
`> sum(is.na(meta$Interest))
[1] 0
> sum(is.na(meta$Region))
[1] 0
> 
```

Issue might be related to this one: https://github.com/bstewart/stm/issues/39

```r
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.2 (Maipo)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] quanteda_0.9.9-47 pryr_0.1.2        stm_1.2.1         dplyr_0.5.0      

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.10        ca_0.70             magrittr_1.5       
 [4] munsell_0.4.3       colorspace_1.3-2    lattice_0.20-34    
 [7] R6_2.2.0            fastmatch_1.1-0     stringr_1.2.0      
[10] plyr_1.8.4          tools_3.3.2         grid_3.3.2         
[13] data.table_1.10.4   gtable_0.2.0        DBI_0.6            
[16] lazyeval_0.2.0      RcppParallel_4.3.20 assertthat_0.1     
[19] tibble_1.3.0        Matrix_1.2-8        ggplot2_2.2.1      
[22] SnowballC_0.5.1     codetools_0.2-15    stringi_1.1.5      
[25] scales_0.4.1       
```

**Comment by Ninoninoninonino** [comment]
If I leave out the prepping, the error doesn't arise

`## remove stopwords
quantdfm <- dfm_select(quantdfm, stopwords("english"), selection = "remove")
class(quantdfm)
## get rid of anything that is not a number or a letter
quantdfm <- dfm_select(quantdfm, "[^a-zA-Z\\s]", selection = "remove", valuetype = "regex")
class(quantdfm)
## Let's get rid of words with less than three (?) letters. Shakespeares' longest word was 27 letters long .. 
quantdfm <- dfm_select(quantdfm, "\\w{2,27}\\b", selection = "keep", valuetype = "regex")
class(quantdfm)
## stem
quantdfm <- dfm_wordstem(quantdfm, language = "porter")
class(quantdfm)
## Let's get rid of words below a certain frequency
quantdfm <- dfm_trim(quantdfm, min_count = 45, min_docfreq = 45)`

**Comment by Ninoninoninonino** [comment]
I'm going to run the model directly with a dfm object ..

**Comment by kbenoit** [comment]
@Ninoninoninonino Could you send me a link to the `quantdfm` object so I can reproduce the problem?

**Comment by Ninoninoninonino** [comment]
Running STM directly with that quantdfm object I get

`Error in validObject(r) :
  invalid class “dgTMatrix” object: lengths of slots i and j must match
Calls: stm ... stm.control -> opt.beta -> mnreg -> sparseMatrix -> validObject
Execution halted
`
for 

`wood_cement_content <- stm(quantdfm, K=0, prevalence = ~ Interest + Region, content= ~ Interest,
                             max.em.its = iterations, data = meta, model = wood_cement_content, init.type = "Spectral")`

What would be a solution to remove empty documents from both the *dfm* and the *meta* file after prepping?

**Comment by kbenoit** [comment]
Thanks for sending the file. Your `quantdfm` has one empty row, following your feature selection.

```r
quantdfm
stmdfm <- convert(quantdfm, to = "stm")
str(stmdfm)
# List of 3
# $ documents:List of 56919
# ..$ 0001.html.xtr4    : int [1:2, 1:106] 154 1 190 5 199 1 228 1 373 1 ...
# ..$ 0002.html.xtr4    : int [1:2, 1:126] 190 7 373 3 497 1 524 1 555 1 ...
# ..$ 0003.html.xtr4    : int [1:2, 1:33] 59 1 119 3 341 4 961 1 1916 3 ...
# ..$ 0004.html.xtr4    : int [1:2, 1:488] 60 1 72 2 97 1 101 1 104 2 ...
# ..$ 0005.html.xtr4    : int [1:2, 1:178] 21 1 68 1 126 1 148 1 154 1 ...
# ..$ 0006.html.xtr4    : int [1:2, 1:102] 104 1 154 1 190 6 373 3 497 1 ...
# ..$ 0001.html.xtr5    : int [1:2, 1:224] 130 1 190 7 199 2 336 1 373 2 ...
# ..$ 0002.html.xtr5    : int [1:2, 1:106] 154 1 190 5 199 1 228 1 373 1 ...
# ..$ 0003.html.xtr5    : int [1:2, 1:167] 97 1 103 1 163 1 190 7 199 1 ...
# ..$ 0005.html.xtr5    : int [1:2, 1:488] 60 1 72 2 97 1 101 1 104 2 ...
# .. [list output truncated]
# $ vocab    : chr [1:12423] "aa" "aac" "aaron" "aashto" ...
# $ meta     : NULL

docnames(quantdfm)[which(!docnames(quantdfm) %in% names(stmdfm$documents))]
# [1] "2203.pdf.xtr1"

docnames(quantdfm)[which(rowSums(quantdfm) == 0)]
# [1] "2203.pdf.xtr1"
```
I suggest before you convert, using this:
```r
> quantdfm <- quantdfm[rowSums(quantdfm) > 0, ]
> quantdfm
Document-feature matrix of: 56,919 documents, 12,423 features (98% sparse).
```
(ignore the warning the first time you use the `>`)

But we will add a warning message that some rows are dropped in the stm conversion. **stm** cannot take an "empty" document as input, which is why it's dropped in conversion.

Note that you have a *very* sparse matrix here - it might make sense to remove some of the very low frequency features before trying to fit a STM.

**Comment by kbenoit** [comment]
Moved to #699.
