### ISSUE TITLE
dfm fails when using keywords from tokens()

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#702]
Hi,

with quanteda version ```quanteda_0.9.9-51``` the following code produces an error:

```

toremove <-  c(stopwords('german'), 
                                  c('dass', 'wurde', 'wurden',
                                    'uns', 'mal', 'mehr', 'schon', 'wurde',  'ja', 
                                    'sagte', 'sagten', 'viele', 'gibt', 'geben', 'wer', 'immer',
                                    'kommen' ,'seit', 'kommen', 'müssen', 'geht', 'gehen', '__', '. . .',
                                    '...', 'ganz', "sagen", "sagt", "tun", "wäre", "the", "machen", "macht",
                                    "herr", "frau", "ab", "heute", "dafür", "beim", "soll", "sollen", "bei", "beim",
                                    "kommen", "kommt", "stehts", "genau", "einfach", "eins", "zwei", "http", "y",
                                    "https", "www"))


posts_dfm <- dfm(posts$post_message, 
           remove = toremove,
           remove_twitter= F,
           remove_separators = T,
           remove_punct = T)

Error in eval(expr, envir, enclos) : 
  the ... list does not contain 3 elements
``` 
The documentation refers to additional keywords for ``tokens()``, which is why I already used the new underscore argument names.

And even after removing those three lines it raises a warning that I don't understand:
````
Warning message:
In features2vector(features) :
  dfm(posts$post_message, remove = toremove) does not support multi-word features
````
If  you need the data to reproduce this please find it [here](https://www.dropbox.com/s/z361h28hj0mkozc/pegida_posts_2017-05-01.RData?dl=1).

**Comment by koheiw** [comment]
The first issue is due to a special handling of old and new arguments of tokens. Short-handed boolean expressions do not work, so please
```r
posts_dfm <- dfm(posts$post_message, 
                 remove_twitter= FALSE,
                 remove_separators = TRUE,
                 remove_punct = TRUE)
```
The second issue is because you are using spaces in the feature vector. ". . ." is interpreted as as sequences of three dots, but `dfm` does not support support multi-word features (`tokens` does). If you want to give features with spaces to `dfm`, give it in a list:
```r
dfm(posts$post_message, remove = c(as.list(stopwords('german')), '. . .' ))

# Note that
dfm(posts$post_message, remove = c(stopwords('german'), '. . .' ))
# is equivalent to 
dfm(posts$post_message, remove = c(as.list(stopwords('german')), c('.', '.', '.')))
```

**Comment by methodds** [comment]
Ah I see, thanks for your explanation. You might want to add these somewhere in the documentation of `dfm()`, most importantly the `T` vs `TRUE` requirement.

**Comment by methodds** [comment]
There is another thing I don't quite understand: How can I pass the language code for the stemmer now within `dfm()`?

**Comment by kbenoit** [comment]
@koheiw I think we should make the second thing work, but issue a warning that the user might not have expected that this would be a compound token:
```r
> dfm(as.tokens(list(c("one two", "three", "one", "two"))), remove = "one two")
Document-feature matrix of: 1 document, 2 features (0% sparse).
1 x 2 sparse Matrix of class "dfmSparse"
       features
docs    one two three
  text1       1     1
Warning message:
In features2vector(features) :
  dfm(as.tokens(list(c("one two", "three", "one", "two"))), remove = "one two") does not support multi-word features
```

**Comment by kbenoit** [comment]
You can't currently pass the language code for the stemmer within the `dfm()` call. But you can form the dfm and then pass it to `dfm_wordstem()`, which does take the `language` argument.
