### ISSUE TITLE
extracting info from tokens object

### ISSUE THREAD

**Issue by daniel-allington** [kbenoit/quanteda#710]
Creating a dfm from a tokens object often causes R to fail, so I'd like to extract information directly from the tokens object using a function of my own. However, I can't figure out how to do this, e.g. `tokens.object$types` just returns ` character(0)`.

**Comment by koheiw** [comment]
I am very curious how `dfm` crashes R. Can you upload a applicable code and your system info? You can also update all the packages (especially Matrix package) to the latest to solve dfm related problems. If you want to use `tokens` in your functions, use `as.list()` so that you can get a normal list object.

**Comment by daniel-allington** [comment]
Thanks for the `as.list()` tip. Could that go in the documentation?

There's nothing odd about my code; it's just e.g. `tweet.dfm <- dfm(tweet.tokens, tolower=TRUE, remove=stopwords())` where `tweet.tokens` is a tokens object.

I think R is hanging because of the size of the tokens object, because the above works with single word tokens but fails with the same corpus divided up into skipgrams. The corpus is fairly large and I'm using a not-particularly-high-spec 64-bit Windows machine provided by my employer (under 8GB RAM).

**Comment by koheiw** [comment]
Thank you for the info. quanteda is memory efficient, but still uses 10x more space in RAM than the original text file on disk. skipgrams really expands sizes of tokens objects.

As for `as.list`, see `?as.list.tokens`.

**Comment by daniel-allington** [comment]
Perhaps it could give some kind of warning before starting to do something that will push the limits of available RAM? The trouble with R is that it can't interrupt a C++ process, so once you've realised that the computer has bitten off more than it can chew, you've got to terminate R and restart.

About `?as.list.tokens` - yes, but how would I have known to type that in if I didn't know that `as.list` was the way to get data out of a tokens object? What I meant was that it would be good for a mention of `as.list` to be added to the documentation for `tokens`.
