### ISSUE TITLE
features handling is inconsistent between dfm and tokens

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#719]
This is an issue arising from #711. Currently for functions that require feature selection, we have alternative ways of selecting them depending on the function and how sequences are handled. I'd like to see these made consistent across the functions.

### Example of the inconsistency: `tokens_remove()` v. `dfm_remove()`:

```r
require(magrittr)
txt <- "one two three four"

dfm(txt, ngrams = 1:2, concatenator = " ") %>%
    dfm_remove(features = c("three", "four", "one two"))
## Document-feature matrix of: 1 document, 4 features (0% sparse).
## 1 x 4 sparse Matrix of class "dfmSparse"
##        features
## docs    one two two three three four
##   text1   1   1         1          1

tokens(txt, ngrams = 1:2, concatenator = " ") %>%
    tokens_remove(features = c("three", "four", "one two"))
## tokens from 1 document.
## Component 1 :
## [1] "one two"    "two three"  "three four"

```

In order to get `tokens_remove()` to behave as it did for `dfm_remove()`, we have to specify a different object type for `features`:
```r
tokens(txt, ngrams = 1:2, concatenator = " ") %>%
    tokens_remove(features = list(c("three", "four", "one two")))
## tokens from 1 document.
## Component 1 :
## [1] "one"        "two"        "two three"  "three four"
```
### What should be the behaviour?

We should have a discussion on this, but my preference is for the way that `dfm_select()` does it above.

### Other functions that could be affected

* `fcm_select()`
* `dfm_select()`
* `tokens_select()`
* `sequences()`
* `kwic()`
* `tokens_compound()`

**Comment by koheiw** [comment]
The difference is coming from the fundamental difference between `dfm` and `tokens`. The latter supports multi-word features, so it need a list of character vectors. Space-separated features are only short-handed command (which is very handy).
