### ISSUE TITLE
Separator of XML-Elements

### ISSUE THREAD

**Issue by Astelix** [kbenoit/quanteda#732]
function (path, textfield, encoding, ...) 
{
 ...
        txt <- paste0(txt, collapse = "")
        return(data.frame(text = txt, stringsAsFactors = FALSE))
    }

replace 'collapse=""' by collapse=" "  or better give the option to the user to select the collapse-separator with a parameter

**Comment by kbenoit** [comment]
Thanks @Astelix - do you mean in the [**readtext**](https://github.com/kbenoit/readtext/blob/master/R/get-functions.R#L140) package? This code is not in **quanteda**. 

Please file an issue [here](https://github.com/kbenoit/readtext/issues) and supply an example of the behaviour you'd like changed. If you want to go further, consider fork the repo, modifying it, and issuing a pull request.

**Comment by Astelix** [comment]
Of couse, you are right. I was exploring the packages together. Without this parameter the the last word of a xml text element is always merged with the first word of the next element.


Von meinem iPad gesendet

**Comment by kbenoit** [comment]
There are other problems with adding a separator, but please file a reproducible example of the problem at https://github.com/kbenoit/readtext/issues.
