### ISSUE TITLE
Tokens not removing 

### ISSUE THREAD

**Issue by Monduiz** [kbenoit/quanteda#733]
I am using tokens to make ngrams and it appears to be removing none of the things it should. I am using the current github version of quanteda. The resulting table still has all the numbers, hyphens, etc. I am not sure what I am doing wrong. Thanks for any insights. I didnt inlcude the file nor the code for bad words but dfm didnt remove them either. The result is a table with ngrams containing numbers and hyphens.

Data: 
    
    fileUrl <- "https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip"
    download.file(fileUrl, destfile = "./data/data.zip")
    unzip("./data/data.zip", exdir = "./data")

    library(tidyverse)
    library(quanteda)
    library(data.tables)
    
    blogs <- read_lines("./data/final/en_US/en_US.blogs.txt")
    sampblogs <- sample(blogs, length(blogs) * 0.3)
    corpus_data <- corpus(sampblogs)

    unigrams <- tokens(corpus_data, what = "word", 
    remove_symbols = TRUE, 
    remove_numbers = TRUE, 
    remove_punct = TRUE, 
    remove_twitter = TRUE, 
    remove_url = TRUE,
    remove_hyphens = TRUE, 
    remove_separators = TRUE, 
    ngrams = 1, concatenator = " ")

    unigrams <- dfm(unigrams, remove = profanities)

    unig_dt <- data.table(ngram = featnames(unigrams), 
    count = colSums(unigrams), key = "ngram")

**Comment by kbenoit** [comment]
Hi @Monduiz - you closed the issue just after opening it - let me know if you still need help with this.

**Comment by Monduiz** [comment]
Ken, yes I am not just sure if this is intended. I seem to have a lot of ngrams with numbers in them. Things like quantities, 10ml, 00something and words starting with a number. I am thinking of removing them with regex. This is all new to me!

**Comment by kbenoit** [comment]
Please supply the `profanities` object or a link to it, so I can reproduce the problem. A smaller reproducible example would be welcome as well.

**Comment by Monduiz** [comment]
I ran the code again last night and the bad words list was removed. So, I am just not sure about words like 00am, 1-cent, 1-mile, 1,000-plus, 1.4-liter, 10-foot, 107th, 10g, etc.

Should tokens remove them? I will provide a sample later today.

**Comment by kbenoit** [comment]
`tokens_remove()` will only remove tokens that match a very specific pattern, according to the match type specified in `value type`. So if your match does not contain any wildcard (or regular expression special match codes) then the fixed match to words will not filter out words that contain numerals, units, ordinal abbreviations, etc.

```r
require(quanteda)
# Loading required package: quanteda
# quanteda version 0.9.9.60
# Using 7 of 8 cores for parallel computing

txt <- "00am 1-cent 1-mile 1,000-plus 1.4-liter 10-foot 107th 10g"
toks <- tokens(txt, 
               remove_numbers = TRUE, 
               remove_punct = TRUE, 
               remove_hyphens = TRUE)
toks
# tokens from 1 document.
# Component 1 :
# [1] "00am"  "cent"  "mile"  "plus"  "liter" "foot"  "107th" "10g"  

tokens_remove(toks, c("am", "th", "g"))
# tokens from 1 document.
# Component 1 :
# [1] "00am"  "cent"  "mile"  "plus"  "liter" "foot"  "107th" "10g"  
```

**Comment by Monduiz** [comment]
This is interesting. Some words that your example removed, were not in my corpus. I will test more and post in the SO channel. Thanks for the explanation!
