### ISSUE TITLE
Error in fetch(key)

### ISSUE THREAD

**Issue by Monduiz** [kbenoit/quanteda#734]
I installed from GitHub two days ago and I get these errors intermittently. I cant load vignettes with ?tokens (e.g.). Also, the error popups at times.

Full message: 

Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/quanteda/help/quanteda.rdb' is corrupt

R version 3.4.0 (2017-04-21)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

**Comment by kbenoit** [comment]
Hi - this is not something we can diagnose without more information. `sessionInfo()`? Is this R, or Rstudio? At what point does the error happen? 

Also I'm not sure what you mean by 

> I cant load vignettes with ?tokens (e.g.).

**Comment by Monduiz** [comment]
Sorry, I left out some things: this is in RStudio 1.0.143 and I have quanteda 0.9.9-59

When I type ?token I get: Error retrieving help. R Code execution error. and the error mentioned above: Error in fetch(key) : 
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.4/Resources/library/quanteda/help/quanteda.rdb' is corrupt

This is true for any quanteda functions.

**Comment by kbenoit** [comment]
Impossible to tell what is happening here, but sometimes RStudio gets stuck when source packages have been installed when the package existed already (or was attached already). See http://stackoverflow.com/questions/30424608/error-in-fetchkey-lazy-load-database. Not really a **quanteda** issue, rather an R/RStudio issue.
