### ISSUE TITLE
dfm stemming issue 

### ISSUE THREAD

**Issue by 02** [kbenoit/quanteda#74]
Hi,
Do I understand correctly that I should expect stemming when I run dfm with stem=TRUE? 

When I do
<code>dcorp <- dfm(rfc,groups="author",ignoredFeatures=stopwords("english"), stem=TRUE)
topfeatures(dcorp)</code>

<code>  women    people      like       men  feminism      just        gt  feminist feminists     think</code>
<code>     5475      4548      4487      4428      4330      4111      3891      3746      3335      3099 </code>

What confuses me here is the word "feminists". Shouldn't that word have been stemmed to "feminist"?
Because:
<code>wordstem("feminists")</code>
<code>[1] feminist</code>

Sorry if I am misunderstanding something basic, I'm just trying to figure out the system. :)

**Comment by kbenoit** [comment]
I just pushed a fix, in 0.9.0.5.  Now it works:

    txt <- "women people like men feminism just gt feminist feminists think"
    wordstem(tokenize(txt))
    ## tokenizedText object from 1 document.
    ## Component 1 :
    ##  [1] "women"    "peopl"    "like"     "men"      "femin"    "just"     "gt"       "feminist" "feminist" "think"   
    dfm(txt, stem = TRUE, verbose = FALSE)
    ## Document-feature matrix of: 1 document, 9 features.
    ## 1 x 9 sparse Matrix of class "dfmSparse"
    ##       features 
    ## docs    women peopl like men femin just gt feminist think
    ##   text1     1     1    1   1     1    1  1        2     1
