### ISSUE TITLE
tokens_select not selecting ngrams

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#740]
I thought we had addressed this already, but maybe this is part of #719.

### for tokens

Define two sets of tokens, simple unigrams and space-separated bigrams:
```r
(toks <- tokens("a b c d e f g"))
# tokens from 1 document.
# Component 1 :
# [1] "a" "b" "c" "d" "e" "f" "g"

(toks2 <- tokens_ngrams(toks, n = 2, concatenator = " "))
# tokens from 1 document.
# Component 1 :
# [1] "a b" "b c" "c d" "d e" "e f" "f g"
```

Then the first works, but the second fails. I'd like the second to work the same as the first.
```r
tokens_select(toks, c("a", "e", "g"))
# tokens from 1 document.
# Component 1 :
# [1] "a" "e" "g"

tokens_select(toks2, c("a b", "d e", "f g"))
# tokens from 1 document.
# Component 1 :
# character(0)
```

### for dfms 

The behaviour is correct for dfms already formed, but incorrect when forming, because I think `tokens_select()` is called before creating the dfm and then using `dfm_select()` inside `dfm()`.
```r
dfm(toks2, select = c("a b", "d e", "f g"))
# NULL

dfm_select(dfm(toks2), c("a b", "d e", "f g"))
# Document-feature matrix of: 1 document, 3 features (0% sparse).
# 1 x 3 sparse Matrix of class "dfmSparse"
#        features
# docs    a b d e f g
#   text1   1   1   1
```

**Comment by koheiw** [comment]
You have to like this to remove ngrams separated by spaces:
```r
tokens_select(toks2, list("a b", "d e", "f g"))
```
if the input is a vector, they are multi-word features.

**Comment by kbenoit** [comment]
Here's an example of awkward syntax for using this structure: http://stackoverflow.com/questions/44030170/compute-chi-square-value-between-ngrams-and-documents-with-quanteda/.

Too complicated?

**Comment by koheiw** [comment]
You do not need to do make a list. Just do like this:
```r
corp_example <- data_corpus_inaugural
corp_example <- corpus_subset(corp_example, Year > 1960)

# this will remove punctuation and numbers
toks_example <- tokens(corp_example, remove_punct = TRUE, remove_numbers = TRUE)

# find and score chi^2 bigrams
coll2 <- textstat_collocations(toks_example, method = "chi2", max_size = 2)
head(coll2, 10)

# collocations (faster)
toks_example_comp <- tokens_compound(toks_example, coll2[1:100])
toks_example_comp[[1]][1:20]

# character vector
toks_example_comp2 <- tokens_compound(toks_example, coll2$collocation[1:100])
toks_example_comp2[[1]][1:20]
```

**Comment by koheiw** [comment]
More tricky case,
```r
# ngrams are joined with whitespaces
toks_example_comp3 <- tokens_compound(toks_example, coll2[1:100], concatenator = ' ')
toks_example_comp3[[1]][1:20]

# features must be a list
toks_example_comp4 <- tokens_select(toks_example_comp3, as.list(coll2$collocation[1:100]))
toks_example_comp4[[1]][1:20]
```

**Comment by kbenoit** [comment]
The original example still does not work:

```r
toks2
# tokens from 1 document.
# Component 1 :
# [1] "a b" "b c" "c d" "d e" "e f" "f g"
 
tokens_select(toks2, c("a b", "d e", "f g"))
# tokens from 1 document.
# Component 1 :
# character(0)
```

I don't think it ought be a list for the features, since it's not for `dfm_select()`. Or we stick more closely to our definitions, that tokens are not features, only dfms have features, and define those differently. This is part of the broader issue in #719.

**Comment by koheiw** [comment]
Please have a look at #804 and comment on features.R. Otherwise I cannot do anything with this.

**Comment by kbenoit** [comment]
will do.

**Comment by kbenoit** [comment]
Fixed in #820

**Comment by cyberosa** [comment]
Hello,
I am new using quanteda. After creating three dfms: one for unigrams, one for bigrams and one for trigrams in my corpus, I used the docfreq() function to perform some frequency analysis and filtered the most frequent ones. Now I need to find bigrams and trigrams beginning with a specific pattern. I wonder if it is possible to select tokens by providing a regex expression as pattern. For instance if I want to find all bigrams that begin with "a"
`# let's suppose that our bigrams are: "a_b", "a_c" and "b_c"
bigrams <- docfreq(bigramDFM)
# How to find all bigrams beginning with "a"?
`
You provided this example:
`dfm(toks2, select = c("a b", "d e", "f g"))`

But that works only if you know the exact bigrams you are looking for. How can I select only bigrams or trigrams that follow a condition?

Thanks in advance.

**Comment by koheiw** [comment]
We are discussing this issue on #1018, but it can be done fairly simply in your case. Try

```r
dfm(toks2, select = c("a *"))
```

**Comment by cyberosa** [comment]
Many thanks. Well my case is a bit more complicated that the example beginning with "a"... I just tried to adapt my question to the examples of this thread. So if I want to traverse the unigram tokens and for each unigram token I want to find the list of bigrams beginning with that unigram whose value is only known in runtime?
`
unigramFreq <- docfreq(unigramDFM) 
// this is transformed into a data frame with 2 variables, word and freq
unigramFreq <- unigramFreq[order(unigramFreq$freq, decreasing = TRUE), ]
// I know that dfm_sort can reorder the frequencies but I do not know yet how to traverse a DFM
for (i in 1:nrow(unigramFreq) ) {
    unigram1 <- unigramFreq[i,]
    filterCondition1<- paste("^",unigram$word, "\\s", sep="")
    bigramsForUnigram1 <- dfm(bigramDFM, select = filterCondition, valuetype = "regex")
}`

Should that work? Btw I have a couple of questions more (one I put it inside the code) ^^

**Comment by koheiw** [comment]
Try this
```r
mt <- dfm(data_corpus_inaugural)
feat <- head(sort(docfreq(mt), decreasing = TRUE), 100)
pat <- paste0(names(feat), '_*')

mt_bi <- dfm(data_corpus_inaugural, ngrams = 2)
mt_bi <- dfm_select(mt_bi, pat)
```
