### ISSUE TITLE
textstat_ca is not working

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#745]
I found `textmodel_ca` does not work even with a moderate size dfm.

```r
load("/home/kohei/Documents/Brexit/Analysis/data_corpus_guardian.RData")
toks <- tokens(corpus_subset(data_corpus_guardian, format(date, '%Y') == '2012'))
mx <- dfm(toks)

dim(mx) # 19489 114543

model <- quanteda::textmodel_ca(mx, nd = 2, sparse = FALSE)
# Error: cannot allocate vector of size 16.6 Gb 

model <- quanteda::textmodel_ca(mx, nd = 2, sparse = TRUE)
# Error in cacpp(P, threads, residual_floor/sqrt(n)) : std::bad_alloc 
```
I also wonder why it uses **RSpectra** instead of **irlba**, the most efficient SVD engine in R.
```r
microbenchmark::microbenchmark(
    RSpectra::svds(mx, 2),
    irlba::irlba(mx, 2), 
times = 10)

# Unit: milliseconds
#                  expr       min        lq      mean   median        uq        max neval
# RSpectra::svds(mx, 2) 5768.2854 6595.1404 7797.6094 6818.610 8037.5398 11896.4191    10
#   irlba::irlba(mx, 2)  221.2775  334.0662  452.5751  357.719  390.0601   973.9994    10
```

**Comment by HaiyanLW** [comment]
What's the object size of your matrix `mx`? 

Regarding the choice of SVD method, I've compared `RSpectra` to `rsvd` and although `rsvd` is much faster the accuracy is not satisfied in this problem. I didn't try `irlba`, maybe can do it.

**Comment by HaiyanLW** [comment]
The `dfm` might be several gbs (`dim(mx)  19489 114543`). That's why the dense version complaint about the size over 16G. The data handled in the sparse version will also be big - depending on the threshold, it can be up to several times of the size of the `dfm`.

**Comment by koheiw** [comment]
Sorry for not replying earlier. The `dfm` is only 77MB. You have the Guardian corpus, so please try on you machine.
```r
print(object.size(mx), unit = 'mb') # 77.7 Mb
```

**Comment by koheiw** [comment]
Reading the difference between outputs of *Rspectra* and *iralba*, they are very close to identical:

```r
res1 <- RSpectra::svds(mx, 2)
res2 <- irlba::irlba(mx, 2)

vec1 <- as.vector(res1$v * res1$d)
vec2 <- as.vector(res2$v * res2$d)

cor(vec1, vec2) # 1
```
Here is an interesting article on the difference:
https://bwlewis.github.io/irlba/comparison.html

**Comment by HaiyanLW** [comment]
Thanks, fixed the bug.
The performance of these packages may subject to different applications, see [this comparison](https://spectralib.org/performance.html). Anyway, the `svds()` function is not the bottle neck of the performance of `textmodel_ca`, you can choose to change one line code if you really prefer `irlba`.

**Comment by kbenoit** [comment]
@kohei can you check your original application now using the new `master` and see if that fixed it? If so, please close the issue.

**Comment by koheiw** [comment]
I do not see any difference. This function still takes a huge amounts memory for the small matrix. You can test this yourself with the data that I shared with both of you.
```r
> library(quanteda)
> load("/home/kohei/Documents/Brexit/Analysis/data_corpus_guardian.RData")
> toks <- tokens(corpus_subset(data_corpus_guardian, format(date, '%Y') == '2012'))
> mx <- dfm(toks)
> 
> dim(mx) # 19489 114543
[1]  19489 114543
> 
> model <- quanteda::textmodel_ca(mx, nd = 2, sparse = FALSE)
 Show Traceback
 
 Rerun with Debug
 Error: cannot allocate vector of size 8.3 Gb > # Error: cannot allocate vector of size 16.6 Gb

> object.size(mx)
81484784 bytes
> print(object.size(mx), unit = 'MB')
77.7 Mb

> gc()
            used  (Mb) gc trigger    (Mb)   max used    (Mb)
Ncells   2514585 134.3    3886542   207.6    3886542   207.6
Vcells 107095537 817.1 1805251219 13773.0 2356855486 17981.4
```

**Comment by kbenoit** [comment]
And if you try it using `sparse = TRUE`?

**Comment by HaiyanLW** [comment]
Yes, has to use `sparse = TRUE`,  otherwise the `dfm` is coerced to a dense matrix of size of `1948x114543`. The updated `sparse` version works for this `guardian` data when I tested.

**Comment by koheiw** [comment]
Is the latest sparse version in the master? My tests with `sparse = TRUE` ended up with a crash, exhausting 7.6GB RAM and 17.6GB disk swap.

**Comment by HaiyanLW** [comment]
It's in master now.

**Comment by HaiyanLW** [comment]
@koheiw Did you use the latest master? try to increase the `residual_floor` to 0.2 or 0.5 to test the feasibility.

**Comment by koheiw** [comment]
It is quanteda version 0.9.9.74. I think this is the latest.

**Comment by koheiw** [comment]
@HaiyanLW residual_floor = 0.5 worked:
```r
> load("/home/kohei/Documents/Brexit/Analysis/data_corpus_guardian.RData")
> toks <- tokens(corpus_subset(data_corpus_guardian, format(date, '%Y') == '2012'))
> mx <- dfm(toks)
>  
> model <- quanteda::textmodel_ca(mx, nd = 2, residual_floor = 0.5, sparse = TRUE)
> str(model)
List of 15
 $ sv        : num [1:2] 0.583 0.522
 $ nd        : num 2
 $ rownames  : chr [1:19489] "text1" "text2" "text3" "text4" ...
 $ rowmass   : num [1:19489] 7.91e-05 2.90e-05 4.35e-05 6.15e-05 7.96e-05 ...
 $ rowdist   : num [1:19489] 13.2 19.4 10.3 13.2 14.7 ...
 $ rowinertia: num [1:19489] 0.01381 0.01098 0.00461 0.01064 0.01722 ...
 $ rowcoord  : num [1:19489, 1:2] -1.1 -1.32 -1.01 -1.11 -1.03 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:19489] "text1" "text2" "text3" "text4" ...
  .. ..$ : chr [1:2] "Dim1" "Dim2"
 $ rowsup    : logi(0) 
 $ colnames  : chr [1:114543] "google" "and" "apple" "are" ...
 $ colmass   : num [1:114543] 7.56e-05 1.91e-02 7.81e-05 4.11e-03 4.29e-05 ...
 $ coldist   : num [1:114543] 11.589 0.341 11.172 0.871 6.414 ...
 $ colinertia: num [1:114543] 0.01016 0.00222 0.00974 0.00312 0.00177 ...
 $ colcoord  : num [1:114543, 1:2] -1.76311 -0.00162 -1.89802 0.02607 -1.66356 ...
  ..- attr(*, "dimnames")=List of 2
  .. ..$ : chr [1:114543] "google" "and" "apple" "are" ...
  .. ..$ : chr [1:2] "Dim1" "Dim2"
 $ colsup    : logi(0) 
 $ call      : language textmodel_ca.dfm(x = mx, nd = 2, sparse = TRUE, residual_floor = 0.5)
 - attr(*, "class")= chr [1:3] "textmodel_ca_fitted" "ca" "list"

> gc()
            used  (Mb) gc trigger   (Mb)  max used   (Mb)
Ncells   2318799 123.9    3886542  207.6   3886542  207.6
Vcells 107107553 817.2  350314838 2672.7 386267578 2947.0

```

**Comment by HaiyanLW** [comment]
That's it. `residual_floor` with a larger value will reduce memory and time cost. It might work with `0.2`.

**Comment by koheiw** [comment]
0.2 works, though it takes 10GB RAM.
```r


> model <- quanteda::textmodel_ca(mx, nd = 2, residual_floor = 0.2, sparse = TRUE)
> gc()
            used  (Mb) gc trigger   (Mb)   max used    (Mb)
Ncells   2325076 124.2    3886542  207.6    2838066   151.6
Vcells 107121171 817.3 1061594718 8099.4 1323937091 10100.9
```
`textplot_scale1d()` looks funny, but you might say this is my data's problem.
```r
> textplot_scale1d(model)
Warning message:
Removed 19489 rows containing missing values (geom_pointrange). 
```
![rplot](https://user-images.githubusercontent.com/6572963/27547912-45f1b5a4-5a8f-11e7-82c5-4ecbf3f9ef2a.png)

**Comment by HaiyanLW** [comment]
Here's the `textplot_scale1d(model)' for `residual_floor = 0.5', 
![image](https://user-images.githubusercontent.com/20244806/27588049-b03be060-5b3e-11e7-9e97-8f1acda2f414.png)
You should always remove unessential features when you carry out your own data analysis, but I don't think here's the place to discuss it.

**Comment by koheiw** [comment]
It is a nice curve. Why don't you residual_floor = 0.5 and sparse = TRUE default?
