### ISSUE TITLE
Limits on nrow and ncol when printing to screen

### ISSUE THREAD

**Issue by thomasd2** [kbenoit/quanteda#756]
It seems like matrices with more than 20 rows or columns are not printed when typing the name of the object. Is there a reason why - the limit seems low, I often want to look for instance at a matrix with 50 rows and 5 columns. I can use View() but that requires more typing. Thanks!

**Comment by kbenoit** [comment]
See `?print.dfm`. That involves even more typing I am afraid! If you have suggestions on how this would be better set, we'd be happy to hear it. Could add to global quanteda options, for instance.

**Comment by thomasd2** [comment]
Thanks. Some solution allowing to set this according to personal tastes when loading the package or even permanently (through specification in Rprofile??) would be great.

**Comment by kbenoit** [comment]
How about

```
quanteda_print_dfm_nrow
quanteda_print_dfm_nfeature
```
as global options?
