### ISSUE TITLE
Error importing updated TM Vcorpus 

### ISSUE THREAD

**Issue by louislouisloui** [kbenoit/quanteda#758]
Hi,

I get the follozing error message important a Vcorpus: Error: nrow(docvars) == length(x) is not TRUE

As far as I could see, it comes from the condition: stopifnot(nrow(docvars) == length(x)) which comes from the user-supplied document-level lines of code.

My VCorp is an updated Vcorp using the extractor content():
content(corpus[[1]]) <- content(corpus[[1]])[1:10]
I need to do this in order to chunk my corpus.

Otherwise, thanks for the great package ;)

**Comment by kbenoit** [comment]
Thanks for the report. Can you pls supply a reproducible error? Can you upload or supply a link to the VCorpus object?

**Comment by louislouisloui** [comment]
Well I basically import 3 texts as a tm Vcorpus for the cleaning features it offers
`corpus <- VCorpus(DirSource("./final/en_US/", encoding = "UTF-8"), readerControl = list(language = 'en'))`

It is very large though so I sample it : 
`corpus_chunk <- corpus
content(corpus_chunk[[1]]) <- content(corpus[[1]])[1:10000}
content(corpus_chunk[[2]]) <- content(corpus[[2]])[1:10000}
content(corpus_chunk[[3]]) <- content(corpus[[1]])[3:10000}`

Then I simply try to convert it as a quanteda corpus cause the perforomance of the dfm are really intersting: 
`quanteda::corpus(corpus_chunk)`

And i get the error :

> Error: nrow(docvars) == length(x) is not TRUE

sessioninfo:

> Session info --------------------------------------------------------------------------------------------
>  setting  value                       
>  version  R version 3.3.2 (2016-10-31)
>  system   x86_64, darwin13.4.0        
>  ui       RStudio (1.0.136)           
>  language (EN)                        
>  collate  en_US.UTF-8                 
>  tz       America/Sao_Paulo           
>  date     2017-05-28                  
> 
> Packages ------------------------------------------------------------------------------------------------
>  package      * version  date       source                           
>  assertthat     0.1      2013-12-06 CRAN (R 3.3.0)                   
>  base         * 3.3.2    2016-10-31 local                            
>  codetools      0.2-15   2016-10-05 CRAN (R 3.3.2)                   
>  colorspace     1.3-2    2016-12-14 CRAN (R 3.3.2)                   
>  curl           2.3      2016-11-24 CRAN (R 3.3.2)                   
>  data.table     1.10.4   2017-02-01 CRAN (R 3.3.2)                   
>  datasets     * 3.3.2    2016-10-31 local                            
>  devtools     * 1.13.1   2017-05-13 CRAN (R 3.3.2)                   
>  digest         0.6.12   2017-01-27 CRAN (R 3.3.2)                   
>  doParallel   * 1.0.10   2015-10-14 CRAN (R 3.3.0)                   
>  fastmatch      1.1-0    2017-01-28 CRAN (R 3.3.2)                   
>  foreach      * 1.4.3    2015-10-13 CRAN (R 3.3.0)                   
>  ggplot2        2.2.1    2016-12-30 CRAN (R 3.3.2)                   
>  git2r          0.18.0   2017-01-01 CRAN (R 3.3.2)                   
>  graphics     * 3.3.2    2016-10-31 local                            
>  grDevices    * 3.3.2    2016-10-31 local                            
>  grid           3.3.2    2016-10-31 local                            
>  gtable         0.2.0    2016-02-26 CRAN (R 3.3.0)                   
>  httr           1.2.1    2016-07-03 CRAN (R 3.3.0)                   
>  iterators    * 1.0.8    2015-10-13 CRAN (R 3.3.0)                   
>  knitr          1.15.1   2016-11-22 CRAN (R 3.3.2)                   
>  lattice        0.20-34  2016-09-06 CRAN (R 3.3.2)                   
>  lazyeval       0.2.0    2016-06-12 CRAN (R 3.3.0)                   
>  Matrix         1.2-10   2017-04-28 CRAN (R 3.3.2)                   
>  memoise        1.1.0    2017-04-21 CRAN (R 3.3.2)                   
>  methods      * 3.3.2    2016-10-31 local                            
>  munsell        0.4.3    2016-02-13 CRAN (R 3.3.0)                   
>  NLP          * 0.1-10   2017-02-21 CRAN (R 3.3.2)                   
>  parallel     * 3.3.2    2016-10-31 local                            
>  plyr           1.8.4    2016-06-08 CRAN (R 3.3.0)                   
>  quanteda     * 0.9.9-65 2017-05-28 Github (kbenoit/quanteda@2e2c08a)
>  R6             2.2.0    2016-10-05 CRAN (R 3.3.0)                   
>  Rcpp           0.12.11  2017-05-22 cran (@0.12.11)                  
>  RcppParallel   4.3.20   2016-08-16 CRAN (R 3.3.0)                   
>  scales         0.4.1    2016-11-09 CRAN (R 3.3.2)                   
>  slam           0.1-40   2016-12-01 CRAN (R 3.3.2)                   
>  stats        * 3.3.2    2016-10-31 local                            
>  stringi        1.1.5    2017-04-07 cran (@1.1.5)                    
>  tibble         1.2      2016-08-26 CRAN (R 3.3.0)                   
>  tm           * 0.7-1    2017-03-02 CRAN (R 3.3.2)                   
>  tools          3.3.2    2016-10-31 local                            
>  utils        * 3.3.2    2016-10-31 local                            
>  withr          1.0.2    2016-06-20 CRAN (R 3.3.0)         


data set: https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip
I jsut us the en_US 3 files

**Comment by kbenoit** [comment]
Have you tried the **readtext** package?

**Comment by louislouisloui** [comment]
Well no ill take a look. But I know that a common problem is that they create one doc per line which lets tm cleaning features super slow. 
Is this an expected behavior this error? Couldn't I do anything on the corpus to make it compliant? I came with the idea of passing by a plaintextsocument but the corpus constructor interprets the meta data as a proper text and create a corpus of 2 texts in the end..

**Comment by kbenoit** [comment]
I think it works, but you are not sampling the documents correctly from the **tm** VCorpus object.  (I don't know how to do this either.)

```r
require(tm)
vcorpus <- VCorpus(DirSource("~/Downloads/final/en_US/", encoding = "UTF-8"), readerControl = list(language = 'en'))
vcorpus
## <<VCorpus>>
## Metadata:  corpus specific: 0, document level (indexed): 0
## Content:  documents: 3
require(quanteda)
corpus(vcorpus)
## Corpus consisting of 3 documents and 7 docvars.
```

This works better:
```r
require(readtext)
txt <- readtext("~/Downloads/final/en_US/en_US.blogs.txt")
data_corpus_enUSblogs <- corpus(txt)
data_corpus_enUSblogs
## Corpus consisting of 1 document and 0 docvars.

data_corpus_enUSblogs2 <- 
    corpus_segment(data_corpus_enUSblogs, what = "paragraph", delimiter = "\\n{1,2}")
data_corpus_enUSblogs2
## Corpus consisting of 899,288 documents and 0 docvars.
head(texts(data_corpus_enUSblogs2), 3)
## en_US.blogs.txt.1 
## "In the years thereafter, most of the Oil fields and platforms were named after pagan \"gods\"." 
## en_US.blogs.txt.2 
## "We love you Mr. Brown." 
## en_US.blogs.txt.3 
## "Chad has been awesome with the kids and holding down the fort while I work later than usual! The kids have been busy together playing Skylander on the XBox together, after Kyan cashed in his $$$ from his piggy bank. He wanted that game so bad and used his gift card from his birthday he has been saving and the money to get it (he never taps into that thing either, that is how we know he wanted it so bad). We made him count all of his money to make sure that he had enough! It was very cute to watch his reaction when he realized he did! He also does a very good job of letting Lola feel like she is playing too, by letting her switch out the characters! She loves it almost as much as him." 
```

**Comment by louislouisloui** [comment]
Thanks for the help. Well unfortunately this method creates as mnay docs as there are lines which becomes hard to process afterward

Thanks !
