### ISSUE TITLE
Documentation for textstat_simil/textstat_dist

### ISSUE THREAD

**Issue by thomasd2** [kbenoit/quanteda#759]
It would be good to have some references or explanations how the similarity/distance measures are calculated, since not all of them are straightforward. For instance, what is the difference between chisquared and chisquared2? Also, some of the measures are defined both for count vectors and for binary vectors - which one is used then? Thanks!

**Comment by HaiyanLW** [comment]
Using real value or binary method depends on your data type. 

The functionality of most of the `quanteda` similarity methods is same as `proxy` package, the exceptions are:
- [chisquared2](https://github.com/kbenoit/quanteda/blob/master/R/textstat_dist.R#L354-L356), as you mentioned
- [chisquared](https://github.com/kbenoit/quanteda/blob/master/R/textstat_dist.R#L296-L300) and the [test](https://github.com/kbenoit/quanteda/blob/master/R/textstat_dist.R#L296-L300)
-  [Kullback-Leibler](https://github.com/kbenoit/quanteda/blob/master/R) and [test] (https://github.com/kbenoit/quanteda/blob/master/R) (not against `proxy`, as `proxy` generates `NA`s)
- [Hamming](https://github.com/kbenoit/quanteda/blob/master/R/textstat_dist.R#L264-L266) and 
 [test](https://github.com/kbenoit/quanteda/blob/master/tests/testthat/test-textstat_dist.R#L202): not in `proxy`, we tested against `e1071` 

We will put up a summary. Thanks.

**Comment by thomasd2** [comment]
I'm still puzzled. Sorry if this is a stupid question, but I'm not so familiar with these measures.
I'm wondering what happens 'under the hood' with that function and if I am warned if I do anything that doesn't make sense. If I specify a binary similarity measure like Jaccard and feed a matrix of counts, is this internally converted to a boolean matrix befor calculating the similarity? Thanks.

**Comment by HaiyanLW** [comment]
Yes, it will be converted to a boolean matrix first.
