### ISSUE TITLE
Consider only comma separated words as different features while creating dfm 

### ISSUE THREAD

**Issue by FinScience** [kbenoit/quanteda#760]
Hi,

I am not sure whether this feature is present. But it would be great to have this. Below is a reproducible code

         df1 = data.frame(ID = c(1,2,3), Keyword = c("good music, wallet, point to be noted", 
                                            "tiger, stone cold,wallet",
                                            "chalk board, board, leather wallet"))
         df1$Keyword = as.character(df1$Keyword)
         text_corp1 = corpus(df1[,2])

          mydfm1 = dfm(text_corp1, removePunct = F)

          mydfm1

                 features
          docs    good music , wallet point to be noted tiger stone cold chalk board leather
          text1    1     1 2      1     1  1  1     1     0     0    0     0     0       0
          text2    0     0 2      1     0  0  0     0     1     1    1     0     0       0
          text3    0     0 2      1     0  0  0     0     0     0    0     1     2       1

The required dfm should be as follows

                 features
          docs    "good music"  "wallet" "point to be noted" "tiger" "stone cold" "chalk board" "board" 
                     "leather wallet"
          text1    1 1 1 0 0 0 0 0
          text2    0 1 0 1 1 0 0 0
          text3    0 0 0 0 0 1 1 1

**Comment by kbenoit** [comment]
There is a way, but it's a bit roundabout. Maybe @koheiw has a more elegant solution?

```r
require(quanteda)
## Loading required package: quanteda
## quanteda version 0.9.9.65
## Using 7 of 8 cores for parallel computing
## 
## Attaching package: ‘quanteda’
##
## The following object is masked from ‘package:utils’:
## 
##     View

keyword <- c("good music, wallet, point to be noted", 
             "tiger, stone cold,wallet",
             "chalk board, board, leather wallet")

mwe <- unlist(strsplit(keyword, "\\s*,\\s*"))
mwe
## [1] "good music"        "wallet"            "point to be noted" "tiger"             "stone cold"        "wallet"           
## [7] "chalk board"       "board"             "leather wallet"  

txt <- c(d1 = "I put a stone cold board in my leather wallet.",
         d2 = "A tiger with good music is a point to be noted.")

toks <- tokens(txt, remove_punct = TRUE)
(toks <- tokens_compound(toks, mwe))
## tokens from 2 documents.
## d1 :
## [1] "I"              "put"            "a"              "stone_cold"     "board"          "in"             "my"            
## [8] "leather_wallet"
## 
## d2 :
## [1] "A"                 "tiger"             "with"              "good_music"        "is"                "a"                
## [7] "point_to_be_noted"

dfm_select(dfm(toks), "*_*")
## Document-feature matrix of: 2 documents, 4 features (50% sparse).
## 2 x 4 sparse Matrix of class "dfmSparse"
##     features
## docs good_music point_to_be_noted stone_cold leather_wallet
##   d1          0                 0          1              1
##   d2          1                 1          0              0
```

**Comment by juoliveiracunha** [comment]
Any updates on this?

**Comment by kbenoit** [comment]
Thanks for chasing us on this. This is actually easy and works already in v1.5.2, using an external tokenizer and then creating a tokens object from this.

``` r
library("quanteda")
## Package version: 1.5.2

txt <- c(
  "good music, wallet, point to be noted",
  "tiger, stone cold,wallet",
  "chalk board, board, leather wallet"
)

tokenizers::tokenize_regex(txt, pattern = ",") %>%
  as.tokens() %>%
  dfm()
## Document-feature matrix of: 3 documents, 9 features (66.7% sparse).
## 3 x 9 sparse Matrix of class "dfm"
##        features
## docs    good music  wallet  point to be noted tiger  stone cold wallet
##   text1          1       1                  1     0           0      0
##   text2          0       0                  0     1           1      1
##   text3          0       0                  0     0           0      0
##        features
## docs    chalk board  board  leather wallet
##   text1           0      0               0
##   text2           0      0               0
##   text3           1      1               1
```
 In the forthcoming v2 we are working on making the tokens constructor even more modular like this, and separating the token segmentation ("tokenization") functions from the `tokens()` constructor. But for your use case this should work fine as shown above.

**Comment by kbenoit** [comment]
The best way to deal with this issue would be to use a better (smarter) tokenizer trained on a French language model. In forthcoming quanteda v2, we are further separating the "tokenization" function of token segmentation from the `tokens()` constructor. But it's already possible in v1.5.2 using **spacyr**, which has a language model for French.

``` r
library("quanteda")
## Package version: 1.5.2

library("spacyr")
# spacy_download_langmodel(model = "fr")
spacy_initialize(model = "fr")
## Found 'spacy_condaenv'. spacyr will use this environment
## successfully initialized (spaCy Version: 2.1.4, language model: fr)
## (python options: type = "condaenv", value = "spacy_condaenv")

txt <- "C'est vrai qu'on aime quanteda."
spacy_tokenize(txt) %>%
  as.tokens()
## tokens from 1 document.
## text1 :
## [1] "C'"       "est"      "vrai"     "qu'"      "on"       "aime"     "quanteda"
## [8] "."
```

If you want the apostrophes removed, simply do this prior to constructing the tokens:
```r
spacy_tokenize(txt) %>%
  lapply(stringi::stri_replace_all_fixed, "'", "") %>%
  as.tokens()
## tokens from 1 document.
## text1 :
## [1] "C"        "est"      "vrai"     "qu"       "on"       "aime"     "quanteda"
## [8] "."
```
