### ISSUE TITLE
'docnames' argument 

### ISSUE THREAD

**Issue by gabrieldaldegan** [kbenoit/quanteda#762]
When creating a corpus object, document names are not properly assigned. Instead, I only get text index: text1, text2...

**Comment by kbenoit** [comment]
We need more of a reproducible example than that... `text1`, `text2`, etc are the defaults if the object from which you construct the corpus has no named elements or document names.

**Comment by gabrieldaldegan** [comment]
Thanks for the quick reply!

I'm ingesting several papers in pdf using TM/XPDF, all of which have document names. When creating a quanteda's corpus, through 'myCorpus <- quanteda::corpus(papers, docnames = names(papers))', or without the docnames argument, I get text1, text2, etc

**Comment by kbenoit** [comment]
`str(papers)` ?

**Comment by gabrieldaldegan** [comment]
> str(papers)
List of 8
 $ arees-informatics-2006-reprint.pdf                                                              :List of 2
  ..$ content: chr [1:1405] "Annu. Rev. Ecol. Evol. Syst. 2006.37:519-544. Downloaded from arjournals.annualreviews.org  Annu. Rev. Ecol. Ev"| __truncated__ "   by 66.190.242.187 on 04/02/07. For personal use only.                                                       "| __truncated__ "                                                                                            First published onl"| __truncated__ "                                                                                            on August 14, 2006 "| __truncated__ ...
  ..$ meta   :List of 7
  .. ..$ author       : chr "Matthew B. Jones,1 Mark P. Schildhauer,1 O.J. Reichman,1 and Shawn Bowers2"
  .. ..$ datetimestamp: POSIXlt[1:1], format: "2015-06-26 18:04:21"
  .. ..$ description  : chr "Annu. Rev. Ecol. Evol. Syst. 2006.37:519-544"
  .. ..$ heading      : chr "The New Bioinformatics: Integrating Ecological Data from the Gene to the Biosphere"
  .. ..$ id           : chr "arees-informatics-2006-reprint.pdf"
  .. ..$ language     : chr "en"
  .. ..$ origin       : NULL
  .. ..- attr(*, "class")= chr "TextDocumentMeta"
  ..- attr(*, "class")= chr [1:2] "PlainTextDocument" "TextDocument"
 $ Borer et al 2009 Bull ESA_Effective Data Management.pdf                                         :List of 2
  ..$ content: chr [1:472] "                                 !\"#$%&'%()#*+',-,%&#." "" "       !\"#$%$&'(#)*%\"#+\",#+\"($%*&-%.*/%&0&1+#*+%.1&.$%)2%(&'\"*),)+3%.*/%0&(\")/),)+34%!)5#'$%0.3%" "       1.*+&%21)0%\".1/-.1&%.*/%$)2(-.1&6%()%$(.(#$(#'.,%.*.,3$&$%.*/%(&'\"*),)+#&$%(\".(%')7,/%8&%" ...
  ..$ meta   :List of 7
  .. ..$ author       : chr "kbailey"
  .. ..$ datetimestamp: POSIXlt[1:1], format: "2009-04-03 17:37:19"
  .. ..$ description  : NULL
  .. ..$ heading      : chr "i0012-9623-90-2-205.pdf"
  .. ..$ id           : chr "Borer et al 2009 Bull ESA_Effective Data Management.pdf"
  .. ..$ language     : chr "en"
  .. ..$ origin       : chr "Adobe Acrobat 8.0"
  .. ..- attr(*, "class")= chr "TextDocumentMeta"
  ..- attr(*, "class")= chr [1:2] "PlainTextDocument" "TextDocument"
 $ Fegraus-esa_bulletin_eml_ms_07_2005.pdf                                                         :List of 2
  ..$ content: chr [1:600] "D E PA R T M E N T S" "" "Emerging Technologies" "" ...
  ..$ meta   :List of 7
  .. ..$ author       : NULL
  .. ..$ datetimestamp: POSIXlt[1:1], format: "2005-07-11 09:35:10"
  .. ..$ description  : NULL
  .. ..$ heading      : chr ""
  .. ..$ id           : chr "Fegraus-esa_bulletin_eml_ms_07_2005.pdf"
  .. ..$ language     : chr "en"
  .. ..$ origin       : chr "Adobe InDesign 2.0"
  .. ..- attr(*, "class")= chr "TextDocumentMeta"
  ..- attr(*, "class")= chr [1:2] "PlainTextDocument" "TextDocument"
 $ Harris_2017_Environ._Res._Lett._12_024012.pdf                                                   :List of 2
  ..$ content: chr [1:692] "Home Search Collections Journals About Contact us My IOPscience" "" "          Using spatial statistics to identify emerging hot spots of forest loss" "" ...
  ..$ meta   :List of 7
  .. ..$ author       : chr "Nancy L Harris"
  .. ..$ datetimestamp: POSIXlt[1:1], format: "2017-02-07 11:23:36"
  .. ..$ description  : chr "Environmental Research Letters, 12 (2017) 1-13. https://doi.org/10.1088/1748-9326/aa5a2f"
  .. ..$ heading      : chr "Using spatial statistics to identify emerging hot spots of forest loss"
  .. ..$ id           : chr "Harris_2017_Environ._Res._Lett._12_024012.pdf"
  .. ..$ language     : chr "en"
  .. ..$ origin       : chr [1:2] "Arbortext Advanced Print Publisher 11.0.2924/W Unicode" "Acrobat Distiller 7.0 (Windows); modified using iText\U3e65613c 5.5.10 \U3e39613c2000-2015 iText Group NV (AGPL-version)"
  .. ..- attr(*, "class")= chr "TextDocumentMeta"
  ..- attr(*, "class")= chr [1:2] "PlainTextDocument" "TextDocument"
 $ Heidorn_2008_Shedding Light on the Dark Data in the Long Tail of Science.pdf                    :List of 2
  ..$ content: chr [1:998] "Shedding Light on the Dark Data in the Long Tail of Science" "" "P. Bryan Heidorn" "Library Trends, Volume 57, Number 2, Fall 2008, pp. 280-299 (Article)" ...
  ..$ meta   :List of 7
  .. ..$ author       : NULL
  .. ..$ datetimestamp: POSIXlt[1:1], format: "2009-02-12 11:21:56"
  .. ..$ description  : NULL
  .. ..$ heading      : NULL
  .. ..$ id           : chr "Heidorn_2008_Shedding Light on the Dark Data in the Long Tail of Science.pdf"
  .. ..$ language     : chr "en"
  .. ..$ origin       : chr "Adobe InDesign CS3 (5.0.4)"
  .. ..- attr(*, "class")= chr "TextDocumentMeta"
  ..- attr(*, "class")= chr [1:2] "PlainTextDocument" "TextDocument"
 $ MORTON_et_al-2008-Global_Change_Biology.pdf                                                     :List of 2
  ..$ content: chr [1:860] "Global Change Biology (2008) 14, 2262\xad2275, doi: 10.1111/j.1365-2486.2008.01652.x" "" "Agricultural intensification increases deforestation fire" "activity in Amazonia" ...
  ..$ meta   :List of 7
  .. ..$ author       : NULL
  .. ..$ datetimestamp: POSIXlt[1:1], format: "2008-08-25 09:36:52"
  .. ..$ description  : NULL
  .. ..$ heading      : chr "Agricultural intensification increases deforestation fire activity in Amazonia"
  .. ..$ id           : chr "MORTON_et_al-2008-Global_Change_Biology.pdf"
  .. ..$ language     : chr "en"
  .. ..$ origin       : chr "3B2 Total Publishing System 8.07f/W"
  .. ..- attr(*, "class")= chr "TextDocumentMeta"
  ..- attr(*, "class")= chr [1:2] "PlainTextDocument" "TextDocument"
 $ Ohara et al 2016_Aligning marine species range data to better serve science and conservation.pdf:List of 2
  ..$ content: chr [1:712] "                                                      RESEARCH ARTICLE" "" "                                                      Aligning marine species range data to better" "                                                      serve science and conservation" ...
  ..$ meta   :List of 7
  .. ..$ author       : chr "Casey C. O'Hara, Jamie C. Afflerbach, Courtney Scarborough, Kristin Kaschner, Benjamin S. Halpern"
  .. ..$ datetimestamp: POSIXlt[1:1], format: "2017-04-12 13:13:34"
  .. ..$ description  : NULL
  .. ..$ heading      : chr "Aligning marine species range data to better serve science and conservation"
  .. ..$ id           : chr "Ohara et al 2016_Aligning marine species range data to better serve science and conservation.pdf"
  .. ..$ language     : chr "en"
  .. ..$ origin       : chr [1:2] "Arbortext Advanced Print Publisher 11.0.2857/W Unicode-x64" "PDFlib+PDI 8.0.2p1 (C++/Win64); modified using iTextSharpTM 5.5.3 \U3e39613c2000-2014 iText Group NV (AGPL-version)"
  .. ..- attr(*, "class")= chr "TextDocumentMeta"
  ..- attr(*, "class")= chr [1:2] "PlainTextDocument" "TextDocument"
 $ peerj-preprints-549.pdf                                                                         :List of 2
  ..$ content: chr [1:908] "PrePrints  The Tao of Open Science for Ecology" "" "           Stephanie E. Hampton, Center for Environmental Research, Education and Outreach," "              Washington State University, Pullman WA 99164 s.hampton@wsu.edu" ...
  ..$ meta   :List of 7
  .. ..$ author       : chr "Stephanie E Hampton, Sean Anderson, Sarah C Bagby, Corinna Gries, Xueying Han, Edmund Hart, Matthew B. Jones, W"| __truncated__
  .. ..$ datetimestamp: POSIXlt[1:1], format: "2014-10-20 00:39:28"
  .. ..$ description  : chr ""
  .. ..$ heading      : chr "The Tao of Open Science for Ecology"
  .. ..$ id           : chr "peerj-preprints-549.pdf"
  .. ..$ language     : chr "en"
  .. ..$ origin       : chr "PeerJ"
  .. ..- attr(*, "class")= chr "TextDocumentMeta"
  ..- attr(*, "class")= chr [1:2] "PlainTextDocument" "TextDocument"
 - attr(*, "class")= chr [1:2] "VCorpus" "Corpus"
>

**Comment by kbenoit** [comment]
OK, so it's a VCorpus. Strange since this works:
```r
> data(crude, package = "tm")
> corpus(crude)
Corpus consisting of 20 documents and 15 docvars.
> docnames(corpus(crude))
 [1] "reut-00001.xml" "reut-00002.xml" "reut-00004.xml" "reut-00005.xml" "reut-00006.xml" "reut-00007.xml" "reut-00008.xml"
 [8] "reut-00009.xml" "reut-00010.xml" "reut-00011.xml" "reut-00012.xml" "reut-00013.xml" "reut-00014.xml" "reut-00015.xml"
[15] "reut-00016.xml" "reut-00018.xml" "reut-00019.xml" "reut-00021.xml" "reut-00022.xml" "reut-00023.xml"
```
Can you send a link to this object so we can test it?

**Comment by gabrieldaldegan** [comment]
sure!
see this link for the [rmd ](https://github.com/Science-for-Nature-and-People/text-mining-r/blob/master/TextMining.Rmd)
and this one for the [pdfs](https://drive.google.com/drive/u/1/folders/0B-3ZXkTf1q9CTE52M05Wd3kxZ00)

**Comment by stefan-mueller** [comment]
Without having access to the PDFs (if you give me permission to download the files I'm happy to send you the complete code), I assume that you might just switch to the [**readtext**](https://github.com/kbenoit/readtext) package to import the files. 

[Here](https://github.com/kbenoit/readtext/blob/master/vignettes/readtext_vignette.Rmd) you find the most important features. You could import all PDFs from one or more folders, and specify that you would like to get the names of the `docvars` from the filenames.

I use the internal readtext files to show how to read PDF files and transform them to a **quanteda** corpus.
```r
require(readtext)
require(quanteda)

# Get the data directory from readtext to read in sample documents
DATA_DIR <- system.file("extdata/", package = "readtext")

rt_pdf <- readtext(paste0(DATA_DIR, "/pdf/UDHR/*.pdf"), 
                     docvarsfrom = "filenames", 
                     docvarnames = c("document", "language"),
                     sep = "_")

corpus_pdf <- corpus(rt_pdf)

summary(corpus_pdf)
# > summary(corpus_pdf)
# Corpus consisting of 11 documents.
# 
# Text Types Tokens Sentences document   language
# UDHR_chinese.pdf   266    559         3     UDHR    chinese
# UDHR_czech.pdf   283    465         9     UDHR      czech
# UDHR_danish.pdf   266    520        13     UDHR     danish
# UDHR_english.pdf   231    547         8     UDHR    english
# UDHR_french.pdf   256    583         7     UDHR     french
# UDHR_greek.pdf   274    536        12     UDHR      greek
# UDHR_hungarian.pdf   281    545        11     UDHR  hungarian
# UDHR_irish.pdf   267    580        14     UDHR      irish
# UDHR_japanese.pdf   243    603         5     UDHR   japanese
# UDHR_russian.pdf   267    473         7     UDHR    russian
# UDHR_vietnamese.pdf   295   3356         6     UDHR vietnamese
# 
# Source:  /Users/stefan/GitHub* on x86_64 by stefan
# Created: Wed May 31 20:16:45 2017
# Notes:   
```
Now each document in the corpus has the name of the PDF document, and we also created additional `docvars` based on the document names.

I hope this solves your problem.

**Comment by gabrieldaldegan** [comment]
Stefan,
thanks for working on it and sharing the code!
I believed I've shared the PDFs with you. You couldn't download them?

**Comment by stefan-mueller** [comment]
Thanks! Yes, now I can download them. Below is the code to import your files. As you see, when you set `docvarnames = filename`, the filenames will be used instead of `text1`, `text2` etc. 

```r
require(readtext)
require(quanteda)

# necessary to set working directory to the folder that contains "PAPERS_TextMining"
# (see ?setwd)

# import all PDF files from the folder and take docvars from filenames
pdf_texts <- readtext("PAPERS_TextMining/*.pdf",
                      docvarnames = "filename")

corpus_texts <- corpus(pdf_texts)

summary(corpus_texts)

# > summary(corpus_texts)
# Corpus consisting of 8 documents.
# 
# Text Types Tokens Sentences
# Borer et al 2009 Bull ESA_Effective Data Management.pdf   480  21241      3167
# Fegraus-esa_bulletin_eml_ms_07_2005.pdf  1664   7095       299
# Harris_2017_Environ._Res._Lett._12_024012.pdf  2196   9701       283
# Heidorn_2008_Shedding Light on the Dark Data in the Long Tail of Science.pdf  2491  11371       493
# MORTON_et_al-2008-Global_Change_Biology.pdf  2373  12607       311
# Ohara et al 2016_Aligning marine species range data to better serve science and conservation.pdf  1891   9029       360
# arees-informatics-2006-reprint.pdf  3389  15900       874
# peerj-preprints-549.pdf  2343   9919       557
```

I would recommend to give the filenames a common pattern, e.g. "Author(s)_Year_Title.pdf". Then you could add, for example, ```docvarnames = c("authors", "year", "title"), sep = "_")``` to the `readtext` command which creates nicer metadata which you can use for grouping or subsetting your corpus.

**Comment by gabrieldaldegan** [comment]
Thank you very much for dedicating time to this!
For some reason that's not exactly what I'm getting. I've just ran it again following you example, and this what I got:
> pdf_texts <- readtext("*.pdf",
+                       docvarnames = "filename")
> corpus_texts <- corpus(pdf_texts)
> summary(corpus_texts)
Corpus consisting of 8 documents.

  Text Types Tokens Sentences
 text1   480  21241      3041
 text2  1664   7095       299
 text3  2196   9701       283
 text4  2491  11371       493
 text5  2373  12607       311
 text6  1891   9029       360
 text7  3389  15900       874
 text8  2343   9919       557
                                                                                           doc_id
                                          Borer et al 2009 Bull ESA_Effective Data Management.pdf
                                                          Fegraus-esa_bulletin_eml_ms_07_2005.pdf
                                                    Harris_2017_Environ._Res._Lett._12_024012.pdf
                     Heidorn_2008_Shedding Light on the Dark Data in the Long Tail of Science.pdf
                                                      MORTON_et_al-2008-Global_Change_Biology.pdf
 Ohara et al 2016_Aligning marine species range data to better serve science and conservation.pdf
                                                               arees-informatics-2006-reprint.pdf
                                                                          peerj-preprints-549.pdf

Source:  /Users/daldegan/GitHubNCEAS/text-mining/* on x86_64 by daldegan
Created: Wed May 31 14:12:32 2017
Notes:

**Comment by stefan-mueller** [comment]
Do you have the most recent version of **quanteda**? I used quanteda_0.9.9-65 and readtext_0.50. Have a look at `sessionInfo()`. Maybe you need to update **quanteda** or **readtext** on your machine using either ```install.packages("quanteda")``` or ```devtools::install_github("kbenoit/quanteda")``` (change "quanteda" with "readtext" to install the other package).

**Comment by gabrieldaldegan** [comment]
that was it! thank you very much!
