### ISSUE TITLE
consolidate initial, default, and user-set quanteda_options

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#763]
Two changes here:

- [x] consolidate options for startup and  `quanteda_options(reset = TRUE)` 

    Currently, we have options set in both `quanteda_options.R` and `zzz.R`. These have different starting defaults, but these should be consolidated into a single function. I prefer the idea of `.onAttach()` in `zzz.R` calling `quanteda_options(reset = TRUE)` to set these, and having the defaults set in `quanteda_options.R`.

- [x] check that user-set options are not overridden on startup. So if a user sets these in `~/.Rprofile` for instance, they should not be overridden by `.onAttach()` in `zzz.R`.

**Comment by HaiyanLW** [comment]
Yeah, seems we double `reset` in `zzz.R`-- [`zzz.R`](https://github.com/kbenoit/quanteda/blob/master/R/zzz.R#L6) does call `quanteda_options(reset = TRUE)`. 
I think we should still allow users to call `quanteda_options(reset = TRUE)`.

**Comment by kbenoit** [comment]
Yes of course we want to keep `quanteda_options(reset = TRUE)`. I am proposing that `zzz.R` call that function to set the options. However we don't want to overwrite values already present, which would be the case if a user had set them in `~/.Rprofile`, so we need to check if they exist or not before we reset those values.
