### ISSUE TITLE
Question regarding textstat_readability

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#766]
Hi, 

I don't quite understand how the ``texstat_readability()`` function works. As an example, the *SMOG* algorithm seems to rely on a dictionary of polysyllable words.  How is this possible for the German version, *SMOG.de*? As far as I can tell quanteda has no access to a dictionary of polysyllable German terms. ``quanteda::data_int_syllables()`` only seems to include English words.

**Comment by kbenoit** [comment]
You are right - It uses the default of `nsyllable()`, which is the dictionary `quanteda::data_int_syllables`. Absent finding a word in the list, it counts the vowels as an approximation. Not very good for German.

Know any Germany syllable dictionaries? We could incorporate them if so.

Alternatively, @unDocUMeantIt, author of **koRpus**, has been working on [sylly](https://github.com/unDocUMeantIt/sylly), which has German support. This could be an alternative to `nysyllable()`. (I have on my To Do list to contribute to this package but too overloaded at the moment.)

**Comment by unDocUMeantIt** [comment]
both [sylly](https://reaktanz.de/R/pckg/sylly/) and a version of [koRpus](https://reaktanz.de/R/pckg/koRpus/) using it are now released for testing in my own repo, installable via
```R
install.packages("koRpus", repo="https://reaktanz.de/R")
```
you can then use it in combination with `koRpus::readability()` (including `koRpus::SMOG()`).
