### ISSUE TITLE
Dev install issue

### ISSUE THREAD

**Issue by joetekyun** [kbenoit/quanteda#77]
Trying to install the dev version, specifically looking for the new textfile function of accepting multiple text files for processing recursively through folders, and getting (added asterisks for my local username):

installing to /Users/****/R-dev/quanteda/libs
** R
Error in .install_package_code_files(".", instdir) : 
files in 'Collate' field missing from '/private/var/folders/kc/bxl23dzd5mv4f409_ctkwn680000gp/T/RtmpOWjsYN/devtools251d7a850440/kbenoit-quanteda-4ff12ab/R':
  weighting.R
ERROR: unable to collate and parse R files for package ‘quanteda’
* removing ‘/Users/****/R-dev/quanteda’
* restoring previous ‘/Users/****/R-dev/quanteda’
Error: Command failed (1)

**Comment by kbenoit** [comment]
Always install from the master branch, dev is work in progress. Master branch working fine in 0.9.1-3.
