### ISSUE TITLE
pkgdown doc site doesn't refer to the current release

### ISSUE THREAD

**Issue by conjugateprior** [kbenoit/quanteda#771]
Would it be a good idea to have the [http://quanteda.io/reference/index.html](http://quanteda.io/reference/index.html)  be about the version of Quanteda that's currently on CRAN? 

Realizing that pages there didn't work because it was about version 0.9.9.67 just bit me. 

Since the site is autogenerated (and this is v cool) maybe have a similar arrangement to e.g. Django? There the docs pages is versioned in the URL which is the current stable release (for us, the CRAN version):

That is: [https://docs.djangoproject.com](https://docs.djangoproject.com) 

currently redirects to 

[https://docs.djangoproject.com/en/1.11/](https://docs.djangoproject.com/en/1.11/)

For extra fanciness, if you follow a link to an older version of the documentation, e.g. from SO, then you get a reminder these probably aren't the pages you are looking for. e.g. from [https://docs.djangoproject.com/en/1.10/genindex/](https://docs.djangoproject.com/en/1.10/genindex/) floating at the bottom right of the screen.
<img width="547" alt="bottom-right-django" src="https://user-images.githubusercontent.com/509288/26836296-769746e8-4aa8-11e7-97cf-e4d4f86477d4.png">

But tbh, just having these pages track CRAN would be better than tracking non-release code.

**Comment by kbenoit** [comment]
We have explored options for this, but it's mainly a problem of the rapid evolution taking place as we approach 1.0. We hope to refresh CRAN within the next 2 weeks, in which case the pkgdown site will match the CRAN version. Then we will follow this advice and keep the pkdown site matching the CRAN version.
