### ISSUE TITLE
Problem with summary(docvars(somecorpus))?

### ISSUE THREAD

**Issue by thomasd2** [kbenoit/quanteda#772]
I guess this doesn't do what it is intended to do? Thanks.
```
dUK <- data_corpus_ukmanifestos
summary(docvars(dUK))
```

**Comment by kbenoit** [comment]
No, that's the correct behaviour, because `docvars(dUK)` returns a data.frame. So you are calling `summary.data.frame()` on the return.

**Comment by thomasd2** [comment]
Yes, I'm expecting a neat data.frame summary of the docvars, but my console gets flooded with stuff, including:

Text     :c("text1", "text2", "text3", "text4", "text5", "text6", "text7", "text8", "text9", "text10", "text11", "text12", "text13", "text14", "text15", "text16", "text17", "text18", "text19", "text20", "text21", "text22", "text23", "text24", "text25", "text26", "text27", "text28", "text29", "text30", "text31", "text32", "text33", "text34", "text35", "text36", "text37", "text38", "text39", "text40", "text41", "text42", "text43", "text44", "text45", "text46", "text47", "text48", "text49", "text50", "text51", \n"text52", "text53", "text54", "text55", "text56", "text57", "text58", "text59", "text60", "text61", "text62", "text63", "text64", "text65", "text66", "text67", "text68", "text69", "text70", "text71", "text72", "text73", "text74", "text75", "text76", "text77", "text78", "text79", "text80", "text81", "text82", "text83", "text84", "text85", "text86", "text87", "text88", "text89", "text90", "text91", "text92", "text93", "text94", "text95", "text96", "text97", "text98", "text99", "text100")  
 Types    :c("1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1")         

[...]

Warning messages:
1: In tokens.character(x, what = "sentence", ...) :
  Arguments maxsumdigits not used.
2: In tokenize.character(object, ...) : Arguments maxsumdigits not used.
3: In nsentence.character(object, ...) :
  nsentence() does not correctly count sentences in all lower-cased text
4: In tokens.character(x, what = "sentence", ...) :
  Arguments maxsumdigits not used.
5: In tokenize.character(object, ...) : Arguments maxsumdigits not used.
6: In nsentence.character(object, ...) :
  nsentence() does not correctly count sentences in all lower-cased text
7: In tokens.character(x, what = "sentence", ...) :
  Arguments maxsumdigits not used.
8: In tokenize.character(object, ...) : Arguments maxsumdigits not used.
9: In tokens.character(x, what = "sentence", ...) :
  Arguments maxsumdigits not used.
10: In tokenize.character(object, ...) : Arguments maxsumdigits not used.

**Comment by kbenoit** [comment]
You're right, this is a bug where the `summary.data.frame()` method is invoking our `summary.character()` on the character columns. It ought to work if these were factors, but they are not.
