### ISSUE TITLE
Create semantic network analysis functions using fcm

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#782]
Semantic network analysis is popular among media analysts, but it a bit difficult for network analysis armatures (including myself). So it is nice to have `plot.fcm()` that visualizes cooccurances of words with proper weighting of graphs. 

Here is my tentative code, but I am sure that @adamobeng can do this much better.
```r
mx <- dfm(data_corpus_inaugural, remove = stopwords())
mx <- dfm_select(mx, features = names(topfeatures(mx, 20)), min_nchar = 2)
mx_col <- fcm(mx)
mx_nor <- mx_col / rowSums(mx_col)
head(mx_nor)

require(igraph)
gr <- graph_from_adjacency_matrix(mx_nor, weighted = TRUE, diag = FALSE)
igraph.options(plot.layout=layout_with_graphopt, vertex.label.family = 'sanserif', vertex.label.cex = 0.8)
plot(gr, edge.width = E(gr)$weight * 20,  edge.arrow.size = 0.5, vertex.size = 20)
```

**Comment by stefan-mueller** [comment]
Good idea. I never worked with network data, but If possible, I'd recommend to use the [`ggnet2()`](https://briatte.github.io/ggnet/) function (part of the [**GGally**](http://ggobi.github.io/ggally/#canonical_correlation_analysis) package). Since all other **quanteda** plots are now based on **ggplot2**, I would stick to this syntax and design. If @adamobeng knows about the pros and cons of the packages, please let us know. I could try to replicate @koheiw's plot based on `ggnet2()`.

**Comment by koheiw** [comment]
@stefan-mueller, I managed to make a nicer network. I am still using **igraph**, but the weighting and coloring are the same to any packages. See https://github.com/koheiw/IJTA/blob/master/documents/advanced.md

**Comment by stefan-mueller** [comment]
This plot looks much better! I was just thinking that a **ggplot2**-based solution would make it possible to apply the same theme easily to all plots (e.g. `theme_bw()`, `theme_minimal()` etc). But since the network analysis graphs usually have a plain white background and no axes, the theme is probably not really important. So I'm happy to continue with **igraph**. Let me know if you would like me to help you with this issue.

**Comment by adamobeng** [comment]
Network visualisation is pretty fraught: there are lots of ways to do it, and it's not always clear which way presents the information most usefully. Does anyone have an example of best practices for this kind of thing in media analysis, which we could use as inspiration?

**Comment by koheiw** [comment]
@adamobeng you are right. There are too many way to visualize network, and risks of misleading users, but network charts are attracts. I think `textplot_network` should be something least misleading (minimal  transformation) and most beautiful (many colors and dynamic shape). I tried to make such a chart in IJTA.

**Comment by koheiw** [comment]
This network looks informative, although not visually appealing.
https://snacda.com/2010/04/13/semantic-network-analysis-of-party-manifestos-ge2010/

**Comment by kbenoit** [comment]
I think **qdap** does word networks. https://rdrr.io/cran/qdap/man/word_network_plot.html

**Comment by methodds** [comment]
Support for semantic network analysis in quanteda would be awesome! I think a lot of users would be happy with that. In this context you might be interested in a script that Christopher Bail used last week for the Summer Institute on Computational Social Science:
https://github.com/compsocialscience/summer-institute/tree/master/2017/materials/day3_text_analysis
 `Ngram Networks Example.R` -> Code
 `Ngram Networks-1.html` -> Slides

**Comment by methodds** [comment]
Thank you so much for implementing semantic networks :) I just tried the examples from the manual and it looks nice and useful. I noticed two things:

- the ggplot object returned by ``textplot_network`` does not contain the network data. Is there a way to change this, or to let the user decide whether the data should be returned? This could be useful for some users who want to do more than just plot the semantic network.
- Especially social scientists would probably be interested in using the semantic network in combination with dictionaries. Maybe you can provide an example for that in the manual.

**Comment by kbenoit** [comment]
On the first, please file this as a separate issue and we will consider it. That would make the resulting object pretty huge, wouldn’t it? An alternative would be to pipe from into a new `textstat_network()` function, and then `textstat_plot()` that. 

On the second, feel free to make that a documentation/feature request new issue. (And consider writing one if you wish!)

**Comment by methodds** [comment]
I think the idea with `textstat_network()` is really good. Maybe in the future, this function could even support other methods for creating network objects. I opened #1117. And as for the dictionary example, I'd be happy to write an example after a decision/implementation for #1117 is resolved.
