### ISSUE TITLE
Feature suggestion: mutual information measure and keyness plot

### ISSUE THREAD

**Issue by methodds** [kbenoit/quanteda#785]
Hi,

I'd like to suggest adding a mutual information measure to quanteda. This could just be another measure that users are able to choose in ```textstat_keyness```. In addition, it would also be awesome to have a plot for keyness term comparisons which could look similar to this one (from [Grimmer 2010](http://web.stanford.edu/~jgrimmer/ExpAgendaFinal.pdf)):

![image](https://user-images.githubusercontent.com/7460499/27001508-fca10fc8-4dcb-11e7-9d97-af68d92a5533.png)

**Comment by kbenoit** [comment]
Good suggestion! We could add mutual information to `textstat_keyness()` very easily. The plot would be a new `textplot_keyness()` that takes the return of a `textstat_keyness()` and plots it.

**Comment by HaiyanLW** [comment]
Is this what you want?
![image](https://user-images.githubusercontent.com/20244806/27551702-613f40e4-5a9c-11e7-8a0a-b5b0225ea743.png)

**Comment by methodds** [comment]
Yes, something like that, looks nice :) Would it also be possible to include "directions" somehow? 

What I mean by this is that the plot would support showing terms with the highest keyness scores that are much more likely (by whatever metric) in corpus 1 , but in contrast also show terms that are much more likely for corpus 2 ? An alternative would be to plot this contrast with a wordcloud, as proposed in #528.

**Comment by HaiyanLW** [comment]
Here's the dual-plot: Blue dots associates with Document 1 and red dots accociated with the 2nd Document. The code is in branch `issue-785`
```r
period <- ifelse(docvars(data_corpus_inaugural, "Year") < 1945, "pre-war", "post-war")
mydfm <- dfm(data_corpus_inaugural, groups = period)
head(mydfm) # make sure 'post-war' is in the first row
```
```
Document-feature matrix of: 2 documents, 9,232 features (34.6% sparse).
(showing first 2 documents and first 6 features)
          features
docs       chief justice    , mr    . vice
  post-war    12      40 2194 25 1804   15
  pre-war     24      97 4832  6 3141    3
```
```r
result <- textstat_keyness(mydfm)
 textplot_keyness(result, showBothDoc = TRUE)
```
![image](https://user-images.githubusercontent.com/20244806/27731931-0bbd53c0-5d87-11e7-8336-607c66d4a4e0.png)

**Comment by methodds** [comment]
cool thanks :) I guess the only thing missing is the label for the second y axis?

**Comment by kbenoit** [comment]
@HaiyanLW I've reviewed (and edited) branch `issue-785` and here are a few suggestions. First, global comment:

The plot looks very good for plotting a `textstat_keyness` result, but I don't think we should combine the scores for different words in a single row of the plot. This suggests there is some link between them, but there is not (only ranking at the top and bottom). In the Grimmer 2010 plot, the right y-axis refers to the committee on which the term was used, so it's an external attribute linked to the term. In ours, the two axes refer to different and unrelated terms. A better alternative would be to plot two vertical panes showing the terms most associated with the target versus reference sets. Even better would be to get rid of the axis altogether and plot the text next to the point. You could put these to the right of the point until halfway up the plot, and then label to the left of the point.

More minor issues:
* need tests for `keyness_pmi()`
* need test for `textplot_keyness()` (see `test-plots.R`)
* I changed your camelCase arguments to snake_case

**Comment by HaiyanLW** [comment]
@kbenoit Here's the plot upon your suggestion:
![image](https://user-images.githubusercontent.com/20244806/28209259-a94080e2-6889-11e7-9cea-a24726734507.png)

**Comment by kbenoit** [comment]
Getting there! How about we split it more like the first plot here: http://varianceexplained.org/r/tidytext-gender-plots/ ?

**Comment by HaiyanLW** [comment]
Here we are: 
![image](https://user-images.githubusercontent.com/20244806/28219206-0d6fa042-68b3-11e7-94f3-c533ab20c0a9.png)

**Comment by kbenoit** [comment]
good! How about the option to stack them as in the blog example?

**Comment by HaiyanLW** [comment]
Could be. Just thought that way sort of waste left/right side space and this way can show more words. You prefer stack them up?

**Comment by HaiyanLW** [comment]
Like this:
![image](https://user-images.githubusercontent.com/20244806/28221109-f1d63628-68b9-11e7-9e10-084edf07c61e.png)

**Comment by kbenoit** [comment]
Yes! but put the blue on the bottom.

**Comment by methodds** [comment]
Thanks for implementing this! Is it supposed to be working for all "keyness" measures? The "pmi" plot looks weird to me, although this is probably due to the skewed distribution of mutual information scores.

```
# compare Trump v. Obama speeches
prescorpus <- corpus_subset(data_corpus_inaugural, 
                            President %in% c("Obama", "Trump"))
presdfm <- dfm(prescorpus, groups = "President", remove = stopwords("english"),
               remove_punct = TRUE)
result <- textstat_keyness(presdfm, target = "Trump", measure = "pmi")

# plot estimated word keyness
textplot_keyness(result) 
```

![image](https://user-images.githubusercontent.com/7460499/28361064-c2f7eb0a-6c77-11e7-95a0-e4df0abf0950.png)

**Comment by kbenoit** [comment]
Thanks @methodds, that's clearly a bug. @HaiyanLW will fix.

**Comment by HaiyanLW** [comment]
`pmi` measure doesn't account for how often the words do not appear. In other words, it is too sensitive to rare occasions. 
```r
> result <- textstat_keyness(presdfm, target = "Trump", measure = "pmi")
> textplot_keyness(result)
> tail(result, 20)
                 pmi            p n_target n_reference
realizes   -20.72327 5.306729e-06        0           1
waves      -20.72327 5.306729e-06        0           1
fills      -20.72327 5.306729e-06        0           1
hearts     -20.72327 5.306729e-06        0           1
represent  -20.72327 5.306729e-06        0           1
greatest   -20.72327 5.306729e-06        0           1
country's  -20.72327 5.306729e-06        0           1
obligation -20.72327 5.306729e-06        0           1
votes      -20.72327 5.306729e-06        0           1
cast       -20.72327 5.306729e-06        0           1
voices     -20.72327 5.306729e-06        0           1
ancient    -20.72327 5.306729e-06        0           1
embrace    -20.72327 5.306729e-06        0           1
solemn     -20.72327 5.306729e-06        0           1
awesome    -20.72327 5.306729e-06        0           1
joy        -20.72327 5.306729e-06        0           1
birthright -20.72327 5.306729e-06        0           1
passion    -20.72327 5.306729e-06        0           1
dedication -20.72327 5.306729e-06        0           1
call       -20.72327 5.306729e-06        0           1
```

**Comment by HaiyanLW** [comment]
and the bars in red are:
```r
> head(result, 20)
               pmi        p n_target n_reference
roberts   1.408425 0.235318        1           0
carter    1.408425 0.235318        1           0
clinton   1.408425 0.235318        1           0
obama     1.408425 0.235318        3           0
rebuild   1.408425 0.235318        1           0
determine 1.408425 0.235318        1           0
confront  1.408425 0.235318        1           0
hardships 1.408425 0.235318        1           0
get       1.408425 0.235318        2           0
four      1.408425 0.235318        1           0
steps     1.408425 0.235318        1           0
orderly   1.408425 0.235318        1           0
transfer  1.408425 0.235318        1           0
first     1.408425 0.235318        4           0
lady      1.408425 0.235318        1           0
michelle  1.408425 0.235318        1           0
gracious  1.408425 0.235318        1           0
aid       1.408425 0.235318        1           0
ceremony  1.408425 0.235318        1           0
however   1.408425 0.235318        1           0
```

**Comment by kbenoit** [comment]
@HaiyanLW this suggests we would want to set a minimum word threshold. LR and chi2 get smoothed with a Yates correction - that would be another option for pmi and exact.

**Comment by HaiyanLW** [comment]
The current `textstat_keyness()` doesn't call `Yates correction` for `LR` and `chi2` although it is implemented as an option for `LR`. Do you think we should include this smoothing as an universal option for `teststat_keyness()`?

**Comment by kbenoit** [comment]
Yes how about a `correction = 0.5` for `textstat_keyness()`?

For `textplot_keyness()` we could include a `min_count = 2` option.

**Comment by HaiyanLW** [comment]
Good idea. `min_count = 2` for both documents?

**Comment by kbenoit** [comment]
experiment a bit first, but I think so.

**Comment by HaiyanLW** [comment]
Maybe use something like `sum >= 2`  to avoid losing some words like `freedom` which appears many time in one document but makes no appearance in another as shown below:
```r
> rr <- result[(result$n_target + result$n_reference) >=2, ]
> dim(rr)
[1] 488   4

> tail(rr,10)
                chi2           p n_target n_reference
may        -1.138108 0.286052488        0           7
still      -1.438830 0.230328801        0           8
know       -1.438830 0.230328801        0           8
generation -1.745145 0.186488268        0           9
journey    -1.745145 0.186488268        0           9
freedom    -1.745145 0.186488268        0           9
common     -1.745145 0.186488268        0           9
must       -2.186399 0.139234488        3          25
can        -3.430790 0.063991497        1          20
us         -9.150147 0.002486981        2          44
> head(rr,10)
               chi2            p n_target n_reference
america   16.010070 6.300646e-05       18          14
protected 11.648620 6.425017e-04        5           0
dreams    11.648620 6.425017e-04        5           0
american   9.827231 1.719470e-03       11           8
first      8.618646 3.327391e-03        4           0
everyone   8.618646 3.327391e-03        4           0
back       8.520896 3.510915e-03        6           2
right      8.315540 3.930732e-03        5           1
country    6.041165 1.397606e-02        9           8
obama      5.635902 1.759629e-02        3           0
```

**Comment by kbenoit** [comment]
agreed
