### ISSUE TITLE
Implement the BOG index for textstat_readability

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#791]
* See the explanation here: http://s3-eu-west-1.amazonaws.com/plcdev/app/public/system/files/36/original/TowardsABetterReadabilityMeasure.pdf.
* More here: https://strainindex.wordpress.com/2010/01/19/stylewriters-bog-index/
* Software link here: https://strainindex.wordpress.com/2010/01/19/stylewriters-bog-index/

This could be difficult because it relies on a large "proprietary word list".

**Comment by contefranz** [comment]
Thank you for having replied me so fast and for issuing this. I link the original paper which introduces the BOG index just for further reference. Find it [here](https://papers.ssrn.com/sol3/papers.cfm?rec=1&pos=9&abstract_id=2560644&srcabs=2552791&alg=1). 

What if we use our own word list? Do you think it would be possible at least as a starting point?
In my view, one can build a BOG index base on different word lists if this is the way to compute that.

**Comment by kbenoit** [comment]
Yes, or we can reverse engineer the word list by 
- prying it out of the software
- using the software to match to a dictionary of english words (actually, my dictionary has only 130,000 words, not 200,000!)

**Comment by beihorse** [comment]
Anyone still interested in this project?

**Comment by kbenoit** [comment]
The problem is a) the copyright on the BOG list and b) the lack of its availability. Would either of the reverse engineering methods above work in a satisfactory way?  

@beihorse  if you can supply the word list, we could add it.

**Comment by beihorse** [comment]
There are some word frequency lists on line, e.g. https://www.wordfrequency.info/free.asp?s=y.  The list does not have to be exact. It should't make much difference as long as we get the more common words right, for example, the most frequent 20,000 words. It is probably more challenging to pick up features such as abbreviations and acronyms, wordiness, passive verbs, and other style issues.
