### ISSUE TITLE
Import lexisnexis output through corpus()

### ISSUE THREAD

**Issue by bstnbckr** [kbenoit/quanteda#80]
I would to use quanteda to analyze articles exported from lexisnexis. The export is in the standard html-format. I use the tm package + plugin to read the lexisnexis output. Unfortunately, an error occurs when transforming the tm-corpus to quanteda-corpus.

    library("tm")
    library("tm.plugin.lexisnexis")
    library("quanteda")
    
    ln <- LexisNexisSource("lexisnexisOutput.html")
    cr <- Corpus(ln)
    crp <- corpus(cr)

    Error in UseMethod("corpus") : 
     no applicable method for 'corpus' applied to an object of class "list"
    In addition: Warning message:
    In corpus(texts, docvars = metad, source = paste("Converted from tm VCorpus '",  :
      Arguments docvarssource not used.

**Comment by kbenoit** [comment]
Was a limitation of corpus.VCorpus when the texts were a vector of char types, not just a single char type. Fixed in 0.9.1-6.
