### ISSUE TITLE
Yoshikoder dictionary wrapper failing / collapsed category structure

### ISSUE THREAD

**Issue by conjugateprior** [kbenoit/quanteda#819]
Consider the following valid Yoshikoder dictionary :
```
s <- '<?xml version="1.0" encoding="UTF-8"?>
<dictionary style="050805" patternengine="substring">
<cnode name="Dictionary">
<cnode name="pos">
<cnode name="Apologeten"><pnode name="Apologeten"/></cnode>
<cnode name="Respekt"><pnode name="Respekt"/></cnode>
</cnode>
</cnode>
</dictionary>'
```
Load into quanteda
```
> dictionary(s, format="yoshikoder")

Error in validate_dictionary(object) : 
  Dictionary elements must be named: <?xml version="1.0" encoding="utf-8"?>
<dictionary style="050805" patternengine="substring">
<cnode name="dictionary">
<cnode name="pos">
<cnode name="apologeten"><pnode name="apologeten"/></cnode>
<cnode name="respekt"><pnode name="respekt"/></cnode>
</cnode>
</cnode>
</dictionary>
```
where it is lowercased but no dictionary is produced.  Same result from a file.

If we recreate the steps inside `dictionary` then we get this:
```
> d <- quanteda:::read_dict_yoshikoder(s)
> d

$Dictionary
$Dictionary$pos
$Dictionary$pos[[1]]
[1] "Apologeten" "Respekt"
```
This is already wrong because it collapses the bottom level of cnodes.  It should be more like:
```
$Dictionary
$Dictionary$pos
$Dictionary$pos$Apologeten
[1] "Apologeten"
$Dictionary$pos$Respekt
[1] "Respekt"
```
but ploughing on...
```
new("dictionary2", quanteda:::list2dictionary(d), concatenator=" ")

Dictionary object with 1 primary key entry and 3 nested levels.
- Dictionary:
  - pos:
    - :
      - Apologeten, Respekt
```
where the level below `pos` and above the patterns is blank and the patterns should be in separate eponymous categories.

(Quanteda 0.9.9.72)

**Comment by kbenoit** [comment]
I think this happened in @koheiw's rewrite of the dictionary functions to use yaml as an intermediate format.

@koheiw can you pls fix and add this as a test?

**Comment by conjugateprior** [comment]
Sounds crazy but it's probably easier to write a SAX parser for ykd format, even in R...  Happy to share the original java implementation, if that's helpful.

**Comment by koheiw** [comment]
It works with the yoshikoder format, if it is given in a file like:
```r
> dictionary(file = './test.txt', format="yoshikoder")
Dictionary object with 1 primary key entry and 2 nested levels.
- Dictionary:
  - pos:
    - apologeten, respekt
```
We were just not expecting to get those dictionary formats in a string.
