### ISSUE TITLE
Punctuation not removed when not followed by a white space

### ISSUE THREAD

**Issue by jernejkase** [kbenoit/quanteda#83]
txt <- "testing:one two three.oh noes!"
tokenize(txt, ngrams=3, removePunct = T, removeSeparators = T)

tokenizedText object from 1 document.
Component 1 :
[1] "testing:one_two_three.oh" "two_three.oh_noes" 

I would expect colon and period to be removed, but they are not.

**Comment by kbenoit** [comment]
I'm going to defend this behaviour as correct: it removes *punctuation*, not *punctuation characters*. Intra-word punctuation characters do not constitute punctuation. `tokenize(x, what = "word", removePunct = TRUE)` (where the `"word"` is the default) is smart enough to know the difference.

However...if you want to remove punctuation *characters* then you can use a dumber (but faster) version: 

```
> tokenize(txt, removePunct = TRUE)
tokenizedText object from 1 document.
Component 1 :
[1] "testing:one" "two"         "three.oh"    "noes"       

> tokenize(txt, removePunct = TRUE, what = "fastestword")
tokenizedText object from 1 document.
Component 1 :
[1] "testingone" "two"        "threeoh"    "noes"      

> txt <- "testing:one two three.oh noes!"
> tokenize(txt, removePunct = TRUE, what = "fasterword")
tokenizedText object from 1 document.
Component 1 :
[1] "testingone" "two"        "threeoh"    "noes" 
```
