### ISSUE TITLE
similiarity() coerces sparse to dense matrix

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#84]
Resulting in memory overload in the case of large sparse matrixes that are too big to be made dense. Solution: reimplement based on a more efficient sparse-preserving computation. See for instance the **qlcMatrix** package.

**Comment by tpaskhalis** [comment]
Had an issue with memory overload several times when doing term similarity for the full SOTU corpus. Another problem is that `margin = c("features", "documents")` makes it the default margin. Say, if I run `similarity(sotuDfm)` it pretty much guarantees to hang the R session if not the whole system. For the time being, before more efficient implementation is found, I'd suggest having documents as the default.

**Comment by kbenoit** [comment]
What, can't your wimpy computer handle a 684 million cell dense matrix?

    > nfeature(SOTUdfm)^2
   [1] 664505284

Maybe you should supply something to the `selection = ` argument.

**Comment by tpaskhalis** [comment]
Well, it was a decent i5, 8Gb. Just tried on i5, 16Gb to the same effect.

**Comment by kbenoit** [comment]
> SOTUdfm <- dfm(SOTUCorpus)
    Creating a dfm from a corpus ...
       ... lowercasing
       ... tokenizing
       ... indexing documents: 230 documents
       ... indexing features: 25,779 feature types
       ... created a 230 x 25779 sparse dfm
       ... complete. 
    Elapsed time: 4.02 seconds.
    sim <- similarity(SOTUdfm)
    > dim(sim)
    NULL
    > object.size(sim)
    45910749608 bytes

**Comment by kbenoit** [comment]
Just kidding - I took your suggestion and changed the default to `margin = "documents`.
