### ISSUE TITLE
Unregistered symbols warnings

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#846]
In current `master`:
```
* checking compiled code ... NOTE
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
Warning in read_symbols_from_dll(so, rarch) :
  this requires 'objdump.exe' to be on the PATH
File 'quanteda/libs/i386/quanteda.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'
It is good practice to register native routines and to disable symbol
search.
See 'Writing portable packages' in the 'Writing R Extensions' manual.
* checking examples ... OK
** found \donttest examples: check also with --run-donttest
```

**Comment by HaiyanLW** [comment]
Updating init.c should work.

**Comment by kbenoit** [comment]
Can you or @koheiw do this? I can't understand why the 
```r
#' @useDynLib quanteda, .registration = TRUE  
```
in `quanteda.R` doesn't take care of this automatically. Can we make this automatic?

Using `tools::package_native_routine_registration_skeleton()` does not help either:
```r
> tools::package_native_routine_registration_skeleton(".", "src/init.c")
Error in native_routine_registration_db_from_ff_call_db(calls, dir, character_only) : 
  no native symbols were extracted
```

**Comment by HaiyanLW** [comment]
```r
> tools::package_native_routine_registration_skeleton(".")
```
should work, but I don't have `"r-devel"` installed now, so the easiest way is to add the new `.cpp` function to `init.c`. I can do it if @koheiw let me know what the new `.cpp` function is.

**Comment by kbenoit** [comment]
That did not work for me, as I commented above. Could you add manually this in a PR?

**Comment by HaiyanLW** [comment]
What is the new added `.cpp` function?

**Comment by kbenoit** [comment]
@koheiw knows

**Comment by HaiyanLW** [comment]
@koheiw What's the new `.cpp` you added in the current master?

**Comment by koheiw** [comment]
`tokens_ngrams_mt2.cpp` is the latest. You can remove it as it is only a clone of `tokens_ngrams_mt.cpp, for development.

**Comment by HaiyanLW** [comment]
Do you mean `tokens_ngrams_mt2.cpp` is the only new added `c` function? If this is the case, just remove it and nothing needed to do with `init.c` to solve this issue.

**Comment by kbenoit** [comment]
The way to regenerate `init.c` is:
```r
tools::package_native_routine_registration_skeleton(".", character_only = FALSE)
```
The unintuitive `character_only = FALSE` is necessary if you are not calling this for the first time.

However: Even after applying this update, on Windows (only) I am still seeing:
```
* checking compiled code ... NOTE
File 'quanteda/libs/x64/quanteda.dll':
  Found no calls to: 'R_registerRoutines', 'R_useDynamicSymbols'

It is good practice to register native routines and to disable symbol
search.

See 'Writing portable packages' in the 'Writing R Extensions' manual.
```
even though both functions are called in the function `void R_init_quanteda(DllInfo *dll)` inside `init.c`. Maybe we have to call that function from somewhere?

**Comment by HaiyanLW** [comment]
Is the new generated `init.c` in the current master now? I notice `R_useDynamicSymbols` is set to `FALSE` in `void R_init_quanteda(DllInfo *dll)` function inside `init.c`, would that be the reason?

**Comment by HaiyanLW** [comment]
Also is `.registration = TRUE` set as such in the `useDynLib` inside `NAMESPACE` after you re-generated `init.c`?

**Comment by kbenoit** [comment]
Not sure... I suggest you branch and test this, with a regenerated `init.c`. The `useDynLib` inside `NAMESPACE` comes from the Roxygen directive in `quanteda.R`.

**Comment by HaiyanLW** [comment]
Ok, I can test it tomorrow on Windows.

**Comment by HaiyanLW** [comment]
Not sure why the `useDynLib` has always been mentioned.

**Comment by kbenoit** [comment]
Tell me the branch and I will pull it and run the tests. You can also always using `devtools::build_win()`.

**Comment by HaiyanLW** [comment]
I ran the `tools::package_native_routine_registration_skeleton(".", character_only = FALSE)` command on my Windows machine and the returned content is exactly same as what inside `init.c` in the current `master`. Also built without any **note**

**Comment by kbenoit** [comment]
I'm still seeing the note in the CHECK --as-cran on my Windows 10 system. And it's in Appveyor. This is insanely frustrating.

**Comment by mpadge** [comment]
@kbenoit There's been an `Rcpp` update which inserts underscores before all `RcppExports` functions. If you've got a pre-generated skeleton, you simply need to manually insert the underscores in all functions there and you should be good to go. Simply check all `R/RcppExports.R` and `src/RcppExports.cpp` and ensure your `init.c` matches.

**Comment by kbenoit** [comment]
Thanks @mpadge, you may have saved a lot more of my hair from being pulled out!!
