### ISSUE TITLE
Question: best way to remove duplicate rows from dfm?

### ISSUE THREAD

**Issue by thomasd2** [kbenoit/quanteda#857]
If I want to remove duplicates only after calling dfm, e.g. because I used some remove arguments, as in:
```
mytweetsdfm <- dfm(tokens(mytweets, what="fasterword",
                      remove_url=TRUE, remove_punct=TRUE))
```
Thanks!

**Comment by kbenoit** [comment]
Once you have your dfm built, you can manipulate it using nearly all of of the functions that are options in `dfm()` (in fact most of those functions call the `dfm_*()` functions). 

I'm not exactly sure what you mean by "duplicates" though or how you produced them. `dfm_compress()` will combine the dfm when feature names and/or document names have become equivalent, but most functions on dfms should not produce this situation, unless you are trying to bypass our beautiful suite of dfm functions and manipulate the elements of the dfm directly. (Which voids your warranty!)

**Comment by thomasd2** [comment]
```
sometext <- c("This is that",
               "This is that!",
              "This is that http://www.hello.com", 
              "This is that http://www.helloagain.com",
              "This is something else")

(dfm1 <- dfm(sometext))

(dfm2 <- dfm(tokens(sometext,
            remove_punct=TRUE,
            remove_url=TRUE)))
```
Is there an easy way of keeping just one of the first four rows of dfm2 (I'm referring to a context where the docnames are irrelevant)?
(I mean without replacing the tokens() call with some 'manual' ex-ante cleaning of the sometext object)

**Comment by kbenoit** [comment]
I'm not sure what output you want - can you clarify? What does "keeping just one of the first four rows of dfm2" mean? This seems to fit that:
```r
dfm_sample(dfm2, size = 1, margin = "documents")
# Document-feature matrix of: 1 document, 5 features (40% sparse).
# 1 x 5 sparse Matrix of class "dfmSparse"
#        features
# docs    this is that something else
#   text4    1  1    1         0    0
```

**Comment by thomasd2** [comment]
Sorry, I meant something like:
`dfm2[c(sample(1:4, 1), 5),]`, 
where we sample one of the duplicate rows and keep all unique ones.

**Comment by kbenoit** [comment]
that works but so does
```r
rbind(dfm_sample(dfm1[1:4], 1), dfm1[5, ])
# Document-feature matrix of: 2 documents, 11 features (50% sparse).
# 2 x 11 sparse Matrix of class "dfmSparse"
#        features
# docs    this is that ! http : / www.hello.com www.helloagain.com something else
#   text3    1  1    1 0    1 1 2             1                  0         0    0
#   text5    1  1    0 0    0 0 0             0                  0         1    1
```

**Comment by thomasd2** [comment]
Yes, but the trickier part is identifying which are the duplicate rows to sample from. By the way, `dfm2` is the one with duplicate rows, not `dfm1` as in your previous post.

**Comment by kbenoit** [comment]
```r
> df <- as.matrix(dfm2)
> duplicated(df) | duplicated(df, fromLast = TRUE)
[1]  TRUE  TRUE  TRUE  TRUE FALSE
```
