### ISSUE TITLE
default quanteda_options when namespace not loaded

### ISSUE THREAD

**Issue by mpadge** [kbenoit/quanteda#864]
Finally enjoying getting to use the package for initial [`flipper`](https://github.com/ropenscilabs/flipper) explorations, but discovered that `quanteda_options` is used throughout, yet is not recognised when the full namespace is not loaded.
```r
pkgs <- tools::CRAN_package_db()
pkg_txt <- apply (cbind (pkgs$Title, pkgs$Description), 1, paste, collapse = " ")
pkg_corpus <- quanteda::corpus (pkg_txt)
pkg_dfm <- quanteda::dfm (pkg_corpus, remove = stopwords ("english"), stem = TRUE,
      remove_punct = TRUE)
## Error in if (verbose) catm("Creating a dfm from a corpus ...\n") :
## argument is of length zero
```
The quick and dirty solution would be to include an extra
```
if (is.null (verbose))
   verbose = FALSE
```
in ... every function.

**Comment by kbenoit** [comment]
@mpadge great to have you using **quanteda** and filing issues! 

On this options/namespace issue, I'd suspected that this would be the case, and I think the solution will be to insert a call to

```r
quanteda_initialize()
```
which will initialize at default values any options not already set. @koheiw could do this today or I will tonight or tomorrow.

**Comment by kbenoit** [comment]
Fixed now in the `master` branch, but: You will still need to use
```r
pkg_dfm <- quanteda::dfm (pkg_corpus, remove = quanteda::stopwords ("english"), stem = TRUE,
                          remove_punct = TRUE)
```
since `stopwords()` is a **quanteda** function.
