### ISSUE TITLE
'stm' converter assigns wrong feature counts

### ISSUE THREAD

**Issue by felixhaass** [kbenoit/quanteda#87]
In line 247 in the `dfm2stmformat()` function in the [converters.R](https://github.com/kbenoit/quanteda/blob/master/R/converters.R) file, you include an `as.integer(as.matrix(data[d, ])))` call. 

But shouldn't this be `as.integer(as.matrix(sortedData[d, ])))`? 

Otherwise you include all features from the original, *unsorted* dfm and assign them the *sorted* feature counts within the `rbind()` call by including `1:length(vocab)`. Since `vocab`is pulled from the `sortedData`dfm, this essentially assigns wrong feature counts to each feature index.

So, in my opinion line 247 should read:

`temp <- as.matrix(rbind(1:length(vocab), as.integer(as.matrix(sortedData[d, ]))))`

**Comment by kbenoit** [comment]
Thanks and well-spotted! Fixed in 0.9.1-9.

**Comment by kbenoit** [comment]
And in 0.9.1-10 I improved the efficiency almost 4x by creating the stm object from the sparse matrix indexes without the costly as.matrix conversion.
