### ISSUE TITLE
Tidy up documentation

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#870]
Based on the edits Ken has made to his PDF of the manual.

**Comment by lmkirvan** [comment]
You probably caught this already but I noticed an error in the documentation for fcm.  

> Note: if x is a dfm object, then context can only be "windows".

I think that this should be 

> Note: if x is a dfm object, then context can only be "documents".

**Comment by stefan-mueller** [comment]
In the documentation for `dfm` , we might also explain the `remove` options more precisely. In particular, `remove_punct` and `remove_twitter` are only mentioned in the examples, not in the "usage" or "arguments" sections.

**Comment by kbenoit** [comment]
@stefan-mueller None of those are "remove" options in dfm any longer, they are all part of `tokens()`. So their documentation is covered by `...` - although I agree this could be more clear.

See also https://github.com/kbenoit/quanteda/issues/690#issuecomment-317806087.
