### ISSUE TITLE
Rethink API's consistency in light of Wickham's comments

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#874]
Hadley Wickham gave us valuable comments on our APIs. Here is my note:

## Implementation
- Use [tidy evaluation](https://cran.r-project.org/web/packages/rlang/vignettes/tidy-evaluation.html) for none-standard evaluation
- **stringr** can be used to handle `patterns` and `valuetypes` consistently

## Naming
According to him, consistency within package is more important than consistency with R's base function.
- `data_dfm_LGBexample` should be lowercased to be all snake cases
- `corpus_*` can be `crps_*`
- `tokens_*` cab be `tkns_*`
- `textstat_*` can be `ts_*`
- `textmodel_*` can be `tm_*`
- `ndoc` should be `n_doc`
- `nfeature` should be `n_feature`

**Comment by kbenoit** [comment]
Extending the tidyeval to replace the pattern/valuetype combination is a great idea and something for 1.5. It may be more involved than we think.

We should remove the caps from `data_dfm_LBGexample`, agreed, but it's hard to deprecate data objects so we would probably make a copy (it's small so no problem here). Also, there are some arguments to the `dfm_weight()` family that still use camel case. Those need to be redone and the old ones deprecated.

On the shortening the core commands, I don't see any compelling reason to do that.
