### ISSUE TITLE
tokens operations in dfm() are partly disabled

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#882]
Part of this has to do with #690, since if we always call `tokens()` on `x` inside `dfm.tokens(x)`, it will perform these operations.

First, we don't currently remove elements before forming bigrams.  Below, the bigrams containing "b" should be eliminated.
```r
char <- "a b c d e"

# doesn't remove bigrams containing "b"
dfm(char, remove = "b", ngrams = 2)
## Document-feature matrix of: 1 document, 4 features (0% sparse).
## 1 x 4 sparse Matrix of class "dfmSparse"
## docs    a_b b_c c_d d_e
##        features
##   text1   1   1   1   1
```

Second, while this works:
```r
toks <- tokens(char)
toks <- tokens_remove(toks, "b", padding = TRUE)

# correct
tokens_ngrams(toks, 2)
## tokens from 1 document.
## Component 1 :
## [1] "c_d" "d_e"
```
these are wrong:
```r
# wrong: does not form bigrams
# wrong: counts the pad
dfm(toks, ngrams = 2)
## Document-feature matrix of: 1 document, 5 features (0% sparse).
## 1 x 5 sparse Matrix of class "dfmSparse"
##        features
## docs      a c d e
##   text1 1 1 1 1 1

# wrong: does not form bigrams
# wrong: does not remove b
dfm(toks, remove = "b", ngrams = 2)
## Document-feature matrix of: 1 document, 5 features (0% sparse).
## 1 x 5 sparse Matrix of class "dfmSparse"
##        features
## docs      a c d e
##   text1 1 1 1 1 1
```

**Comment by kbenoit** [comment]
Note that in the first test above, it renders this untrue, from the documentation of `?dfm`:

> The default behavior for remove/select when constructing ngrams using `dfm(x, ngrams > 1)` is to remove/select any ngram constructed from a matching feature. 

We need to fix the behaviour to make this true.

**Comment by koheiw** [comment]
I am making `tokens.tokens()` and managed make its ouput very close to `tokens.character()`, but there is one condition where I cannot. 

Currently, `tokens.character()` works like this with the `remove_hyphens` argument:
```r
tokens('a b-c d', remove_hyphens = FALSE, remove_punct = TRUE)
# tokens from 1 document.
# text1 :
#     [1] "a" "b" "-" "c" "d"

tokens('a b-c d', remove_hyphens = TRUE, remove_punct = TRUE)

# tokens from 1 document.
# text1 :
#     [1] "a" "b" "c" "d"
```
With `tokens.tokens(remove_hyphens = FALSE)`, I have to insert new tokens to create `c("a",  "b", "c", "d")` from `c("a",  "b-c", "d")`, but it is easy to make `c("a",  "b c", "d")` from `c("a",  "b-c", "d")`. I also think it might be more useful to keep `"b-c"` in `tokens.character(remove_hyphens = FALSE)`. Current behavior is more like `split_hyphens = TRUE`.

**Comment by koheiw** [comment]
It is, however, possible to insert element if I upgrade `qatd_cpp_tokens_replace()`.

**Comment by kbenoit** [comment]
It doesn't have to match perfectly, and the idea is to allow (eventually) different tokenisation engines, so we will never have a perfect match. I think this is better than trying to reprogram the C++ functions to try to match the current `tokens()` behaviour.

**Comment by methodds** [comment]
Hi,

I can't use stemming for a corpus with the latest version. Is this related?
Here's the error:
```
yt_dfm <- dfm(yt$comment_text, groups = yt$max_t4, stem = TRUE)

Error in char_wordstem.character(featnames(x), language = language) : whitespace detected: you can only stem tokenized texts 
11. stop("whitespace detected: you can only stem tokenized texts") 
10. char_wordstem.character(featnames(x), language = language) 
9. char_wordstem(featnames(x), language = language) 
8. dfm_wordstem.dfm(x, language) 
7. dfm_wordstem(x, language)
 6. dfm.dfm(result, tolower = FALSE, stem = stem, valuetype = valuetype, verbose = verbose, ...) 
5. dfm(result, tolower = FALSE, stem = stem, valuetype = valuetype, verbose = verbose, ...) 
4. dfm.tokenizedTexts(temp, verbose = verbose, tolower = FALSE, stem = stem, remove = remove, select = select, groups = groups, thesaurus = thesaurus, dictionary = dictionary, valuetype = valuetype, start_time = start_time) 
3. dfm(temp, verbose = verbose, tolower = FALSE, stem = stem, remove = remove, select = select, groups = groups, thesaurus = thesaurus, dictionary = dictionary, valuetype = valuetype, start_time = start_time) 2. dfm.character(yt$comment_text, groups = yt$max_t4, stem = TRUE) 
1. dfm(yt$comment_text, groups = yt$max_t4, stem = TRUE)
```
The corpus is pretty big, but if needed I can also try to set up a reproducable example.

**Comment by kbenoit** [comment]
Please do supply a reproducible example and we will try to fix this asap. Probably has to do with something we introduced with the new `dfm_group()` function.

**Comment by methodds** [comment]
Ok, please find an image for reproduction [here](http://polsoz.uni-bamberg.de:1337/data/ted/dfm_stem_example.RData) (440mb, sorry).
And here is my session in case you need it:

```
yt_dfm <- dfm(yt$comment_text, groups = yt$max_t4, stem = TRUE)


sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 18.2

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods  
[8] base     

other attached packages:
 [1] bindrcpp_0.2      dplyr_0.7.2       purrr_0.2.2.2     readr_1.1.1      
 [5] tidyr_0.6.3       tibble_1.3.3      ggplot2_2.2.1     tidyverse_1.1.1  
 [9] sentimentr_2.0.0  GGally_1.3.1      ggdendro_0.1-20   textmineR_2.0.5  
[13] Matrix_1.2-10     lubridate_1.6.0   gridExtra_2.2.1   reshape2_1.4.2   
[17] sjPlot_2.3.1.9000 sjmisc_2.5.0.9000 scales_0.4.1      stm_1.2.2        
[21] stringr_1.2.0     quanteda_0.9.9.86

loaded via a namespace (and not attached):
 [1] nlme_3.1-128        httr_1.2.1          RColorBrewer_1.1-2 
 [4] tools_3.4.1         TMB_1.7.10          R6_2.2.2           
 [7] DT_0.2              sjlabelled_1.0.1    lazyeval_0.2.0     
[10] colorspace_1.3-2    nnet_7.3-12         mnormt_1.5-5       
[13] compiler_3.4.1      rvest_0.3.2         xml2_1.1.1         
[16] sandwich_2.3-4      labeling_0.3        effects_3.1-2      
[19] lmtest_0.9-35       mvtnorm_1.0-6       psych_1.7.5        
[22] blme_1.0-4          digest_0.6.12       foreign_0.8-69     
[25] minqa_1.2.4         stringdist_0.9.4.4  pkgconfig_2.0.1    
[28] htmltools_0.3.6     lme4_1.1-13         readxl_1.0.0       
[31] pwr_1.2-1           htmlwidgets_0.8     rlang_0.1.1        
[34] shiny_1.0.3         bindr_0.1           jsonlite_1.5       
[37] zoo_1.8-0           magrittr_1.5        modeltools_0.2-21  
[40] textclean_0.3.1     Rcpp_0.12.12        munsell_0.4.3      
[43] RcppProgress_0.3    abind_1.4-5         stringi_1.1.5      
[46] multcomp_1.4-6      merTools_0.3.0      MASS_7.3-47        
[49] plyr_1.8.4          parallel_3.4.1      forcats_0.2.0      
[52] lattice_0.20-34     haven_1.1.0         splines_3.4.1      
[55] sjstats_0.10.3.9000 hms_0.3             knitr_1.16         
[58] codetools_0.2-15    stats4_3.4.1        fastmatch_1.1-0    
[61] glue_1.1.1          data.table_1.10.4   RcppParallel_4.3.20
[64] modelr_0.1.1        nloptr_1.0.4        lexicon_0.4.0      
[67] httpuv_1.3.3        cellranger_1.1.0    gtable_0.2.0       
[70] reshape_0.8.6       assertthat_0.2.0    mime_0.5           
[73] coin_1.2-1          syuzhet_1.0.2       xtable_1.8-2       
[76] broom_0.4.2         coda_0.19-1         survival_2.40-1    
[79] arm_1.9-3           glmmTMB_0.1.1       corrplot_0.77      
[82] TH.data_1.0-7  
```

**Comment by kbenoit** [comment]
The problem is that you are trying to stem features that contain whitespace, for whatever reason. Inspecting some of the intermediate objects reveals some pretty crazy stuff in your text.

Here are the tokens that contain a simple space character:
```r
yt_toks <- tokens(yt$comment_text)
yt_toks_withwhitespace <- tokens_select(yt_toks, " ", valuetype = "regex")
head(yt_toks_withwhitespace[lengths(yt_toks_withwhitespace) > 0])
tokens from 6 documents.
# text507 :
# [1] " ̶"
# 
# text582 :
# [1] " ͡"       " \u035c" " ͡"      
# 
# text586 :
# [1] " ͡"       " \u035c" " ͡"      
# 
# text590 :
# [1] " ͡"       " \u035c" " ͡"      
# 
# text591 :
# [1] " ͡"       " \u035c" " ͡"      
# 
# text592 :
# [1] " ͡"       " \u035c" " ͡"   
```

You can remove these in the following way:
```r
yt_toks_nosymbols <- tokens(yt_toks, remove_symbols = TRUE, remove_punct = TRUE)
yt_toks_nosymbols <- tokens_remove(yt_toks_nosymbols, " ", valuetype = "regex")

yt_dfm <- dfm(yt_toks_nosymbols, stem = TRUE, verbose = TRUE)
# Creating a dfm from a tokens object ...
# ... lowercasing
# ... found 1,126,527 documents, 460,612 features
# ... stemming features (English), trimmed 73369 feature variants
# ... created a 1,126,527 x 387,244 sparse dfm
# ... complete. 
# Elapsed time: 6.66 seconds.
```

**Comment by methodds** [comment]
Thanks for inspecting this. Do you know what's the problem here? Is this possible an encoding issue? These texts are youtube comments and I don't understand why features are mixed up with whitespace.

**Comment by kbenoit** [comment]
Here's the issue: (from the 592nd document)

```r
txt <- "( ͡° ͜ʖ ͡°) Who's the chick in your profile picture, I see her everywhere"
tokens("( ͡° ͜ʖ ͡°) Who's the chick in your profile picture, I see her everywhere")
# tokens from 1 document.
# text1 :
#  [1] "("          " ͡"          "°"          " \u035c"    "ʖ"          " ͡"          "°"          ")"          "Who's"     
# [10] "the"        "chick"      "in"         "your"       "profile"    "picture"    ","          "I"          "see"       
# [19] "her"        "everywhere"
```
`stringi::stri_trim_both()` would get rid of that leading space.

**Comment by koheiw** [comment]
As for ngrams, I noticed that `dfm` does not have `ngram` argument, so there is no `tokens_ngrams` in it. We can generate tokens ngrams in `dfm` but only in `dfm.tokens`. We should not do this to if we want to keep the signature of the `dfm.tokens` and `dfm.dfm` the same.

**Comment by kbenoit** [comment]
Ah but here is the beauty of #690: `dfm.tokens(x, ...)` will internally still call `tokens(x, ...)` just as `dfm.character(x, ...)` does already. We can do this because of the way that `tokens.tokens(x, ...)` now works, which if no arguments are called that are not already implemented, should just return itself. So the ellipsis passing not only will work for the tokens arguments, but also makes the "one-signature" function used in `dfm()` now truly functioning as one signature.

**Comment by methodds** [comment]
Sorry for spamming in this closed issue one more time, but I now encountered the problem with whitespace in other datasets for which I'm sure there was no error message in older quanteda versions. Are you sure you want the users handle such cases manually? The routine explained above,
`` yt_toks_nosymbols <- tokens_remove(yt_toks_nosymbols, " ", valuetype = "regex") ``, couldn't this be implemented automatically for robustness? I can't think of any reason why users would ever want to keep these weird whitespaces.

**Comment by kbenoit** [comment]
Not at all @methodds - can you put the error you are now encountering into a new issue, so we can reproduce and fix it? Would be very important to catch this now, as we are about to submit a CRAN update!

**Comment by methodds** [comment]
Sure, I opened #909.
