### ISSUE TITLE
selectFeatures and regular expressions

### ISSUE THREAD

**Issue by rafaelrpaiva** [kbenoit/quanteda#89]
I'm sorry if it's not the best place for that, but I'm trying to use ` selectFeatures()` function in a dfm to test performance of searching directly a word, but apparently using regular expressions inside that function is not working as expected.

* I created a 2-ngram dfm for the exampleString text, and I'm trying to search every 2-gram who has the word "thousands".

```{r}
dfm_n2 <- dfm(exampleString, ngrams = 2, concatenator = " ")
selectFeatures(dfm_n2, "^thousands.*$", valuetype="regex")
selectFeatures(dfm_n2, "^(thousands).*$", valuetype="regex")
```

The selectFeatures return everything, not only the ngrams starting with the word. What's wrong?

PS: I'm using the 0.9.2 version installed directly from cran.

**Comment by kbenoit** [comment]
The problem is your regular expression.  Here you only need a simpler pattern match, so use:

    grep("thousands", features(dfm_n2), value = TRUE)
    ## [1] "of thousands"    "thousands of"    "by thousands"    "thousands since"

or 

    > selectFeatures(dfm_n2, "thousands")
    kept 4 features, from 1 supplied (glob) feature types
    Document-feature matrix of: 1 document, 4 features.
    1 x 4 sparse Matrix of class "dfmSparse"
           features
    docs    of thousands thousands of by thousands thousands since
      text1            5            5            1               1
