### ISSUE TITLE
Add character class valuetype for pattern

### ISSUE THREAD

**Issue by koheiw** [kbenoit/quanteda#890]
This should be easily done through `rege2id`. It would look like this:

```r
tokens_remove(toks, pattern = c('P', 'N'), valuetype = 'charclass')

tokens_remove(toks, pattern = c('Kana', 'Han'), valuetype = 'charclass')
```

**Comment by koheiw** [comment]
This issue needs some discussion to specify its behavior. I think, for example,  `
tokens_select(toks, pattern = 'L', valuetype = 'charclass')` should select token types comprised of ONLY letters. If so, we should only generate a regex pattern `'^[\\p{L}]+$'` and set `valuetype = regex` internally.

`stri_detect_charclass` is faster than `stri_detect_regex` but we cannot select types ONLY with a letters with it:
```r
require(stringi)

toks <- tokens(data_corpus_inaugural)
types <- attr(toks, 'types')

microbenchmark::microbenchmark(
stri_detect_charclass(types, '\\p{L}'),
stri_detect_regex(types, '\\p{L}')
)

# Unit: microseconds
# expr     min       lq      mean   median       uq      max neval
# stri_detect_charclass(types, "\\\\p{L}")  95.544  461.511  591.5141  491.404  578.286 4984.433   100
# stri_detect_regex(types, "\\\\p{L}") 834.743 1753.994 1992.5693 1889.486 2186.172 4506.719   100

stri_detect_charclass('abc', '\\p{L}') # TRUE
stri_detect_regex('abc', '\\p{L}') # TRUE

stri_detect_charclass('abc.', '^[\\p{L}]+$') # Error 
stri_detect_regex('abc.', '^[\\p{L}]+$') # FALSE
```

**Comment by kbenoit** [comment]
We've decided not to do this, since charclass is not really for word matches, and since it can be built into regex matches easily.
