### ISSUE TITLE
create a tokens_segment()

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#902]
This would mean:

Running `tokens_segment(tokens(a_corpus))` would be roughly the same as `tokens(corpus_segment(a_corpus))`.

**Comment by kbenoit** [comment]
How's this for an idea: we keep the groups as is, add a `corpus_group()`, and create new functions to replace `corpus_segment()`, called `corpus_split()`, and `tokens_split()`. We keep the older reshape and segment functions as they are, but deprecate them since the new segment functions will do what they did previously.

We need to design the `tokens_split()` to be as consistent as possible with `corpus_split()`, and right now the `tokens_segment()` is basically like the `corpus_segment(x, what = "other")`. Allowing sentence segmentation is really important for users who don't know how to construct a character class for sentences or paragraphs. (And, `corpus_segment()` uses the *stringi* sentence boundary definitions, so it's smarter.) The `what = "tags"`, tags is slightly different again, but it's a super-useful function (and easy to implement in a `tokens_split()`.

**Comment by koheiw** [comment]
I was thinking to name them `corpus/tokens_join()` and `corpus/tokens_split()` (`dfm_group()` will remain the same, because we cannot split a dfm), but I am OK with `corpus/tokens_group()` and `corpus/tokens_split()`.

I had noticed that `corpus_segment()` needs generalization by adding arguments:

- `position` (`before/after`): segment before or after the delimiter
- `remove_delimiter` (`TRUE/FALSE`): remove the delimiter after segmentation
- `save_delimiter` (`TRUE/FALSE`): save the matched delimiter to docvars

Combination of these should cover all the cases. For example, sentences are `position = after` & `remove_delimiter = FALSE` & `save_delimiter = FALSE`; tags are  `position = before` & `remove_delimiter = TRUE` & `save_delimiter = TRUE`. Add `save_delimiter` is a bit complex, but other two are easy implement.

If I add these to `corpus_segment()` and `tokens_segment()`, they will be almost the same.

**Comment by kbenoit** [comment]
Interesting idea. any `tokens_remove()` operation would mess up the positions though, no?

Also one of the ideas here is to make this as simple as possible. Maybe `*_split()` should be a fairly basic but flexible function, and a wrapper function could call it with options specific to tags? 

Also note that the sentence splitter for character/corpus has access to better methods than just recognizing sentence punctuation marks as does the draft `tokens_segment()`. Once we allow a POS tagged such as **spacyr** to do the tokenization and tagging, it also has sentence identifiers. So we don't want to make all functions depend on matching a character class, especially given the complexities of sentence boundaries in other languages.

**Comment by koheiw** [comment]
These three arguments can be just internal, but this is the way I will implement `tokens_split()`. Set `pattern = {\\p}` when `what = `sentences` is trivial, but `tokens_split()` will have only "sentences" or "other" for `what` (`tag` will be supported in the future). When it is "other", users will have full control with those new arguments.

I have seen ICU's definition of sentence boundaries. It is basically just a period or new lines:
http://unicode.org/reports/tr29/#Default_Sentence_Boundaries
Extra rules are not to segment texts where it shouldn't (e.g. period after acronyms). These errors are less likely to happen in tokens.

As for POS taggers, you should check my prototype:
https://github.com/kbenoit/quanteda/blob/dev-tokens_select_pos/R/tokens_select_pos.R

**Comment by kbenoit** [comment]
@koheiw can you make a few modifications to this, to make it consistent with the `corpus_segment()`/`char_segment()` behaviour? I know we discussed leaving it out, but you might be able to use the tagging code you are working on to make this work. (And, we will keep this internal for now.)

Right now:
```r
txt <- ". This is, is a sentence!  Second sentence."

char_segment(txt, "tag", delimiter =  "[^\\P{P}#@'-]", valuetype = "regex")
# [1] "This is"         "is a sentence"   "Second sentence"

char_segment(txt, "other", delimiter =  "[^\\P{P}#@'-]", valuetype = "regex")
# [1] "."                "This is,"         "is a sentence!"   "Second sentence."
```
The segmentation for tags is how we split texts in `textstat_collocations()` to ensure that terms with punctuation in between are not considered as collocations (see https://github.com/kbenoit/quanteda/blob/master/R/textstat_collocations.R#L197). But this has no equivalent in `tokens_segment()`, because we did not implement `what = "tag"` for that function.

```r
toks <- tokens(txt)

quanteda::tokens_segment(toks, "tag", delimiter =  "[^\\P{P}#@'-]", valuetype = "regex")
# Error in match.arg(what) : 'arg' should be one of “sentences”, “other” 

quanteda::tokens_segment(toks, "other", delimiter =  "[^\\P{P}#@'-]", valuetype = "regex")
# tokens from 8 documents.
# text1.1 :
# [1] "."    "This"
# 
# text1.2 :
# [1] ","  "is"
# 
# text1.3 :
# [1] "a"
# 
# text1.4 :
# [1] "sentence"
# 
# text1.5 :
# [1] "!" "A"
# 
# text1.6 :
# [1] "second"
# 
# text1.7 :
# [1] "sentence"
# 
# text1.8 :
# [1] "."
```
and the second is not what we should expect either - this ought to be more like:
```r
# tokens from 4 documents.
# text1.1 :
# [1] "."    "This"
# 
# text1.2 :
# [1] ","  "is"  "a"  "sentence"
# 
# text1.3 :
# [1] "!" "A"  "second"  "sentence"
# 
# text1.4 :
# [1] "."
```

**Comment by koheiw** [comment]
You simply should not use what you want to keep (non-punctuation) as delimiters. My addition of `remove_delimiter` in a new PR should fulfill you needs.

```r
txt <- ". This is, is a sentence!  Second sentence."

char_segment(txt, "other", delimiter = "[\\p{P}#@'\\-]", valuetype = "regex", remove_delimiter = TRUE)

# tokens from 4 documents.
# text1.1 :
#     character(0)
# 
# text1.2 :
#     [1] "This" "is"  
# 
# text1.3 :
#     [1] "is"       "a"        "sentence"
# 
# text1.4 :
#     [1] "Second"   "sentence"

tokens_segment(tokens(txt), "other", delimiter = "[\\p{P}#@'\\-]", valuetype = "regex", remove_delimiter = TRUE)

# tokens from 4 documents.
# text1.1 :
#     character(0)
# 
# text1.2 :
#     [1] "This" "is"  
# 
# text1.3 :
#     [1] "is"       "a"        "sentence"
# 
# text1.4 :
#     [1] "Second"   "sentence"

```
Nonetheless, this is a temporary solution for collocation analysis. We should let C++ function to ignore specified types of tokens as segmenting a large token object is really inefficient.

**Comment by kbenoit** [comment]
See https://github.com/kbenoit/quanteda/pull/917#issuecomment-320987041

**Comment by kbenoit** [comment]
See my R-based workaround hard-coded for punctuation, `tokens_segment_by_punctuation()`, added in #922. Is this much slower than doing it in C++?
