### ISSUE TITLE
generation of ngrams is producing string of prefix, suffix and elsewhere underscores

### ISSUE THREAD

**Issue by myusrn** [kbenoit/quanteda#923]
When i use quanteda functions for generating ngrams from my corpus text, including just an excerpt that can repro issue below, i'm finding i end up with feature names / ngram results that have string of prefix, suffix and elsewhere underscores.   As shown in repro example this then leads to issues creating data.table with pre-processed column additions to help optimize next word prediction lookups.  

Am i missing some parameter setting that would avoid this issue?  In some cases this leads to there being 1-grams/unigrams in result set once you strip off the leading or training underscores which is a problem for dataset only supposed to have 2 thru 5 ngrams present.

-------------------------------------------------------
```
version$version.string; paste("quanteda package version", as.character(packageVersion("quanteda")))

corpusText = "Palo Alto Players, Lucie Stern Theatre, 1305 Middlefield Road, Palo Alto. $15-$32. paplayers.org or 650-329-0891Test first period -____-\"I think you've taken control\""

dfmNgrams <- dfm(corpusText, tolower = T, stem = F, # what = "fastestword",
    remove_numbers = T, remove_punct = T, remove_symbols = T, remove_separators = T,
    remove_twitter = T, remove_hyphens = T, remove_url = T, 
    ngrams = 2:5  #, skip = 0, concatenator = "_"
) # use tokens_wordstem(dfm) if you later want result that stem = T would have produced
dtNgrams <- data.table(ngram = featnames(dfmNgrams), keep.rownames = F, stringsAsFactors = F)
dtNgrams[, base := strsplit(ngram, "_[^_]+$")[[1]], by = ngram]
dtNgrams[, prediction := tstrsplit(ngram, paste(base, "_", sep = ""), fixed = T, keep = 2)[[1]], by = ngram]
dtNgrams[, ngramsize := length(strsplit(ngram, "_")[[1]]), by = ngram]
dtNgrams[, frequency := colSums(dfmNgrams)]

#check for one or more '_' prefix, suffix and anywhere in between
dtNgrams[grep("^_{1,}", dtNgrams$ngram),]; dtNgrams[grep("_{1,}$", dtNgrams$ngram),]; dtNgrams[grep("_{2,}", dtNgrams$ngram),] 
```
-------------------------------------------------------

Note that i also tested and get the same result using the following alternative quanteda calls to generate ngrams.   The existence of these other apis is also somewhat confusing to me as it has me wondering which calls are the optimal way to arrive at a dfm.

-------------------------------------------------------
```
#corpusTokens <- quanteda::tokenize(corpusText, what = "word", # using library prefix to ensure readr::tokenize not used
corpusTokens <- tokens(corpusText, what = "word", # not sure what the difference is between tokens and tokenize
        remove_numbers = T, remove_punct = T, remove_symbols = T, remove_separators = T,
        remove_twitter = T, remove_hyphens = T, remove_url = T #,
        #ngrams = 1, skip = 0, concatenator = "_", simplify = F, verbose = F
)
corpusTokensNgrams <- tokens_ngrams(corpusTokens, n = 2:5)
dfmNgrams <- dfm(corpusTokensNgrams, tolower = T, stem = F)
```
-------------------------------------------------------

**Comment by kbenoit** [comment]
Running the code above, 1st block, I get:
```r
> head(dtNgrams)
                 ngram    base  prediction ngramsize frequency
1:           palo_alto    palo        alto         2         2
2:        alto_players    alto     players         2         1
3:       players_lucie players       lucie         2         1
4:         lucie_stern   lucie       stern         2         1
5:       stern_theatre   stern     theatre         2         1
6: theatre_middlefield theatre middlefield         2         1
> tail(dtNgrams)
                                    ngram                            base prediction ngramsize frequency
1: paplayers.org_or_0891test_first_period paplayers.org_or_0891test_first     period         5         1
2:             or_0891test_first_period_i        or_0891test_first_period          i         5         1
3:          0891test_first_period_i_think         0891test_first_period_i      think         5         1
4:            first_period_i_think_you've            first_period_i_think     you've         5         1
5:            period_i_think_you've_taken           period_i_think_you've      taken         5         1
6:           i_think_you've_taken_control            i_think_you've_taken    control         5         1
```
Looks ok to me. (Using v0.9.9.9)

**Comment by myusrn** [comment]
i get the following different result 

```
> version$version.string; paste("quanteda package version", as.character(packageVersion("quanteda"))) [1] "R version 3.3.3 (2017-03-06)" [1] "quanteda package version 0.9.9.65" > head(dtNgrams)                  ngram    base  prediction ngramsize frequency 1:           palo_alto    palo        alto         2         2 2:        alto_players    alto     players         2         1 3:       players_lucie players       lucie         2         1 4:         lucie_stern   lucie       stern         2         1 5:       stern_theatre   stern     theatre         2         1 6: theatre_middlefield theatre middlefield         2         1 > tail(dtNgrams)                            ngram                          base prediction ngramsize frequency 1: or_0891test_first_period_____ or_0891test_first_period_____         NA         8         1 2:  0891test_first_period______i    0891test_first_period_____         NA         9         1 3:     first_period______i_think           first_period______i         NA         9         1 4:    period______i_think_you've           period______i_think         NA         9         1 5:     _____i_think_you've_taken           _____i_think_you've         NA         9         1 6:  i_think_you've_taken_control          i_think_you've_taken         NA         5         1
--
 
> | >
>
```

**Comment by kbenoit** [comment]
Please re-try installing the GitHub version. v0.99 is with CRAN right now and should be published there within 2-3 days.

**Comment by myusrn** [comment]
Thanks, executing following to update quanteda package to GitHub version allowed me to repro result you got.  

q1. Does one have to move to r 3.4.1 client with this v0.99 release or is that just a github drop package installer related matter given it is hardcoded bot build using 3.4 Rcpp package?

q2. Any insights on the buried question about their being any difference using dfm(corpus, . . .) vs dfm(tokens_ngrams(tokenize/tokens(. . .), . . .)) approach to arriving at dfm object?

q3. Anything in quanteda package to facilitate adding a katz back-off good-turning discounting / probability column to data.table derived from dfm object to help choosing best case result when dfm contains 2 - 5 ngrams?

```
install.packages("Rcpp"); install.packages("devtools") # using r 3.4.1 client 
require(Rcpp); require(devtools); install_github("kbenoit/quanteda")
# optionally uninstall "Rtools 3.4" afterwards to recover 800MB of %systemdrive%/RBuildTools/3.4 space
```

```
> version$version.string; paste("quanteda package version", as.character(packageVersion("quanteda")))
[1] "R version 3.4.1 (2017-06-30)"
[1] "quanteda package version 0.99"
> 
```

**Comment by kbenoit** [comment]
Q1: I think it will work with the standard package installer using the pre-compiled binaries (for Windows and macOS) once on CRAN.

Q2: They should be the same but doing it in parts - first tokens, maybe some manipulation of the tokens, then dfm - gives you more control. `dfm()` is a convenience one-step method.

Q3: Sorry can't help you there - maybe StackOverflow?

**Comment by myusrn** [comment]
Thanks for additional details that helps.

Not sure where i should take related discussions, perhaps quanteda specific stackoverflow forum vs here ???, but here is something i also found using quanteda::dfm(corpusObject, . . . ).  I found it to performs significantly slower with large sample sizes, e.g.  100 & 400k lines of text vs 1 & 10k algorithm vetting sample sizes, to the point of appearing like it wouldn't complete in any acceptable amount of time if the remove parameter is specified.  I had been using remove parameter to strip out bad words using both a dataset made up of the  [7 dirty words ](https://en.wikipedia.org/wiki/seven_dirty_words) and a larger one generated from one of the publicly maintained bad words csv downloads.   

Is that an expected result when including the "remove" parameter in dfm calls, which i think may have gone by "ignoredFeatures" parameter name, e.g. ignoredFeatures = stopwords("english"), in older dfm implementations?

**Comment by kbenoit** [comment]
`dfm.corpus()` has to tokenize the text first, so it's always slower than `dfm.tokens()`. Suggest you try comparing:

1. tokens(corpusObject) %>% tokens_remove(sevendirtywords %>% dfm
2. tokens(corpusObject) %>% dfm %>% dfm_remove(sevendirtywords)
3. dfm(corpusObject, remove = sevendirtywords)

and let us know which performs better, posting the results in https://github.com/kbenoit/quanteda/issues/498 perhaps.

**Comment by myusrn** [comment]
Thanks for the followup on these matters.   

Back on the source of this issue's initial post when i expand use of github v0.99 release to my larger sample size, e.g. 56714 lines of text, i'm again able to repro the matter of '_' prefix, suffix and elsewhere hits being found in results that confuse calls to progress featnames() set when building a data.table out dfm result.  For example it causes my approach to computing the prediction column, ngram last word extraction, to throw errors when it first hits an unexpected presence of '_' and generate NA results from that point forward.  

You can repro using the following, note i commented out dfm_select() searches for unexpected '_' pattern as it appeared to be much faster putting featnames() in a data.table and doing grep() searches against that.

```
#corpusText = "Palo Alto Players, Lucie Stern Theatre, 1305 Middlefield Road, Palo Alto. $15-$32. paplayers.org or 650-329-0891Test first period -____-\"I think you've taken control\""
tempFileName <- tempfile()
download.file("https://mysawestus.blob.core.windows.net/public/corpusTextEx.txt", tempFileName)
require(readr); corpusText <- read_lines(tempFileName, progress = F) # 4 MB / 56714 lines 
unlink(tempFileName); rm(tempFileName)

require(quanteda)
dfmNgrams <- dfm(corpusText, tolower = T, stem = F,
    remove_numbers = T, remove_punct = T, remove_symbols = T, remove_separators = T,
    remove_twitter = T, remove_hyphens = T, remove_url = T, # what = "fastestword",
    ngrams = 2:5  #, skip = 0, concatenator = "_"
) # use tokens_wordstem(dfm) if you later want result that stem = T would have produced
#dfm_select(dfmNgrams, "^_{1,}", selection = "keep", valuetype = "regex") # look for '_' prefix
#dfm_select(dfmNgrams, "_{1,}$", selection = "keep", valuetype = "regex") # look for '_' suffix
#dfm_select(dfmNgrams, "_{2,}", selection = "keep", valuetype = "regex") # look for '_' anywhere in between

require(data.table)
dtNgrams <- data.table(ngram = featnames(dfmNgrams), keep.rownames = F, stringsAsFactors = F)
dtNgrams[, base := strsplit(ngram, "_[^_]+$")[[1]], by = ngram]
dtNgrams[, prediction := tstrsplit(ngram, paste(base, "_", sep = ""), fixed = T, keep = 2)[[1]], by = ngram]
dtNgrams[, ngramsize := length(strsplit(ngram, "_")[[1]]), by = ngram]
dtNgrams[, frequency := colSums(dfmNgrams)]

# check for one or more '_' prefix, suffix and anywhere in between hits
dtNgrams[grep("^_{1,}", dtNgrams$ngram),]; dtNgrams[grep("_{1,}$", dtNgrams$ngram),]; dtNgrams[grep("_{2,}", dtNgrams$ngram),] 
head(dtNgrams); tail(dtNgrams)
```

```
                             ngram                         base prediction ngramsize frequency
 1:                        _per_day_                    _per_day_         NA         3         1
 2:                      _____i_have                       _____i         NA         7         1
 3:              _____i_have_finally                  _____i_have         NA         8         1
 4:     _____i_have_finally_accepted          _____i_have_finally         NA         9         1
 5: _____i_have_finally_accepted_the _____i_have_finally_accepted         NA        10         1
<snip />
```

**Comment by myusrn** [comment]
. . . and also just realized that it appears dfm(. . . , remove_numbers = T) doesn't appear to do what i might expect given executing the following on the dfm or data.table containing featnames(dfm) column returns hits that i assumed would have been stripped unless i'm using parameter incorrectly.

```
# check for one or more numbers anywhere in results, that remove_numbers = T should have handled
#dfm_select(dfmNgrams, "\\d+", selection = "keep", valuetype = "regex") 
dtNgrams[grep("\\d+", dtNgrams$ngram),]
```

```
                       ngram               base prediction ngramsize frequency
    1:         before_9.30pm             before     9.30pm         2         1
    2:        9.30pm_another             9.30pm    another         2         1
    3:    well_before_9.30pm        well_before     9.30pm         3         1
    4: before_9.30pm_another      before_9.30pm    another         3         1
    5:    9.30pm_another_had     9.30pm_another        had         3         1
   ---                                                                        
13279:         on_the_1st_of         on_the_1st         NA         4         1
13280:    the_1st_of_october         the_1st_of         NA         4         1
13281: by_usborne_on_the_1st  by_usborne_on_the         NA         5         1
13282: usborne_on_the_1st_of usborne_on_the_1st         NA         5         1
13283: on_the_1st_of_october      on_the_1st_of         NA         5         1
```

**Comment by kbenoit** [comment]
On the first: underscores are defined as "word" characters, and are therefore not removed through `remove_punct = TRUE`. You can however remove them like this:
```r
colnames(dtNgrams) <- stri_replace_all_regex(colnames(dtNgrams), "_{2,}", "")
dfm_compress(dtNgrams)
```

On the second, "9.30pm" is not a number. Words that contain numerals, such as "4ever" or "gr8" are not numbers. If you want to remove the numerals manually, you can use something like above, otherwise you can use `tokens_select()` or `dfm_select()` to remove any tokens or features that contain numerals.

**Comment by myusrn** [comment]
Thanks for clarifications.  

q1. Did you inadvertently reference "dtNgrams" [ data.table extraction of ngrams from dfm object ] instead of "dfmNgrams" [ dfm() call generated object ] in example workaround above?

q2. Would you typically expect users to remove "_{2,}", and "\d+[^\d]+\d?", hits from corpus text before generating dfm object vs afterwards using proposed workaround above, i.e. is doing it after the fact expected to be less efficient?

**Comment by kbenoit** [comment]
You're right that should be `dfmNgrams`.

You can use `tokens_remove()` on a tokens object, or `dfm_remove()` after creating the dfm. I'm interested to know for your application which is more efficient.

`featnames()` is an encapsulation for `colNames()`, but you cannot assign `featnames` but you can assign `colNames()`. Here you are tinkering directly with the structure of a **quanteda** object, not through a **quanteda** function, so it comes with an Advisory Warning (but works).

**Comment by myusrn** [comment]
Thanks these are helpful details to understand when trying to address undesired word tokens arising with my corpus sample distribution.  In my application i had a placeholder tidyCorpus() function intended in to handle scrubbing anything from corpusText i didn't want included in quanteda sentence and work tokenization and ngram generation activities.   I'll have to do a comparison to see if the system.time()[["user.self"]] for addressing underscores and words containing numerals is more performant being done at that point or being done using quanteda dfm object. 
```
tidyCorpus <- function(corpusText) { 
    corpusTextClean <- gsub("_+", "", corpusText) # 1 or more underscores for some reason only in bigger sample sizes
    #corpusTextClean <- gsub("_{2,}", "", corpusText) # 2 or more underscores leaving email and emoticon cases intact
    corpusTextClean <- gsub("\d+[^\d]+\d?", "", corpusText) # words that contain numerals, e.g. 9:30pm or 4ever or gr8
    corpusTextClean
}
```

**Comment by myusrn** [comment]
To conserve space i'm looking to generate all 2 thru 5-grams but only top 20 1-grams/unigrams.  When executing dfm(...,ngrams = 1) is there a recommended way to extract or remove all but the top 20 frequency 1-gram entries in that object and then merge that dfm object set with a dfm object containing all 2 thru 5-grams?
