### ISSUE TITLE
Add Option for Supplementary Column or Rows in Correspondence Analysis

### ISSUE THREAD

**Issue by cmldyu** [kbenoit/quanteda#925]
Thx for your work CA for large text data is possible. However, at present, I can only represent the tokens and the documents on a biplot, but cannot superimpose some supplementary information (like meta-data) on it.  Without it, the plot is very hard to be interpreted. Hope for an option for supplementary rows or column in CA will be available.

**Comment by stefan-mueller** [comment]
I'm not sure what you mean by extra columns, but keep in mind that all `textplot` objects are based on ggplot2, so you can easily add a title, subtitle or caption manually. For more information you might look at this [post](https://www.r-bloggers.com/subtitles-and-captions-with-ggplot2-v-2-2-0/). Would this solve your problem?

**Comment by kbenoit** [comment]
@stefan-mueller is correct, you can always embellish the plot with additional information, possibly from the docvars in the dfm, using manual commands.
