### ISSUE TITLE
Textstat_simil(dfmObj, method="cosine") calculation is not stable for empty rows

### ISSUE THREAD

**Issue by EricHe98** [kbenoit/quanteda#929]
The textstat_simil returns NaN for cosine distance calculations when the entire row of the dfm is composed of 0 values. This is a problem when tf-idf log-average weightings are used on highly similar documents; a document whose texts are a subset of the texts of other documents in the corpus will have term weightings of 0 for every term. 

```{r}
a <- corpus(c("a b c", "a b c d"))

(b <- dfm(a))
Document-feature matrix of: 2 documents, 4 features (12.5% sparse).
2 x 4 sparse Matrix of class "dfmSparse"
       features
docs    a b c d
  text1 1 1 1 0
  text2 1 1 1 1

(c <- tfidf(b, scheme_tf="logave"))
Document-feature matrix of: 2 documents, 4 features (12.5% sparse).
2 x 4 sparse Matrix of class "dfmSparse"
       features
docs    a b c d
  text1 0 0 0 0      
  text2 0 0 0 0.30103

textstat_simil(c, method="cosine")
      text1
text2   NaN
```

The NaN comes from division of 0, since cosine similarity divides the dot product of the two document vectors by the products of their magnitudes, and the magnitude of text1 is 0.

It would be best to throw an error when this occurs, or to automatically remove 0-magnitude rows during the calculation and give a warning. Another solution would be to set NaN values to 0, but this may mislead users who would expecting high similarity scores, since the raw text1 and text2 are almost identical.

**Comment by EricHe98** [comment]
Actually, I just read a solution in the comments in [this blog post](http://www.p-value.info/2013/02/when-tfidf-and-cosine-similarity-fail.html). Rather than using the [standard SMART idf](https://en.wikipedia.org/wiki/SMART_Information_Retrieval_System), which follows the formula

log (N / ni), 

N being the totalnumber of documents in the corpus and ni being the number of documents which contain at least one appearance of the term,

we instead calculate idfs using the formula

1 + log ( N / ni + 1).

This ensures that words which appear in every document in the corpus are not set to 0, allowing for stable and accurate cosine distance calculations. Perhaps this could be implemented as another option in the tfidf method argument?

**Comment by kbenoit** [comment]
On the first: Thanks for pointing this out. _tf-idf_ on a zero document frequency should be zero, in order words, _tf_ = 0 should turn a weight where that component is a product, into zero too.

On the second: While this is not an option in `tfidf()`, you can fine-tune the SMART components (smoothing parameters _K_ for instance) by multiplying `tf()` and `idf()` after computing them separately. We didn't implement all of these options in `tfidf()` because users found it confusing and because most never wanted or needed them.

**Comment by EricHe98** [comment]
Oh, the smoothing and K parameters in the docfreq() function are perfect. Thanks!
