### ISSUE TITLE
term similarities using similarity()

### ISSUE THREAD

**Issue by philippdreyer** [kbenoit/quanteda#93]
When trying to measure term similarities  for the words "economy","women", and "health" in the State of the Union (SOTU) corpus R does not return term similarities for "economy". 

similarity(dfmSOTU, c("economy", "health", "women"), method="cosine", n = 20)

**Comment by kbenoit** [comment]
No, not if that features does not exist in `SOTUdfm`, for instance if features are stemmed. So either report that there is no feature "economy" to report similarity for, or change your feature label in the `similarity()` command to whatever is returned by `wordstem("economic")`.
