### ISSUE TITLE
Create a corpus keep sentences? 

### ISSUE THREAD

**Issue by jimcat** [kbenoit/quanteda#936]
This is a suggestion rather than an issue. 

Currently, the functions `corpus_trim` and `corpus_trimsentences` allow you to get rid of parts of the corpus given a set filter. However doing the contrary would be interesting, i.e. keep only the sentences that match a set filter (and get rid of the rest). 

**This is actually possible** using `corpus_trim` and `corpus_trimsentences` with a 'negative lookahead' regex expression -- e.g. `/^((?!(EU)|(Europ)).)*$/g` would keep in the new corpus only sentences containing EU or any Europ* . However, this is a bit of a workaround that may be confusing or difficult to get to by some users. A function to trim the corpus and only keep sentences according to a filter would be more fit for this purpose and also could have interesting options like keeping previous and/or following sentences, etc.

**Comment by koheiw** [comment]
Thank you @jimcat . We are currently working to streamlining functions for corpus objects, so will try to reflect your suggestion. 

However, I prefer to select sentences by keywords in tokens and dfm. Please try in like this:
```r
corp <- corpus_segment(data_corpus_irishbudget2010)
toks <- tokens(corp)
mx <- dfm(toks)
mx2 <- mx[rowSums(dfm_select(mx, c('eu', 'europ*'))) > 0,]
mx3 <- dfm_group(mx2, docvars(mx2, '_document')) # merge all sentences 
head(mx3)
```
Here, you do not need to write complex regex to avoid false matches as texts are already tokenized.
