### ISSUE TITLE
Subset and add dictionaries

### ISSUE THREAD

**Issue by stefan-mueller** [kbenoit/quanteda#942]
Applying a dictionary with many keys to a large dfm can take very long, but researchers might be only interested in few categories of the dictionary. A command like `dictionary_subset()` with a similar syntax as `corpus_subset()` might be useful (see example below). But maybe there is already a base R option for this I am not aware of? Either way, I think a **quanteda**-specific implementation might be good for consistency.

Moreover, it would be great to merge entire dictionaries as it is implemented for corpora: `dictionary_joined <- dict_1 + dict_2`.  

```r
library(quanteda)
download.file("https://goo.gl/5gmwXq", tf <- tempfile())
mfdict <- dictionary(file = tf, format = "LIWC")

# subsetting that works (and which I currently use)
mfdict_subset1 <- mfdict[1]
str(mfdict_subset1)

# Formal class 'dictionary2' [package "quanteda"] with 2 slots
# ..@ .Data       :List of 1
# .. ..$ :List of 1
# .. .. ..$ : chr [1:16] "amity" "benefit*" "care" "caring" ...
# ..@ concatenator: chr " "

# does not work as it returns characters
mfdict_subset2 <- mfdict$HarmVirtue
str(mfdict_subset2)

# chr [1:16] "amity" "benefit*" "care" ...

# desired format
mfdict_subset <- dictionary_subset(mfdict, key == "HarmVirtue")

# or 
keys <- c("PurityVirtue", "HarmVirtue")
mfdict_subset <- dictionary_subset(mfdict, key %in% keys)

**Comment by kbenoit** [comment]
The standard `[` works just fine already, see below.  Did you have something else in mind?

```r
> mydict <- dictionary(list(christmas = c("Christmas", "Santa", "holiday"),
+                           opposition = c("Opposition", "reject", "notincorpus"),
+                           taxing = "taxing",
+                           taxation = "taxation",
+                           taxregex = "tax*",
+                           country = "america"))
> mydict
Dictionary object with 6 key entries.
- christmas:
  - christmas, santa, holiday
- opposition:
  - opposition, reject, notincorpus
- taxing:
  - taxing
- taxation:
  - taxation
- taxregex:
  - tax*
- country:
  - america
> mydict[2:3]
Dictionary object with 2 key entries.
- opposition:
  - opposition, reject, notincorpus
- taxing:
  - taxing
```

**Comment by koheiw** [comment]
Dictionary objects have a special internal structure, but it can be converted to a list and back to a dictionary. Please try:
```r
# subset
dictionary(as.list(mfdict)['HarmVirtue'])
# conbine
dictionary(c(as.list(mfdict[1:2]), as.list(mfdict[4])))
```

**Comment by stefan-mueller** [comment]
Thanks both! Yes, that's the output I was looking for. If you don't mind I make a quick PR and add the examples to the "dictionary" man page and the [LIWCalike](https://github.com/kbenoit/LIWCalike) manual? Subsetting and combining dictionaries might be useful for other users too.
