### ISSUE TITLE
text2vec comparisons fail in test-fcm.R

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#949]
No doubt because something changed in **text2vec**. Not failing on CI or CRAN because skipped if the package is not installed, and we do not Suggest it, but would be nice to fix.

**Comment by dselivanov** [comment]
In 0.5 logic was changed a bit. In 0.4 didn't count co-occurrences of the word with itself. Now we count them, so diagonal in `tcm` matrix is not empty anymore. I found with this gives better results in glove.
