### ISSUE TITLE
tokens_lookup return all instances when a word coexists across more than one dictionary list members

### ISSUE THREAD

**Issue by elyksenyah** [kbenoit/quanteda#954]
Currently the tokens_lookup returns the first instance found ...

    dict <- dictionary(list(country = 'United States',
    sea = c('Atlantic Ocean', 'Pacific Ocean','United States')))
    lis <- tokens("The United States has the Atlantic Ocean and the Pacific Ocean")
    tokens_lookup(lis, dict, exclusive=F)
     tokens from 1 document.
    text1 :
    [1] "The"     "COUNTRY" "has"     "the"     "SEA"     "and"     "the"     "SEA"    

It would be useful to return all instances. so:

    dict <- dictionary(list(country = 'United States',
    sea = c('Atlantic Ocean', 'Pacific Ocean','United States')))
    lis <- tokens("The United States has the Atlantic Ocean and the Pacific Ocean")
    tokens_lookup(lis, dict, exclusive=F)
    tokens from 1 document.
    text1 :
    [1] "The"     "COUNTRY" "has"     "the"     "SEA"     "and"     "the"     "SEA"    
    [2] "The"     "SEA" "has"     "the"     "SEA"     "and"     "the"     "SEA"   

Apologies if this has been raised and closed already.

Thanks
Kyle

**Comment by koheiw** [comment]
Thank you @elyksenyah ,

`tokens_lookup` counts the same word under different keys to allows multiple membership of words, but you can still get what you what:
```r
dict <- dictionary(list(country = 'United States',
                        sea = c('Atlantic Ocean', 'Pacific Ocean','United States')))
toks <- tokens("The United States has the Atlantic Ocean and the Pacific Ocean")

toks_dict1 <- tokens_lookup(toks, dict[1:2], exclusive = FALSE)
toks_dict2 <- tokens_lookup(toks, dict[2], exclusive = FALSE)

names(toks_dict1) <- paste(names(toks_dict1), 'd1', sep = '.')
names(toks_dict2) <- paste(names(toks_dict2), 'd2', sep = '.')

toks_dict <- c(toks_dict1, toks_dict2)

# tokens from 2 documents.
# text1.d1 :
#     [1] "The"     "COUNTRY" "has"     "the"     "SEA"     "and"     "the"     "SEA"    
# 
# text1.d2 :
#     [1] "The" "SEA" "has" "the" "SEA" "and" "the" "SEA"
```
Note that names of documents have to be unique to apply `c()`, although it is a bit tedious to rename.

**Comment by elyksenyah** [comment]
Thanks so much @koheiw, that's exactly what I am looking for 👍
