### ISSUE TITLE
Not able to create compound tokens with tokens_compound

### ISSUE THREAD

**Issue by cspenn** [kbenoit/quanteda#961]
I'm using Quanteda 0.99 via devtools on Mac R Studio/R 3.4.1.

In this code:
```
df <- readLines(file.name)
dict <- readLines(dictionary.file)
doc.corpus <- corpus(df)
tokentext <- tokens(doc.corpus,remove_punct=TRUE,remove_symbols=TRUE)
compoundtext <- tokens_compound(tokentext, dict, concatenator="_",case_insensitive=TRUE,join=TRUE)
```

My dictionary is composed of phrases, one per line, plain text.
When I inspect compoundtext, I would expect to see things like text_mining in the tokens, based on my read of the manual, but instead I see "text" "mining".

What am I doing wrong?

**Comment by kbenoit** [comment]
See `?phrase`.  Also if you paste in a section of `dictionary.file` here so we can see exactly the issue, I am pretty sure I can solve this quickly.

**Comment by koheiw** [comment]
Basically, dictionary is a special object constructed by `dictionary()`, not just a character vector from `readLines`. Yet, character vectors works for `tokens_compound()` if words are segmented by space and the vector is wrapped by `phrase()` like:
```r
words <- c('A B', 'C D')
tokens_compound(tokentext, phrase(words), concatenator="_",case_insensitive=TRUE,join=TRUE)
```

**Comment by kbenoit** [comment]
That's right - more simply:
```r
words <- c('A B', 'C D')
tokentext <- tokens("A B and C D A.")
tokens_compound(tokentext, phrase(words))
# tokens from 1 document.
# text1 :
# [1] "A_B" "and" "C_D" "A"   "." 
```

**Comment by cspenn** [comment]
Here's a sample of the dictionary:
buy bitcoin
buy bitcoins
bit coin
bitcoin exchange
bitcoin websites
bitcoin mining
bitcoin wallet
bitcoin website
bitcoins trade
bitcoin companies
got bitcoin
generating bitcoin
bitcoin reviews

**Comment by cspenn** [comment]
I'll give phrase() a go!

**Comment by cspenn** [comment]
Boom, phrase(dict) works beautifully. Thank you!
