### ISSUE TITLE
Add the Lexicoder Sentiment Dictionary

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#963]
Create a `data_dictionary_LSD2015` object (already done in the **textscaling** package) and be sire to include the negations in `LSD2015_NEG.lc3`.

Need to pay attention to the licensing disclaimer about non-commercial use, and get approval from Soroka and Young before publishing. (Preliminary approval already given by email.)

**Comment by stefan-mueller** [comment]
I was wondering whether we should print a message in the console to cite Young and Soroka (if it's used in a publication) when  `data_dictionary_LSD2015` is part of a command? I think it's a great service by the authors to make their dictionary available in **quanteda**, and they deserve the acknowledgement.

Also, we might update the manual and say that `[neg_negative]` and `[neg_positive]` can only be applied to a `dfm`with bigrams (if that's correct)?
