### ISSUE TITLE
Error in validate dictionary

### ISSUE THREAD

**Issue by janebunr** [kbenoit/quanteda#967]
> dict <- dictionary(list(one=c("a","b"), two=list("c","d")))
Error in validate_dictionary(object) : dictionary elements must be named

I got error creating and adding simple texts to my dictionary. How should I fix this?

**Comment by koheiw** [comment]
Your command should look like this:
```r
dictionary(list(one=c("a","b"), two=c("c","d")))
# Dictionary object with 2 key entries.
# - [one]:
#     - a, b
# - [two]:
#     - c, d
```
Please also try the latest master, which include a lot of dictionary-related changes.
