### ISSUE TITLE
Unexpected results word stemming in French

### ISSUE THREAD

**Issue by Wiedel79** [kbenoit/quanteda#969]
Hi all,

I'm quite new to both R and the quanteda package and I'm currently testing the functionalities on a dataset in French. After applying the tokens_wordstem function I see some unexpected results, see attached textfile.

I would expect the word stemming to conjugate all verbs to the infinitive form (e.g. suis > être, avons > avoir etc.). However, this is not the case: sais remains sais and does not become savoir, débloques becomes débloqu instead of débloques etc.

The infinitive form is even changed to something new while another conjugation of the same verb is changed to something else (!): rebattre (inf.) becomes rebattr and rebats becomes rebat... I also come accross some other unexpected results (e.g. coté becomes cot, vers becomes ver etc.).

Does anyone know whether the French dictionary used by quanteda is reliable? Or is there another problem? (or I don't get it and the results are logical?)

Many thanks in advance for your reply!

Kind regards,

W.

[ExampleQuantedaStemmingFrench.txt](https://github.com/kbenoit/quanteda/files/1299761/ExampleQuantedaStemmingFrench.txt)

**Comment by kbenoit** [comment]
You've just illustrated the difference between _stemming_ and _lemmatization_. **quanteda**'s stemmer relies on the **SnowballC** library, which uses a standard stemming algorithm. That library removes suffixes but will not convert conjugated irregular verbs (e.g.) into their lemmas.

```r
SnowballC::wordStem(c("c'est", "délicat", "rebattre", "sais"), language = "french")
[1] "c'est"   "délicat" "rebattr" "sais" 
```

For lemmatisation, you can try [**spacyr**](http://github.com/kbenoit/spacyr) with [spaCy](https://spacy.io) installed using a [French language model](https://spacy.io/docs/usage/models). (I have not yet tried this.)
