### ISSUE TITLE
tokens_lookup(x, dictionary, exclusive = TRUE/FALSE) inconsistent

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#970]
This is inconsistent:
```r
toks <- tokens("say good bye to Hollywood")
dict <- dictionary(list(pos = "good", farewell = "good bye"))

tokens_lookup(toks, dict, exclusive = TRUE)
# tokens from 1 document.
# text1 :
# [1] "pos"      "farewell"

tokens_lookup(toks, dict, exclusive = FALSE)
# tokens from 1 document.
# text1 :
# [1] "say"       "FAREWELL"  "to"        "Hollywood"
```
Also it's unclear whether we should be counting values as matches that are fragments of phrases. The second usage seems more correct to me. We had a similar discussion in https://github.com/kbenoit/quanteda/issues/837 for `tokens_compound()`.

**Comment by koheiw** [comment]
Nested patterns had been ignored in earlier versions, but we changed the behavior. If we are not clear which is better, just add an argument to change how the function works.

**Comment by kbenoit** [comment]
That's one issue, but also there is the inconsistency above depending on the value of `exclusive`. We get two matches in the first case, but just one in the second. The behaviour should be consistent, but it is not.

**Comment by koheiw** [comment]
C++ function for `exclusive = TRUE` seems to have the old behavior.
