### ISSUE TITLE
Add FirstName docvar to inaugCorpus

### ISSUE THREAD

**Issue by chmue** [kbenoit/quanteda#99]
The `President` variable in the `inaugCorpus` currently only stores the president's last name. When I use this variable as a grouping variable when constructing a `dfm`, presidents with the same last name, e.g. Teddy Roosevelt and FDR, are treated as the same person.

The problem does not occur when you use the corpus without grouping because adding the year to the last name makes clear which person is meant.

A possible solution could be to add the initials to ambiguous names, e.g. "Roosevelt, T" and "Roosevelt, FD".

**Comment by kbenoit** [comment]
Very true - and this contrasts with:

```
> data(SOTUCorpus, package = "quantedaData")
> head(docvars(SOTUCorpus))
                 FirstName  President       Date delivery type    filename       party
Washington-1790     George Washington 1790-01-08   spoken SOTU  su1790.txt Independent
Washington-1790b    George Washington 1790-12-08   spoken SOTU su1790b.txt Independent
Washington-1791     George Washington 1791-10-25   spoken SOTU  su1791.txt Independent
Washington-1792     George Washington 1792-11-06   spoken SOTU  su1792.txt Independent
Washington-1793     George Washington 1793-12-03   spoken SOTU  su1793.txt Independent
Washington-1794     George Washington 1794-11-19   spoken SOTU  su1794.txt Independent
```

So: `inaugCorpus` needs a `FirstName` docvar.  I can get around to this soon, or you are welcome to add one in a fork and issue a pull request - I will add your credit to the .Rd file for inaugCorpus!
