### ISSUE TITLE
Deep pass through code

### ISSUE THREAD

**Issue by kbenoit** [kbenoit/quanteda#994]
This is the sort of thing that @kbenoit, @koheiw and @HaiyanLW should do over a day or two, working together, to make sure we like the formatting and organisation of each file.

**Comment by koheiw** [comment]
It is a bad practice to use a global variable
https://github.com/kbenoit/quanteda/blob/9346f3375a535c4b7fe76cac0526754aaa69c67c/R/dfm.R#L129-L130
I think we no longer need to time dfm construction.

**Comment by kbenoit** [comment]
True but I like the timing report, and that was the only way I could figure out how to access it across the complicated way of functions that are called by `dfm()`.
